### ISSUE TITLE
BitmapText: Anchor does not work as expected

### ISSUE THREAD

**Issue by marekventur** [pixijs/pixi.js#1769]
When setting a ```BitmapText``` anchor to (0.5, 0.5) I would expect the text to be centered on its position -- at least ```Text``` does exactly that. 

For some reason the anchor seems to remain in the top left corner:

![image](https://cloud.githubusercontent.com/assets/158185/7538270/a4b3263c-f596-11e4-9289-af7621e56fcc.png)

http://jsbin.com/micazuqalu/2/edit?js,output

(I'm having the same problem with 3.0.3, but I couldn't find a good cdn for it, so the jsbin is usind 3.0.2)

**Comment by englercj** [comment]
The difference is that `Text` is a sprite, has a texture, and therefore has an `anchor` property to modify that texture. `BitmapText` is a `Container` that has many sprites, and therefore has no `anchor` property.

Right now you will have to calculate the position manually. I'm leaving this open as a reminder for my to change the implementation to use a sprite and rendertexture instead of direct children to support cases like this, and potentially improve performance for high-character text, but it would reduce performance for often-changing text...so not sure what I want to do yet.

**Comment by marekventur** [comment]
Oh, ok. That makes sense. Could the size of the container not be updated when the text changes or am I missing something? 

Is there another way of centering BitmapText?```align = "center"``` only seems to work for multiline text.

**Comment by englercj** [comment]
I think the only way right now would be to position it manually `obj.position.x = centerX - (obj.width / 2);`.

Sorry about that :/

**Comment by RoryPicko** [comment]
@marekventur I use a little hack for single line BitmapText aligning.

```
PIXI.extras.BitmapText.prototype.updateTextDefault = PIXI.extras.BitmapText.prototype.updateText;
PIXI.extras.BitmapText.prototype.updateText = function(){
	this.updateTextDefault();
	switch(this.align) {
		case 'center':
			this.pivot.x = this.textWidth * 0.5;
		break;
		case 'right':
			this.pivot.x = this.textWidth;
		break;
		default:
			this.pivot.x = 0;
		break;
	}
}
```

**Comment by englercj** [comment]
That works too :)

**Comment by marekventur** [comment]
Thanks! I'll create a local subclass with that code, that should fix the problem for me.

**Comment by marekventur** [comment]
Oh, sorry, forgot you wanted to keep it open as a reminder

**Comment by GoodBoyDigital** [comment]
we have anchor working like a champ in the dev branch thanks to @marekventur  :) 👍
