### ISSUE TITLE
TilingSprite gap when y is not rounded

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#1773]
Hello, 

Following this issue https://github.com/GoodBoyDigital/pixi.js/issues/1683 I'm opening a new bug report as Chad asked me.

Unfortunatly the "gap" bug is still here. I have this.shader.uniforms.uTransform.value[0] and this.shader.uniforms.uTransform.value[1] both at 0 so the commit https://github.com/GoodBoyDigital/pixi.js/commit/8f2a9cf2782fa38c5aa2059f2a198295d78d8c38 could not fix it for me.

https://cloud.githubusercontent.com/assets/581736/7416695/7c3aa18e-ef61-11e4-8c06-b6f2927dc917.png

https://cloud.githubusercontent.com/assets/581736/7416718/a50be24e-ef61-11e4-8242-75b757345d5b.png

**Comment by englercj** [comment]
Thanks for opening this @JiDW, when you get a chance to put together a running case I will look into this again!

**Comment by georgiee** [comment]
Hi Chad,
huge thanks for looking into this.

I just picked the latest build and modified one of my earlier testcases.
http://jsfiddle.net/georgie/ta6e0h1t/3/

First of all, we are talking about webgl. Canvas looks totally fine!
Now how and what to reproduce:
I can see gaps too. I think they have always been there as a fraction of a pixel, but with the new rounding, it's getting worse.

1. Visit the testcase page. You should see a gap.
![screen shot 2015-05-09 at 09 59 07](https://cloud.githubusercontent.com/assets/1701755/7549372/116c5186-f632-11e4-9c81-90c80eee5b66.png)


2. Move the slider 'Tile X'
You see that the gaps are repeated at the borders and that those gaps are flickering. This is because I give not always integers to the tile position. That's there I actually thought I could fix this by just rounding the tile position now. Yes it's working, but..

3. Enable 'Round Tile X?' in the panel
Yapp, the gaps are disappearing. So far so good.

4. Change the next value in the panel: 'Tile Scaling'
This is a slider from 100 to 200 which maps to 1.0 - 2.0 to scale the tile container.
Move it around. With activated tile position round there is only a single value without gaps: 100.
Not even the double scaled version (200) is without the gaps.

5. Move the slider  'Tile Scaling' back to 100 so the gaps are disappearing again. Now pick the Slider 'Outer Scaling'. This applies the scale to the outer container, not on the stage itself. And guess what?
It is the same like in 4.) 

So what would be the best to fix? I think the new tiling shader is missing a bit of information about the scaling and a little bit of a correct rounding operation.
Could you incorporate the world scale of the object and the tiling position to do a proper rounding for the tiling position? Is it as easy as reading the worldTransform of the TilingSprite ?

I hope this helps a little bit.
Thanks!

**Comment by englercj** [comment]
Ah, I just realized that you both were talking about non-rounded coords causing gaps. This is a combination of rounding errors when using non-int positions and scaling with LINEAR scaling causing rounding errors from scaling.

I am not 100% sure how to fix this, in the past I have used NEAREST scaling and integer coords to solve this problem. If you have any ideas on how to make it work I am all ears O.o

**Comment by georgiee** [comment]
Hi,
Today I spent the afternoon with testing some parameters in the TillingSpite shader, looking into the _renderWebGL method and the sprite renderer. I basically tried two approaches:
1. With the shader & sprite renderer: Let the tiling sprite overlap instead of creating a gap. But I did not find a single position in the shader or the sprite renderer to create an overlapping. 
2. A solution solely inside the TilingSprite: Incorporate the world scale value of the tiling sprite to apply some kind of counter scaling or offsets to match whole pixels.

I did not even get near a solid base to investigate further down. I mangled the shader with many variations and deviations of parameters and looked into so many places in the pixi render pipeline. It was a great experience but with zero output. 

Maybe you have some other ideas and or approaches in your mind ?
Thanks

**Comment by englercj** [comment]
@GoodBoyDigital Do you happen to have any ideas about the gapping that is happening in latest dev? I don't have time to track this down further at the moment.

**Comment by JiDW** [comment]
This thing is still present in the latest release. It's a very tricky thing to fix and we ran out of idea. Half pixels are hard to deal with

**Comment by RainingChain** [comment]
Any update on this? This is causing issues in my project. There shouldn't be a gap inbetween the green squares. It should be one long green rectangle.

![](https://puu.sh/AnCrL.png)

Files to reproduce the bug: https://puu.sh/AnCFE.zip

Thanks.

**Comment by ivanpopelyshev** [comment]
There is a special parameter: http://pixijs.download/dev/docs/PIXI.extras.TilingSprite.html#clampMargin

Pixi cant detect those seams automagically, you have to change it manually.

**Comment by RainingChain** [comment]
I tried various clampMargin and none of them worked. This is the resulting image with clampMargin = -0.5.
Note: The block has red padding. There are still semi-transparent pixels.
![](https://puu.sh/Ap6tP.png)

**Comment by ivanpopelyshev** [comment]
```
imgTexture.baseTexture.mipmap = false;
```

**Comment by RainingChain** [comment]
@ivanpopelyshev Thank you so much. It fixed my problem.

**Comment by ivanpopelyshev** [comment]
But if you want mipmapping, you should put tiled things in separate atlas.
