### ISSUE TITLE
context.imageSmoothingEnabled and anitalias:false

### ISSUE THREAD

**Issue by Phiphel** [pixijs/pixi.js#1862]
When making a canvas renderer and passing "antialias:false" as the options, then it should add

    ctx.imageSmoothingEnabled = false;
    ctx.mozImageSmoothingEnabled = false; // for firefox

to the canvas.

Right now I do this manually, and it's no big deal, but it would be convenient if it did it automatically.

**Comment by englercj** [comment]
Good catch!

**Comment by DubiousDillan** [comment]
I have this issue too!
These values need to be set every time the canvas is resized.

**Comment by themoonrat** [comment]
Hi @DubiousDillan 
The code has
`this.rootContext[this.smoothProperty] = (CONST.SCALE_MODES.DEFAULT === CONST.SCALE_MODES.LINEAR);
`
called after every resize, which is why it's being reset
Is changing the default scale mode a valid option to you?
`PIXI.SCALE_MODES.DEFAULT = PIXI.SCALE_MODES.NEAREST`

**Comment by themoonrat** [comment]
On a side note, I was about to create a PR for this; but I'm not sure I agree with the OPs request? Image smoothing and anti-aliasing are 2 separate things imo.

**Comment by DubiousDillan** [comment]
@themoonrat I figured out that I could change the default after looking through the source- it worked. I mentioned it in another issue.

**Comment by englercj** [comment]
This shouldn't change on anti-alias, but we do use it for nearest scaling of images.
