### ISSUE TITLE
PIXI.Text hard-coded textBaseline

### ISSUE THREAD

**Issue by darryldaniel** [pixijs/pixi.js#1866]
Had a problem recently where I found it impossible to center numbers (PIXI.Text) within a circle graphics object. After looking through the source code for the Text implementation, I found that the textBaseline property is hard-coded to 'alphabetic'. For numbers, this means that there is a slight y-offset because of the text ascent. This makes it impossible to center the numbers across different mobile devices because they have different text ascents. 

I managed to solve this by not using PIXI.Text at all but creating my own canvas and creating a texture from there. I was wondering if it was at all possible to make this textBaseline configurable (with the default being 'alphabetic'). I understand that for 90% of applications this is not necessary but it would be a nice feature.

**Comment by GoodBoyDigital** [comment]
Think this was due to the way all browsers treat the baseLine differently. FF being the biggest culprit! Alphabetic is the only one that works constantly across browsers (Maybe things have changed mind!)

Pixi should always keep the text generally in the same position though? If you could provide a little fiddle demonstrating the issue I'l be sure to take a look!

**Comment by darryldaniel** [comment]
So I've done a code pen. You can find it here:
http://codepen.io/dndaniel/pen/rVmYrm 

If you look at it, you can see that the y-anchor of 0.4 centers the number (on Chrome). The other one looks off. This is different across different mobile devices.

**Comment by englercj** [comment]
This should be fixed, it is now configurable.
