### ISSUE TITLE
hitArea property with PIXI.RoundedRectangle doesn't work correct

### ISSUE THREAD

**Issue by newAlexMatveev** [pixijs/pixi.js#1889]
Click on rounded rectangle - how clear rectangle. Need support rounded rectangle for hitArea

var button = new PIXI.Graphics();
button.beginFill();
button.drawRoundedRect(500, 500, 224, 164, 40);
button.endFill();
button.buttonMode = true;
button.interactive = true;
button.hitArea = new PIXI.RoundedRectangle(500, 500, 224, 164, 40);
this.addChild(button)

**Comment by adelciotto** [comment]
What exactly is the issue you are having? I quickly coded up an example and it seems to work ok.

http://codepen.io/anthdeldev/pen/7ad870c7c95a82ee8e4b58b91d37396e?editors=001

**Comment by newAlexMatveev** [comment]
![rect](https://cloud.githubusercontent.com/assets/12848940/8156823/7f1416b8-1358-11e5-8737-ea80108e9476.png)
Click in rect at the corner.
Click should not work in a corner of the rectangle

**Comment by GoodBoyDigital** [comment]
Fixed in v4 I believe 👍

**Comment by godric3** [comment]
Unfortunately not, because RoundedRectangle.contains is almost the same as in Rectangle:
https://github.com/pixijs/pixi.js/blob/master/src/core/math/shapes/RoundedRectangle.js#L79

Here is example:
https://jsfiddle.net/vLvo28ge/
And my not perfect attempt to fix it(on left original, on right with new contains())
https://jsfiddle.net/vLvo28ge/1/

**Comment by themoonrat** [comment]
Closing as https://github.com/pixijs/pixi.js/pull/3176 fixes this
