### ISSUE TITLE
pivot affects object position

### ISSUE THREAD

**Issue by ppoliani** [pixijs/pixi.js#190]
I have a question with regards to the pivot property of a DisplayObject. In particular, i want to rotate a DisplayObjectContainer around its center; so i set the pivot to its center point. However, i've noticed that this affects the position of the element.

For example, if i set the position to 0,0 (which is the default one) pixijs will try to position the object according to its center point and not the top left corner. So the children of the the DisplayObjectContainer (which in my case is an instance of the Graphics class) run out of the left and top edges of the viewport.

Is there any way to set the rotation point but still position the object in respect to its top left corner.

**Comment by ivan-kleshnin** [comment]
**Will this behavior be fixed in v4?**

I decided to try Pixi out and immediately hit this "bug".
After a few hours googling I still don't understand how this supposed to work.
Most people on forums just say "pivot behavior is broken". Not very helpful.

**Comment by GoodBoyDigital** [comment]
Neither is your comment I'm afraid. This is the way pixi deals with pivot.
If this 'bug' is too much to bare please provide a pr or jog on..

On Thursday, 10 March 2016, Ivan Kleshnin <notifications@github.com> wrote:

> *Will this behavior be fixed in v4?*
>
> I decided to try Pixi out and immediately hit this "bug".
> After a few hours googling I still don't understand how this supposed to
> work.
> Most people on forums just say "pivot behavior is broken". Not very
> helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/issues/190#issuecomment-194833811>.
>


-- 
Mat Groves

*Technical Partner*


 Telephone: 07708 114496 :: www.goodboydigital.com
 First Floor, Unit 9B, Queens Yard, White Post Lane, London, E9 5EN
 goodboy©. All Rights Reserved.

**Comment by ivan-kleshnin** [comment]
> Neither is your comment I'm afraid

Please do not take "Not very helpful" personally. It's here to describe my emotional state, not to offend.

> If this 'bug' is too much to bare please provide a pr or jog on..

I don't know if this is a bug or not because I'm a noob in this industry.
I just shared my experience and asked about change in v4.

**Comment by GoodBoyDigital** [comment]
Hi there! 

No worries man, sorry if I was a bit short, you caught me at the end of a long day!

Pivot is meant to behave as a non normalised anchor point.

The easiest way to fix it is to add the object into a container and rotate the container, whilst moving the object around internally. 

Hope that helps!

**Comment by ivan-kleshnin** [comment]
No problem. Thanx. I'll try to use your advice.

**Comment by mattat11** [comment]
In my opinion, the easiest way to rotate a graphic (or a container) around its center point is to save the center point coordinates, where a graphic was drawn. Then, set the position and the pivot of the graphic to the center point.
Here is an example:

If you for example create a graphic object, you can start to draw primitives on it. 
`
var test = new PIXI.Graphics();
test.drawRoundedRect(100, 100, 200, 200,12);
`
The primitive is always drawn relative to the position of the Graphics object (which is 0 as default).
Therefore, we need to set the new position of the graphic object to 200, because it's the current center point of our primitive.
`
test.position.x = 200;
test.position.y = 200;
`
Now we can see, that the primitive just has been shifted, therefore we need to set the pivot to the same coordinate and it will stay at the same position, where we had drawn it.
`
test.pivot.x = 200;
test.pivot.y = 200;
`
 
The pivot property isn't buggy, it's just a little bit confusing to understand how it works and why it "affects object position". The object is always rotating around the own position and the pivot helps us to set a new point from where it rotates.

**Comment by jdnichollsc** [comment]
Hello guys! Can I use the pivot with angles? I'm trying to modify the angle of one sprite (using the pivot to modify the rotation position) to follow the mouse, but I can't, can you help me, please?

Check my codepen example => http://codepen.io/jdnichollsc/pen/KgdRvV?editors=0010
And the error => http://screencast.com/t/hSSaaTO4j0

Thanks in advance, Nicholls

**Comment by jdnichollsc** [comment]
Done! Only using pivot.y or pivot.x hahaha! Thanks for all Pixi team! :+1:

**Comment by gai-sama** [comment]
> In my opinion, the easiest way to rotate a graphic (or a container) around its center point is to save the center point coordinates, where a graphic was drawn. Then, set the position and the pivot of the graphic to the center point.
> Here is an example:
> 
> If you for example create a graphic object, you can start to draw primitives on it.
> `var test = new PIXI.Graphics(); test.drawRoundedRect(100, 100, 200, 200,12);`
> The primitive is always drawn relative to the position of the Graphics object (which is 0 as default).
> Therefore, we need to set the new position of the graphic object to 200, because it's the current center point of our primitive.
> `test.position.x = 200; test.position.y = 200;`
> Now we can see, that the primitive just has been shifted, therefore we need to set the pivot to the same coordinate and it will stay at the same position, where we had drawn it.
> `test.pivot.x = 200; test.pivot.y = 200;`
> 
> The pivot property isn't buggy, it's just a little bit confusing to understand how it works and why it "affects object position". The object is always rotating around the own position and the pivot helps us to set a new point from where it rotates.

Hey dude,I think that was a hack,cause it has a side effect: the position has been changed.
