### ISSUE TITLE
Include helpful guards in pixi debug version

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#2034]
It would be pretty cool if our debug build of pixi was instrumented with helpful debug guards. For example, ensuring you don't assign `NaN` to matrix values. This could be done via some metaprogramming that ensured the production build did not include any of the guards for maximum performance.

**Comment by devdoomari** [comment]
:+1 on this...
I just got burnt by having NaNs creep out on transform matrices.
I couldn't figure out why my someGraphics.rotate didn't work
 -- turned out I set someGraphics.x = undefined somewhere.
I've lost like 7 hours on this :(

Anyway, are 'isNaN' calls expensive?
Also, what are you thinking about code inclusion/exclusion?
I don't have any ideas on what pixify is, so I'm wondering what pixify can do

**Comment by englercj** [comment]
pixify is just a collection of browserify transforms and build scripts that we use.
