### ISSUE TITLE
What are the limitations of the canvas fallback?

### ISSUE THREAD

**Issue by callumlocke** [pixijs/pixi.js#2088]
The pixijs.com homepage mentions 'seamless' canvas fallback, but I can't find any more info about this.

- What are the limitations?
- What is performance like?
- Can I force-enable the canvas fallback, so I can test it?

Sorry if this is documented somewhere, but I can't find it.

**Comment by photonstorm** [comment]
Seamless in the sense that you don't have to totally rewrite your code just for a specific renderer. But where something is technically impossible in canvas then of course limitations apply - such as shaders/filters not working in canvas, sprite batching have no real difference, and performance differences of course, depending on what you're actually doing. There's no hard and fast list though. You can just create a CanvasRenderer instead of a WebGL or Auto one and you'll soon see the difference.

**Comment by GoodBoyDigital** [comment]
What @photonstorm said.

WebGL - filters / better performance
Canvas - extra blendModes

Other than that they should be the very much the same :+1:
