### ISSUE TITLE
Animate circle (improving performance)

### ISSUE THREAD

**Issue by lapidus** [pixijs/pixi.js#2177]
Would much appreciate if someone could take a look at this: http://stackoverflow.com/questions/33437002/pixi-js-animate-circle-improving-performance

**Comment by adelciotto** [comment]
You could pre-render the circle into a texture using ```graphics.generateTexture()```, then use that texture to create 1000 sprites. You can then animate properties of each sprite such as position, tint (fill), alpha,  scale (radius) etc.

If you want even more performance, and you only need to mutate simple properties such as (pos, scale, rotation) and not advanced properties such as tint, masking, etc then use a ```PIXI.ParticleContainer``` to store the circle sprites.

**Comment by amytych** [comment]
@adelciotto thanks for that! I'm struggling with similar issue and have additional question. I tried this approach but it seems I loose the quality when scaling the generated sprite. Or maybe I'm doing something wrong and it shouldn't be an issue? And if the circle has outline it get's scaled as well I think? No way to control it so it stays the same no matter the size of the circle.

Thanks again!

**Comment by englercj** [comment]
I don't know what your animation is, but you could likely draw it once then rotation/scale/transform it instead of redrawing each time?

**Comment by adelciotto** [comment]
@amytych I assume by losing quality your talking about blurriness, this happens because the texture would be scaling using the default linear interpolation mode. You could try pre-rendering the circle texture slightly larger or based on the canvas dimensions. However if in ur animations your scaling up the circles quite a lot I'd try @englercj's suggestion and just draw it once and modify its properties every animation frame. 

The circle outline (stroke) will get scaled along with it because the circle has been pre-rendered into a texture and the whole thing is scaled, to control the outline too you would need a separate sprite for the outline (stroke) which could be pre-rendered as as unfilled circle into another texture.

**Comment by amytych** [comment]
Thanks @adelciotto that helped a lot. Still managing the outline with unfilled circle is tricky but I'm onto something now.

**Comment by GoodBoyDigital** [comment]
looks like this has a happy ending :) closing for now!
