### ISSUE TITLE
Texture compression support in PIXI.loader and PIXI.texture

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#2200]
Im helping devs of a specific app (I mentioned it in pixi-spine) that have really big number of textures and atlases, and it affects both loading time and amount of used videomemory.

It seems that we need to load different kind of textures based on which compression is supported by device. I know that there's some simple mechanism for retina textures, I dont know if the same way can be applied to compressed textures

**Comment by JiDW** [comment]
No, compressed textures are not yet supported by PIXI, you need to modify PIXI and code your own class to handle compressed textures.

It can be done (we've done it) but it's a good amount of work.

1) The loader is able to understand binary datas so you can load your compressed textures into an arraybuffer without any modification to the code
2) You need a class/library to parse this array. Most of the code you will need can be found inside Toji's texture tester project here https://github.com/toji/texture-tester/blob/master/js/webgl-texture-util.js
3) You need to modify PIXI to tag your compressed textures (we use "isCompressed" parameter on the base texture source)  in order to hack the call to "gl.texImage2D" inside WebGLRenderer.prototype.updateTexture and use glCompressedTexImage2D instead.

Please note that every compressed texture must be a power of two, and if you want to use PVR on iOS, your textures needs to be square.

If you prefer to wait for PIXI to deals with compressed texture itself, you can follow this issue : https://github.com/pixijs/pixi.js/issues/1343

**Comment by photonstorm** [comment]
@JiDW even if you can't submit a PR (and I understand why not, the changes to PIXI must be vast) - if you could still share your source then I'm sure someone would be able to extract what they need from it. Saves re-inventing the wheel and all that.

**Comment by ivanpopelyshev** [comment]
@JiDW make it as PR or patch for pixi that re-defines some functions, PLEASE PLEASE PLEASE.

**Comment by JiDW** [comment]
The changes in PIXI aren't that big, since we use an external class and don't mind about compatibility with further version of PIXI. It's why we can't push a PR too, it's not generic enough, it only deals with the formats/options we need, and it's linked to our own 3d engine too.

To be honest, most of the code is where I linked. Most of the work is about setting a working flow to integrate compressed images inside your project. WebGL lacks some tools to do it easily, we had to create our own tool in java to make it easier. 

If it can help, here is our PIXI.js and class. Just ctrf+f on "compressed" and that should do the job.

https://game.celsiusheroes.com/pixi.js
https://game.celsiusheroes.com/compressedImage.js

**Comment by ivanpopelyshev** [comment]
@JiDW yeah, it seems that your game downloads @2x dds files for windows, that's nice. And I like that game!

**Comment by JiDW** [comment]
Yes, It depends of what kind of compressed texture you can use : http://toji.github.io/texture-tester/

**Comment by ivanpopelyshev** [comment]
Is that game in production?

**Comment by JiDW** [comment]
Currently in a soft launch (search for Celsius Heroes on Facebook or Android). Polishing stuffs, fixing some stability issue on android and making sure the servers can hold the load.
We looked at Spine in our early stage of development but we didn't find good examples of what Snipe can do with characters facing you, it was only from the sides (and it makes sense for me).

This place may not be the best way to talk about it anyway. I planed to post soon on html5dev forum to present the game and what we learned from 1yr and a half with PIXI, Cocoon and WebGL. I was just waiting for the full release.

**Comment by ivanpopelyshev** [comment]
@JiDW I just cant wait to read that post :)

**Comment by manelis** [comment]
I am looking for a way to reduce the load size of the textures and found this. 

If I were to change my pixi class (which already has changes anyway) and add your compressedImage.js to my project, how would be the workflow to be able to do this? Do I need to change something in the source texture? If yes, how will old browsers and gpus (we want to support really old stuff, one of our test pcs has a 7600gs) work with it? 

Thank you for the help.

**Comment by JiDW** [comment]
Well, you need to generate the compressed textures, in 3 formats (DTX, ATC and PVR) + keep the PNG source too.

"Old" browsers won't have WebGL anyway, so the main compatibility issue is on the GPU. You don't know what compressed format they can read so you need to have all possibles formats ready to download.

In compressedImage.js you will find a getCompressedFormat function that will tell you what format to use. You can use this value to load a different batch of images in your PIXI loader.

Then you need to make all of your calls to PIXI.Sprite.fromImage with "CompressedImage.getNomFichierCompresse()" (sorry for the french, company code rule... It should be getCompressedFileName in english)

Please remember that compressed textures are lighter in the memory (by a 4x factor) but heavier on the disk. It is not too bad between a PNG and a DDS (1.4x), but if you compare with a JPG, it can be 15x time heavier to download. So it's all about finding the good balance.

**Comment by manelis** [comment]
Oh, then this is exactly the opposite of what I was looking for, I want to reduce the download size, the memory is less of an issue right now. 

Thank you for the help anyway :)

**Comment by ivanpopelyshev** [comment]
I'm moving your code here: https://github.com/pixijs/pixi-compressed-textures

**Comment by ivanpopelyshev** [comment]
@JiDW done. Please look at github.

Also, [demo is working](http://ivanpopelyshev.github.io/examples/index.html?s=textures&f=dds.js&title=DirectDrawSurface%20(DDS)&plugins=pixi-compressed-textures)

You can try using pixi.js and pixi-compressed-textures.js from that demo in your project.

Do I have to mention in the comments that I took CompressedImage code from you? Or did you take it from other source?

**Comment by ivanpopelyshev** [comment]
Also please join gitter: https://gitter.im/pixijs/pixi.js

**Comment by JiDW** [comment]
Cool work Ivan ! ;)

Most of the texture parsing was done by Toji ( http://toji.github.io/texture-tester/ )
We integrated it inside PIXI. We didn't release it under MIT so officially it's still copyrighted (as it is a part of Celsius Heroes). However I can tell you that we accept this use of the CompressedTexture.js file and will later release this file under MIT licence.

We won't change our code to try yours just because we do not intend to update PIXI in this specific project so it would be pointless but we for sure try it for our next project.

There are some things that I could see done in another way regarding specification compliance (for example, .atc is a fake extension that we made up to distinguish between DXT and ATC compression but ATC is supposed to use a .dds extension (dds is only a container)) but I will comment about it when I get the time to do so and I will do it in your repo.

**Comment by ivanpopelyshev** [comment]
@JiDW did you have problems with pre-multiplied alpha? We are getting very strange things in production. Something wrong with blending and other stuff

![Strange yellow thing](https://monosnap.com/file/Sn7aEcFJ2z4y1xPlL3Oq4VFu1OrnYK.png)

**Comment by JiDW** [comment]
Yes indeed, you need to use textures with premultiplied alpha only.
Premultiply your PNG and then compress them.

**Comment by ivanpopelyshev** [comment]
Ok, found some problems in png and dds files , its fixed. When will you try my library and pixi3.0.9-dev?

**Comment by JiDW** [comment]
I don't know, not before being done with our current project, so I guess in two months.

**Comment by ivanpopelyshev** [comment]
Ok, everything is working in pixi-compressed-textures, and it also supports multiple resolutions, even stuff like @.5x . We can close the issue.
