### ISSUE TITLE
Optimisation: Replace native Array.pop with manual pop function

### ISSUE THREAD

**Issue by adelciotto** [pixijs/pixi.js#2212]
Due to the recent array optimisation implemented in #2209, I also tried implementing my own pop function and benched the performance. 

For me (Chrome OSX) there is a 50% speed increase using the manual pop. I noticed this function is used quite a bit in the library, and perhaps some performance could be gained. 

Benchmarked using JsPerf [here](http://jsperf.com/array-pop-vs-manual)

The manual pop function:

```js
function pop(arr) {
    var last = arr[arr.length-1];
    arr.length--;
    return last;
}
```

Files native pop is used:

![screen shot 2015-11-26 at 11 54 48 am](https://cloud.githubusercontent.com/assets/3887730/11412751/8f2f5212-9434-11e5-842a-b64539970478.png)

**Comment by photonstorm** [comment]
Runs slower on Safari 9 and very little in it on FireFox.

Would be worth checking if there would be any marked difference in a cold vs. warm test too.

The places `pop` is used are pretty hot, but the array size in most of those cases is likely to be extremely tiny (how many elements are usually in a typical filter stack for example?!), I think only the Graphics points data is a candidate for growing to any reasonable size, and even then only in some cases.

**Comment by GoodBoyDigital** [comment]
Interesting stuff! thanks for sharing @adelciotto and @photonstorm :+1:

**Comment by mudcube** [comment]
It seems the only way to know for sure whether these kinds of optimizations will be faster than the native versions would be to run a performance test in the browser on page load (due to the changing performance of native functions in the various browsers over time). 

In reference to the recent #2209 , it appears although the update improved speed Firefox, it decreased speed in Chrome/Safari/Opera and IE - http://jsperf.com/removeitems/2

**Comment by GoodBoyDigital** [comment]
closing for now, all areas where there are lots of pop / pushs in v4 no use an index point to keep track of length. :+1:
