### ISSUE TITLE
Border around PNG image, is it possible with pixi?

### ISSUE THREAD

**Issue by mihkell** [pixijs/pixi.js#2256]
How to draw a border around PNG image like here: https://jsfiddle.net/dasmus/5onobcnj/

Thought about trying to check if pixel is transparent or not, but can't see anyway to get to the image so to compare pixels :)

**Comment by englercj** [comment]
If you are OK with WebGL only:

https://github.com/pixijs/pixi-extra-filters/blob/master/src/filters/outline/OutlineFilter.js

If you need to support canvas, then I recommend having a sprite that also is outlined ad just swapping textures.

**Comment by mihkell** [comment]
I couldn't get the pixels values, to compare what are on the border line, and then color them manually?

**Comment by englercj** [comment]
You could, but I expect you will want to add and remove the outline, possibly when people hover over it?

Doing what you suggest everytime someone rolls over would be highly inefficient, especially in WebGL (because the pixels have to be read off the GPU into CPU, modified slowly, and written back). I would suggest doing the outlining once, caching the result and swapping between then rather than recalculating the outline each time.
