### ISSUE TITLE
MovieClip update method is called by shared ticker

### ISSUE THREAD

**Issue by Jorisslagter** [pixijs/pixi.js#2325]
I am extending the MovieClip object so I can use an AssetManeger to autoload the frames of an MovieClip. After loading, my engine tries to call the update method of Pixi's MovieClip. I designed my code, that when there is an update method on an object, the super object (GameObject) tries to call the update methods on all children. But Pixi's movieclip uses the shared ticker to play and stop the movie clip. This means for me, that the movie clip will always play on load. I also found out that Pixi doesn't checks when the update method is called, that the movie is actually should play. 

I believe this can be solved by adding an if statement in the update method:

``` javascript
if(this.playing) {
  // the rest of the update method
}
```

And my suggestion is to make the shared ticker an optional choice. Because when I make my own code structure, in this way, the update method is called by two tickers. I also tried to overwrite the play, stop and update methods, but with no results (jet).

Maybe somebody have some tips for me to solve this issue?

I fixed it with this code, but I believe this can be done beter.

``` javascript

define(["pixi", "core/AssetManager"], function (PIXI, AssetManager) {
    var MovieClip = function (assetId) {

        var mnr = AssetManager.get();
        var frames = [];

        var sprites = mnr.getAsset(assetId);
        for(var frameId in sprites) {
            var frame = [];
            frame['texture'] = PIXI.Texture.fromFrame(sprites[frameId].url);
            frame['time'] = 20;

            frames.push(frame);
        }
        PIXI.extras.MovieClip.call(this, frames);

        this.loop = false;

    }
    extend(MovieClip, PIXI.extras.MovieClip);

    MovieClip.prototype.play = function() {
        if(this.playing) {
            return;
        }

        this.playing = true;

    }

    MovieClip.prototype.stop = function() {
        if(!this.playing) {
            return;
        }

        this.playing = false;

    }

    MovieClip.prototype.update = function(delta) {
        if(this.playing) {
            this.super.update.call(this, delta);
        }

    }


    return MovieClip;

}); 
```

**Comment by AndyBarron** [comment]
The PIXI docs [show how to disable and/or manually update `PIXI.ticker.shared`](https://pixijs.github.io/docs/PIXI.ticker.html#.shared). I'd also like a way to opt-out or unregister `MovieClip`s from the shared ticker, but this could at least help you out in the meantime!

**Comment by drkibitz** [comment]
@Jorisslagter because PIXI is designed to be pretty much plug-n-play, the design of the shared ticker is intentional to be opt-out instead of opt-in. If you are have your own engine, and using PIXI as a base library, I would simply keep what you have as I think it's actually just fine for your use-case, or go with the suggestion from @AndyBarron and opt-out completely.

I would need to understand your engine a bit better to make a *better* suggestion. Right now I can only make an assumption that the term "GameObject" sounds similar to an entity system as Unity's, and most likely has a top-down approach. This is not how PIXI's MovieClip function because they're updates, as well as the InteractionManager's are intentionally kept separate from the render loop for the original reason to run at different speeds, and to be taken care of for most use cases. To understand move, might actually mean a better suggestion of the issue you describe, or maybe something else, like a different implementation, or digging into a more specific bug with PIXI's MovieClip that you are solving by extending it. I might suggest to just wrap the PIXI MovieClip object in your own component, where your component simply owns a PIXI MovieClip.

To opt-out completely, follow the suggestion above, but you will also need to keep in mind that you will need to call `update` for the InteractionManager if you are using it, potentially the new prepare plugin in PIXI v4, and MovieClip objects. It sounds like you are already calling MovieClip's `update`, but please keep in mind the others.

Actually looking at the new prepare plugin, it exposes a `tick` method that would need to be invoked, this breaks the pattern of `update` methods, so that might need to be addressed for people opting out of the shared ticker like this.

**Comment by drkibitz** [comment]
@GoodBoyDigital @englercj Can you shed some light on why MovieClips should even be implemented like this outside of the render loop? Is it just a legacy implementation, or is there a significant performance gain? I get why the InteractionManager is like this, but I can't currently think of a reason why the `update` method of a MovieClip couldn't be called from overridden `_renderWebGL` and `_renderCanvas` methods. Am I missing something obvious here?

**Comment by drkibitz** [comment]
I might be answering my own question here... the renderer itself does not provide timing information, so there would need to be an implementation of this in the MovieClip class if not consumer the ticker. Or the renderer would need gain another plugin to keep track of this.

**Comment by englercj** [comment]
@drkibitz We wanted MovieClip to be time-based instead of frame-based.

**Comment by GoodBoyDigital** [comment]
Good shout!

**Comment by englercj** [comment]
This is a pretty big change, and since we are rewriting MovieClip in v5 (#3122) going to move this one to that milestone.
