### ISSUE TITLE
The gpu utilization is extremely high when rendering an empty fullscreen renderer

### ISSUE THREAD

**Issue by stephenweaver** [pixijs/pixi.js#2351]
I'm running into performance issues when running my pixi app. 
It kills the battery any device that's not plugged in at an alarming rate.
I started monitoring my gpu utilization and realized that the size of the renderer is directly proportional to the gpu utilization percentage. 

Here is a fiddler of what I"m using at a baseline for pixi performance. https://jsfiddle.net/sweaver/eLhhbrmu/2/. Just make sure that the canvas is as large as jsfiddle will allow. 

I have a new laptop with an integrated graphics card that idles at over 50% when running this
And I have a desktop with 2gb dedicated nvida graphics card that idles at 25-30% when running this.

This hardly seems acceptable, is there any way to bring the gpu utilization down?

**Comment by englercj** [comment]
> I started monitoring my gpu utilization and realized that the size of the renderer is directly proportional to the gpu utilization percentage.

Absolutely, shaders run on the viewport. The larger the viewport the more pixels your frag shaders run on. With a resolution of 2, that is even more space the shaders have to run on.

> I have a new laptop with an integrated graphics card that idles at over 50% when running this

It isn't idling, you are rendering frames, 60 of them per second. Just because the output is black doesn't mean the render process isn't running. If you want to not run render when idle don't call `.render()`.

**Comment by GoodBoyDigital** [comment]
Hi there, 
Thanks for sharing this! I have taken a look at what happens when a frame is empty. The only thing happening on the GPU each frame is the following 3 instructions :

![screen shot 2016-02-11 at 19 16 25](https://cloud.githubusercontent.com/assets/3112434/12987457/0bcd37e8-d0f4-11e5-8977-9348a54e0e03.png)

I would recommend recreating the example using a vanilla webGL context so we have something to measure your results against. 

Cheers!

**Comment by photonstorm** [comment]
So GPU use goes up as the sheer volume of pixels being rendered increases? This
is surprising why exactly?

There are plenty of things you can do:

* Don't use such a stupidly big base canvas
* Don't render at 60 fps
* Don't render at all unless the scene has changed
* Do everything you can to arrange assets properly to minimise draw calls

All of which needs doing on a case-by-case basis, i.e. are user-land
responsibilities.

And it's entirely possible that even after doing the above it still runs
hot because of things outside of your or pixis control (browser land GPU
code)



On Thursday, 11 February 2016, stephenweaver <notifications@github.com>
wrote:

> I'm running into performance issues when running my pixi app.
> It kills the battery any device that's not plugged in at an alarming rate.
> I started monitoring my gpu utilization and realized that the size of the
> renderer is directly proportional to the gpu utilization percentage.
>
> Here is a fiddler of what I"m using at a baseline for pixi performance.
> https://jsfiddle.net/sweaver/eLhhbrmu/2/. Just make sure that the canvas
> is as large as jsfiddle will allow.
>
> I have a new laptop with an integrated graphics card that idles at over
> 50% when running this
> And I have a desktop with 2gb dedicated nvida graphics card that idles at
> 25-30% when running this.
>
> This hardly seems acceptable, is there any way to bring the gpu
> utilization down?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/issues/2351>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by stephenweaver** [comment]
It's not that it's surprising that the gpu goes up when more pixels are rendered. I guess I expected that the gpu utilization would go down if nothing had changed. Like there was some optimizations in pixi that was using the requiresUpdate to only hit the gpu when changes were made. 

Because all the examples that i"ve seen just use an un-optimized game loop, I just figure that was the suggested way of rendering, and pixi was handled optimizing the load on the gpu

I'm not familiar with webgl, which is why I've found using PIXI.js so helpful. 

As far as the suggestions from @photonstorm 
1) Isn't an option.
2) Last resort.
3) Is there anything built into pixi to help handle this, or is it up to the developer to do this? Also the interactive part of pixi seems to be tied to the game loop (not positive), So what can be done to get the interaction events when not rendering?
4) Is there a recommended way to arrange assets?

**Comment by dinoc** [comment]
Here's a fiddle that I created.  https://jsfiddle.net/dcarlos/y4dLcd0j/

It doesn't have a recursive render loop.  Intead, it is calling render on the sprite during onDragMove.  The result is that the sprite renders but everything else is black.  I've tried using different combinations of clearBeforeRender and preserveDrawingBuffer.  If I have clearBeforeRender set to false and preserveDrawingBuffer set to true, I get this trailing render effect on the bunny.  

Is there a way in PIXI to only re-render a specific area on the stage?  Possibly use dirty regions and a back buffer and blit the newly rendered regions onto the buffer.

We built an app that has a large-sized canvas with elements that are changing at a variable rate.  How can we achieve optimal performance without having to call render on the entire stage within a recursive animation loop?

**Comment by themoonrat** [comment]
You must have preserveDrawingBuffer to true; the reason you are getting the bunny trailing effect is because the screen is no longer being automatically cleared for you, which is actually what you want.

Say all of your bunny sprites are in one container. When you detect a change that will need a redraw you could
* Iterate over all sprites figuring out which ones need to be re-drawn (whether it's because it has moved, or because of overlapping ). 
* Ones that need to be re-drawn, set renderable to true, otherwise set to false.
* Manually clear the areas behind each of the 'dirty' sprites using their position and dimensions.
* .render() the container.

Even though you've set renderable to false for the other sprites, because _you_ are controlling the clearing of the screen, they'll still be visible

As for clearing the areas, Canvas 2d has clearRect, WebGL has clearColor - do a search for this.clearBeforeRender to see examples within pixi.

(disclaimer: never actually tried this method in pixi)

**Comment by englercj** [comment]
> Is there a way in PIXI to only re-render a specific area on the stage? Possibly use dirty regions and a back buffer and blit the newly rendered regions onto the buffer.

You can implement this yourself with RenderTextures.
