### ISSUE TITLE
Shader for a sprite with a texture from atlas

### ISSUE THREAD

**Issue by chronszcz** [pixijs/pixi.js#2352]
Hello, 

I have a sprite which has a texture from a texture atlas. When I assign a simple shader to it, the vTextureCoord vector ranges from i.e. [0.03, 0.03] to [0.05, 0.05] instead of [0, 0] to [1,1]. The coordinates are from the baseTexture instead of the frame. Is this how it's supposed to work? It doesn't seem to be very intuitive. What's the best solution for my problem?

**Comment by englercj** [comment]
They have to be from the baseTexture because we don't "cut out" that frame from the image and pass that to the GPU, we just pass the entire image to the GPU.

The uvs you get are the frame normalized to the image (or should be). That's how we can do batching with texture atlases, because all the sprites with different frames are all drawing from the same texture on the GPU just different uvs.

**Comment by englercj** [comment]
Closing this since you can now pass a local coord matrix if you want, and I feel like the question has been answered.
