### ISSUE TITLE
Memory leak on Google Chrome OSX version

### ISSUE THREAD

**Issue by louisatome** [pixijs/pixi.js#2360]
Pixi seems to have a memory leak on Google Chrome OSX version. If i go to the [basic pixi example page](http://pixijs.github.io/examples/) with this browser, the memory usage increase slowly without stopped. With the Windows version of Chrome the problem doesn't appear.

**Comment by englercj** [comment]
The fact that it happens on one OS and not another suggests that it isn't a leak so much as a different GC pattern, not necessarily a leak. JS code doesn't run differently on different platforms, but the engine may and there isn't anything we can do about that.

If you have a profile that shows a leak we can look into it, but if you are just looking at Chrome memory usage and seeing it go up there isn't anything we can do about that.

**Comment by louisatome** [comment]
Yes you're right after some researches it seems to be linked to the chromium JS engine.

**Comment by photonstorm** [comment]
Also worth adding that the very act of profiling with Chrome Dev Tools incurs its own overhead. Profiling is done in the same address space as the page itself, often leading to what looks like continuous increases in memory (or memory spiking) which is entirely due to the fact the Dev Tools profiler is running, and nothing to do with the actual code itself.

Actually using profiler creates garbage and uses memory, and this is _included in the graphs it generates_ (which is batshit crazy imho, but sadly that is how it's done right now).

**Comment by louisatome** [comment]
Actually i didn't use the Chrome Dev Tools i just watch the process from the Chrome Task Manager. But i found this in chromium issue tracker : https://code.google.com/p/chromium/issues/detail?id=120186
