### ISSUE TITLE
How do I use the begin and end paths as done in canvas ?

### ISSUE THREAD

**Issue by chiragsanghvi** [pixijs/pixi.js#2365]
```javascript
 var backgroundGridImg = new Image(),
 backgroundGridImg.src = "http://picpaste.com/thumbs/local_background-VVUamyzZ.1455987094.png";
 ctx.drawImage(backgroundGridImg, 0, 0, 600, 600);
		
 ctx.fillSyle="black";
 ctx.beginPath();
 ctx.arc(300, 300, 300,0, 2*Math.PI);
 ctx.rect(0,0,600,600);
 ctx.closePath();
 ctx.fill();

```
This is the output of the above code for canvas. How do I attain this using Pixi.js. 

![humanswarm](https://cloud.githubusercontent.com/assets/1658152/13197868/35bd7d08-d7af-11e5-9d10-cf7b549e2254.png)

**Comment by KingdomHS** [comment]
If you're more familiar with canvas, you may look at [CanvasBuffer](https://pixijs.github.io/docs/PIXI.CanvasBuffer.html) and then create a new texture [fromCanvas](https://pixijs.github.io/docs/PIXI.Texture.html#.fromCanvas).
```javascript
var canvas = new PIXI.CanvasBuffer() ; 
var ctx = canvas.context ;
/* Do your stuff here */
var sprite = new PIXI.Sprite(new PIXI.Texture.fromCanvas(canvas.canvas)) ;
```
You can also look at the [Graphics](https://pixijs.github.io/docs/PIXI.Graphics.html) library, which look similar to canvas drawing.
```javascript
var g = new PIXI.Graphics() ;
g.beginFill(0x000000) ;
g.moveTo(x, y) ;
g.arcTo(x1, y1, x2, y2, radius) ; 
/* Stuff here... */
g.endFill() ;
```
 Note that Graphics inherits from Sprite class, and that Graphics methods return the graphics object, so you can do chaining instead of splitting like I did in the exemple.

**Comment by englercj** [comment]
Looks like this has been answered.
