### ISSUE TITLE
Text size is wrong on creation

### ISSUE THREAD

**Issue by Aciho** [pixijs/pixi.js#2376]
It doesn't update properly until you call updateText() (or maybe wait a frame, I haven't tried that).

Repro:
https://jsfiddle.net/yvk256L1/7/

(I was trying to make the text fit in the rectangle, if it's not clear)

**Comment by whizzkid** [comment]
Weird.

The texts width property seems to be correct though. 
You can workaround this problem without using updateText by calculating the scale yourself
(probably faster than setting width, and reading the scale)

```
var rect2 = drawRect(70,150);
var bounds2 = rect2.getBounds();
var centerLabel2 = new PIXI.Text("Here Is Some Very Long Text");
centerLabel2.anchor.set(0.5,0.5);
centerLabel2.scale.set(bounds2.width/centerLabel2.width);
rect2.addChild(centerLabel2);
```

p.s. for scale and anchor (i.e. all Points) you can use .set(x,y) instead of making a new Point yourself ;)

**Comment by GoodBoyDigital** [comment]
fixed in v4 👍
