### ISSUE TITLE
SpritesheetParser middleware may block UI for large spritesheets

### ISSUE THREAD

**Issue by rincedd** [pixijs/pixi.js#2377]
When loading large spritesheets containing thousands of sprites, the [spritesheet parsing loop](https://github.com/pixijs/pixi.js/blob/master/src/loaders/spritesheetParser.js#L32) can take quite some time with v3.0.9. As textures are created synchronously within the loop, this leads to a noticeable UI lag whenever spritesheets have to be loaded. 

In my use case, multiple large spritesheets (containing about 4000 images each) have to be loaded at different times in the application. For each spritesheet the application is blocked for the time it takes to parse it and create textures from it.

A potential resolution could be making the texture creation loop asynchronous, so that the spritesheet parsing can be distributed over multiple event loops.

**Comment by GoodBoyDigital** [comment]
Very interesting! thanks for sharing this, Sounds like a pretty useful idea! @englercj is this something we could move onto a webWorker?

**Comment by englercj** [comment]
We could move the loading to a web worker, but we would still have to create the textures on the main thread since that's where the gl textures have to be.

Did you profile this? What is the expensive part? I'd like to see a CPU profile of this "lag" so we can determine what the expensive part is and optimize it before we jump to conclusions. It may just be GPU upload time for a sheet that massive.

**Comment by lukastaegert** [comment]
Hi,
working on the same team as @rincedd, I did some thorough profiling on this issue. As it turned out, the spritesheet parsing middleware is only part of the problem and as you correctly noted, GPU upload time seems to be the bigger culprit, more precisely, the function texImage2D (at least according to the Chrome dev tools).

Nevertheless, there is still some room for improvement with the sprite sheet parser. Currently, we load the following types of sprite sheets dynamically:
* 80x80 sprites on sheets containing 900 sprites each,
* 40x40 sprites on sheets containing 3600 sprites each,
* 10x10 sprites on sheets containing 57600 sprites each,
one sheet of 3x3 sprites containing > 150000 sprites,

Using console.time/console.timeEnd, I found that on my (rather fast) machine, parsing takes about:
2-4ms for the 80x80 sprites,
10-16 ms for the 40x40 sprites,
140 - 200ms for the 10x10 sprites, and
~400ms for the 3x3 sprites

Especially for the latter sprites, skipping the event loop once every ~1000 sprites could definitely improve responsiveness. I have prepared a pull request to illustrate this idea, it is really simple; I think a web worker would not be necessary, especially since all other middlewares seem to run rather quickly, <1ms each.

Still, the bigger issue definitely seems to be the GPU upload time. Since you already stated that this needs to happen on the main thread, i suppose there is no other means of improvement (e.g. a way to sneak in a few setTimeout(..,0) or something similar) besides using smaller textures?
If you have any ideas on how to further reduce UI lag when loading these textures we would be more than happy. In any case, I would appreciate if you take a look at the pull request and maybe implement something like this, even though this is probably a corner case for most.

**Comment by lukastaegert** [comment]
Thanks for the response!

And yes, that is definitely what we want :)
This will be part of a business application which provides a visual way to browse a huge library of product images (currently >150000 images), which are supplied as auto-generated sprite sheets and full-size images by our backend. Our main concern is zooming, which requires switching image resolutions mid-flight and as smoothly as possible. Pre-loading all images is not really an option, especially for the larger sprite sizes and considering that we already need > 4GB main memory.

If there is any way to lower the memory consumption while keeping responsiveness, even at the cost of longer image update times, we would be more than happy.

**Comment by englercj** [comment]
In what you are talking about, I would take the google-maps approach. Each tile is a small separate piece that is loaded when rendered. This results in a small delay before the user sees the image when tiles switch (because it needs to be loaded and then drawn) but you can dump out of memory all the ones you are not using and load smaller things on demand rather than huge sheets.

**Comment by lukastaegert** [comment]
This is actually what we are doing for larger tile sizes. However, this approach does not scale very well when zooming out, as in this case, we have potentially up to 10,000 (very small) images on screen at the same time. Considering limitations of the browser as for the maximum number of simultaneous downloads and the fact that part of our user base is on high latency connections, it is clear that we need to switch our approach at some zoom level.
I guess it will boil down to finding the best compromise:
* large sprite sheets reduce the number of downloads but waste a lot of memory and have a noticeable negative performance impact when being loaded into the graphics memory
* single images optimize loading performance and memory consumption, but cannot be downloaded in a reasonable amount of time
* smaller sprite sheets will provide better performance and a smaller memory footprint at the cost of download time; however, there is only any real advantage over single images if the sprite sheets remain cached in memory

**Comment by englercj** [comment]
> there is only any real advantage over single images if the sprite sheets remain cached in memory

Also drawing 10 tiles from a single spritesheet is 1 draw call, whereas drawing 10 tiles all from different images is 10 draw calls.

**Comment by lukastaegert** [comment]
> Also drawing 10 tiles from a single spritesheet is 1 draw call, whereas drawing 10 tiles all from different images is 10 draw calls.

Another part of the dilemma... :wink:

**Comment by GoodBoyDigital** [comment]
looks like this has reached an end.. closing for now 👍
