### ISSUE TITLE
Container#destroy will pass down the first parameter regardless if the child is a Sprite instance, is this right?

### ISSUE THREAD

**Issue by inetfuture** [pixijs/pixi.js#2392]
```js
/**
 * Destroys the container
 * @param [destroyChildren=false] {boolean} if set to true, all the children will have their destroy method called as well
 */
Container.prototype.destroy = function (destroyChildren)
{
    DisplayObject.prototype.destroy.call(this);

    if (destroyChildren)
    {
        for (var i = 0, j = this.children.length; i < j; ++i)
        {
            this.children[i].destroy(destroyChildren);
        }
    }

    this.removeChildren();

    this.children = null;
};
```

When call `container.destroy(true)` and if one of the children is a `Sprite`, its `destroy` method will also be called with `true`, which means destroy the current texture of the sprite as well, is it intentional?

I'm developing a single page app, where when route changed, I will create and destroy the stage and renderer accordingly. When I use `stage.destroy(true)` and recreate it later when user navigates back, sprites didn't show, there is an error `Cannot read property 'hasLoaded' of null` of Sprite.js, I'm guessing it's because their texture cache has been destroyed. So I put an empty function on sprite's `destroy` after I created it, then it can show up again.

**Comment by ivanpopelyshev** [comment]
Yeah, that's a problem :)

**Comment by inetfuture** [comment]
> Yeah, that's a problem :)

So what should we do?

**Comment by mike-tomko-codebaby** [comment]
Also encountering this issue in a single page app experience.

While I agree ```Container.destroy(true)``` shouldn't cause child sprites to destroy their textures by default, I think the underlying issue is that the ```Texture.destroy``` method doesn't remove the texture from the ```textureCache```, so there's a destroyed texture still in cache. This means that when you try to recreate the texture with the same imageId, it sees that it's already cached and tries to use the already-destroyed texture instance.

```BaseTexture``` properly deletes itself from the ```baseTextureCache``` in its ```destroy()``` method, which is what ```Texture.destroy()``` should be doing.

I made a jsFiddle that represents what I think is the situation @inetfuture and I, are running into. https://jsfiddle.net/sjs2ye2u/2/ It renders a stage with a sprite, then after 5s it simulates a single page app page change by telling the stage to destroy, and then reinitializing the stage and sprite. As you'll see in the console, when it simulates the SPA page change, it throws the error @inetfuture references (at least on Chrome, different wording in Firefox).

**Comment by andrewstart** [comment]
A (breaking) change could be made such that `Sprite.destroy()` has `destroyChildren`, `destroyTexture`, and `destroyBaseTexture` as the parameters. Sprites are Containers too, after all. `Container.destroy()` could be set up with the same parameters as well just for passing to children, so that you could fully destroy an entire display list from the top.

**Comment by GoodBoyDigital** [comment]
All fixed in v4 👍
