### ISSUE TITLE
v4 Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixi.js#2455]
In setVertexAttributes module you get this error if you have any prototype modifications to Array type.

E.g. I added isArray=true and other helper methods used throughout our project to Array.prototype.

One simple fix with a minor performance penalty is:

```javascript
for (i in attribs)
{
  if (attribs.hasOwnProperty(i))
     tempAttribState[attribs[i].attribute.location] = true;
}
```

**Comment by GoodBoyDigital** [comment]
thanks for sharing! The code has been tweaked to iterate with:
```for (i = 0; i < attribs.length; i++)```

**Comment by brianblakely** [comment]
I am getting this issue in v4-rc3.  Chrome for Desktop is A-OK, but my Chromebook w/ touchscreen is producing this error.  Also, my iPhone is not having it, but I can't see its dev console right now.

Demo:
http://codepen.io/brianblakely/pen/EyzXWJ

Stack Trace:
```
VertexArrayObject.addAttribute (VertexArrayObject.js?cd22:170)
Quad.initVao (Quad.js?9c56:87)
FilterManager.applyFilter (FilterManager.js?1789:185)
Filter.apply (Filter.js?c140:74)
FilterManager.popFilter (FilterManager.js?1789:130)
Container.renderWebGL (Container.js?2d81:469)
WebGLRenderer.render (WebGLRenderer.js?f0d1:249)
(anonymous function) (script.js?9a95:46)
(anonymous function) (script.bundle.js:493)
__webpack_require__ (script.bundle.js:20)
(anonymous function) (script.bundle.js:48)
__webpack_require__ (script.bundle.js:20)
(anonymous function) (script.bundle.js:40)
(anonymous function) (script.bundle.js:43)
```

**Comment by ivanpopelyshev** [comment]
Try rc4 https://github.com/pixijs/pixi.js/releases

**Comment by brianblakely** [comment]
Thanks, just updated, although the issue remains.

**Comment by GoodBoyDigital** [comment]
Hi there! This usually happens when an attribute is declared but not actually used in the shader. The complier often optimises out the properties completely on some devices.

Is it a default pixi filter? Or a custom one? If is custom can you post you filter code up please? 

The example unfortunatly the demo is impossible to debug. If you could set up an isolated filter we will be able to help you much quicker 👍 

Cheers!

**Comment by brianblakely** [comment]
It is a custom filter.  Here is the code:

https://github.com/brianblakely/shader-particle-animation-example/blob/master/script.js
https://github.com/brianblakely/shader-particle-animation-example/blob/master/shader.glsl

**Comment by brianblakely** [comment]
By some amalgam of updating to v4 stable and/or gradual codebase changes since 5 days ago, this problem has resolved itself.

**Comment by ggarek** [comment]
**It is probably not an issue with PIXI itself. Though i would add some screaming to console when shader was not compiled.**


Hello, it seems i have the same issue with v4.2.2 PIXI.
The issue appeared after i upgraded from v3.0.11 to v4.2.2.

I got various exceptions, one of them, and most often, happened when `attributes.location` was accessed, where `attributes` was `null`.

In general it seems the shader compilation process, built in PIXI, does not scream when something bad happens.

In my case the problem was, that default vertex shader changed in v4.2.2 relative to one in v3.0.11, and some of my shaders tried to use `vColor` variable in fragment shader, which is absent in v4.2.2 default shader.

Same error will happen if you make any typo in shader text, for example using variable without being defined first. You will get the same `Cannot access location of null` in result.

So as a general advice i would say check your shaders, try to switch them off and turn one by one with recompiling. You will find which one causes the error eventually.

p.s.: If upgrading from v3 PIXI you may consider to bring its default vertex shader to your codebase. It will do if you need to fix things fast.
