### ISSUE TITLE
pixi.js example question

### ISSUE THREAD

**Issue by geraldstanje** [pixijs/pixi.js#2514]
Hi,

i have created the following example:
http://jsfiddle.net/kdoodo3t/11/

could you tell me why the red circle does not move until it reaches x=maxX? it seems it moves out of the boundary...

with WebGLRenderer it's scaled and with CanvasRenderer it's ok...any idea whats wrong?
It *seems* to be treating the coordinate system as always being 800x600

edit: seems i had a old version of pixi.js

i updated to the newest version: http://jsfiddle.net/kdoodo3t/20/
but why cant i see any circle rendered?

**Comment by whizzkid** [comment]
You've put the backgroundcolor and view in 2 separate objects, instead of in just 1.

your code: 
```
renderer = new PIXI.autoDetectRenderer( //autoDetectRenderer WebGLRenderer CanvasRenderer(
    maxX, //512,
    maxY, //384,
    {backgroundColor: 0xFFFFFF},
    {view: myView}
  );
```


correct code:

```
renderer = new PIXI.autoDetectRenderer( //autoDetectRenderer WebGLRenderer CanvasRenderer(
    maxX, //512,
    maxY, //384,
    {   backgroundColor: 0xFFFFFF, view: myView}
  );
```

**Comment by whizzkid** [comment]
Also,  you can simply use requestAnimationFrame, PIXI already handles the polyfill  for you.

**Comment by geraldstanje** [comment]
@whizzkid thanks for the info.
could you tell me what you exactly mean by: "Also, you can simply use requestAnimationFrame, PIXI already handles the polyfill for you." ?

**Comment by whizzkid** [comment]
Why the weird shape? 
Because you're creating your renderer for a specific size, and then stretching your view in your programs init function.

this bit:
` renderer.view.style.width = window.innerWidth + "px";
  renderer.view.style.height = window.innerHeight + "px";
`

If you want to keep the correct aspect ratio, you should resize the renderer.

`renderer.resize(window.innerWidth, window.innerHeight);`

Also, you probably want to resize this whenever the window size changes, and not only in the init() function.  

Recommend using a reusable texture? 
That depends on your project. Will the circles graphics ever change?  if not, using a texture will be faster. Although you might not notice if you're not drawing a LOT of them anyways.
Are the circles NOT static and will stuff be drawn in it?  then don't use a texture.


Why dont you see all circles?
Because you're drawing them with this linestyle:
` circle.lineStyle(100, 0xFFFFFF);`

That means the outline of the circle is 100 pixels wide.. the topmost circle obscures all the ones underneath it with its white outline. Change the 0xFFFFFF to 0x0000FF to see what it's actually drawing. you can't see it now because its a white background with a white line.

change it to 
` circle.lineStyle(1, 0xFFFFFF);`

(tip: dont draw stuff in the same color as the background if you're new to all of this. you would've seen this error yourself immediately)

and lastly about using requestanimationframe.  PIXI already did this bit for you:

`window.requestAnimationFrame = (function() {
  return window.requestAnimationFrame ||
    window.webkitRequestAnimationFrame ||
    window.mozRequestAnimationFrame ||
    window.oRequestAnimationFrame ||
    window.msRequestAnimationFrame ||
    function( /* function FrameRequestCallback */ callback, /* DOMElement Element */ element) {
      return window.setTimeout(callback, 1000 / 60);
    };
})();
`

So you can remove that from your code. and requestAnimationFrame (that you already use) will simply just work :)

**Comment by whizzkid** [comment]
I've made some changes to your script:

http://jsfiddle.net/whizzkid74/kdoodo3t/26/

**Comment by whizzkid** [comment]
this can probably be closed.
