### ISSUE TITLE
maxLineHeight not working?

### ISSUE THREAD

**Issue by TolgaND** [pixijs/pixi.js#2522]
Hi, I created a BitmapText with a custom font, but I can't seem to use maxLineHeight or lineHeight in order to close the vertical gap between the text I am using. It seems somewhat like this:

/**
Hello

World
**/
and I want it to be like this
/**
Hello
World
**/

Any working examples? Please give us more examples next time.

**Comment by englercj** [comment]
Do you have a running example of this not working properly? ([How to report an issue](https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md#reporting-issues)]

**Comment by TolgaND** [comment]
Of course, here is an example (I made this example using my existing code):
```
this.loader = PIXI.loader.add( "jandaCG.xml" ).load();
this.loader.once("complete", function() {
this.myText = new PIXI.extras.BitmapText( "Hello\nWorld" , { font: "40px jandaCG", align: "left" /*, maxLineHeight:10*/});
this.myText.maxLineHeight = 10; // doesn't work..
}).load();
```

**Comment by TolgaND** [comment]
@englercj 

Why is there really no one who can help me with this issue for so long? I can't post a working example, because you need a xml file.

I thought that PIXI JS would be used by a large group of people who are also willingly to help.

**Comment by themoonrat** [comment]
Try calling updateText() on myText after setting the maxLineHeight

`this.loader = PIXI.loader.add( "jandaCG.xml" ).load();
var self = this;
this.loader.once("complete", function() {
self.myText = new PIXI.extras.BitmapText( "Hello\nWorld" , { font: "40px jandaCG", align: "left" /*, maxLineHeight:10*/});
self.myText.maxLineHeight = 10; // doesn't work..
self.myText.updateText(); // <-- try this
}).load();
`

**Comment by TolgaND** [comment]
@themoonrat 

Nope, doesn't work...

**Comment by TolgaND** [comment]
Guys come on!! I have been waiting way too long for an answer here!!! Where are the developers who make this library???

**Comment by photonstorm** [comment]
If your issue is so time sensitive that a mere 5 days is 'way too long'
then you ought to seek help elsewhere _as well_ (post it to the forum, ask
on Stack overflow, actually go through the source and figure out what's
happening for yourself).

The more you rant, the more you increase the chance of never getting a
response at all. There are issues here that take months to get answers, _if
ever_, so try and help yourself as much as you can.


On Monday, 25 April 2016, Tolga Demir <notifications@github.com> wrote:

> Guys come on!! I have been waiting way too long for an answer here!!!
> Where are the developers who make this library???
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/issues/2522#issuecomment-214203849>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by TolgaND** [comment]
@photonstorm 

I understand every last of your comment, but this problem should not exist and I don't have the time to understand the source code because of a deadline I am working on. Please understand that it wasn't my intention to make everything worse, I just need help, that's all.

**Comment by englercj** [comment]
@TolgaND This project is run by people who work on it in their free-time, something we don't have much of lately. I understand your problem is time sensitive, the best way to fix the problem is research and understand the code and debug it yourself.

I have deadlines too, and they have nothing to do with pixi or this issue. If I get time to look at this I will, but in the meantime you can try to solve your own problem the same way I would. Debugging your example and figuring out where the value gets set incorrectly.

**Comment by TolgaND** [comment]
@englercj 

Thanks for your reply, I will try to look into it soon.

**Comment by themoonrat** [comment]
@TolgaND  - as it stands right now, pixi uses the line height as defined in the .fnt file of the font you want to use; in your case, jandaCG.xml. You'll see a line something like

`<common lineHeight="87" base="61" scaleW="512" scaleH="512" pages="1" packed="0"/>`

So you can't change the line height on a per BitmapText instance, only per font loaded

**Comment by themoonrat** [comment]
As a quick hack around the above, if you needed the same font to have multiple line heights, I'd do something like
```
this.loader = PIXI.loader.add( "jandaCG-lineheight50.xml" ).load();
this.loader = PIXI.loader.add( "jandaCG-lineheight75.xml" ).load();
```
So have 2 xml files... both point to the same .png of the font, but with their names and lineheights changed within each xml file

```
<info face="jandaCG-lineheight50" size="70" bold="0" italic="0" chasrset="" unicode="0" stretchH="100" smooth="1" aa="1" padding="0,0,0,0" spacing="1,1"/>
<common lineHeight="50" base="61" scaleW="512" scaleH="512" pages="1" packed="0"/>
```

```
<info face="jandaCG-lineheight75" size="70" bold="0" italic="0" chasrset="" unicode="0" stretchH="100" smooth="1" aa="1" padding="0,0,0,0" spacing="1,1"/>
<common lineHeight="75" base="61" scaleW="512" scaleH="512" pages="1" packed="0"/>
```

**Comment by TolgaND** [comment]
@themoonrat

Instead of creating another xml file, I just changed the lineHeight and it worked!! Thanks a lot man! :)
