### ISSUE TITLE
Suggestion: Use promises for textures, loader()

### ISSUE THREAD

**Issue by DennisSmolek** [pixijs/pixi.js#2538]
I'm working on using Pixi for a few things and I ran into an issue where I was calling for a texture that hadn't been loaded yet but I didn't know that so it took me a bit to hunt down the problem. The image is local but my script fired too fast..

Now one simple fix is to use the asset loader which I did right away and it fixed the problem, but I noticed a habit around the code of using "Events" and listeners which work but are a bit verbose. Consider:
```javascript
var bunny = PIXI.Sprite.fromImage('assets/bunny.png');
if(bunny.BaseTexture.hasLoaded) {
	onlyWhenLoaded();
}else {
	bunny.texture.on('update', function() {
		if(bunny.baseTexture.hasLoaded){
			onlyWhenLoaded();
			//Is there a way to do an off??
		}
	});
}

function onlyWhenLoaded() {
	//..do stuff like:
	console.log('Bunny Width', bunny.width);
}
```
would be

```javascript
var bunny = PIXI.Sprite.fromImage('assets/bunny.png').loaded(function(){
	console.log('Bunny Width', bunny.width);
})
```

My loader looks something like: 
```javascript
var loader = PIXI.loader;

loader.add('bgImg', "assets/images/starryBase.png");

loader.once('complete', onAssetsLoaded);

loader.load();

function onAssetsLoaded() {
	animate() //or whatever
}
```

with promises:
```javascript
PIXI.Loader.add('bgImg', "assets/images/starryBase.png").loaded(function() {
	animate(); //or whatever
});
```

You could leave the event stuff in place and just add a loaded function, or even an Error one, that would be cool too. 

If it seems like a good idea and isn't too insane I could take a crack at a PR..

**Comment by englercj** [comment]
Nope!

The loader returns itself and exposes a fluent API, your paste was the most verbose possible. For less typing try:

```js
PIXI.loader
    .add('bgImg', "assets/images/starryBase.png")
    .load(function onAssetsLoaded() {
        animate(); //or whatever
    });
```

**Comment by DennisSmolek** [comment]
Thanks for that!
That's fine for the loader, I was using the loader setup of one of the examples so didn't know it could be shortened like that. 

For Textures though I still think it would be helpful.

**Comment by englercj** [comment]
I recommend browsing the [resource-loader](https://github.com/englercj/resource-loader) repo, it is well commented.

For textures, IMO you shouldn't be using the `fromImage()` API at all. It already "acts" like a "promise" that it will be a texture eventually when it loads. Adding more plumbing into that system to handle loading is the opposite direction I want to go.

**Comment by DennisSmolek** [comment]
The problem is I will be pulling in images on the fly and wont know what they are until they come in. Then I have to do other stuff to the textures that wont work until it's fully loaded. 

I've also seen a few comments on folks with similar needs for basics like height/width. 

Besides just appearing when done loading is there another event that fires besides "update" ?

**Comment by DennisSmolek** [comment]
Or, as I'm now thinking about the loader more, could you use the Loader while running?
So do something like:
```javascript
PIXI.loader.add('1234','path/to/1234.jpg').load(function(){
    doWhatever();
}
```

**Comment by englercj** [comment]
This is all very vague, I don't know what you are asking for. What do you mean "use the loader while running"?

**Comment by DennisSmolek** [comment]
Sorry for causing confusion, let me try to clarify. 

I haven't been using the (pre)loader before firing my pixi code so I've only touched that in the last hour and am not very familiar with it. 

I had assumed it was just a preloader so in my code I've been using Sprite.fromImage() throughout my code while my web-app is running. 

I use the image size that gets loaded to generate a grid, table, and create some other elements but I started to get `imageIWant.height = 1;`
or generating black particles. 

Consider:
```javascript
var myImage = PIXI.Sprite.fromImage('assets/images/myImage.png');
function makeGrid(myImage) {
    var height = myImage.height; //returns 1;
    ...
};
```
even on my local machine served locally the javascript fired too fast before the texture was loaded but in console the value was right so it took me a bit to figure it out. 

In Angular (which I spend most of my time in) they've started using Observers and Promises a ton so I've gotten in the habit of using them so I thought it would be a good idea for Pixi as well. It keeps code that MUST have the data loaded holding until it's ready. 

BUT if the loader can be used even while the app is running and not just as a preloader I think it will work too, and would probably work better because then it could be pulled in other parts of the app.

**Comment by englercj** [comment]
It is just a resource loader. Not pixi specific, nor tied to any lifecycle of any app.

**Comment by GoodBoyDigital** [comment]
I like this! very clean! What do you think @englercj ?

**Comment by englercj** [comment]
I think adding promises as a dep to this lib is not a great idea. However, we might be able to make `.fromX()` methods less painful with a better, more fluent, api. Something along the lines of making those methods actually just wrap a loader under the hood...

**Comment by Hachitus** [comment]
@englercj I'm sorry to just jump on this from outside, but can I ask out of curiosity why not? I don't consider basic promise functionality a dependency anymore, they are native by standards. Sure you have to add a polyfill for them, but it's actually really small. So is there another reason behind it, than just avoiding to add one functionality more to the lib?

**Comment by englercj** [comment]
Problem is that it isn't just adding a small piece of functionality to the lib, we will basically end up building all functionality of the loader all over again in a completely different way that isn't related. So we have two fully fleshed out ways of loading in the library that barely interact with eachother at all.

Rather than forking how we handle resource loading in pixi, we should be consolidating. I can't count the number of times users have been confused by the fact that we have two ways of loading things right now. I want there to be 1 loading method, if we have 2 interfaces I can live with that; but unify their usages.

As far as promises, I strongly feel they don't belong in libraries. AS library using promises infects forces an application to have to use them as well. and if you don't you will have a bad time with any exceptions that occur during async handling (it iwll enter random `.catch()` blocks instead of your normal callback flow you expect. Applications can always translate callbacks/events into Promises, and most libs even have a feature to make it trivial to do so. I think promises have a nice interface, but fail to allow you to properly express async activity. Lots of libraries that were built on promises are struggling to add more advanced features because of the interface of promises prohibits it (for example: https://github.com/mzabriskie/axios/issues/50, this problem is trivial if the lib was callback-based instead of promised-based).

My personal philosophy that evolved from years of using both styles is that libraries should be callbacks/events, applications should be promises (*if* you want them).

**Comment by Hachitus** [comment]
Thank you for the extensive answer @englercj. Appreciated!

I read a lot about the example issue you linked and that's an interesting case, which also enlightens me.

Ultimately I mostly just agree with you on promises. But I think you have the more technical perfection-point of view on this, than me. My difference in views is that, it would depend on the library. Since I think average developer will make less bad choices and end up in bad code structure less likely with promises than with callbacks and thus promises are working a lot like code structure enforcement, guiding the developer to a more clearer structure. So in this sense e.g. in angular it makes sense. They (at least in angular 1), tried to guide developers to one specific format, so continuing on that path using promises would make sense. Also promises have a set standard API, which people will know better, when comparing to using callbacks and events.

But I have no quarrel regarding loaders API. I've wrapped my own preferenced promise to it anyway, it's not a big thing. I think the API works well as it is. The API is small and really easy to use, so promises wouldn't have much of an effect. Only if PIXI would use mainly promises, it would make sense to have the same standard.

Though I think it is possible, that in the future when promises (and ES2016...) will become more used, you might have to refactor in the end anyway :). Since it's more about what people are used to and prefer, than what is the best solution.

P.S.
Aaand after I wrote this, I realized/remembered that angular actually isn't a library so your point is even more valid then :).

**Comment by lebesnec** [comment]
If you really want to use promise or have to because you are chaining the loader to others async call, you can use the following syntax:

```javascript
return new Promise((resolve, reject) => {
   myLoader.load(function() {
     resolve();
   });
});
```

**Comment by SET001** [comment]
or simple one liner to use with async/await

`await new Promise((resolve, reject)=> myLoader.load(resolve))`

**Comment by SET001** [comment]
well, actually you will need to resolve it with loaded resourses:
`const resources = await new Promise((resolve, reject)=>loader.load((loader, resources:any[]) => resolve(resources)))`
