### ISSUE TITLE
V4: Texture Error: frame does not fit inside the base Texture dimensions

### ISSUE THREAD

**Issue by adoxographer** [pixijs/pixi.js#2661]
When moving to V4 we're getting a: 
Texture Error: frame does not fit inside the base Texture dimensions

It seems that the new code in set frame no longer accounts for trimming.

previous code was: 

```js
if (!this.trim && !this.rotate && (frame.x + frame.width > this.baseTexture.width || frame.y + frame.height > this.baseTexture.height))
{
    throw new Error('Texture Error: frame does not fit inside the base Texture dimensions ' + this);
}
```
in V4:

```js
if (frame.x + frame.width > this.baseTexture.width || frame.y + frame.height > this.baseTexture.height)
{
    throw new Error('Texture Error: frame does not fit inside the base Texture dimensions ' + this);
}
```

**Comment by ivanpopelyshev** [comment]
That's ok, we changed Texture definition. Frame must fir the baseTexture, while Orig is original frame.

**Comment by ivanpopelyshev** [comment]
Please give me parts of your code that work with that interface, i'll help you to move

**Comment by funkypaul** [comment]
Was there a solution for this found?

Im having the same issue.
The error comes up on atlases using the trim option from texture packer. Best solution would be not to use trim on atlases but we have A LOT of them and this kinda is not an option now. 

Im checking the source for new Texture.as and it looks like this.trim is not used for calulations. 

I was thinking that maybe the trim action is in spritesheetParser.js but this havent changed since v3.

**Comment by ivanpopelyshev** [comment]
gimme that atlas :) i changed API for textures, and tested it, but may be i missed something

**Comment by ivanpopelyshev** [comment]
@funkypaul got your atlas. It works with v4 just fine. Please look if you have custom spritesheet parser somewhere.

**Comment by funkypaul** [comment]
hmmm, I have a custom spritesheet parser, Ill take a look into this, thanks!
