### ISSUE TITLE
9-slice, 9-patch feature request

### ISSUE THREAD

**Issue by LukaszGrela** [pixijs/pixi.js#2672]
Hi, would it be possible to implement the 9-patch/9-slice scaling feature? I know that there is https://github.com/SebastianNette/PIXI.NinePatch but would like something that will require only 1 image and a rectangle.

**Comment by englercj** [comment]
This would be an awesome plugin :+1:

**Comment by andrewstart** [comment]
Oh boy, this is a thing that I did! I made [a display object](https://github.com/CloudKidStudio/springroll-utils/blob/master/src/pixi/Slice9Sprite.js) to be used with [a texture bundle](https://github.com/CloudKidStudio/springroll-utils/blob/master/src/pixi/Slice9Textures.js). I also made 3-slice versions, and a Texture subclass for cropping a texture horizontally or vertically based on a percentage (like a bar filling up).
I can spruce those up by taking them out of SpringRoll's namespacing system, allowing a rectangle as input, and documenting them better, and some other improvements.
Side note: `Container`'s width/height properties are not configurable - would it be acceptable to make them configurable so that subclasses can override those properties?

**Comment by whizzkid** [comment]
You could also use a PIXI.mesh.Plane and change the UV's and vertices.

**Comment by whizzkid** [comment]
I've created a 9Slice scaling Plane. #2688 
hopefully it gets accepted :)

**Comment by ivanpopelyshev** [comment]
@whizzkid It will be, but if it wont, you can always make your own plugin based on https://github.com/pixijs/pixi-plugin-example/ . I also added a suggestion about evil UVs but that's not your problem actually, it must be done in Mesh and TextureUVs.

**Comment by GoodBoyDigital** [comment]
We has one in v4 👍
