### ISSUE TITLE
adding "snap to pixel" feature

### ISSUE THREAD

**Issue by pc035860** [pixijs/pixi.js#27]
Would you consider adding "snap to pixel" feature to both of the renderers?

After making a little demo yesterday, I found that my sprite blurs when it is not positioned at
integer points.

The sub-pixel bluring effect looks the same with one in the article
http://seb.ly/2011/02/html5-canvas-sprite-optimisation/

**Comment by bartvanheukelom** [comment]
I'd appreciate support for this in Pixi itself (currently patching it in). How do you envision arranging it in user-land? It's doable if all display objects are in a single, pixel-aligned container, but it becomes highly impractical when nested objects are used, where the misalignment may occur at any level in the tree.

**Comment by englercj** [comment]
The short answer is take care not to assign floating values to your positions, if something is a delta change round/floor/ceil it before assigning.

You're right, this isn't an easy problem to solve, but the solution isn't to make objects everywhere have an expensive math operation to catch mistakes. Canvas renderer currently has a [roundPixels](http://pixijs.github.io/docs/PIXI.CanvasRenderer.html#roundPixels) option that increases rendering speed by flooring positions as images are drawn, but it doesn't work like that on WebGL. We would have to round/floor/ceil positions in js which would negatively effect the renderer's performance.

There is also the issue that some applications want to round positions as the move, some want to floor, and some want to ceil, some want to let the browser interpolate normally. It depends on the application. If the answer is "it depends on the application" it probably doesn't belong in the core. I'm not convinced that this belongs in pixi core because it means adding a branch to every update transform call at best, or many branches at worst. I'm still of the opinion that you should just round/floor/ceil your values you assign to positions as you do it in your application, if it makes sense to do so in your application.

**Comment by bartvanheukelom** [comment]
Take for example a spaceship moving slowly around a space. You don't want to round its `x` and `y`, because then you can't achieve the slow motion. The spaceship has lots of elements, rotating turrets, etc. Also, there is zooming and rotation of the view going on.
You only want the leaves in the display tree, the actual sprites, to snap to the pixel grid. The only practical place to apply this would be somewhere between `updateTransform` and the actual rendering.

I fully sympathize with not wanting to add code to fix a very specific problem in such a general location. I'm all for separation of concerns. (Why does `BaseTexture` deal with loading/caching images from urls? :-] )
So would you consider adding an optional callback inside/after `DisplayObject.transform`? It would receive the updated matrix, allowing it to modify it further, e.g. applying rounding/flooring/whatever to the translation values.

If you're worried about branching, you might implement it somewhat like this:

    DisplayObject.prototype.setTransformCallback(cb) {
		if (cb != null) {
			this.updateTransform = function() {
				DisplayObject.prototype.updateTransform.call(this);
				cb(this.worldTransform);
			};
		} else {
			delete this.updateTransform; // revert to using the prototype version
		}
	}

**Comment by englercj** [comment]
> (Why does BaseTexture deal with loading/caching images from urls? :-] )

Historical and usability reasons, it was written like that a long time ago before we had a loader and unfortunately people started using it and expect it to be that way :( I hate it.

> So would you consider adding an optional callback inside/after DisplayObject.transform? It would receive the updated matrix, allowing it to modify it further, e.g. applying rounding/flooring/whatever to the translation values.

I have thought so long and hard about this one. The challenge is making it happen in a way that is performant, and I haven't found a method with low enough overhead to make it acceptable, yet.

> If you're worried about branching, you might implement it somewhat like this:

Well we definitely can't do that since that will change the hidden class of the object. But I understand what you are going for. I'll try to think about this problem more and see if we can't get a good solution.

**Comment by bartvanheukelom** [comment]
It would change the hidden class, but only for users who explicitly want to have that callback and are ready to take the performance hit.
Also, if the new `updateTransform` were not to be a closure but a function defined once (with the callback stored as a property), it would add only one hidden class.

Anyway, I've looked around the source a bit and found things like `displayObjectUpdateTransform` and `_originalUpdateTransform`. I'm sure you're able to find a way to work this in :)

**Comment by englercj** [comment]
@bartvanheukelom Yeah it is possible, those aren't adding/removing properties though just chaning them. And displayObjectUpdateTransform is just a shortcut to calling up the prototype chain to reduce the call stack in hot methods.

In other words, those examples add speed but yours reduces it :P let me think on this a bit.

**Comment by endel** [comment]
Also I noticed that PIXI.Text gets blurry when not using roundPixels. It's very difficult to not use floating numbers on the final position since the anchor/pivot usually are float values (0.5 for center), so this is not on the user control anymore - using integers on x/y will not ensure that the evaluated position is actually an integer.

Maybe just PIXI.Text should round it's position in this case, and not the entire core.

**Comment by GoodBoyDigital** [comment]
Hello! With v3 you can snap to using ```renderer.roundPixels = true```

**Comment by skaraman** [comment]
@GoodBoyDigital This issue still exists when rotation/angle is used unfortunately. Can the same algorithm that is used by CSS3 rotateZ, etc, be used here?

**Comment by GoodBoyDigital** [comment]
@skaraman im not sure i follow i'm afraid? If you provide an example of the issue and what needs solving that would be ace. Thanks!

**Comment by skaraman** [comment]
@GoodBoyDigital actually it was to do with retina resolution - http://www.html5gamedevs.com/topic/20776-pixel-percision-on-rotation-for-renderer/

**Comment by sketch34** [comment]
I'm trying to *avoid* this pixel snapping functionality. I want to have a lot of slow moving sprites and the motion looks awful as they snap to each pixel. I've tried `renderer.roundPixels = false` but it has no effect (Pixi.js 4.5.1 - Canvas). 

Is there any way to fix this?

I can easily repro it in the "tinting" demo with these line modifications:
`//dude.scale.set(0.8 + Math.random() * 0.3); // Comment out this line`
`//dude.rotation = -dude.direction - Math.PI / 2; // Comment out this line`
`dude.speed = 0.1 //2 + Math.random() * 2; // Make them move slowly`

[](http://pixijs.github.io/examples/#/demos/tinting.js)

**Comment by sketch34** [comment]
Hi all, any ideas as to why `renderer.roundPixels = false` seems to have no effect in my case above? Thanks for any suggestions.

**Comment by ivanpopelyshev** [comment]
RoundPixels is off by default. How big coordinates are you working with? May be its precision problem.
