### ISSUE TITLE
getBounds still not working 100% correctly

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#2745]
@ivanpopelyshev  I think this is something you need to check out?

Please see my example at: 
https://jsfiddle.net/whizzkid74/3d48rfyk/

this is using the current dev branch of Pixi.

I recurse through my stage and draw the bounds of every object.
As you can see, the bounds are not correct.
![image](https://cloud.githubusercontent.com/assets/323372/17103963/1e9efc58-5281-11e6-9a53-d9a71e4c938e.png)

However, if you call the container you just requested the bounds of for its width, the bounds object you've just requested gets updated with the correct values.

If you uncomment this line in the example,  the thing works as it should.
 //var wtf = container.width;

![image](https://cloud.githubusercontent.com/assets/323372/17103978/31f358b2-5281-11e6-9240-9f9384fc7994.png)

In the console I've outputted the values of the bounds object before and after calling    wtf=container.width, so you can see the change.

console outputs:
incorrect:
![image](https://cloud.githubusercontent.com/assets/323372/17104027/4a975fbc-5281-11e6-9402-4c7f5a32835c.png)

correct:
![image](https://cloud.githubusercontent.com/assets/323372/17104062/72b17cda-5281-11e6-828d-102be72acd2f.png)

p.s. yes I know adding the gfx object changes the bounds afterwards, this is just a quick test :)

**Comment by ivanpopelyshev** [comment]
Try that one? I just built it https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds3/pixi.js

**Comment by whizzkid** [comment]
Now the result is incorrect in both cases.
(you can try in my jsfiddle by removing pixi.js and substituting it with your pixi's url. )

**Comment by ivanpopelyshev** [comment]
drawBounds is obviously incorrect.

You are adding rectangle of getBounds() to the container itself. getBounds() are global coords. Its not that its changes the bounds, its just you have to subtract container coords from (x,y) before you add it.

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital Could you check this out?

**Comment by GoodBoyDigital** [comment]
Will do!

**Comment by GoodBoyDigital** [comment]
Hi @whizzkid !

Had a look at your code this evening, I have to say its pretty confusing! That said, I am fairly confident that this is working as intended.

You are drawing the GLOBAL bounds of the object inside a LOCAL coord space - this basically will magnify your offsets.

Two fixs that would sort it:

1: Draw the bounds in a separate root container that is not nested in the object you are inspecting.
2: Instead of ```getBounds()``` change that one to ```getLocalBounds()```    

Calling ```width``` of the container actually calls ```getLocalBounds``` internally which is why it 'fixes' itself.

Hope that helps!

cheers 👍
