### ISSUE TITLE
Parent-child relationships

### ISSUE THREAD

**Issue by mrgoonie** [pixijs/pixi.js#2856]
I wouldn't call this as issue, it's more like a feature request. In my opinion, it should be able to access the child object through the parent by object hierarchy type.

For example:

```
var container = new PIXI.Container();
stage.addChild(container);

var child = new PIXI.Container();
container.addChild(child);

// then... this should work:

container.child.scale.set(0.5, 0.5);

// instead of:

container.child = child;
container.child.scale.set(0.5, 0.5);
```

What do you think?

**Comment by GoodBoyDigital** [comment]
problem is you can have multiple child objects?

**Comment by mrgoonie** [comment]
It should works with multiple child objects:

```
var container = new PIXI.Container();
stage.addChild(container);

var child1 = new PIXI.Container();
container.addChild(child1);

var child2 = new PIXI.Container();
container.addChild(child2);

var grandson = new PIXI.Container();
child1.addChild(grandson);

// then... these lines should work:

container.child1.scale.set(0.5, 0.5);

container.child2.rotation = 0.1;

container.child1.grandson.x = 500;
container.child1.grandson.y = 500;

```

What I'm trying to say is, you could easily access to the child by its parent, no matter where you're at. Isn't that how display object hierarchy should work? 

Sorry if this is too dumb, I got started as a Flash developer, so I think this is much convenient & easy to understand the display object structure.

**Comment by photonstorm** [comment]
Sadly the above syntax isn't technically possible (as is), because there is no way to derive the child's name from the variable it gets _assigned_ to. You could do it if you maybe passed in a string for it to be referenced as as well: `addChild(child, 'bob')` - but then you need to start protecting the names against already existing properties. For example if you create a child with the name `alpha` it would over-write the alpha property of the Container.

More importantly, it changes the shape of the Container class dramatically, if you start adding in new properties at run-time.

I agree it would make accessing children easier though, but I think you'd be better off implementing it via your own extension to `PIXI.Container`.

**Comment by GoodBoyDigital** [comment]
Great explanation - @photonstorm is spot on! Thanks for that dude! Closing for now as this is resolved

**Comment by mrgoonie** [comment]
I still think that it can be able to solve... but, well, maybe later then! :)

**Comment by kaansoral** [comment]
@mrgoonie you can create your own `add_child` function, with 3 lines of code, that does what you want, with what @photonstorm describes

It's common practice to extend the container yourself, instead of custom game objects, I use PIXI objects for example, like a Sprite, the code becomes much simpler

You can just add a children as a custom property, expecting this from PIXI, is just futile and pointless
