### ISSUE TITLE
shader texture size changed in v4

### ISSUE THREAD

**Issue by blancoberg** [pixijs/pixi.js#2868]
The size of the shaders/filters in v4 seem to be multiples of 2 now rather than the actual texture size  (256x256,512x512,1024,1024 and so on). I didn't see any documentation about this so I assume it is a bug?

**Comment by GoodBoyDigital** [comment]
Hi there! Yes the v4 filters have been tweaked slightly to use po2 textures and does indeed need to be documented a little.

The main reason for going down this path is we should end up with a smaller textures being used for filters (previously in v3 a texture was always the size of the renderer, not so efficient if the filter was applied to something very small! )

The down side is there is a increase in complexity when it comes to transforming the uvs so that they work as most users would expect.

Until the docs are ready, the best place to start is to look at the filters that we currently have and that should hopefully give you an idea of how it works.

Cheers!

**Comment by ivanpopelyshev** [comment]
look into other similar issues, for example 'migration guide', i just posted it. First thing is about mappedMatrix , the second is about filterClamp. Sources for pixi blur and displacement will help you with that.

**Comment by blancoberg** [comment]
@ivanpopelyshev Thanks for the tip! I will look into that.

**Comment by brianblakely** [comment]
> The down side is there is a increase in complexity when it comes to transforming the uvs so that they work as most users would expect.

It's a lot more complicated.  Maybe Pixi can provide a little more plumbing to shaders to help with this?

**Comment by englercj** [comment]
Closing this since the information is currently in #2867, and should be moved into https://github.com/pixijs/pixi.js/wiki/Pixi-v4-Migration-Guide soon.
