### ISSUE TITLE
mouse cursor position bug

### ISSUE THREAD

**Issue by blancoberg** [pixijs/pixi.js#2930]
Hello!
When moving the cursor outside of the browser window, the cursor position is still registered inside of the canvas and continues to emit mouse events when objects move over it.

I'v made a little fiddle for you here:
https://jsfiddle.net/3u6dotL4/2/

Just move the mouse outside of the canvas window, and you will see that the mouse-over of the rectangle is triggered when it moves past the last registered mouse position.

Maybe an mouseout-event should be added to the window so the mouse handler could get reset?

**Comment by themoonrat** [comment]
Hiya, this issue was been previously been reported: https://github.com/pixijs/pixi.js/issues/2914 - Good fiddle though, more tests help.

I put up 2 PRs, the first just checking mouseover and mouseout on the canvas, the other trying to work out the position of the canvas to know when the mouse is 'over' or not'.

The first one works on this fiddle, - https://jsfiddle.net/8aq74eak/4/ - but has the disadvantage that, say, if a small square dom element was placed over the middle of the canvas, no mouseover/mouseout events would fire from it.

The second PR resolved that, but as it's basing it on relative positioning of the canvas, does not work in your fiddle that can have that interactive part hide behind another frame

We'll see if the first PR side effects are deemed acceptable :)

**Comment by GoodBoyDigital** [comment]
Hey chaps! Pretty busy at the mo, but will make time to check all the exciting new interaction prs soon 👍

**Comment by themoonrat** [comment]
@englercj This can be closed after https://github.com/pixijs/pixi.js/pull/2996 was merged
