### ISSUE TITLE
Does pixi support webgl2

### ISSUE THREAD

**Issue by barbarosso** [pixijs/pixi.js#3028]
Is it possible to run pixi with webgl2?
If so, are there any performance gains if we do so?
If not, is it possible to enable webgl2 rendering?

**Comment by englercj** [comment]
> Is it possible to run pixi with webgl2?

Yes, you can pass a context into the renderer so you could create a WebGL2 context and pass it in manually.

> If so, are there any performance gains if we do so?

Not really. There are more features that if used could offer perf gains, but since we have a wide variety of platforms and browsers to support, and almost none of them support WebGL2 we don't use any of those features.

> If not, is it possible to enable webgl2 rendering?

Not sure what you are asking by this.

**Comment by GoodBoyDigital** [comment]
My 2 Pence on this one. I was thinking much like we have the 'canvas renderer' and 'webGL renderer' we could create a 'webGL2 renderer' later down the line. I already know 3D textures alone will give us the ultimate sprite batching technique :D

**Comment by englercj** [comment]
WebGL2 also include MRT which opens up deferred rendering and other nice things :)

**Comment by GoodBoyDigital** [comment]
indeedy!

**Comment by barbarosso** [comment]
@englercj I will close this one for now. Thx!
