### ISSUE TITLE
Deprecation not working in current dev branch

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#3062]
Hey Chaps - this one is breaking quite a lot of our games for me :(

Looks like it should be working, deprecation is being imported. But nothing setting? My es6-fu is not strong enough.. Sure it will be a quick one for @englercj and @bigtimebuddy mind!

To Test simply open the console and type ```PIXI.MovieClip``` or try to find any other deprecated item.

**Comment by englercj** [comment]
Heading home and will try to look into this tonight.

(Just remembered you mentioned this to me before, and I forgot to fix it. SORRY!!!)

**Comment by englercj** [comment]
OK, I see why this is happening. The deprecation stuff is included *after* we export `core`. And the code that is generated for `export * from './core';` looks like this:

```js
               var _core = require('./core');
                Object.keys(_core).forEach(function(key) {
                    if (key === "default" || key === "__esModule")
                        return;
                    Object.defineProperty(exports, key, {
                        enumerable: true,
                        get: function get() {
                            return _core[key];
                        }
                    });
                });
```

Since it copies all the keys to the export object, the later added deprecation stuff isn't making it out. Moving up the deprecation includes should fix it right up. Should work when the new dev build finishes.

**Comment by englercj** [comment]
Also related: 7014b25df82dc346fcd9ad5c5a8cfd4dae05b075 and ca43f7698a56c62200893c24c1ca209345f90621
