### ISSUE TITLE
Video is not working in video example under pixi v4

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi.js#3066]
The video example on the pixi website is not working in pixi v4. The sound is playing, but the video isn't visible (as seen in Chrome and Firefox). Not sure if pixi video is not working in v4, or it's just this demo not working fine together with v4, but just to let you know.

https://pixijs.github.io/examples/?v=v3.0.11#/basics/video.js

**Comment by themoonrat** [comment]
This has been fixed in the latest dev branch; to confirm please go to
https://pixijs.github.io/examples/?v=dev#/basics/video.js

**Comment by Friksel** [comment]
Thanks @themoonrat . Very nice this is fixed. Chances are high I need it in a new project, so that's very welcome :)

**Comment by weepy** [comment]
Hi --- the example doesn't work in iOS Chrome or Mobile Safari ---- ?

**Comment by englercj** [comment]
Even using the "Latest Development" selection? (see link in [this comment](https://github.com/pixijs/pixi.js/issues/3066#issuecomment-251615605))

**Comment by weepy** [comment]
So in iOS Chrome - the latest dev version: Video goes full screen

Mobile Safari - black rectangle.

**Comment by englercj** [comment]
I don't have an iOS device to test on, would you mind opening a new issue so we can track this and get someone to look into it?

**Comment by pr1ntr** [comment]
in ios10 it works with the playsinline tag but it seems that on ios9 i just see a black rectangle.

**Comment by themoonrat** [comment]
There are a few things at play here.
1. Because the pixi example video has sound, there needs to be an 'interaction' to start playing it. That's why it's just a big black box
2. ios10 _can_ play videos automatically, but not if they have sound
3. anything before ios9 can draw the first frame of a video, but as soon as you all play on it within a user interaction, it'll go full screen. It's not natively possible to have ios9 and under to play inline videos. They will always go full screen
