### ISSUE TITLE
Remove Sprite#shader and Mesh#shader properties

### ISSUE THREAD

**Issue by ttencate** [pixijs/pixi.js#3086]
According to https://github.com/pixijs/pixi.js/issues/2290#issuecomment-252630058, `Sprite#shader` doesn't do anything, even though it exists and is documented to work.

My testing suggests that the same is true for `Mesh#shader`.

Should these properties just be removed, including their documentation?

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital is working on great PR that supports them.

**Comment by MuneebBaderoen** [comment]
Im really keen on that PR, I've been searching through the issues for recommendations, and writing a [custom objectRenderer](https://github.com/pixijs/pixi-plugin-example/blob/master/src/PictureRenderer.js) seems a little advanced for me. Taking the plunge though, since working around the missing functionality is turning into more work than doing it the recommended way 😭 

Is there a target release for the PR? Im sure your guys' implementation will be far superior to anything I can get working

**Comment by ctechdevelopment** [comment]
@GoodBoyDigital is there any progress on enabling a custom shader with sprites or meshes? I'm wanting to manually transform the mapping coords in the frag shader of a mesh....

**Comment by ivanpopelyshev** [comment]
@ctechdevelopment tell me more, im doing exactly that right now

**Comment by GoodBoyDigital** [comment]
Closing for now as v5 will lets you create custom meshes and custom shaders to go with them 👍
