### ISSUE TITLE
Refactor TextStyle

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi.js#3121]
Right now to add/remove properties to TextStyle requires a bit of boilerplate. I'd like to change it to be simpler, where all you need to do is add a property and it works.

**Comment by BrianDGLS** [comment]
@englercj Is this still needing work?

Could you give and example of the boilerplate required and what the outcome should be? 

I'll be happy to pick this up with a bit more info.

**Comment by themoonrat** [comment]
This is still something we'd like to do.
@bigtimebuddy had a good idea about ultimately having a single TextStyle that could work across different types, like `Text` and `BitmapText` that we have now. These classes would need a way to register to TextStyle which properties they support. And TextStyle could generate a lot of the setters / getters in code, rather than having to list them all out.

**Comment by AndresMurguido001** [comment]
Just to see if im understanding this correctly, would something like this be what you're looking for?
Creating a text style with bitmap set to true would allow access to properties unique to Bitmap Text, and the default would access regular text properties? 
```js
new PIXI.TextStyle({ bitmap: true, tint: #ccc })
```
