### ISSUE TITLE
No 'children' property on PIXI.DisplayObject

### ISSUE THREAD

**Issue by dmitrymatveev** [pixijs/pixi.js#3126]
Hello,

using latest 4.0.3 release in a webpack setup (appended to bundle as is from vendor folder).

I noticed that at some point PIXI removed child display objects from PIXI.DisplayObject.
However after passing a single DisplayObject to renderer.render(...) function am getting a TypeError from PIXI when it attempts to to access a null 'children' property.

Rendering PIXI.Container works as expected, as it should I guess.

![capture](https://cloud.githubusercontent.com/assets/3842466/19416469/dd546e32-93ed-11e6-9fd2-c194a063228d.PNG)

**Comment by dmitrymatveev** [comment]
is it assumed that DisplayObjects are not passed to renderer directly and only Containers used at root level?

**Comment by ivanpopelyshev** [comment]
it can be removed in destroy(). Dont destroy parent in a event, i suppose :)

**Comment by englercj** [comment]
I don't think we ever "removed" the children property from DisplayObejct. Container has children, but DisplayObject does not (and never has).

This error is probably because `interactiveTarget` has a [`interactiveChildren`](https://github.com/pixijs/pixi.js/blob/e9cb6a164157a62bdb82cec49993bf7e12915a92/src/interaction/interactiveTarget.js#L29) property that defaults to true. When mixed into DisplayObject this means that it will hit this check. This is just a bug, we need to do one of the following:

- Have interactiveChildren default to false in DisplayObject constructor, OR
- Add a check to ensure children exist in processInteractive. `if (interactiveChildren)` -> `if (interactiveChildren && children)`

**Comment by dmitrymatveev** [comment]
#3132 done.

Yep, you are right Chad, I thought I used a DisplayObject in my probe project a year ago but that in fact was a Container as I just double checked :)

And only now I realized that documentation specifically mentions not using abstract DisplayObject (maybe renaming it into AbstractDisplayObject would be a good idea in the future too, but thats my ocd talking)

Nevertheless, here is a pull request with a fix you suggested.

Thanks for quick tips.
