### ISSUE TITLE
ParticleContainer  doesn't  support Filter & Mask

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3131]
I port  the code of  http://www.goodboydigital.com/pixijs/examples/15/indexAll.html  to  PIXI.js v4 with ParticleContainer , the filter no effect ,  after change to Container everything is OK.

===============
I try it on  http://pixijs.github.io/examples/#/filters/  ,  change theContainer to ParticleContainer ,  also not support  Filter and Mask.

**Comment by themoonrat** [comment]
This is by design; the particle container is designed to be lightning fast when it contains and draws sprites from the same texture. To achieve this, there is a trade off of less functionality with it, including no filters / masks etc. This is described in the documentation file for this class :)

https://pixijs.github.io/docs/PIXI.particles.ParticleContainer.html

**Comment by ivanpopelyshev** [comment]
You can add filters and masks to PARENT container :)

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital I think its not a bug, we just need to update docs to solve that, right?

**Comment by finscn** [comment]
@ivanpopelyshev , I've add   filters and masks to PARENT container , but still no effect.

**Comment by finscn** [comment]
@ivanpopelyshev ,  I found the reason : 
When add filters and masks to PARENT container , the filterArea must be set.
But if container is Container ,  filterArea is optional , Why ?

**Comment by ivanpopelyshev** [comment]
Because ParticleContainer does not calculate dimensions of children. Because performance.

**Comment by finscn** [comment]
@ivanpopelyshev , thanks

**Comment by yahiko00** [comment]
@ivanpopelyshev Thanks for the trick about applying filter on parent container :)
You're everywhere! 😄
