### ISSUE TITLE
Can't change RETINA_PREFIX value in the latest PIXI version

### ISSUE THREAD

**Issue by FFankias** [pixijs/pixi.js#3170]
In pixi 4.0.x we overrides RETINA_PREFIX and RESOLUTION properties to handle resolution properly with custom assets directories structure.

Is there some workaround or can you add possility to set these properties?

**Comment by ivanpopelyshev** [comment]
Check if you can use https://github.com/pixijs/pixi-compressed-textures

**Comment by englercj** [comment]
What is the problem you are having? Do you have a reproduction example?

Thanks!

**Comment by themoonrat** [comment]
@englercj this is related to what i mentioned in slack i believe, where properties in the const file are now exported as read only since the move to es6.

**Comment by englercj** [comment]
Oh, sorry I thought we had fixed that

**Comment by Zenext** [comment]
So what would be the best way to go with this one? Just declare these properties with `let`?

**Comment by FFankias** [comment]
temporal solution will be overriding 'textureParser' function in the loader.

```
PIXI.loaders.Loader._pixiMiddleware[1] = function () {
   return function textureParser(resource, next) {
    ....
   };
}
```
where BaseTexture created with required resolution value.

**Comment by englercj** [comment]
This is interesting, because the reason these are readonly is actually *not* because they are declared `const`. They are read only because when we import them into the main core file we use `export * from './const';` which outputs Babel code like this:

```js
            var _const = require('./const');

            Object.keys(_const).forEach(function (key) {
                if (key === "default" || key === "__esModule") return;
                Object.defineProperty(exports, key, {
                    enumerable: true,
                    get: function get() {
                        return _const[key];
                    }
                });
            });
```

There are a couple solutions to this:

1. Rewrite const to be `export default { /* all properties */ }`
 * This requires also rewriting all import locations of const
2. Hack around it by using `module`, `exports`, and `require` directly
 * No rewrite necessary, but breaks ES6 consistency
3. ???

**Comment by themoonrat** [comment]
I'd lean towards 1, with a second choice of 3.

It's kinda... These aren't necessarily all pixi consts, but pixi defaults that users may want to override. So a breaking api change to redefine what these are makes sense. If this was a v4.0 release I'd definitely be in the 1 camp, but this isn't, so i fully understand why 3 would be preferable.

**Comment by themoonrat** [comment]
@bigtimebuddy reminder that this can be closed now :)
