### ISSUE TITLE
vTextureCoord goes up to 0.5 in some cases

### ISSUE THREAD

**Issue by adrianton3** [pixijs/pixi.js#3179]
This seems to depend on the position of the sprite. Repro:
1. go to https://jsfiddle.net/3kL64q8j/2/ - the shader simply outputs u and v to red and green
2. notice that the colors are not as bright as they should be
3. uncomment line 12
4. notice that the colors are as bright as they should be

**Comment by ivanpopelyshev** [comment]
Its ok. https://github.com/pixijs/pixi.js/issues/2867 - use mapCoord thingy

**Comment by funkybjorn** [comment]
adrianton3,

This is my first comment, woo!

I came across the same issue and it boggled me for days till I finally happened upon the solution, rather by accident. It seems the new version of PIXI adds padding to its filter prototype, from what I can tell. I remedied this by creating a reference to the filter, then setting the padding property to 0. Seemed to do the trick.

See below for quick solution:

You had:
```
outputSprite.filters = [new PIXI.Filter(PIXI.Filter.defaultVertexSrc,  '
			varying vec2 vTextureCoord;
			uniform sampler2D uSampler;

			void main () {
				gl_FragColor = vec4(vTextureCoord, 0.0, 1.0);
			}
		')]
```

which I changed to:

```
var filter = new PIXI.Filter(PIXI.Filter.defaultVertexSrc,  `
			varying vec2 vTextureCoord;
			uniform sampler2D uSampler;

			void main () {
				gl_FragColor = vec4(vTextureCoord, 0.0, 1.0);
			}
		`);
filter.padding = 0;

outputSprite.filters = [filter];
```

**Comment by ivanpopelyshev** [comment]
@funkybjorn that's not the solution. Textures are pow2 from a pool, so you have to use mapCoord

**Comment by funkybjorn** [comment]
@ivanpopelyshev 

I see, thank you. My goal was somewhat different than the example above, though changing the padding to 0 here seemed to work for this example as well, which is why I figured I'd share it. I am glad there's a proper solution, though I'm a bit unclear on how to apply it to my specific problem. Perhaps you could clarify? Here is my problem in the most basic terms:

I have a Sprite whose texture will vary in size, but height and width will always be equal, ie. 92x92, 14x14, 189x189, etc. Before I go on, be aware I know how to work with masks, circular or otherwise -  I'm just putting this example in the simplest terms for the sake of clarity.

I need to apply a filter to this Sprite, which needs to act as a perfectly circular mask on this perfectly square Sprite. I wrote shader code before which did exactly this:

![example_right](https://cloud.githubusercontent.com/assets/23385889/20226712/01cc79ca-a7fe-11e6-8d0c-720d813ac393.png)

But after updating to PIXI v.4.1.1, the center of the circle became offset up and to the left:

![example_wrong](https://cloud.githubusercontent.com/assets/23385889/20226729/155ae6c0-a7fe-11e6-9a13-af28b105e16d.png)

I finally solved this and acheved the old result by setting the padding of the filter to 0.

How could I accomplish this using mapCoords instead of changing the filter padding to 0?

I'll omit any code I've written for now to get a fresh perspective.

Thanks!

**Comment by GoodBoyDigital** [comment]
closing this as setting padding did the trick 👍
