### ISSUE TITLE
Missing default export for 4.1.0

### ISSUE THREAD

**Issue by Lapixx** [pixijs/pixi.js#3204]
Hey, we're using babel/webpack to build our Javascript frontend, and I noticed that after the 4.1.0 release, we had to change the way we import Pixi into our files.

```js
// pre-4.1.0
import Pixi from "pixi.js";

// since 4.1.0
import * as Pixi from "pixi.js";
```

I'm assuming this happened after moving some of the code base to ES6 internally (if I understood correctly), but I can't really find anything on whether this is an intentional change or not. I'd propose adding a `default export` for the package as well. Any thoughts?

**Comment by funkjunky** [comment]
This also breaks pixi-react.

I'd recommend not making such changes without a major release.

**Comment by englercj** [comment]
Note that this broke for you because we were using non-es6 modules before. Because of that, babel was hacking around us not using them by adding a fake default export for you. We never had a "default export" before (as we were CommonJS ES5.

Since we do not have a default export the correct way to import Pixi was (and is) `import * as Pixi`. You can add back in that hack by adjusting the babel config to treat pixi as an ES5 module, or use the correct `import * as` syntax.

I wish babel wouldn't do that magic under the hood because it causes confusion like this. For the future, remember that `import X from 'y';` is **not** the same as `var X = require('y');`; however, `import * as X from 'y';` is the same semantics as `var X = require('y');`.

Unfortunately, we use the `export * from` syntax in our exports, so exporting a default object is actually a non-trivial change. going to close this, but thanks for bringing it up, I hope this explanation makes more sense.

**Comment by funkjunky** [comment]
Sorry to bringing this back, I've been away from my personal projects for over 2 months.

You have a global PIXI implementation for people who don't use modules. If that is the case, why couldn't you export that global PIXI object as default?
[p.s. I don't mind if you keep this closed, it's not an imperative issue, because most, if not all, libraries have probably updated to use import *.]
(Side note: I'm not sure if the reasoning was clear last time. The issue was that not having import default breaks other libraries. It's easy for me to import *, but if I include another library like import pixi react and it doesn't import correctly, then i'm up a creek.)

**Comment by englercj** [comment]
Read my previous post and thing of the semantics, `import X from 'y';` is the same as `var X = require('y').default`.

> Side note: I'm not sure if the reasoning was clear last time. The issue was that not having import default breaks other libraries. It's easy for me to import *, but if I include another library like import pixi react and it doesn't import correctly, then i'm up a creek.

Those libraries should've never written that, `import PIXI from 'pixi.js'` was *never valid*. The only reason it worked is because some (not all) build systems hack (incorrectly) ES5 CommonJS modules into having a "default" export (usually by rewriting your import to be correct on building when it detects it is really an ES5 module). If you have `var PIXI = require('pixi.js')` and then you move to ES6 and do `import PIXI from 'pixi.js';` those are *not the same thing*. If those underlying libs are doing `import PIXI from 'pixi.js'` then they should update, because they are incorrect.
