### ISSUE TITLE
PIXI.Text cant be displayed when add to a child container

### ISSUE THREAD

**Issue by gaccob** [pixijs/pixi.js#3223]
take http://pixijs.github.io/examples/#/demos/text-demo.js for example,

I added a container named view to stage,
![1](https://cloud.githubusercontent.com/assets/4684354/19838024/0daacf72-9f01-11e6-82e2-88e4acf9538c.png)

and add textSample to view,
![2](https://cloud.githubusercontent.com/assets/4684354/19838029/1eaf25c0-9f01-11e6-87c2-843f7ec88797.png)

then, the textSample won't be displayed, is it correct or a bug?

**Comment by themoonrat** [comment]
It's correct.. and the reason is the ordering of the children.

You see, within the init() function you have 
```
// add a shiny background...
var background = PIXI.Sprite.fromImage('required/assets/textDemoBG.jpg');
stage.addChild(background);
```
This background is added _after_ the view container is added, and so will be drawn after anything added to your new view container. If you move the
```
var view = new PIXI.Container();
stage.addChild(view)
```
to just before 
`view.addChild(textSample);`
You'll see it works just fine :)

**Comment by gaccob** [comment]
got it, thanks a lot.
