### ISSUE TITLE
Image with no file extension fails to load

### ISSUE THREAD

**Issue by chyde** [pixijs/pixi.js#3241]
Image without a file extension (like 'https://dummyimage.com/600x400/123/fff') fails to load, and gives error: "Uncaught Error: Invalid image type in URL.".   This may be expected for security, but there should be a work around if so.  This error is not in v4.0.0 but in v4.1.1.  (I will investigate and report if I find anything, but still wanted to post just in case)

**Comment by chyde** [comment]
We should get the MIME type of an asset if it has no file extension instead of just throwing.  Looks like it is possible to do without too much effort:  

* http://stackoverflow.com/questions/18299806/how-to-check-file-mime-type-with-javascript-before-upload

**Comment by englercj** [comment]
#3207 should fix this for you.

That link you posted seems to be about getting that information for local resources (on disk) not resources loaded from over the network. Best way for over the network is to use the headers, which we don't have access to when loading via Image elements. If you loaded the blob via XHR and got the mime type that way, it would work better; but also be unnecessary because that would be in the loader and it would actually do that for you now when creating the image element from the blob (see the [blob parser](https://github.com/englercj/resource-loader/blob/master/src/middlewares/parsing/blob.js)).
