### ISSUE TITLE
Is the dev branch is the default branch , now ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3310]
I found when I click the link of src in github , the default branch is dev.

**Comment by bigtimebuddy** [comment]
Yes. We have changed our default to dev, which is where most of the activity is. One benefit is that pull requests will now automatically be made against **dev** instead of **master**. In summary, here are our main branches:

1. **next** working towards next major release (least stable)
2. **dev** working towards next minor release
3. **master** branch for any patches and hotfixes
4. **release** capture of our latest build on master (most stable)
