### ISSUE TITLE
cdnjs link not yet updated 

### ISSUE THREAD

**Issue by dohomi** [pixijs/pixi.js#3312]
Hi there,
took me a while where the error came from:

```<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.2.2/pixi.min.js"></script>```

This link does not exist (yet..), the latest cdnjs version is still at 4.1.1.

It would be great if this project would have its core source in its own cdn.

Cheers

**Comment by englercj** [comment]
Do we even control when this is updated? I've never put pixi on that CDN, and have no idea how it gets there.

**Comment by OSUblake** [comment]
Pixi was submitted to cdnjs several years ago, and is set for auto updating via npm, but this hasn't happened since v4.1.1. You can update it to the latest version by submitting a pull request.

It would also be nice if you could make sure the [jsDelivr CDN](http://www.jsdelivr.com/projects/pixi.js) stays to up to date. Right now, it's at v3.0.7. I would prefer using jsDelivr over cdnjs because you can load multiple files in a single http request.

**Comment by bigtimebuddy** [comment]
Look like our changing the output from "bin" to "dist" broke the auto-updates via NPM. I'm planning to make a PR to cdnjs to fix this auto updating feature and add missing versions 4.2.1 and 4.2.2.

**Comment by bigtimebuddy** [comment]
Here are the updated PRs for those two CDNs. Thanks for pointing this out @OSUblake.
* **jsDelivr** PR: https://github.com/jsdelivr/jsdelivr/pull/14878
* **cdnjs** PR: https://github.com/cdnjs/cdnjs/pull/9687

**Comment by bigtimebuddy** [comment]
cdnjs has been updated, jsDelivr will get updated with the next release.
