### ISSUE TITLE
IE 11 support with Pixi v4

### ISSUE THREAD

**Issue by shanemccartney** [pixijs/pixi.js#3336]
We recently updated Pixi from v3 to v4 and noticed that the autoDetectRenderer is no longer allowing for WebGL to be used with IE 11, in case its of importance the render options we have used are as follows:

var rendererOptions = {antialias:false, view:canvasView, resolution:resolution, transparent:false, preserveDrawingBuffer:false, autoResize:true, clearBeforeRender:true};

this.renderer = PIXI.autoDetectRenderer(width, height, rendererOptions);

The resolution value is determined by the value of window.devicePixelRatio, just in case you are interested :)

So I am wondering is this lack of support for Windows with IE and Edge with PIXI 4 intentionally not supporting these browsers?

**Comment by themoonrat** [comment]
Hi @shanemccartney 
The reason PIXI does not support IE11 is because of it's lack of stencil support in it's WebGL implementation. Looking through the code, the check for the stencil support was added in February 2015.

**Comment by siwel** [comment]
In that case it might make sense to update the supported WebGLRenderer browsers on the [FAQ?](https://github.com/pixijs/pixi.js/wiki/FAQs)

**Comment by GoodBoyDigital** [comment]
Hey @shanemccartney! hope all is well! Thats a bit of an odd one, v4 webGL should certainly be capable of running in IE11. Possible an oversight here. @themoonrat hows about we label this as a browser bug to be investigated.

**Comment by shanemccartney** [comment]
Hey @GoodBoyDigital, yes all is going great! 

I agree something strange within the conditions of what you require for support with WebGL in the latest version of PIXI v4 as I say in v3 WebGL with IE 11 works fine. For now I am just accepting this as a limitation of PIXI v4 as a client wanted us to update an old HTML5 project.

**Comment by GoodBoyDigital** [comment]
hello! Man, took a while to get round to this! - but investigation is complete! After looking into this a little further the issue seems to be specific to older versions of IE11.

In browser stack IE11 on (windows 8.1) does not work with v4. This is due to a particular version not supporting ```STENCIL_TEST ```, ```gl.UNSIGNED_SHORT``` and ```gl.UNSIGNED_BYTE``` 

These are important elements that we use for batching and masking in v4. This being the case, its probably best to use canvas for theses older versions of IE11.

The good news is that All versions of IE11 (windows 10) afterwards and all versions of edge I tested seem to work (and default to the WebGL renderer) thought which is cool! 

Hopefully that all makes sense! 

Cheers!
