### ISSUE TITLE
Graphics arc issue

### ISSUE THREAD

**Issue by istersin** [pixijs/pixi.js#3343]
When creating an arc I get the following: "Uncaught TypeError: Cannot read property 'shape' of null" in PIXI.Graphics.arc, on line var points = this.currentPath.shape.points;

The same code works fine one 4.0.3. Also it might be related to #1086.

**Comment by ggarek** [comment]
Hey, have same issue.

Here is a small [fiddle](https://jsfiddle.net/avprqboq/), which is based on official example for Graphics module.
It shows the problem. My guess is that there is a bug in begin/end -Fill methods.

- The example first draws a triangle, then an arc. If you run it as is, then script wont fail but the arc will be connected to the triangle, despite there are proper begin/end -Fill calls.
<img width="317" alt="screen shot 2016-11-26 at 20 21 54" src="https://cloud.githubusercontent.com/assets/5501062/20642032/04e3a61e-b416-11e6-9b8e-c57c9b0cd2b7.png">


- Then if you try to uncomment a code which draws rounded rectangle, the script will fail with the error mentioned by @istersin

**Comment by staff0rd** [comment]
@ggarek your first issue, where the arc is connected to the previous shape is because `beginFill` and  `endFill` do not actually define the start/finish of a shape, rather they just change the current fill settings for the current shape.  Thus, arc (and arcTo) just continue drawing to the current shape.

I'm not sure what code changes need/should occur, however calling `moveTo` is a workaround; https://codepen.io/staff0rd/pen/aBqmEW?editors=0010

**Comment by staff0rd** [comment]
Closed via #3363

**Comment by ArronFerguson** [comment]
Thank you for this fix! Appreciate it!
