### ISSUE TITLE
Strange behaviour of cacheAsBitmap

### ISSUE THREAD

**Issue by pypmannetjies** [pixijs/pixi.js#3374]
Hi there,

I've found some strange interactions between objects that are cached as bitmaps:

1. Create a graphics object and cache as bitmap
2. Add to a container
3. Cache the container as bitmap
4. Manipulate the child's position
5. Notice strange things happen

Here is a fiddle: https://jsfiddle.net/h91snopz/

Note that only the green block remains - you would expect the container to remain unchanged and / or the red block to be unaffected.

**Comment by staff0rd** [comment]
Not super certain what you're looking at considering your fiddle does not include a reference to the pixi version you're using.  Here's one that points at the dev build; https://jsfiddle.net/39gvo85q/

In that case, the red square is still there, it's under the green square (because the green square was added after).  The reason why it's lost its offset I presume is because cacheAsBitmap is producing a sprite that's anchored at 0,0, rather than the 100,100 that the original rectangle was - which I feel is a bug.

**Comment by pypmannetjies** [comment]
Thanks, I was pointed to 4.2.2 but the fiddle must not have saved it.

**Comment by lancewellspring** [comment]
@staff0rd  I made a codepen to demonstrate this problem more clearly: http://codepen.io/anon/pen/pNpbKm?editors=0010

**Comment by staff0rd** [comment]
Further findings show that the greenblock must be cached, the parent container must be cached, and the red block must be present (but not necessarily cached) for it to break.  Should either the greenblock not be cached, or the parent not be cached, or the red block not be present, then the resulting render is correct.

Difficult to create a test that proves this at the moment considering the bounds on all three objects seem to always be correct.  Additionally, the anchor of the greenblock does not change when switching the caching/presence per the above.

**Comment by GoodBoyDigital** [comment]
haha! Lord knows why anyone would need to cacheAsBitmap within a cacheAsBitmap object :P

**Comment by pypmannetjies** [comment]
Granted it's a weird use case. But suppose you have drawn a graphics object and cached it. Then you add it to a parent container which is itself also cached (maybe due to some lower down class specification). It happens... :)

**Comment by GoodBoyDigital** [comment]
aahhh! I see 👍  @pypmannetjies true enough!
