### ISSUE TITLE
Using a graphics object through generate texture as a displacement filter is not working

### ISSUE THREAD

**Issue by kadir-uix** [pixijs/pixi.js#3390]
What I was trying to achieve is the following: 

Draw a box using the PIXI.Graphics
Use the drawn box as a displacement filter. 
Trying the same with a normal Sprite.fromImage works. 

As a reference I also render the graphics element. Positioning seems totally of to me I am not sure if it's a fault on my end or a bug. 

https://jsfiddle.net/20o6cmt1/2/

**Added sprite to the stage**
https://jsfiddle.net/20o6cmt1/4/

**Comment by ivanpopelyshev** [comment]
I cant test it right now, this laptop doesnt support webgl :( But I see that You haven't add displacementSprite to the stage. It represents the coordinates where filter is applied.

**Comment by kadir-uix** [comment]
You mean this? I tried it but seems like I have forgotten to add it in the fiddle. 
`stage.addChild(stx);`

It does not change the outcome though.

**Comment by GoodBoyDigital** [comment]
hello! I believe the generate texture function should be fixed in the dev branch. 
With regards to the positioning, this is due to the fact that all pixels will be moved 200 by the displacement filter unless the color is grey ( 0x707070 ) eg: https://idesignux.files.wordpress.com/2015/02/diamond_plate_specular.jpg

Hope that helps!
