### ISSUE TITLE
[confused] Why isn't the uniform vec3 passing to the shader?

### ISSUE THREAD

**Issue by lancewellspring** [pixijs/pixi.js#3394]
http://codepen.io/Lancer611/pen/LbeyqP?editors=1010

Right now I have it setup to work as expected, but the glowColor is hard coded in the fragment shader.  Change which glow line is uncommented to use the uniform instead, and see that it doesn't work as expected.

**Comment by lancewellspring** [comment]
changing glowColor in the uniforms object to an array instead of a dictionary with x,y,z works, but the implementation doesn't feel consistent.

**Comment by finscn** [comment]
Passing  an array to  the  ```vec2/vec3/vec4``` of a shader is the specification in WebGL.
the  x/y/z/w, r/g/b/a, s/t/p/q  are just the aliases  in shader.

If PIXI.js supports those aliases, it has to convert dictionary to Float32Array. This way is not efficient I think.

**Comment by englercj** [comment]
WebGL uses TypedArrays for all their vec/mat APIs. We have special handling for vec2 that translates an object with x/y properties into a Float32Array for you to support PIXI.Point. However, since we don't have any objects that are x/y/z we don't have any special support to translate that for you.

I'd be OK with a PR to add this support, but right now using a Float32Array is the correct method (though a normal array will work as well).
