### ISSUE TITLE
BitmapText .textWidth only correct after render?

### ISSUE THREAD

**Issue by userusernamenameception** [pixijs/pixi.js#3461]
After setting the .text property of a BitmapText, the .textWidth is incorrect until after a render. Had to use requestAnimationFrame() to wait when doing re positioning calculations. Is this expected behavior?

**Comment by themoonrat** [comment]
Err, it's expected behaviour right now because that's what the code does, but we can make it better ;)

You see, text isn't updated until it's renderered for performance reasons. Imagine you had a counter, counting up super fast. You wouldn't want to re-create each number in the text class because it's only when it's rendered that you need it to show the right thing.

The normal Text class, for example, makes sure that when you try to get the width of it, it updates the text outside of the rendering loop, to make sure that the value returned is accurate and up to date. BitmapText is not doing this (but it should).

Whilst a fix is created, you can call .updateText() on the object before querying .textWidth. This should give you the accurate measurement without having to wait for a rAF

**Comment by userusernamenameception** [comment]
So fix would be inside the getter for .textWidth to call .updateText before returning value? Do you think that this should also be done for .width? I would sway towards not updating .width until render.

**Comment by themoonrat** [comment]
the fix would be to make the current .textWidth a private ._textWidth, create a read only getter called .textWidth, which calls .validate() before returning ._textWidth;

for the getter of .width (and height),, I believe it should call .updateTransform() before returning the width

**Comment by userusernamenameception** [comment]
.validate is what I was looking for. Thanks :). I'll implement + pr later this evening if I get a chance.
