### ISSUE TITLE
suggestion:  partial render

### ISSUE THREAD

**Issue by iauther** [pixijs/pixi.js#3503]
The following method can realize the partial render mode,  which can improve the render efficiency.

```
displayObj.render(...)  {
...
    if (this.children.length) {
        for (var i = 0; i < this.children.length; i++) {
              this.children[i].render();
        }
    else {
        ....render code
    }
...
}

displayObj.clear(...) {
...
    if (this.children.length) {
        for (var i = 0; i < this.children.length; i++) {
              this.children[i].clear();
        }
    else {
        ....clear code
   }
...
}
```

thus, we needn't render the total frame but the partial area.

**Comment by ivanpopelyshev** [comment]
Which complicates things a lot, and it will actually have bad performance in WebGL. 

If you want to cache some elements, use RenderTexture or cacheAsBitmap.

**Comment by ivanpopelyshev** [comment]
I wont explain all point of how wrong is that, but imagine just one: if an element changed place, there's no way to know where was it before, and thus clear() is impossible.

**Comment by iauther** [comment]
The performance partly depend on the method of the calling.  One can use parent.render, also can use child.render(). I do think that the performance of them is different.
Yes, there are some problem in WebGL. I just give a direction that rendering the changed area instead of the all, no matter WebGL and Canvas. The smaller data-size, the better performance.
It is easy to store the previous position for the movement of the element.

**Comment by ivanpopelyshev** [comment]
> The smaller data-size, the better performance.

Can't be applied to webgl stuff, calculating the overlapping change will take more time. 

> It is easy to store the previous position for the movement of the element.

previous movement, previous size, all previous filters, whole previous state.

**Comment by englercj** [comment]
If did implement partial rendering, we would likely use some kind of "dirty rectangle" implementation, similar to browsers.

The reason we didn't do this is two fold:

1) It is pretty complex to build a dirty-rect rendering system, and it puts a lot of work on CPU. This is a problem because JS is already slow, our bottleneck is almost always CPU; not GPU.

2) Many of the applications built with JS wouldn't benefit from this optimizations. Most games don't do this because too much changes almost every frame.

Certainly won't be doing this anytime soon. But you can do a simple version yourself with cacheAsBitmap and RenderTextures.
