### ISSUE TITLE
Sluggish performance when dragging a sprite with your mouse

### ISSUE THREAD

**Issue by F2** [pixijs/pixi.js#3504]
I made a small sample application that contains a circle which you can drag with your mouse: https://jsfiddle.net/xo6sv8nc/

Even though the FPS is high, the performance feels sluggish. The circle cannot keep up with the mouse movement - it is trailing after the mouse. Try for yourself, or see [this gif](http://i.imgur.com/UbyywtX.gifv) (it runs in slow motion to make it easier to see).

I have googled the issue, and some people suggest that the scene is rendered more often than the handling of mouse events. Allegedly a solution for this should be to change `renderer.plugins.interaction.interactionFrequency`. Its value is normally 10, and I have tried setting it to both 1 (this is the value in the jsfiddle) and 60, but it doesn't change anything.

Does anyone know if it is possible to make pixi more responsive to mouse events?

**Comment by themoonrat** [comment]
In this example, interactionFrequency isn't a factor because it's used more for checking things like mouseovers, and cursor changes. With your dragging, the window mousemove event gets triggered, and that then gets emitted through each of the interactive sprites.

**Comment by GoodBoyDigital** [comment]
This is an interesting one, not really sure why the delay feels so long. Could it be something to do with the fact the interaction manager and renderer run on different ticks?

**Comment by pkieltyka** [comment]
btw, how come pixi has _tick method called so often? I was profiling my game and just realized that the FPS jank was a result of too much time spent in _tick, and when I commented out the _tick code, my game worked the same as before and FPS improved.

**Comment by pkieltyka** [comment]
are new objects made with PIXI automatically added to the listeners? is there a way to prevent this in favor of my own reqAniFrame loop?

**Comment by themoonrat** [comment]
Each AnimatedSprite joins the shared ticker to be able to change frames automatically. The only other place i can think of that could have heavy demands on the tick update is the InteractionManager. It has to check for the mouse move event on each interactive display object... so if you have loads of those i could perhaps see an issue.

The profiling should show where the tick method then goes to?

**Comment by pkieltyka** [comment]
@themoonrat from what I can tell, my slow down were multiple requestAnimationFrame calls, one for my game loop and one from https://github.com/pixijs/pixi.js/blob/dev/src/core/ticker/Ticker.js#L135

It didn't seem that the update in the ticker method stood out from the profiling. Btw, I am on a new MBP (late 2016) on Chrome 56. 

In my particular case where I manage the interaction myself, I'd rather remove all event emitters and tickers. After setting `PIXI.ticker.shared.autoStart = false; PIXI.ticker.shared.stop();` I'm getting consistently 60 fps without any jankiness.

**Comment by englercj** [comment]
Profiling, most of the time is spent in a few functions that we could probably optimize:

![image](https://cloud.githubusercontent.com/assets/944497/25110372/577674a0-2398-11e7-8dda-a9f79a49dbd6.png)

Not convinced this is the reason, but did want to mention it.

**Comment by andrewstart** [comment]
Possibly related to #3895

**Comment by gordyr** [comment]
Is PIXI waiting for a new animation frame before updating the mouse position?  If so, that's the likely cause.  

Ideally PIXI should fire a mouse/pointer event every single time the browser does so that sprites can have their positions updated in synced instantly inline with the browsers native input handling.  Only the rendering itself or any other heavy lifting should be decoupled with the use of ```requestAnimationFrame```.

```
stage.on('pointermove', function(event){
    //Anything here should fire for EVERY single native browser event without delay
});
```

I could be quite wrong with this, but I suspect that PIXI's interactionManager decouples the events, and the above callback, from the browsers native input events in order to deal with hit detection etc.  Meaning that any code placed in the callback above has to wait for the next animation frame before it executes.

While this rightly ensures that the tickers update function is throttled, it also would mean that any position updates made when dragging sprites, as in your demo, will always be a single frame behind the users input.

Again, I could be completely wrong here, i'll try to have a poke around in PIXI's internals over the next few days to see precisely what's going on with input handling.

But anyway, if this is the case, then perhaps the firing of the mousemove/pointermove callback above could be restructured to execute instantly for every single native browser event, allowing any code passed into the callback to be entirely in sync with the users input.   PIXI's hitdetection on the other hand, could still continue to be decoupled with the current use of ```requestAnimationFrame``` and the tickers ```update()``` function.

Doing so would make dragging sprites around as responsive as possible.

Once other potential issue you could be seeing is the infamous Vsync bug in certain versions of both Chrome and Firefox.  If so there's little that can be done other than to continue you bang on at both Mozilla and Google in the respective bug reports.

[http://www.vsynctester.com/](url)

**Comment by andrewstart** [comment]
Pixi updates the mouse position on pointermove/mousemove immediately, and also does hit testing on animation frames.

**Comment by gordyr** [comment]
@andrewstart - Indeed... Having investigated I can see that any attached callback is firing immediately.

My money is on the vsync issue then.  It's been known to adversely impact input lag on effected configurations.
