### ISSUE TITLE
Reverse Z-ordering

### ISSUE THREAD

**Issue by DubiousDillan** [pixijs/pixi.js#3514]
I recognise that there's no z-indexing but my game requires the ordering to be the opposite of what it is right now: the first sprite added should be on top.

There should be an option for this because it's as simple as reversing a loop.

Thanks for listening!

**Comment by ivanpopelyshev** [comment]
There's pixi-display plugin, there's even a demo in pixi-examples

**Comment by themoonrat** [comment]
Options are using the plugin as shown above - or you can manually change order of children for a container. Containers contain a member called children, which is an array you can re-order as you please. Or you could create your own custom build of PIXI that uses .unshift rather than push within the addChild function for Container. 
Hopefully one of these options works for you :)
