### ISSUE TITLE
Why roundPixels uses floor instead of round?

### ISSUE THREAD

**Issue by trsh** [pixijs/pixi.js#3581]
I would prefer that roundPixeled scene, looks as much as possible as the original one (one without rounded pixels), and math.floor clearly does NOT the job.

Consider 3 object:

1) x= 100.1
2) x= 100.5
3) x= 100.99

When floored, they are on same line. But when rounded, 3rd object will be 101, what is visually much closer to original. 

There is no ideal scenario, but math.round is the ideal compromise/midlepoint in my opinion.

**Comment by trsh** [comment]
Ideally I could define it like roundPixels(myCustomFunction|boolean), where myCustomFunction = function(val) { return myroundfunc(val); }

**Comment by themoonrat** [comment]
Not a definitive answer, as I've not looked into it, but I do know I've had personal issues with Internet Explorer and using resolutions less than 1. Essentially, if you have an image that's 25px by 25px, but the draw command says draw 26x26 pixels on that texture (via rounding issues with resolutions); most browsers just silently deal with it, but IE throws errors. Flooring all draw commands via roundPixels solved the problem for us

**Comment by trsh** [comment]
@themoonrat i did not get your point. Sorry. From test I have done, round pixel just takes decimals like 1.90, and before drawing floors to 1. It could also do round and it would become 2. I don't see a problem there.

**Comment by photonstorm** [comment]
Yes, drawImage on IE (and older Firefox) used to crash if you tried to
round-up the number of available pixels the image actually had during
drawing.

However I don't believe it'll make any difference here, because roundPixels
only adjusts the x/y position the image is drawn to, not the dimensions of
it. The original comment misleadingly used 'Width' in the example, where it
should probably have said 'x' instead to avoid confusion.

It's a fair request, although the terseness of it leaves a lot to be
desired ('NOT', 'BAD', etc, is subjective, and unnecessary).



Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by trsh** [comment]
@photonstorm thanks for the remarks. I changed width to x, and removed "BAD" name in original comment. The "NOT" part is not  subjective, if you got the context (floor does a worse job in matching not rounded scene, than math.round - it's a fact).

**Comment by trsh** [comment]
Maybe I can change myself, for my project scope? Can't figure out where :)))

**Comment by finscn** [comment]
I prefer `floor` rather than `round`.
In the similar situation ， most frameworks/engines use `floor` .

**Comment by GoodBoyDigital** [comment]
Hi @trsh, good question! As @finscn mentioned, this using ```floor``` is the standard way to pixel snap stuff. Also as @themoonrat mentions we must be sure to not use numbers larger than the texture dimensions, as this will cause IE to throw an error. Using ```floor``` ensures this never happens.

Cheers!
