### ISSUE TITLE
Graphics.hitArea not triggering interaction when mask attached

### ISSUE THREAD

**Issue by ricklamers** [pixijs/pixi.js#3589]
I think I found a bug in pixi.js. 

If I add a mask like this:

```
this.container = new PIXI.Container();

var mask = new PIXI.Graphics();
//mask.beginFill(0x000000); <-- note I'm not calling this line
mask.drawRect(0,0,500,500);

this.addChild(mask);
this.container.mask = mask;
```

When I run this, I do see that the mask is clipping the content but the interaction is not working, only after I added beginFill(0x000000) it started clipping **and** allowing interaction.

Maybe it's just a mistake on my side, but I spent almost an hour figuring this out. I initially thought I had to set filterArea (which according to the comments in the source is also responsible for interaction clipping in v4, which was hard to find in the docs) in order to get interaction to work.

Maybe this is not so much of a bug as a documentation issue, I just didn't know how to get masking + interaction working. Turns out, I just needed to call beginFill(0x000000) on the masking object.

**Comment by staff0rd** [comment]
Are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js) for us to mess with/debug?

**Comment by ricklamers** [comment]
Hello staff0rd, I've implemented the bug in a codepen. 

Here's the result: 

http://codepen.io/ricklamers/pen/ygVqaB

To find the core problem, Ctrl+F for 'ISSUE'. You'll see this line:

`// mask.beginFill(0xFFFFFF, 1);`

Uncomment it to make interaction work through the mask. 

Kind regards,

**Comment by staff0rd** [comment]
Hey @ricklamers, thanks for the pen.

It would seem the reason that interactive does not work when you don't use a fill is because of [this](https://github.com/pixijs/pixi.js/blob/e1b98404a982467811ee655de8372bd5d1d77177/src/core/graphics/Graphics.js#L863-L866), which is called by `InteractionManager` when [testing hits on masks](https://github.com/pixijs/pixi.js/blob/e1b98404a982467811ee655de8372bd5d1d77177/src/interaction/InteractionManager.js#L794) (note the adjacent code for specifying either `hitArea` or `filterArea` to achieve similar results.

Considering fill is an expectation of `Graphics.containsPoint` (I've opened #3608 to confirm this), I'd say that if there's any bug here it's that the masking works when the fill is not evident.

For the moment, specific to interaction, you must either fill, or use `hitArea` or `filterArea`.

**Comment by ricklamers** [comment]
Hi staff0rd,

That makes sense, the confusion was caused by the fact that masking is working while interactivity is not. If both were not working it would make more sense I think. 

Furthermore, I tried to circumvent the lack of interaction with hitArea of filterArea but to no avail. Could you demo in the pen how you would do that?

Because something like this:

`mask.filterArea = new PIXI.Rectangle(0,200,500,200);`

did not have any effect for me. Also, I couldn't find hitArea in the docs and felt that in v4 hitArea got supplanted by filterArea. But I might very well be wrong on this.

**Comment by staff0rd** [comment]
@ricklamers actually it does look like a bug here.  I tried setting `hitArea` on the `graphics` object and the handlers are not triggered.  Currently the only work around is to use `beginFill`.

I'll write some tests to help determine where the issue is - won't be able to do this until around 24 hours from this post however.  For now i'll mark this as a bug.

**Comment by staff0rd** [comment]
Duplicate #3151
