### ISSUE TITLE
PIXI.Text dropShadowBlur also affect text

### ISSUE THREAD

**Issue by lucap86** [pixijs/pixi.js#3621]
PIXI.Text dropShadowBlur also affect text not only dropped shadow.

https://pixijs.github.io/examples/#/basics/text.js

try to set 

```
var style = {
    fontFamily : 'Arial',
    fontSize : '36px',
    fontStyle : 'italic',
    fontWeight : 'bold',
    fill : '#F7EDCA',
    stroke : '#000000',
    strokeThickness : 5,
    dropShadow : true,
    dropShadowBlur: 8,
    dropShadowColor : '#000000',
    dropShadowAngle : Math.PI / 2,
    dropShadowDistance : 150,
    padding: 10
};
```
is this normal?

**Comment by themoonrat** [comment]
Nopes, it's a bug and I can see where to fix it :) Thanks for reporting!

**Comment by themoonrat** [comment]
May have been hasty on the where I thought I could fix it.... but thanks still lol

**Comment by lucap86** [comment]
thank you,
i've had a fast look to the code.
maybe can be a solution using a different canvas context for shadow in updateText method and than merge it with text one into a single texture?

**Comment by themoonrat** [comment]
We would want to avoid that technique if possible, because it'll be resource intensive. 
I believe the issue is lines 280/281 on Text.js

this.context.shadowColor = style.dropShadowColor;
this.context.shadowBlur = style.dropShadowBlur;

these context styles are set for drawing the drop shadow, but aren't removed for drawing the regular text. I'll give it a go now :)

**Comment by themoonrat** [comment]
Boom. It was an easy fix in the end. Thanks again :)
