### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by juliocanares** [pixijs/pixi.js#365]
Hey guys, pixi.js has support for gif images? Let me know if you have it and I need to insert gifs on canvas, thanks in advance :).

Greeting

**Comment by sbfkcel** [comment]
https://github.com/sbfkcel/pixi-apngAndGif

**Comment by rpatwariingenuity** [comment]
> https://github.com/sbfkcel/pixi-apngAndGif
> 
> Let Pixi.js support apng, gif images. And allow control of its operation.

Is this compatible with PIXI-v5?

**Comment by muhammadhaseebsohail** [comment]
can anyone please let me know how can i animate the gif?
i want to render the full gif.

**Comment by bigtimebuddy** [comment]
Because of the browser limitations with GIF, there is not an easy path and this is unlikely to be a path we invest serious time in. If someone want to make a plugin, it seems like there are some GIF parsing libraries available that might help (and there seems like interest here!)

As a workaround, for animated sequences I'd suggest using AnimatedSprite or creating a video and using video source for the BaseTexture. These options will give you a much better playback experience, better file sizes, and better compression options.

**Comment by muhammadhaseebsohail** [comment]
Thanks @bigtimebuddy
