### ISSUE TITLE
Blur on scale not disabled

### ISSUE THREAD

**Issue by Edisoni** [pixijs/pixi.js#3672]
Pixels blurred 
![2017-01-29 14 14 13](https://cloud.githubusercontent.com/assets/10086099/22403581/41bbcf64-e62d-11e6-87e2-7f77f2510f91.png)

Check link my demo
http://51.15.38.31/

**Comment by staff0rd** [comment]
Hi @Edisoni!  Not sure what I'm looking at here - are you able to make a [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example) on [codepen](https://codepen.io) that displays this issue against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by englercj** [comment]
It has been a while since this has had any activity. Are you still experiencing an issue @Edisoni? Can you elaborate on what you are trying to accomplish and what isn't working?

Thanks!

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍

**Comment by simon-brandt** [comment]
Hi, I think I have a similay or same issue right now. I think @Edisoni was refering to the fact that a small graphic gets blurred when its scaled above 100%. 
In this topic from 2013 there was mention about "unfiltered scaling": 
[http://www.html5gamedevs.com/topic/706-scaling-blur/](url) 
Although I´m guessing 5 year old information would probably be outdated now.
So is there a way to prevent this from happeing and instead of 

![image](https://user-images.githubusercontent.com/29025263/37802299-31825776-2e2a-11e8-849a-075e47295d47.png)

have something more like

![image](https://user-images.githubusercontent.com/29025263/37802322-4beaa0b4-2e2a-11e8-9836-612b19ad4a25.png)

?

**Comment by englercj** [comment]
Have you tried setting the scale mode before rendering the texture?

http://pixijs.download/release/docs/PIXI.BaseTexture.html#scaleMode

**Comment by simon-brandt** [comment]
Thanks alot for the quick reply!
These lines finally worked for me:

`    sprite = new PIXI.Sprite(myTexture);
    sprite.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;    
    sprite.scale.set(6, 6);`
