### ISSUE TITLE
PIXI.Container size changes when cacheAsBitmap is set to true

### ISSUE THREAD

**Issue by krojew** [pixijs/pixi.js#3681]
When setting cacheAsBitmap to true, the size of the container (width, height) changes for some reason. The extra space is black. When not using caching, the size is correctly computed from its children.

**Comment by staff0rd** [comment]
Hey @krojew, are you able to supply a [pen](https://codepen.io) that displays this issue you're having against the latest [dev build](//d157l7jdn8e5sf.cloudfront.net/dev/pixi.js)?

**Comment by krojew** [comment]
For some reason I'm unable to make pixi draw anything in a pen. I did some investigation and this seems to be related somehow to container pivot. Here are the steps to reproduce:

1. Create a container with 135x135 grid of 32x32 sprites.
1. Cache it as bitmap.
1. Add it to the stage container.
1. Increase the stage pivot point coordinate.

In this case, the stage container gets its width and/or height increased as the pivot coordinates increase. If no caching as bitmap occurs, both width and height remain unaffected.

**Comment by staff0rd** [comment]
Here's a template; https://codepen.io/pen?template=XjmggJ

**Comment by krojew** [comment]
Here you go: http://codepen.io/anon/pen/WRMbyO

If you move the mouse over the view with the left button down, you should see the stage size in the console. Notice how it's changing with the pivot.

If you comment out the container.cacheAsBitmap = true; line, the size will not change with the pivot.

**Comment by staff0rd** [comment]
Simplified; http://codepen.io/staff0rd/pen/wgyMrz?editors=0010

**Comment by staff0rd** [comment]
Seems specific to WebGL.

WebGL: http://codepen.io/staff0rd/pen/YNOEzb?editors=0010
Canvas: http://codepen.io/staff0rd/pen/rjZYBJ?editors=0010

Note the pivot distance is visible in the WebGL render, but not in the Canvas render.

**Comment by staff0rd** [comment]
Occurs on Canvas also provided you don't render between setting `cacheAsBitmap = true` and changing the pivot: http://codepen.io/staff0rd/pen/mRgeNG?editors=0010

**Comment by BossLevel** [comment]
Just as an FYI, I'm managing to recreate this issue without any manipulation of the pivot - simply calling cacheAsBtmap can cause it to happen.

**Comment by staff0rd** [comment]
@BossLevel pen?

**Comment by BossLevel** [comment]
Yeah I'm sorry but I'm struggling to provide one that illustrates the problem - my code base/render process is complex and there are clearly extraneous factors involved and which to date I am unable to narrow down. However I definitely know it's happening - I'm drawing identical lines on overlapping "layer" containers and when I cache one of them, one of the lines will shift slightly off-center due to a slightly larger width/height. The pivot on all containers is initially set to 0.5 and never re-set.

Re the extraneous factors, I did find one of them to be related to #3374 - turning off cacheAsBitmap on the child solved the issue. I'm now only caching on the "layer" containers themselves but as I said, the problem persists in other cases.

Due to other factors, I had to park this and move on, but I'm hoping to get a chance to look at it again later this week.  However my hope was that with their being a working, illustrative pen above, I wasn't impacting the debugging/PR process by not furnishing one at this stage.  I promise I will post more info as and when I get it though.

**Comment by Armegalo** [comment]
I also am experiencing a similar problem when caching. It seems to me that PIXI is caching from 0,0 to the bottom right edge of my object (a bitmap text), no matter how I do it. The object origin and width and height modify themselves as soon as I cache. This throws out a shader I'm throwing over the object.
I can cache the object, or its container, even the containers container. It only stops doing it if I place the object at 0,0 through any manipulation of containers you care to mention.

**Comment by ivanpopelyshev** [comment]
Fixed in #3681
