### ISSUE TITLE
4.3.3 to 4.3.4 - Cursor's doesn't work anymore

### ISSUE THREAD

**Issue by kaansoral** [pixijs/pixi.js#3689]
Hi

I don't know whether this a known issue, yet, on the 4.3.4-dev version, the .buttonMode or .cursor==="pointer" doesn't render the cursor as "pointer"

**Comment by bigtimebuddy** [comment]
Ping @andrewstart

**Comment by andrewstart** [comment]
It seems to be working fine in http://pixijs.github.io/examples/?v=dev#/basics/click.js

**Comment by kaansoral** [comment]
I'm toggling 4.3.3 and the latest 4.3.4, what works in 4.3.3, doesn't work in 4.3.4 for me

Is there anything specific I should look for?

The .cursor gets set to "pointer" - yet the pointer doesn't show up

**Comment by themoonrat** [comment]
@kaansoral There is also an option you can choose at the top of the drop down list on that examples page called 'latest development'. This is code newer then 4.3.4 and has reworked cursor code. This is what andrewstart linked to... please try it out as it's due to be in the next actual release, so feedback on if it works helps us massively!

**Comment by GoodBoyDigital** [comment]
Hey Chaps, I get the same issue. Weirdly no pointer for me on the example?

**Comment by GoodBoyDigital** [comment]
it kind of flickers in for a micro second I think

**Comment by andrewstart** [comment]
That's odd, on Windows with FF 51 and Chrome 56, I'm not seeing any cursor problems on any release or the latest dev. Also, for the record, 4.3.4 should have older InteractionManager code - both the major refactoring and my cursor changes are only in the latest development, as there hasn't been in a release yet. As such, if regular 4.3.4 is having problems, then something confusing is afoot.

**Comment by kaansoral** [comment]
I'm using these:
```
Unminified: [http://pixijs.download/dev/pixi.js]
Minified: [http://pixijs.download/dev/pixi.min.js]
```

Similar to @GoodBoyDigital - Example works for me, however, on the same machine, OSX Macbook, same browser, in my own game, no pointer for me, however, right after clicking, the pointer is very briefly visible

**Comment by bigtimebuddy** [comment]
I'm also not able to reproduce this bug.

@kaansoral and @GoodBoyDigital could you double-check that you cleared your browser's cache and then re-run? Also, can you be specific about which browser(s) you're using?

**Comment by kaansoral** [comment]
I'm using Chrome 55.0.2883.95 on OSX, importing the file manually, so the browser cache doesn't apply, I've just re-verified the issue too, simply, if I toggle back to 4.3.3, cursors work

From my side, I don't know how the PIXI Cursor system works, so I can't look for a cause efficiently, since the game has overlays, I wonder if they could be a cause, however, since @GoodBoyDigital experienced the same issue on the example, I suspect it's a browser based issue

**Comment by bigtimebuddy** [comment]
I'm using the same browser (version and all) and testing on the example page and seeing no difference in cursor behavior from 4.3.3, 4.3.4 or dev. I don't think it's a browser bug.

Here are the steps I took: I loaded each version, cleared browser cache, hovered over the sprite and the cursor changed to a pointer. When rolling out, it changed back to default cursor.  Is this not the behavior you're seeing @kaansoral or @GoodBoyDigital 

Thanks for helping us track this down.

**Comment by kaansoral** [comment]
From @GoodBoyDigital's findings, I theoritized that it's a bug that differentiates browsers

Separately, on my local system and on my live game, I can clearly observe the 4.3.4-dev introducing the issue

Here's the game if you want to check it: http://adventure.land - the NPC's, Door's supposed to have "pointer"'s, yet, for me, nothing has pointers anymore (The live version uses an earlier 4.3.4 dev version, but for the sake of this issue, the cursor issue is present in both)

(FYI, I've also tested with/without pixi-display, the result was the same)

Let's assume there is no bug, what could cause be the cause on my end to break the cursor behaviour?

**Comment by andrewstart** [comment]
In your game currently, it appears to be displaying the bug that came from the post 4.3.4 InteractionManager refactor. I fixed it in my cursor overhaul, but the bug was that the mouseover cursors only worked while you were holding the mouse down on something that should be a pointer. As far as problems where you know that you are using the latest dev, I have no idea what could cause it. 

When using the latest dev, I'd suggest setting 
```javascript
yourRenderer.plugins.interaction.cursorStyles.pointer = function() {
    console.log('Should be a pointer');
};
yourRenderer.plugins.interaction.cursorStyles.default= function() {
    console.log('Should be default cursor');
};
``` 
That should give a little more insight into what is happening by replacing the CSS changes with callbacks to your code.

**Comment by kaansoral** [comment]
Just re-updated to the latest version to re-make sure

Using the code:
<img width="228" alt="screen shot 2017-02-04 at 04 50 58" src="https://cloud.githubusercontent.com/assets/170243/22614621/9dc5a8cc-ea95-11e6-9633-086ef389dd05.png">

Let me know what we can check next, these are supposed to be pointers (.buttonMode is true and .cursor is "pointer" on these entities)

**Comment by andrewstart** [comment]
That is certainly interesting - that callback should only be getting called when the cursor changes from not-default to default. The only way it should get called otherwise is if InteractionManager is getting a lot of `mouseout` (technically `pointerout` events from a mouse) events from when the mouse leaves the canvas. Also, it apparently never considered it to have moused over any `pointer` style display objects in the first place.
I've got a busy weekend, but I will think about what comes next. Right now I am thinking of swapping out the `pointerout` event for `pointerleave` to see if that changes anything. Given the [docs for `pointerout`](https://developer.mozilla.org/en-US/docs/Web/Events/pointerout) and what we use it for, it might be that `pointerleave` is all we need anyway.

**Comment by andrewstart** [comment]
@kaansoral could you try using http://pixijs.download/fix-mouse-events/pixi.js ? I've added a bunch of logging to try to figure out exactly what is going on when you mouse over pixi elements.

**Comment by kaansoral** [comment]
Sure, thanks

<img width="582" alt="screen shot 2017-02-06 at 06 31 06" src="https://cloud.githubusercontent.com/assets/170243/22633857/f4430964-ec35-11e6-8e8c-712c99802486.png">

As far as I test, it's always this in repeated form

**Comment by andrewstart** [comment]
And that repeated bit is when the mouse is over a buttonMode object? It's odd that when moving, there weren't any logs from event handling, like `onPointerMove - event type: pointermove` or something.

**Comment by kaansoral** [comment]
I think the problem is, there is an interference with this new method, something is acting like an interactive object and it's resetting the cursor

<img width="644" alt="screen shot 2017-02-07 at 01 07 31" src="https://cloud.githubusercontent.com/assets/170243/22668506/fb4972a6-ecd1-11e6-941d-085d9c4043c7.png">

I was probably a bit sleep deprived when I originally tested the modified pixi.js, in hindsight, it now seems obvious

I have an interactive map/container, clicks to this map/container is for the character to move, the map/container doesn't have a pointer

There are doors/entities on top of this map/container, they have special cursors, what happens is that, instead of these entities determining the cursor, the event is likely propagating somehow and the map is resetting the cursor - I've verified this by setting my map/container to `.interactive=false` - It's also the reason this doesn't manifest in the example, as there is no interactive parent

**Comment by andrewstart** [comment]
That does make a lot of sense. That seems like a thing that should be handled by the cursor code, so I will have to think about it/dig into the event bubbling that happens. It also occurs to me that I should change where I am comparing 'new' cursor mode to the current one, so that it doesn't keep setting it to `null`/`'default'` repeatedly like that.

**Comment by andrewstart** [comment]
Could you try that branch again? I've removed all those logs and made a change that I think will fix the issue.

**Comment by kaansoral** [comment]
Tested, it does work indeed

As another heads up, `.defaultCursor="help"` is ineffective, don't know whether it's because this is just a test build or the method to modify the cursor has changed

**Comment by andrewstart** [comment]
The method to modify the cursor has (will) change - `.cursor` is the important property on DisplayObject (`defaultCursor` is deprecated). `cursor` is a cursor mode rather than CSS. The `cursorStyles` object on the InteractionManager for your renderer is a dictionary of what to do for each cursor mode, and by default it only has entries for `default` and `pointer`.
Documentation for the property is:

> Dictionary of how different cursor modes are handled. Strings are handled as CSS cursor values, objects are handled as dictionaries of CSS values for interactionDOMElement, and functions are called instead of changing the CSS.
