### ISSUE TITLE
Mipmaps not updating?

### ISSUE THREAD

**Issue by fanjules** [pixijs/pixi.js#3692]
When I call .update() on .texture or .texture.baseTexture, everything proceeds fine, but the mipmap never updates so when viewed from afar the old image is still present.

Even when I set .mipmap=false for the texture and then call update(), the mipmaps are still used and they are never disabled.

Am I missing something?

**Comment by GoodBoyDigital** [comment]
Thanks for sharing! If you could provide a fiddle for us to debug that would be ace 👍

**Comment by fanjules** [comment]
Thanks for your swift response.  Not familiar with making a fiddle (especially with pixi.js running) I suspect it would take as much time as I've already spent this morning trying to sort it!

If it's of any help, the source image is a HTML Canvas, nothing unusual about the tasks.  Very simple:

`Lcanvas=Lsprite.texture.baseTexture.source;`
`\\`
`\\modify canvas`
`\\`
`Lsprite.texture.baseTexture.update();`


For now I have resolved the situation by calling .dispose() on the baseTexture before .update(), but suspect this is an inefficient way to go about things?

**Comment by ivanpopelyshev** [comment]
yep, that's true.

**Comment by staff0rd** [comment]
Here's a template; https://codepen.io/pen?template=XjmggJ

**Comment by fanjules** [comment]
Ah, thanks!  Here goes then, hope this works: https://codepen.io/fanjules/pen/xgzOYw

A sprite is generated with a HTML Canvas object, which is filled with a yellow box.  After 1 second, the box is changed to red and the texture updated.  It is also scaled to 0.1 (causing the mipmap to be rendered).  The box remains yellow.  Try it scaled 1.0 instead, and of course it is red.

I've also just noticed that the problem doesn't occur in Microsoft Edge, but is present in Chrome and Firefox.

**Comment by staff0rd** [comment]
Nice pen @fanjules, clear and concise.

The matter of mipmaps not updating after the texture has been created seems to be by design.  Note the docs on `BaseTexture`;

> Set this to true if a mipmap of this texture needs to be generated. This value needs to be set before the texture is used

[In the code](https://github.com/pixijs/pixi.js/blob/bed84b9ff04cf98c536401d36841d447b74917fe/src/core/renderers/webgl/TextureManager.js#L141-L144), generate mipmaps is only called if the texture didn't previously exist.  Interesting that you find Microsoft Edge still works - perhaps a bug/feature there is enabling it.

I'm not well versed on webgl so I'm not sure whether it's valid to call `generateMipMaps` on every `updateTexture` or not.  What do you think?

**Comment by spacejack** [comment]
I just ran into this problem. Is there a way to get the mipmaps to update when the texture is updated? I think this should be the default behaviour.

**Comment by ivanpopelyshev** [comment]
I've made workaround:

```js
renderer.bindTexture(myTexture, 0, true);
renderer.gl.generateMipmap(renderer.gl.TEXTURE_2D);
```

**Comment by spacejack** [comment]
@ivanpopelyshev thanks very much, it seems to work!
