### ISSUE TITLE
Adding WebGL game to iOS home screen causes severe performance loss.

### ISSUE THREAD

**Issue by sommerper** [pixijs/pixi.js#3697]
A drop from 60 fps to 1-2 fps occurs when game is run via home screen link.

When switching to CanvasRenderer the performance is ok again but then other problems happen with scaled or masked elements.

I'm not sure if this is related to Pixi or iOS. As far as I know the Nitro engine was enabled on the home screen in iOS 8.

A thing I noticed was that the game runs at a high frame rate the first second and then drops to the aforementioned 1-2 fps. Could it be a memory leak problem?

**Comment by macguffin** [comment]
FYI Hi just tested a game that is fairly animation heavy, pixi, spine2d
animation with meshes. I'm not seeing and performance drop ( iPhone6 iOS 10)


:)

**Comment by sommerper** [comment]
@macguffin And you are sure you are WebGLRenderer? I mean not the AutoDetectRenderer which could maybe switch to CanvasRenderer.

**Comment by macguffin** [comment]
Hi to be sure I've forced webGL and my game still runs fine so the issue might be due to something else.

Have you got a URL, I could see how it runs on a different device if you like?

https://medium.com/@firt/dont-use-ios-web-app-meta-tag-irresponsibly-in-your-progressive-web-apps-85d70f4438cb#.macr8qces

According to this article:
_On iOS the engine is not the same as the browser, there are differences in compatibility, bugs and they work in separate containers for cookies and local storages. You must test it there._

So maybe there is something else the the homescreen engine doesn't like.  
Are you using anything other than pixijs?
If you run your game in Chrome with the dev tools and the timeline profile running are you getting that classic 'saw tooth' graph?
Finally what's your code doing in the first few seconds, just building the game etc?
:)

**Comment by sommerper** [comment]
Sorry, it took so long to get back to you. I did manage to track down the issue and it was due to the blur effect being added to the main container.

This had _no_ effect whatsoever in iOS Safari but caused a serious slow down when run via the home screen. Android is not affected by this.

The workaround is to only add the blur filter when you need it and completely remove it when it's not in use.

I don't really think this is a bug with pixi but I'll let it be up to you to close it if you want.

**Comment by englercj** [comment]
Closing, since this seems answered.
