### ISSUE TITLE
How many guys come here because of Google's PangolinLove Game ?

### ISSUE THREAD

**Issue by AJLoveChina** [pixijs/pixi.js#3731]
I am.... haha

**Comment by ivanpopelyshev** [comment]
They have used 4.0.3, its more stable than 4.2-4.3, I hope that 4,4 will be next stable version :)

**Comment by kaansoral** [comment]
That's very very interesting, Indeed somewhere after 4.0 things became very chaotic

**Comment by ivanpopelyshev** [comment]
@kaansoral btw, you asked about pixi-tilemap before, and i updated it. Also, dev version have my fixes for transforms and other stuff that was broken in 4.2

**Comment by kaansoral** [comment]
My approach is a bit blind when it comes to pixi bug hunting, players report and re-report issues, as it is, there are recurring WebGL crashes, it seems `CONTEXT_LOST_WEBGL` might be to blame, however, I don't have enough to go on myself, and to justify and point to a tangible bug

That's why I found the `4.0.3` selection interesting, I wonder if they continually test PIXI and stayed at `4.0.3` - But I guess someone would report the issues if that was the case

**Comment by GoodBoyDigital** [comment]
honestly I wouldn't read too much in to the version they used, most people grab a copy and get coding and generally don't update mid project.

**Comment by stbaer** [comment]
Google's PangolinLove Game ? What's that, is there a link?

**Comment by ivanpopelyshev** [comment]
@stbaer 

https://www.google.com/doodles/valentines-day-2017-day-1

**Comment by englercj** [comment]
Closing this now, but thanks for telling us!
