### ISSUE TITLE
[Docs] hitArea

### ISSUE THREAD

**Issue by lgraziani2712** [pixijs/pixi.js#3775]
I was searching information about how/when/where to use `hitArea`, and didn't find anything about it in the docs.

1. On what classes can be used?
2. How it works? Is it magic, or I have to check on my own something?

Thank you!

**Comment by bigtimebuddy** [comment]
`hitArea` is a mixin from interaction, which means it's added to DisplayObject. 

https://github.com/pixijs/pixi.js/blob/8fe33af38245326255e5556ea0e1479b4814f0f2/src/interaction/interactiveTarget.js#L32-L38

Might be more useful if we document these mixins as properties of DisplayObject so they are easier to find.

**Comment by ivanpopelyshev** [comment]
That's the only place: https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L863

Its deep inside interactionManager.

**Comment by LucianoGraziani** [comment]
Oh~~

So only `Container, Sprite, and TilingSprite` (https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L758) can have a hitArea prop?

And the hitArea prop will be validated only if `interactive` is true, right?

**Comment by ivanpopelyshev** [comment]
Sprite and TilingSprite are containers too. I dont know why is it there. 

> And the hitArea prop will be validated only if interactive is true, right?

yep

**Comment by LucianoGraziani** [comment]
Perfect! Thank you @ivanpopelyshev 

Yes, it is shown in the docs, by the way.

**Comment by LucianoGraziani** [comment]
I will reopen this. Why DisplayObject mixin is set in InteractionManager?

BTW, if I search `interactiveTarget` into docs, I won't find anything. But if I go to DisplayObject, I will see the `@mixes PIXI.interaction.interactiveTarget`, and I can access to that file from there.

But that isn't friendly for new people (like me 😛).

Another thing. If I go to the `interactiveTarget` documentation, I only will find two methods: `buttonMode` and the deprecated `defaultCursor`.

`buttonMode` is being shown because has the `@memberof PIXI.interaction.interactiveTarget#` attribute, and is a public method.

**Comment by staff0rd** [comment]
@lgraziani2712 yeah that looked wrong - I've opened #3784 to fix.  Thanks for the report!
