### ISSUE TITLE
Masking/Clipping issue

### ISSUE THREAD

**Issue by vanderlin** [pixijs/pixi.js#3778]
![image](https://cloud.githubusercontent.com/assets/149997/23283949/bc7407d0-f9f6-11e6-8916-9b3c0f691080.png)

I am trying to figure out the masking system in Pixi, but I am getting the results above. Is there a way to change the globalCompositeOperation or is that not how this is getting clipped? I want the opposite masked and not the weird overlapping parts. 

Here is a codeped that shows the results
http://codepen.io/vanderlin/pen/KWKoQa

Am I missing something, just want to make a eraser.

**Comment by staff0rd** [comment]
Hi @vanderlin.  Did you fix this?  Looks like this for me;

![image](https://cloud.githubusercontent.com/assets/6289998/23337902/26c05e4e-fc50-11e6-80f5-77fd399f1632.png)

**Comment by DerivcoHK** [comment]
I found that the demo set the sprite as a mask instead of graphics as a mask, Therefore, the sprite become the alpha mask. The intersection problem still exist

**Comment by englercj** [comment]
Ping! Is this issue still active? Seems to be working for me in the demo?

Can you elaborate on what the problem is and provide a demo showing the broken behavior?

**Comment by DerivcoHK** [comment]
Change the line 12
graphics.mask = room
into
room.mask = graphics;
You will see the problem

**Comment by englercj** [comment]
I see, this is because each circle is an individual shape and the shapes overlap. If you instead combined the circles into a single polygon you used as the mask it would work.

Generally the best strategy for an "eraser" type mask like this is to draw the circles to an offscreen canvas, then use that canvas as the texture for the mask. That will "combine" the shapes for you. You could also render the graphics object with all the circles to a RenderTexture that you then use for a mask.

Hopefully one of those methods work better for you, let me know if you have any more questions or can't get it to work!
