### ISSUE TITLE
[v4] Intent Clarification: Filter vs Shader

### ISSUE THREAD

**Issue by atkinchris** [pixijs/pixi.js#3788]
Looking through the examples and issues, I see lots of demos for filters - but few for shaders.

What is the Pixi intended _paradigm_ for when to use a filter vs a shader? For example, when is it recommended or appropriate to use `Sprite.filters = [myFilter]` vs `Sprite.shader = myShader`?

**Comment by ivanpopelyshev** [comment]
I don't know what paradygm was used in the start. 

How i see it:

Shader can be applied to many batched sprites. Filter is applied to one big sprite to make it look cool. 1000 sprites with Filter will destroy your performance.

1. Filter must be applied to region of texture, and not full texture, (mapCoord,unmapCoord) is required if its not pixel-to-pixel shader. 
2. Filter must use filterClamp, otherwise there'll be problems
3. It may have two inputs - the "background" and "sprite" that it applies on it.

**Comment by atkinchris** [comment]
Hi @ivanpopelyshev - thanks for the clarification. That makes sense - even if there does seem a little magic around shader batching.

Would you recommend shaders over filters for rendering sprites to intermediate textures?

**Comment by ivanpopelyshev** [comment]
Rendering sprites to what? 

There's a problem with batching - if you look at https://github.com/pixijs/pixi-plugin-example - that's v4 example for shaders, that renderer doesnt know how to batch. It needs to fill groups in "render" and then draw them in "flush". 

I hope to solve that problem for pixi 4.5. Both shaders and filters need an enchantment to make their use-cases more clear.

**Comment by atkinchris** [comment]
I meant in the case of rendering a `Sprite` (or any other `DisplayObject`) with
```javascript
const renderTexture = PIXI.RenderTexture.create(...)
app.renderer.render(sprite, renderTexture)
```

`flush` in the `pixi-plugin-example` is a no-op?

**Comment by ivanpopelyshev** [comment]
Yes, because it renders stuff in "render" instead of batching it.

RenderTexture case has the same performance, so I recommend shaders.

Just for your knowledge - it gives one extra edge for some shaders - "pixi-picture" plugin can utilize it to emulate blendModes that exist in canvas2d but not in webgl. Those shaders can't be batched, they are all about beauty, not the performance.

**Comment by ivanpopelyshev** [comment]
@ctechdevelopment no, you have to create your own renderer for it (pixi-plugin-example) . But I think i can help for your case.

**Comment by ctechdevelopment** [comment]
@ivanpopelyshev great - I'll use one of the existing renderers as a basis and change what i need - seemed like an overkill... but only just :)

**Comment by ivanpopelyshev** [comment]
TilingSprite is a bit difficult, but you can see that it actually takes uvTransform, passes to fragment or vertex shader. Same can be done in your case, just with a lot less code.
