### ISSUE TITLE
TextStyle.align justify support

### ISSUE THREAD

**Issue by jwhayman** [pixijs/pixi.js#3799]
Hi, just wanted to know whether a 'justify' alignment option would be considered for the TextStyle.align property. Something similar to the ```text-align: justify``` style in CSS. Thanks.

**Comment by LukMona** [comment]
Hi, maybe you were thinking about adding that? justify for text align will be much appriciated by me and my team, I desperetaly need that to dazzle others with my amazing text style.

**Comment by bigtimebuddy** [comment]
Great idea, I think we would only consider this for v5 (the current **next** branch) and are closing v4 to new features. We really want to improve Text for v5, so we'll keep this in mind.

In the meantime, I created this Text object that's rendered using SVG instead of context2d text rendering. This would easily support justify  (bonus, supports browser emojis):
https://jsfiddle.net/bigtimebuddy/wyacb6g1/
