### ISSUE TITLE
Application Ticker Animation (Flickering)

### ISSUE THREAD

**Issue by ghost** [pixijs/pixi.js#3835]
Hi, I think this is a bug. At the least it seems confusing/inconsistent. I made two Code Pens to demonstrate.

[Pen 1](http://codepen.io/anon/pen/yMPXYj)  uses Application and Application.ticker.add

[Pen 2](http://codepen.io/anon/pen/KWyqZB) uses requestAnimationFrame instead. Otherwise, the two Code pens are the same.

What they do is create a simple sprite (a red square). When you click on the canvas (anywhere on the bottom frame) the sprite is added to the stage at position (0, 0). Then in the animation function, the sprite is moved to the center of the frame. You can click again to remove the sprite and repeat the test.

With Pen 2 (requestAnimationFrame) it works as expected. When I click on the canvas, the red square appears at the center.

But with Pen 1 (Application/ticker) the red square flashes in the upper left corner and then re-appears in the center.

So it seems the sprite is being rendered in between ticks. If it works this way by design, then I'll work around it, but I'm hoping it's a bug with an easy fix:) Also, if it's intentionally different, I'm curious as to why?

**Comment by jaspervaz** [comment]
P.S. - On [Pen 1](http://codepen.io/anon/pen/yMPXYj) if you happen to click right before a tick, then you won't notice the issue. Just click again to remove the square. Then click again to add it again. The flickering occurs at least 90% of the times that I test it, but just in case you don't see it the first time, try again :).  Also I've tested with both v 4.4.1 and 4.4.2 (the Code Pen uses 4.4.2)

**Comment by andrewstart** [comment]
In the first example, the Application's render and your `animate()` function are listeners to the same ticker, but the Application's callback got added first, so it gets handled first. As such, in a frame the event order is mouse -> render via Application -> your callback. I'm not really sure what the best fix for this behavior would be, possibly adding some sort of `addLate()` method to Ticker so that Application or anyone else can specify a 2nd stage tick callback.

**Comment by jaspervaz** [comment]
But shouldn't the animate function be called **before** the application renders, giving me a chance  to update my sprites before each rendering? For example, with Babylon JS engine, you can pass your animation function to registerBeforeRender(). I guess I assumed that app.ticker.add() worked the same, allowing me to specify code to be run before each rendering...

**Comment by andrewstart** [comment]
The Application isn't running the ticker, it is hooked into the ticker with `app.ticker.add()` just the same as you so that it can render each frame.

**Comment by jaspervaz** [comment]
Wouldn't it be more correct/useful/intuitive for the ticker to call my animate function before the application's render function then? Or is there a way to add my ticker to the beginning of the chain? Or is only appending to the end of the chain supported?

**Comment by jaspervaz** [comment]
If there's an array of functions that the ticker calls, it seems like my animate function could just inserted to the beginning of it instead of added to the end?

**Comment by jaspervaz** [comment]
Sorry, hopefully I'm understanding it well enough to ask the right questions now;)

**Comment by andrewstart** [comment]
The array of functions that the ticker calls is hidden inside an EventEmitter from EventEmitter3. Playing with that order without having a priority functionality is pretty fiddly and generally not recommended. That's why I think having `ticker.add()` and `ticker.addLate()` would be the simplest solution - the ticker would just handle 2 different events internally, instead of just the current one.

**Comment by jaspervaz** [comment]
OK, for now I'll just work-around by calling my positioning function right before adding new elements to the stage and again in the animate function, so that the position is always correct. Thanks for explaining. yeah ticker.addLate() would make it easier, but good to know what's going on in the meantime :)

**Comment by jaspervaz** [comment]
@andrewstart , @ivanpopelyshev Hi guys. Working around this issue ending up making my game coding so cumbersome/annoying, that I ended up making a little edit to PIXI.Application. You can now optionally pass a 6th parameter to its constructor, named animate. If passed, this function is added to the ticker before Application.render. This simple solution fixes the flickering problem. Now that the animate function is called first, before render, game code behaves as expected, since the animate-render order is now consistent with the old requestAnimationFrame paradigm, where render was typically called at the end of the animate function. A caveat is that a context for the animate function is not able to be passed. I considered adding a 7th optional argument to PIXI.Application's constructor, which would allow a context to be provided, but I don't personally need this and I'm not sure if it's the most elegant solution. Anyway, here's the new Application class, if anyone wants to try it out I guess you can just copy and paste it over the old Application class. The changes are very minimal, maybe 5 or 6 new lines of code and a few lines of documentation, using version 4.4.2. 

PS - this eliminates the need to set positions before adding to the stage and after resizing, since the positions can now be handled in one place, the animate function, without that annoying flickering. I think there are many other cases where updating the display object's properties before rendering, rather than after, is desirable, but I can't think of them right now;)  Of course, there may well be a better/more elegant solution, but this works for now and is extremely simple and straightforward :)

`    var Application = function () {
        /**
         * @param {number} [width=800] - the width of the renderers view
         * @param {number} [height=600] - the height of the renderers view
         * @param {object} [options] - The optional renderer parameters
         * @param {HTMLCanvasElement} [options.view] - the canvas to use as a view, optional
         * @param {boolean} [options.transparent=false] - If the render view is transparent, default false
         * @param {boolean} [options.antialias=false] - sets antialias (only applicable in chrome at the moment)
         * @param {boolean} [options.preserveDrawingBuffer=false] - enables drawing buffer preservation, enable this if you
         *      need to call toDataUrl on the webgl context
         * @param {number} [options.resolution=1] - The resolution / device pixel ratio of the renderer, retina would be 2
         * @param {boolean} [noWebGL=false] - prevents selection of WebGL renderer, even if such is present
         * @param {boolean} [options.legacy=false] - If true Pixi will aim to ensure compatibility
         * with older / less advanced devices. If you experience unexplained flickering try setting this to true.
         * @param {boolean} [useSharedTicker=false] - `true` to use PIXI.ticker.shared, `false` to create new ticker.
         */
        function Application(width, height, options, noWebGL) {
            var useSharedTicker = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : false;

            _classCallCheck(this, Application);

            /**
             * The animate function that's called before render.
             * @member {function}
             * @default null
             */
            this._animate = arguments.length > 5 && arguments[5] !== undefined ? arguments[5] : null;

            /**
             * WebGL renderer if available, otherwise CanvasRenderer
             * @member {PIXI.WebGLRenderer|PIXI.CanvasRenderer}
             */
            this.renderer = (0, _autoDetectRenderer.autoDetectRenderer)(width, height, options, noWebGL);

            /**
             * The root display container that's rendered.
             * @member {PIXI.Container}
             */
            this.stage = new _Container2.default();

            /**
             * Internal reference to the ticker
             * @member {PIXI.ticker.Ticker}
             * @private
             */
            this._ticker = null;

            /**
             * Ticker for doing render updates.
             * @member {PIXI.ticker.Ticker}
             * @default PIXI.ticker.shared
             */
            this.ticker = useSharedTicker ? _ticker.shared : new _ticker.Ticker();

            // Start the rendering
            this.start();
        }

        /**
         * Render the current stage.
         */
        Application.prototype.render = function render() {
            this.renderer.render(this.stage);
        };

        /**
         * Convenience method for stopping the render.
         */


        Application.prototype.stop = function stop() {
            this._ticker.stop();
        };

        /**
         * Convenience method for starting the render.
         */


        Application.prototype.start = function start() {
            this._ticker.start();
        };

        /**
         * Reference to the renderer's canvas element.
         * @member {HTMLCanvasElement}
         * @readonly
         */


        /**
         * Destroy and don't use after this.
         * @param {Boolean} [removeView=false] Automatically remove canvas from DOM.
         */
        Application.prototype.destroy = function destroy(removeView) {
            this.stop();
            this.ticker = null;

            this._animate = null;

            this.stage.destroy();
            this.stage = null;

            this.renderer.destroy(removeView);
            this.renderer = null;
        };

        _createClass(Application, [{
            key: 'ticker',
            set: function set(ticker) // eslint-disable-line require-jsdoc
            {
                if (this._ticker) {
                    if (this._animate) {
                        this._ticker.remove(this._animate);
                    }
                    this._ticker.remove(this.render, this);
                }
                this._ticker = ticker;
                if (ticker) {
                    if (this._animate) {
                        ticker.add(this._animate);
                    }
                    ticker.add(this.render, this);
                }
            },
            get: function get() // eslint-disable-line require-jsdoc
            {
                return this._ticker;
            }
        }, {
            key: 'view',
            get: function get() {
                return this.renderer.view;
            }

            /**
             * Reference to the renderer's screen rectangle. Its safe to use as filterArea or hitArea for whole screen
             * @member {PIXI.Rectangle}
             * @readonly
             */

        }, {
            key: 'screen',
            get: function get() {
                return this.renderer.screen;
            }
        }]);

        return Application;
    }();

    exports.default = Application;`

**Comment by jaspervaz** [comment]
Also, this simple little function would work too, maybe a better solution:

`Application.prototype.setAnimate = function (animate, context) {
    if (this._ticker) {
        this._ticker.remove(this.render, this);

        if (this._animate) {
            this._ticker.remove(this._animate, this._context);
        }

        this._ticker.add(animate, context);
        this._ticker.add(this.render, this);

        this._animate = animate;
        this._context = context;
    }
};`

**Comment by jaspervaz** [comment]
@andrewstart , @ivanpopelyshev 

This simple little function would work too, maybe a better solution:

`Application.prototype.setAnimate = function (animate, context) {
    if (this._ticker) {
        this._ticker.remove(this.render, this);

        if (this._animate) {
            this._ticker.remove(this._animate, this._context);
        }

        this._ticker.add(animate, context);
        this._ticker.add(this.render, this);

        this._animate = animate;
        this._context = context;
    }
};`

**Comment by jaspervaz** [comment]
Just realized this change should be made to the edited Application class as well:

` // Start the rendering if an animation function was not supplied
            if (!animate) {
                this.start();
            }`

**Comment by drkibitz** [comment]
@jaspervaz with the addition with `PIXI.Application` by @bigtimebuddy, I think this issue shows a definite need. One that is quite common among most renderers. I avoided in my original refactor of the Ticker class, because PIXI was still pushing the standard `raf` approach, and the Ticker was just a helper at the time, although consumed by two important components (MovieClip, aka AnimatedSprite, and the InteractionManager).

Now, with this new usage, and common pattern. The tickers needs one small, but very important change, which can be achieved 1 of 2 ways.

The first, would need a second internal event. Now everything is one internal `"tick"` event. What it needs is a `"tock"` event. Or in other common terms, "update" and "postUpdate". Most of the time, rendering is done in "postUpdate" or "tock", and consumers are only concerned with "update" or "tick". This would mean an overhaul of the public API.

The second, could be a priority based API (which I would prefer) added to `add` and `addOnce`. The default priority could simply be `10`, while internal `PIXI` consumers can added their listeners at specific priorities. The interaction manager at default - 3, the animated sprite default - 2, and the `PIXI.Application` render default - 1. Then all consumer methods would be above all those by default. Upon adding listeners, they are ordered by priority from highest to lowest. Lowest being called last, highest being called first.

**Comment by bigtimebuddy** [comment]
Created a new PR #3859 which addresses this issue. Validated that it works in your Pen if you use https://pixijs.download/ticker-priority/pixi.js

**Comment by bigtimebuddy** [comment]
Fixed in **dev**
