### ISSUE TITLE
Rope should support real vertical points, without changing texture.rotate.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3839]
If I use `texture.rotate=2` in Rope for vertical points ,

When  the texture also be used in a sprite, I have to set `rotation=realRotation-Math.PI/2`  to sprite.
Because the `sprite.rotation` will not be real rotation in logic.
The game logic will be broken.

So I think Rope should support real vertical points.

`change texture.rotate`  is not intuitive and maybe cause confusion.

**Comment by ivanpopelyshev** [comment]
Just clone the texture. UVs rotation and sprite rotation are completely different things. 

Yes, I have to make more examples and docs on this, because texture rotation was kinda invented by me: I found a gamedev use-case for (Dihedral group)[https://groupprops.subwiki.org/wiki/Dihedral_group:D8] . Its not an actual rotation, its like an "orientation" of the texture.

Rope works with horizontal textures, and I don't agree with adding orientation to the rope when we already have orientation in the texture. I can explain that thing through another example: I remember that you don't like the fact that anchor is in sprite and you want trims to take parts of its function. Everything texture-related has to be in texture, or may be in some "SpriteFrame" object, but not in the instanced object itself. 

Adding orientation to the Rope also will spawn one more "if" that I really want to avoid.

**Comment by ivanpopelyshev** [comment]
I'm closing it in favor of #3836, which is correct of the question. If you want your own ropes or other generated meshes - implement them in a plugin, we really need extra meshes of all sorts! The code of original Rope became much clearer for people who will study it, I don't want that extra "ifs" to be there: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/Rope.js
