### ISSUE TITLE
Interaction Issue - Button clicks go through to buttons below.

### ISSUE THREAD

**Issue by bob-builder-ngg** [pixijs/pixi.js#3851]
Hi,

We have recently updated our code to use pixi 4.4.0 from 4.3.5 and have come across an issue with mouse/touch events firing on multiple interactive elements when they overlap. This issue is still present in V4.4.2.

We were able to reproduce this issue with this simple PIXI example: https://jsfiddle.net/apodgg2c/2/

Red box is drawn below the blue box. 

Click the red box and you get a console output "RED FIRED"

Click the blue box and you get a console output "BLUE FIRED"

Click the overlapping region and both RED and BLUE will fire. 

In the previous version (4.3.5) only the BLUE will fire when you click the overlapping region. (as would be expected)

A little more information:
- If we add two interactive elements (buttons) as siblings to a container then they work fine and they will not click through when they overlap.
- If you create two containers as children of a parent container and place a button inside each of the containers then it fails. 

Here are some examples of scene graph hierarchies and which ones work (no click through) and which ones fail (clicks through)

```
OK

	Stage
	/  \
     Btn1   Btn2


Fail
	Stage
	/   \
 container container
      /       \  
    Btn1      Btn2


Fail 
(Btn1 added first)
	Stage
	/   \
      Btn1 container
              \  
              Btn2


OK 
(Btn1 added last)
	Stage
	/   \
 container  Btn1
      /         
    Btn2      

```

Any suggestions for a work around or is this something that will like be fixed in future versions?

This issue may be related to the DOM elements also clicking through?
https://github.com/pixijs/pixi.js/issues/3847
https://github.com/pixijs/pixi.js/issues/3790

**Comment by andrewstart** [comment]
Do you have any problems with https://d157l7jdn8e5sf.cloudfront.net/fix-interaction-issues/pixi.js?

**Comment by bob-builder-ngg** [comment]
Hi, thanks for the quick reply.  Yes this version of PIXI seems to resolve the issue. :) Will this be rolled into a future release?

**Comment by andrewstart** [comment]
Yeah, we'll make a patch as soon as I work out some other issues people have reported.

**Comment by bigtimebuddy** [comment]
I'll make this a high priority release if @andrewstart you can make a PR to master.

**Comment by Tigerwulf** [comment]
Hey, 
that bug is not fixed yet. In some specific cases the will still bubble the event over all displayObjects.
For that a short fiddle example. https://jsfiddle.net/d41h5g4d/8/
Here the big red button is below the purple button. Both get fired when i clicked on the purple button. White area is a nonClickable area, but it dont block the clicks to the red button. In this example you can set nonClickableArea.interactive = true, than it will dont call the redbutton clicked event. When its false, it will also call the red button.

The specific case that we have here is, that the button is a normal Pixi.Container and some Pixi.Graphics as child, on that container, for the visual things only (interactive = FALSE).

To hunt that bug down, it toke some hours.. ehh more than a day, but at the end im glad that im able to tell you why.

In your 'new' recursive function that case will never give a return HIT_INTERACTIVE, what is necessary to stop blubbling events to other child objects of that parent.


                if (childHit) {
                    // its a good idea to check if a child has lost its parent.
                    // this means it has been removed whilst looping so its best
                    if (!child.parent) {
                        continue;
                    }

                    // we no longer need to hit test any more objects in this container as we we
                    // now know the parent has been hit
                    interactiveParent = false;

                    // If the child is interactive , that means that the object hit was actually
                    // interactive and not just the child of an interactive object.
                    // This means we no longer need to hit test anything else. We still need to run
                    // through all objects, but we don't need to perform any hit tests.

                    if (childHit === HIT_INTERACTIVE) {
                        hitTest = false;
                        debug = 'A';
                        hit = HIT_INTERACTIVE;
                    } else if (hit === HIT_NONE) {
	                    debug = 'D' + child.interactive;
                        hit = HIT_ANY;
                    }
                }

That if(childHit === HIT_INTERACTIVE) will never be true.

Hit will be set by:
```
if (hitTest && hit !== HIT_INTERACTIVE) {
                if (displayObject.hitArea) {
                    displayObject.worldTransform.applyInverse(point, this._tempPoint);
                    if (displayObject.hitArea.contains(this._tempPoint.x, this._tempPoint.y)) {
                        hit = displayObject.interactive ? HIT_INTERACTIVE : HIT_ANY;
                    }
                } else if (displayObject.containsPoint) {
                    if (displayObject.containsPoint(point)) {
                        hit = displayObject.interactive ? HIT_INTERACTIVE : HIT_ANY;
                    }
                } 
            }
```
To set hit to HIT_INTERACTIVE it has to go into displayObject.containsPoint. But a Container don't have that function. But on that container we have the click callback. So the recursive function return HIT_ANY and go to other child objects below and call that event there too.

One option to fix, but i guess its not smart to do that. Just give the container the function to check if "containsPoint". Or add for the hit Test the case
```
else if ( hit && displayObject.interactive ){
	hit = HIT_INTERACTIVE;
}
```

This fixed the button bug, but not that bug with the white box.
Hope it helps to fix it.

**Comment by andrewstart** [comment]
Thanks for figuring this out, saved me some time.

> But it bring some other side effects that the mouseout event dont work right. ;)

Yeah, I noticed that when I tried it while making the previous PR.

**Comment by Tigerwulf** [comment]
What i notice too, is that a recursive function is not the best in Javascript. Because you never now where the program just send a window pointer event and stop your code, to call the callback function for that event. That brings sometimes weird behaviour of that code.
To solve this, its good to use a FIFO queue.
Another fact of that kind of recursive implementation, is that in worst case you have to check every displayObject, in best case only one (when you break the foreach that check all childs). 

A good solution for a constantly performance cost is a quadtree. But i guess it will be difficult to implement and handle this. Other idea is to check parent first, if the mouse is inside the bounds. Than check the next displayObject. A Simple AABB test, that you can break the check if already one axes of the mouse is not inside.

When you find the last child, that is hit, just go back over parent and call the events.
Maybe like this:

```
function bubbleEvents(displayObject) { 
    if (displayObject.parent !== null) { 
       if (displayObject.parent.interactive) {
           displayObject.parent.sendEvent();
           bubbleEvents(displayObject.parent);
       }
    }
}
```

A second performance leak is, that you just check every mouse event. Maybe for the mouseover/mouseout and so on, it makes more sense to check only if the mouse position is changed. 

```
if ( ~~mouse.position.x !== lastPosition.x || ... ) {
    lastPosition = mouse.postion;
    //check now
}
```

Hope my english is not to bad and that you dont understand it wrong. I dont want be mean or something else. You guys do a great job :)

**Comment by englercj** [comment]
Hey all, can this be closed? Looks like we merged the PRs in question.

**Comment by bob-builder-ngg** [comment]
From our perspective this issue has been resolved, thank you. I believe the issue can be closed.
