### ISSUE TITLE
Bug with Touch in Chrome (android)

### ISSUE THREAD

**Issue by iRomano** [pixijs/pixi.js#3886]
Hello

I have a bug in Chrome - Android:
I can't get touches in touchmove event:
event.data.originalEvent
touches - is undefined. 
changedTouches - is undefined.

But this work in Safari - iOS.
I want get data from touches.

**Comment by andrewstart** [comment]
With PIXI 4.4.0, we prioritize PointerEvents in browsers that support it, and have proper support for multitouch - you should get a separate event callback for each changed touch, and in browsers like Chrome the `originalEvent` would be a PointerEvent instead of a TouchEvent. [While we are normalizing event data to the PointerEvent standard](https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1505), it looks like we are dropping the ball on actually getting the normalized data to the listeners. We should fix this by applying the touch/pointer data to the InteractionEvent passed to your listener as `event`. @bigtimebuddy - patch or minor bump for that change?

**Comment by bigtimebuddy** [comment]
I'm for a patch, feels more bug-like to me. We can add to 4.4.5 if it's not a big deal to add.

**Comment by iRomano** [comment]
@andrewstart 
I had tried "pointermove". But touches - undefined )
How i can get touches array in event.data.originalEvent? This is work in iOS.
Or I need to wait for the update to 4.4.5?

Sorry for my english.

**Comment by andrewstart** [comment]
You'll have to wait for 4.4.5, when we'll supply the information from both the PointerEvents and changedTouches on `event.data`.

**Comment by c-andrews** [comment]
Hi, I've got the same issue with Chrome on Android. Is there a work around or solution available? I am using v4.5.1

**Comment by andrewstart** [comment]
#3963 should fix this, once it is merged.

**Comment by c-andrews** [comment]
Thanks, any idea when it might be merged?
