### ISSUE TITLE
WebGL warning: drawElements in Firefox

### ISSUE THREAD

**Issue by gordyr** [pixijs/pixi.js#3897]
Although everything appears to work fine, i'm getting this error in Firefox when rendering sprites:

```Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow.```

Is there a more optimal solution?

**Comment by englercj** [comment]
This usually is logged in firefox when you try to read pixels from an out-of-viewport location and render them. Because there are no out-of-viewport pixels to read the borwser has to create a buffer filled with zeroes for you, which is slow.

Can you provide a minimal code pen/jsfiddle that shows this issue happening please?

**Comment by coderD1mka** [comment]
I have same error.  All code is here:

[mainApp.zip](https://github.com/pixijs/pixi.js/files/1098051/mainApp.zip)

**Comment by kevingranade** [comment]
http://pixijs.github.io/examples/#/basics/basic.js exibits this.

**Comment by grondilu** [comment]
FYI, this message shows up on the Khronos WebGL tutorial called "SpiritBox" : 
https://www.khronos.org/registry/webgl/sdk/demos/webkit/SpiritBox.html

No message is shown with that same page on Microsoft Edge.  Can't try with chrome.

**Comment by nxtpl** [comment]
No message in Chrome either

**Comment by trongthanh** [comment]
Still got this message with the [basic example](http://pixijs.github.io/examples/#/basics/basic.js) on Firefox 57, macOS 10.13.1 and the demo cause the laptop heat up although no significant CPU activities.

**Comment by finscn** [comment]
in the last version of Firefox , there is a warning about SpriteRenderer  too: 

Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow.

**Comment by GoodBoyDigital** [comment]
closing as this has been fixed in v5 👍

**Comment by finscn** [comment]
@GoodBoyDigital  could you tell me how to fix it? I want to fix it in my fork-v4 . thanks

**Comment by GuillaumeLeclerc** [comment]
How to get this since the v5 has not been released yet ?

**Comment by tywang2006** [comment]
You can safely ignore this error.

This comes from the diffuseTexture of the ground taking time to load. So the RTT cannot render because the meshes are not ready (waiting for the diffuse texture to load). Then when you run the main rendering, the RTT are used as texture but need to be zero out as they don't have data yet (which will be fixed as soon as the diffuseTexture is ready)

**Comment by tywang2006** [comment]
> How to get this since the v5 has not been released yet ?

You can safely ignore this error.

This comes from the diffuseTexture of the ground taking time to load. So the RTT cannot render because the meshes are not ready (waiting for the diffuse texture to load). Then when you run the main rendering, the RTT are used as texture but need to be zero out as they don't have data yet (which will be fixed as soon as the diffuseTexture is ready)
