### ISSUE TITLE
Gradient Issues

### ISSUE THREAD

**Issue by darkfrog26** [pixijs/pixi.js#3946]
Perhaps I'm doing something wrong, but in this example:

https://jsfiddle.net/u5tt0z8u/1/

You can see that it's just Red, Green, and Blue and if I change the stops to 0.0, 0.5, and 1.0 everything is fine, but switching it to 0.0, 0.3, and 1.0 the red bleeds between the green and blue.  Is this a bug or something stupid I'm doing?

**Comment by englercj** [comment]
Looks like a bug to me!

**Comment by themoonrat** [comment]
That example using the above PR fix: https://jsfiddle.net/Ltc5znx6/

**Comment by darkfrog26** [comment]
@themoonrat awesome and fast work, thanks!

**Comment by darkfrog26** [comment]
somewhat unrelated, but apart from creating a `CanvasGradient`, it doesn't appear that Pixi has any built-in functionality for radial gradients?

**Comment by themoonrat** [comment]
Correct. When I added gradients to PIXI.Text, I wanted the API to be simple and repeatable over multiple lines. It takes custom code, for example, to allow a vertical gradient to be visually the same over multiple lines (effectively repeating the gradient for each line), rather than a gradient that just starts at the top and ends at the bottom.

Radial gradients can't have that repeat-ability - or at least, not easily, and I don't require it so wasn't willing to invest the time into it! Fill does allow a CanvasGradient if the default options aren't powerful enough :)

**Comment by darkfrog26** [comment]
@themoonrat does the WebGL renderer support `CanvasGradient` as well?

**Comment by themoonrat** [comment]
yeps. All text and gradient stuff is done via a canvas anyway, then used as a texture
