### ISSUE TITLE
Z Order

### ISSUE THREAD

**Issue by JAA17** [pixijs/pixi.js#3999]
I am not sure if this is the right place to ask this. If it is wrong, I will delete this.
I have 4 layers.
1. The background
2. The sprites on the background 1.
3. An elevated background.
4. The sprites on background 3.

Layer 1 is furthest back and they are in order. However sprites in 2 and 4 can flip flop back at forth between layers.

I have read and understand:

http://pixijs.github.io/examples/#/display/zorder.js

But what is the best, optimized way of flip flopping sprites between layers 2 and 4. It could be changing every frame.

Should I create 2 sprites for each sprite and have 1 permanently reside in each layer and alter the visibility depending on which layer it should be in?

Or should I constantly add and remove a single sprite from each layer?

**Comment by JAA17** [comment]
At the moment I have tried the following, and it seems to work.
All I do is put everything into the same container. Give each sprite a zOrder member, which can change each frame. Then use
```
children.sort(function(a, b){
    if(a.zOrder === b.zOrder) return 0;
    else return (a.zOrder<b.zOrder ? -1 : 1);
});
```
This seems a lot simpler that the example link I have given above.

**Comment by themoonrat** [comment]
If you are using that plugin, then you can just change the display group that a sprite is part of, following that example. It is actually a cool way of very easily changing rendering order without having to deal with arrays....

Which, in pure pixi, is how you need to do it, and which is what your code does.

You'll want to apply the zOrder property to Containers, rather than just Sprites, so that Graphics objects can also work with the order.

And you can then apply that sort to PIXI.Container.onChildrenChange, so that zOrder is recalculated if sprites are added or removed. Cache that sorting function rather than creating it every time anything changes.

Finally, if you create a getter and setter for zOrder, on the setter call the parent.onChildrenChange. This is because changing a sprites zOrder means it needs its parent to resort it's children array.
