### ISSUE TITLE
issue, Pixi don't use true Alignment !? in Align only container ??

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4002]
Hi guys and girls thank for help me about this issue.
I have some bug with the Align of pixi.text
Normally the alignment is supposed to work this way
![afvafgvawe](https://cloud.githubusercontent.com/assets/24865815/25791763/7dbf1632-3390-11e7-84fe-544dd3256e17.jpg)

But it is impossible for me to make text center (String) or right Justify, Same line in photoshop or Word.
I noticed that no demo or sample seems to show this possibility.
Is there a specific technique to use a true alignment? (text Justify)

for now **.setPixiTextStyle( {align: 'center'} )**
Not center the container but not the string ??
thank for help about this issue

**Comment by themoonrat** [comment]
text.style.align = 'left' / 'center' / 'right' only really effects multiline text. This is due to the way we draw text onto a canvas, and use that canvas as a texture to draw from.

What you can do is use text.anchor.x = 0 to left align, text.anchor.x = 0.5 to center align, and text.anchor.x = 1 to right align
