### ISSUE TITLE
Ticker and UPDATE_PRIORITY. v4.4.4 to v4.5.2

### ISSUE THREAD

**Issue by SebastienFPRousseau** [pixijs/pixi.js#4042]
Hello,

I have updated my project using PIXI.js this morning to the v4.5.2 from the v4.4.4 and now all my animations are broken. 
Considering this code (which was perfectly working in v4.4.4):
```
nodeMoveToX(target, direction, x)
    {
        if ((target.x * direction) < ( x * direction))
        {
            target.x += 10 * direction;
            this.app.ticker.addOnce(this.nodeMoveToX.bind(this, target, direction, x));
        }
        else
        {
            target.x = x;
        }
    }
```

This function is called the first time by a click event on a `DisplayObject`. This was working pretty well before I updated PIXI. 
The object is supposed to move to position x frame by frame so we can see it moving.

Now, the problem with the new version is that the object moves as it should but the render method doesn't seem to be executed on each frame. 
The object disappears from its starting position and appears a the final one. I tried a lot of combinations of UPDATE_PRIORITY on the `ticker.add` and `ticker.addOnce` methods for my method and inside the `render` method. 
Results are always different depending on the value of UPDATE_PRIORITY but the animation of the movement is never like it was before the PIXI.js update.

Is there any problem with the new Ticker implementation or is my approach not working anymore with PIXI 4.5.2?

Thanks for your answer,

**Comment by bigtimebuddy** [comment]
Hi @SebastienFPRousseau, thanks for point this out. I worked on the revised ticker code. I added a lot of unit-tests but maybe there some case here that I wasn't hitting. Would it be possible for you to put together a jsfiddle which demos this behavior?  It would be helpful to see.

**Comment by SebastienFPRousseau** [comment]
Thanks for your answer.

I did many test. 
First, i did the fiddle you asked for. You can see the problem I mentioned before : 
https://jsfiddle.net/L9raquf7/3/

Then, I realized than my application never stops its method execution. My method `nodeMoveToX` is called to infinite and crash the application. I tried to understand why, so I replaced it by just a `console.log` method and the problem is still the same. I prepared another fiddle demonstrating this behavior and searched the differences between the fiddle and my application. 
And i found it. I created a new `Ticker` instead of the default one. And when I dis this on the dedicated fiddle, the method was never called.
You can check the code here : https://jsfiddle.net/0aot56n8/3/
I'd be happy to help your further if you need some more information to reproduce the problem.

Thanks in advance,

**Comment by bigtimebuddy** [comment]
With your second link, a ticker is not started by default, unless you pass the `autoStart` constructor argument. You need to call `ticker.start()` to get it going. The reason your example logs out when you remove the manually created ticker is because the new Ticker created on the Application auto-starts.

---

There was a slight change in Ticker's functionality. Namely, when you `addOnce`, if it can be called in the current stack, it will be. In your case, you `addOnce` expecting this be the next render frame, but it's actually done in the same call stack, so it's called immediately. That's why it skips to the end. 

The up-side to this new Ticker is that when you remove items from the ticker, it happens immediately. Where before it would call things on the stack that were cached.

There are two workarounds to make sure it's not called in the current stack:

1. https://jsfiddle.net/rk1v01pn/ use `setTimeout(fn, 0)` to wait until the next event loop
2. https://jsfiddle.net/odno02qc/ use an increasing higher priority each `addOnce`. If `addOnce` is the same or lower priority, it will be called immediately.

Given your use-case, I'm still not 100% on the current implementation. Introducing priority and having immediate removing/adding of items to the ticker definitely has advantages. But there certainly might be convenience to adding something like `addNext` or `addOnceNext`, that's only added after the current process is complete. 

cc @drkibitz

**Comment by SebastienFPRousseau** [comment]
I forgot the `ticker.start()` in the fiddle, it is called into my project.

Now my project works like the v4.4.4 with your solution.
I think it's a good idea to add `addNext` and  `addOnceNext` into a forthcoming release.

Thanks for answers.

**Comment by drkibitz** [comment]
@bigtimebuddy @SebastienFPRousseau 

My 2¢

I'm sold on priority, but not on the current implementation of modifying the current list. Even though it may have its benefits, this is unusual, and an uncommon approach to this common design pattern.

If you are seriously considering adding `addNext` and `addOnceNext`, I would suggest just making it the default implementation of `add` and `addOnce`.

If you really think the current implementation has benefits, I would still consider changing it to not modify on the current list. Then make new methods of `addNow` and `addOnceNow` that do.

**Comment by drkibitz** [comment]
@bigtimebuddy @SebastienFPRousseau 

My opinion is the same for the remove method.

BTW, this is usually achieved without asynchronous calls. Mark something as removed, or added.
Added is actually put in a new list to add after the tick loop.
Removed is also put into a new list to remove after the tick loop.

So it's like:
- tick loop (things get added removed, etc. so we mark them that way with temporary lists)
- actually add the things waiting to be added
- actually remove the things waiting to be removed

The temporary lists must also be modified by their corresponding actions. e.g. the added list must get things removed when things are removed, and the removed list gets things removed when things are added.

This is a common approach to synchronizing a mutable list in almost any language.

**Comment by drkibitz** [comment]
Alternatively, can just go back to using an array, dereference from ticker on tick, and copy it when modified (add, remove).

**Comment by GoodBoyDigital** [comment]
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍
