### ISSUE TITLE
Left and Right Click Same Time

### ISSUE THREAD

**Issue by zcr1** [pixijs/pixi.js#4048]
I cannot left + right click at the same time when Pointer Events is enabled in the browser. Setting window.PointerEvent=null allows InteractionManager to fall back to mouse events and both onClick events to fire properly. 

Pointer events do not to seem trigger another click event when one is already pressed but other events will have the updated button info. For example - https://jsfiddle.net/us6kn78p/3/

**Comment by andrewstart** [comment]
Just in case this is related to some sort of browser implementation issue, what browser are you having this issue in?

**Comment by zcr1** [comment]
I am using Chrome 58.0.3029.110. Firefox has Pointer Events disabled by default so no issues there. Issue is also present in Edge.

**Comment by themoonrat** [comment]
Anyway, this behaviour is as designed in the PointerEvent spec: note https://www.w3.org/TR/pointerevents/#chorded-button-interactions
and there is a converstation about this very issue on the official w3c github: https://github.com/w3c/pointerevents/issues/33

So, pointerdown only ever fires when that element has gone from nothing pressed, to something pressed. Likewise, pointerup only fired when the element has gone from something pressed to nothing pressed.
Think of 'pointermove' more of a 'pointerchange' (they kept the move name to keep consistent with mouse events). If pointerdown has been fired, and whilst holding a button down you press a second button down, a pointermove event is guaranteed to be fired with the correct .buttons value.

How you nicely integrate that way of working into our interaction manager beats me. Almost getting to a point of 'should we ignore actual pointer events and just normalise mouse and touch events instead' due to the problems actual pointer events are causing
