### ISSUE TITLE
Change base texture of AnimatedSprite and upload it to gpu

### ISSUE THREAD

**Issue by krompir2** [pixijs/pixi.js#4081]
I am trying to replace a texture atlas of the animated sprite with another one, and play it.
On every click I first fetch the texture atlas image from server. Than I make periodic checks if there is any animation still running. Once there is no animation running, I replace animatedSprite.textures with the new on and upload that tetxure atlas to the gpu. After it is uploaded, I set canRunNext to true, signaling, that everything is uploaded and ready to go.

The issue is that app.renderer.plugins.prepare.upload uploads every second texture, for reasons unknown to me.

Now this could be hard to visualize so I created a dummy example. After each animation, I run a random next one.  you MUST run this on a slow mobile device to see my issue. The textures in use are just placeholders.

Link: http://forwardingsolutions.club/

Now, the first and second texture are uploaded as expected. if you click on square, the animation is triggered right away.  But watch out, the 3. one is not, then the 4. is uploaded, then the 5. again, is not and so on. On every second click, my animation is not uploaded to gpu. I am not getting why is this happening.  How would you fix this issue?

All the code is available at the website I posted. The meat are these two functions:
```
setupSpritesAnimation()
setupNextSpritesAnimation()
```

I don't think you need to look at anything else.

I hope you can help me out with this stubborn issue. 
Best regards, Mitt

**Comment by themoonrat** [comment]
Sorry for a (very) late reply but I wonder if this is due to how many texture units the device has.
WebGL is very fast when it can render from the same base texture over and over. When you change the base texture you are drawing from, it may have to upload the new one to the GPU. The older the device, the less base textures a device can hold at once, the more uploading to gpu required.

May or may not be it, but we've been slow to this so the example isn't there anymore.

Will close this for inactivity, and I hope you solved the issue. Please open a new one if you're still having issues
