### ISSUE TITLE
ResourceLoader 'Cannot add resources while the loader is running.'

### ISSUE THREAD

**Issue by FabianElsmer** [pixijs/pixi.js#4100]
Hello PIXI Team,

I have a question regarding the resource loader,
with the switch from PIXI v3 to v4 an error message has been added when you try to queue a resource while the loader is already running, is this really necessary?

What would be the standard way to attempt retrying of the loading process of a resource if it fails?
In our software we simply remove the resource from the loader as the error happens and add another resource with its exact name+url, all while the loader keeps loading.

For now I removed the throwing of the error and the loader still seems to work the exact same way as before.

**Comment by themoonrat** [comment]
I may be wrong, but I think adding resources to the queue whilst active created bugs relating to loading progress.

The way I'd do retrying is to store the failed resources, then when the loader has ended, reset it, and add those failed resources to the queue to try again.

**Comment by englercj** [comment]
> an error message has been added when you try to queue a resource while the loader is already running, is this really necessary?

Yes, adding a root asset while the loader is running is an error. You can add assets to the loader while it is running, but they must be a child of an existing asset (this is how the spritesheet loader middleware adds image loads based on the json file, for example).

> What would be the standard way to attempt retrying of the loading process of a resource if it fails?

Once the loader has completed loading, call `.reset()` and then add/load all the failed resources to try again.

> In our software we simply remove the resource from the loader as the error happens and add another resource with its exact name+url, all while the loader keeps loading.

Unfortunately this is not a supported workflow. This is a known feature request I just haven't had time to implement yet: https://github.com/englercj/resource-loader/issues/73.

> For now I removed the throwing of the error and the loader still seems to work the exact same way as before.

It probably won't, the async queues are not built to be used in the way you are using them. You will likely experience strange and difficult to track down issues.

Closing this, since it is really a discussion that can be continued on the linked resource-loader issue if need be.
