### ISSUE TITLE
Expose InteractionTrackingData Class through PIXI.interaction

### ISSUE THREAD

**Issue by FabianElsmer** [pixijs/pixi.js#4118]
Hey Pixi Team,
I recently found myself trying to add features to the InteractionManager by overwriting functions, but realized I could not get access to the InteractionTrackingData class through PIXI.interaction, its simply not in the https://github.com/pixijs/pixi.js/blob/dev/src/interaction/index.js during build.

Shouldn"t all classes be accessible like that? Or is there already a way to get your hands on that class somehow?

**Comment by bigtimebuddy** [comment]
It seems like InteractionTrackingData and InteractionEvent are not exported here:
https://github.com/pixijs/pixi.js/blob/dev/src/interaction/index.js

I assumed this is an oversight since these were added recently and were probably assumed they didn't need to be publicly accessible. @andrewstart thoughts? I would accept a PR to add two lines to the file above.

**Comment by andrewstart** [comment]
Yeah, I imagine they weren't exported because they were little things that were considered to be output (from the library to games/applications) only. Exposing them should be fine.

**Comment by FabianElsmer** [comment]
https://github.com/pixijs/pixi.js/pull/4120
