### ISSUE TITLE
img load update sprite scale.x/y but not child scale

### ISSUE THREAD

**Issue by JenGL** [pixijs/pixi.js#4142]
As in the subject if I create a Sprite from an Image without waiting the img.onload event and I change its width and height (maybe in order to match the renderer dimensions) when the images loads the sprite scale x and y are updated.
But if I add a child to that sprite, when the image loads it updates only its scale x and y values and the child become much smaller in respect of the parent (because the sprite initially has width 1 and height 1)

This causes the same code to have different behaviour depending on how fast is the image.load event.

An example here: https://jsfiddle.net/220t9e2r/1/ , if you load it the first time you should see the inner sprite very small, if you reload you should see it fitting the stage.

**Comment by englercj** [comment]
Your URLs use localhost?

**Comment by ivanpopelyshev** [comment]
Yes, it depends on which sprite (first or second) will be loaded first. If you want steady behaviour, please specify width and height of texture independently from load, store it somewhere. Some links:

https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L570

https://github.com/pixijs/pixi.js/blob/dev/src/core/display/DisplayObject.js#L235

https://github.com/pixijs/pixi.js/blob/dev/src/core/display/Container.js#L343

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L352

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/Sprite.js#L142

The problem is, there is no way to scale Sprite without scaling the child, that's a problem I made several PR's for but they were all rejected, so objectively so far there is no good solution for it. 

Workaround: use Container that has both sprites inside of it.

**Comment by JenGL** [comment]
oh yes sry it use localhost server that works as crossorigin proxy on images.
use this url: https://jsfiddle.net/220t9e2r/2/

**Comment by englercj** [comment]
Can you just not use the images until after they are loaded, circumventing this problem altogether?

**Comment by ivanpopelyshev** [comment]
@JenGL there is "Texture.WHITE" that is 10x10 size and you dont have to load it.

**Comment by JenGL** [comment]
@englercj yes it obviously solve the problem, this doesn't changes the fact that the expected behaviour (at least what I was expecting :D) is different from the actual implementation. I was just reporting this to your attention, i've already solved the problem using a 1x1 img.

@ivanpopelyshev Thx for the suggestion but I need it black :P. I can create the texture from canvas in the same way it is created the white texture in PIXI probably.

**Comment by ivanpopelyshev** [comment]
@JenGL believe me, nobody expects spanish inquisition^W^W pixi behaviour of width/height properties. We need better updateTransform() logic to handle those corner cases, and its already too complicated.

**Comment by JenGL** [comment]
I was hoping to help, not to do an inquisition :D. If the problem is known you can close this issue ^_^

**Comment by ivanpopelyshev** [comment]
You actually helped me, that's one more case for better updateTransform() handling 👍  =^_^=
