### ISSUE TITLE
URI dependencies for v5

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4143]
Resource-loader uses "parse-uri" and "window.URL", at the same time pixi uses require("url") in spritesheet.

Can we make a separate lib for it instead? These dependencies are giving me headache.

**Comment by englercj** [comment]
resource-loader uses `parse-uri` as a lightweight alternative to the `url` module. 

The loader build package went from 79.7KB -> 25.2KB when I removed `async` and replaced `url` with `parse-uri`. For a small module like resource-loader this was really important. For PixiJS, not as important, but we could switch to save some file size!

**Comment by Elvynia** [comment]
Hi,
I'm using Polymer 3 custom elements in a TypeScript project and I can't get Pixi working with typescript imports.
I use `import * as PIXI from 'pixi.js'`, but it gives me an error at runtime. The dependency package 'url' is request like this `http://localhost:8081/url` but it should just be `http://localhost:8081/node_modules/url`. It works for all other dependencies I use, but the uri built for this package is wrong.
I don't understand what's going on, except maybe because url package is not defined as an ES module.

It works however if I remove all TypeScript imports of Pixi, let the errors going through transpilation and use `<script src="node_modules/pixi.js/dist/pixi.min.js"></script>` in the HTML document. But even if I get rid of the errors I wont be able to use Pixi's types, an it sucks :/

I was thinking about making another issue, but ES module imports & npm seems to have many problems this year and the title of this issue seems to relate with my problem. Do you have any advice ?

**Comment by englercj** [comment]
This problem is completely unrelated, please open a new issue.

**Comment by bigtimebuddy** [comment]
And provide a reproducible example too

**Comment by Elvynia** [comment]
[Issue created](https://github.com/pixijs/pixi.js/issues/5939), sorry I was hoping to discuss the problem before making it an issue...
