### ISSUE TITLE
Texture cache collision

### ISSUE THREAD

**Issue by gle6da** [pixijs/pixi.js#4156]
Hello. I'm using PIXI v4.5.2 and found same problem as here https://github.com/pixijs/pixi.js/issues/312

I have tons of assets with same names in different modules of app. As I adding module to core game I dynamically creating loader and load assets with prefix. Code for asset Loader looks like that:

```js
	return new Promise((resolve) => {

		const loader = new PIXI.loaders.Loader()

		for (let a in assets) {
			loader.add(`${prefix}:${a}`, assets[a])
		}
		loader.load((loader, resources) => {
			loader.reset()
			loader.destroy()
			resolve(resources)
		})
	})
```

So when I loading assets for example for 'Building1' I use code like this:

```js
const assets = {
	body: require('../assets/tiles/house1/body.png'),
}
let textures = await Loader(assets, 'building1')`
```

After that in another module I use same scheme, but with another prefix. For example 'building2'
And here is the problem — PIXI automatically adds urls of assets to textureCache even if they provided with names in Loader.

So in texture cache I have:

```
/building1:body:Texture
/building2:body:Texture
/body.png:Texture 
```

Here we have warning '**BaseTexture added to the cache with an id [/body.png] that already had an entry**'
And of course my modules works incorrect.

Here is fiddle (look at the console) — why we add urls, when we have explicit names?
https://fiddle.jshell.net/jz9xx0hm/7/

**Comment by englercj** [comment]
The only reason this would be causing a problem is if you are using the loader to load assets then doing `.fromImage` on a texture and passing in the URL. For example, since you use the `resources` from the loader in your example it works perfectly fine. What is the issue you are having?

That warning is just telling you that we overrode the entry for the url in the cache with something else, but since you aren't doing cache lookups by URL that shouldn't matter (and you shouldn't be doing cache lookups by URL).

**Comment by gle6da** [comment]
Thanks for reply, found that problem was in webpack, which overrides images and causing incorrect loader behavior.
