### ISSUE TITLE
Graphics mask not working on PixiJS v4.5.4

### ISSUE THREAD

**Issue by anticore** [pixijs/pixi.js#4177]
Hello,

Switching to PixiJS v4.5.4 causes masks constructed with PIXI.Graphics to stop working. 
[You can reproduce this bug here in this JSFiddle.](https://jsfiddle.net/anticore/x02y6ncy/)
If you switch the pixi.js file located in the External Resources of the fiddle back to version v4.5.3, you can see the mask in effect (two squares) but in v4.5.4  there's no change.

Cheers

**Comment by anticore** [comment]
This issue seems to be caused by fix #4164.
This fix, by the way, is not listed in the v4.5.4 release.

**Comment by bigtimebuddy** [comment]
Thanks for reporting, we are looking into it. I'll make sure to add that to the release notes.

**Comment by bigtimebuddy** [comment]
PIXI.Graphics masks are, in fact, working in v4.5.4 https://jsfiddle.net/b8cqv9du/ What changed is that if you draw multiple shapes to a graphic, these are combined instead of overlapping shapes being subtracted. WebGLRenderer's masks are now consistent with the CanvasRenderer's. We considered this a bug.

For developers that were using this functionality to draw holes in their objects, would strongly consider using the [`addHole`](http://pixijs.download/release/docs/PIXI.Graphics.html#addHole) API in Graphics class. For instance, https://jsfiddle.net/Lpo52xfo/

_Note: `addHole` only works with primitive drawing commands (arcTo, lineTo, bezierCurveTo, etc) and does not work with convenience shapes (drawCircle, drawRect)._

**Comment by anticore** [comment]
Okay, this makes sense. Thank you for your help.
I'm closing the issue.

**Comment by anticore** [comment]
Excuse me for reopening the issue, but the solution you provided doesn't work when on Canvas. Is this an issue on PixiJS's part?

**Comment by bigtimebuddy** [comment]
Seems like a bug. I will open a new issue for it.
