### ISSUE TITLE
Adding ~4000 PIXI.Text sprites to the stage slows down render.

### ISSUE THREAD

**Issue by amirrajan** [pixijs/pixi.js#418]
Given that pixi can handle many many sprites, I was surprised to see a slowdown for adding this many text elements. I'm making an ascii based game. Sample code to recreate:

```
var asciiRow = 89;
var asciiCol = 44;
var stage = new PIXI.Stage(0x000000);
var renderer = PIXI.autoDetectRenderer(maxWidth, maxHeight);

function draw() {
  renderer.render(stage);
  requestAnimFrame(draw);
}
_(asciiRow).times(function(row) {
  _(asciiCol).times(function(column) {
    stage.addChild(new PIXI.Text("", { font: "20pt monospace", fill: "gray" }));
  });
});

requestAnimFrame(draw);
```

Any ideas?

**Comment by grovesNL** [comment]
@englercj: Would you mind providing an example or further explanation of the sprite sheet option? I understand I need to create a sprite sheet (similar to `fnt` files for `BitmapText`), but it's not clear which of the following methods is recommended here:
1. Draw all characters into a single `Sprite`
2. Create separate `Sprite` for each logical text grouping
3. Create a sprite per text character (which seems to be the approach used in `BitmapText`)

I would like to avoid having a sprite for each text character because I plan to have several thousand instances, as discussed in this issue. I am wondering if there is a native way to calculate the character positions or whether I will have to create this myself.

**Comment by englercj** [comment]
Create as many sprites as you want, as long as there is only one texture that is all that matters. BitmapText uses a sprite per character when writing text, but they all share the same texture so it doesn't matter.

**Comment by grovesNL** [comment]
@englercj: Thanks for the clarification! I have been testing BitmapText so far but the initial object creation seemed to take a while (i.e. constructing several thousand BitmapText instances). I was hoping to lower this load time but perhaps it is unavoidable with the current state of the technology. BitmapText appears to reference texture by `BitmapText.fonts[this._font.name]`, which suggests that all instances share a single texture.

**Comment by englercj** [comment]
You should start a new issue to ask your question or post on the forums. You almost certainly shouldn't be creating thousands of BitmapText instances, like ever.

Additionally, allocation takes a lot of time. So create thousands of *any* object will take quite some time reguardless. Again you almost certainly shouldn't be creating thousands of *any* object at one time.

**Comment by grovesNL** [comment]
Sorry, I didn't intend to divert this issue. I agree that this requirement isn't typical. For example, object pools combined with restricting sprite creation to visible regions solves the majority of these cases.

I am mostly okay with the performance of BitmapText, so this may be a non-issue. I'll post a question if it's holding me back. Thanks!

**Comment by zzm2q** [comment]
BitmapText BitmapText em..., there are 26 characters in English while 2000 characters frequently-used in Chinese.
