### ISSUE TITLE
Example filters don't seem to work + quick question.

### ISSUE THREAD

**Issue by lancewellspring** [pixijs/pixi.js#4181]
So if you look at http://pixijs.github.io/examples/#/filters/blur-filter.js and all other filters there, none of them seem to work.

I also can't seem to get my filter/shader (clarification?) from v3 to work after moving to v4.  I've stripped it down to just the basics here: https://codepen.io/Lancer611/pen/brGXZj?editors=1010.

I've spent a fair bit of time going through documentation and examples, and don't see anyone else struggling with shaders, so what am I doing wrong?

**Comment by giraluna** [comment]
The filter examples look fine to me.

Your codepen doesn't show anything because the filter doesn't actually have anything to filter. Setting `stage.filterArea` or `sprite.width` & `sprite.height` shows a grey rectangle.

At least one breaking change in v4 was that the old `Filter.uniforms` is now `Filter.uniformData`. `Filter.uniforms` is now used to directly store the values of custom uniforms.

**Comment by lancewellspring** [comment]
Well it all seems to work fine on my work pc, so I guess something is wrong with my home pc :(.

My home pc is Windows 10, latest Chrome, i7 2600K, nvidia gtx 960.  Any thoughts on why the filters don't work?

Otherwise, I'm content for this ticket to be closed, thanks again!
