### ISSUE TITLE
discussion: are elements out of canvas' viewport rendered or not?

### ISSUE THREAD

**Issue by gg4u** [pixijs/pixi.js#4203]
I refer to:
https://github.com/pixijs/pixi.js/issues/4201

where a culling technique was suggested.

How are elements that are out of canvas viewport treated by PIXI : as example, are they actually rendered even if not visible because of the stage, or not rendered by default?

I would like to learn some of concepts behind optimisation and performance of webgl on canvas.

**Comment by ivanpopelyshev** [comment]
There's no culling in pixi. The only good thing is that fragment shader isnt run for pixels outside the screen.

**Comment by englercj** [comment]
CPU still runs on those elements, and vert shaders still run on those elements. Then those verts are culled from the pixel shading process since they are out of the viewport.

However, unless you are doing culling on the CPU in your app, you are almost certainly overdrawing. This can either be a huge problem or something that doesn't matter at all depending on your application's needs.

**Comment by gg4u** [comment]
Thank you for explain! 
Well, so far it is ok, eventually in the future I will come back to see if I handled culling well :)
