### ISSUE TITLE
Can't import a spritesheet in React (w/webpack)

### ISSUE THREAD

**Issue by patientplatypus** [pixijs/pixi.js#4219]
Seemingly no matter what I do I cannot get a spritesheet to import in React. 

I've tried doing: 

```
  var littlemarioforwardwalk = PIXI.loader.resources[require("../../../../../public/mario_characters/littlemarioforwardwalk.json")].textures;
  let spritelittlemarioforwarlkwalk = new PIXI.Sprite(littlemarioforwardwalk[require("../../../../../public/mario_characters/littlemarioforwardwalk.png")]);
```

As my best guess at how to get it to work and that gives the error "cannot read property textures of undefined". I've tested that my paths are correct and that the files exist (they are and they do). What is wrong here?

I've tried several other ways of trying to get this to work (from the examples at kittykatattack and also from here) and nothing seems to work. Is there an update somewhere or a working example I can follow?

The full gist can be seen here: https://gist.github.com/patientplatypus/d7091a02d0965759534ecbc266334756

**Comment by paramahamsa** [comment]
For me loading in React works fine. Im using React create app so static files are in public folder (public/img/mapping.json)
`PIXI.loader.add('mapping', '/img/mapping.json').load(this.loadMapResources.bind(this))`

**Comment by patientplatypus** [comment]
Can you show a full example paramahamsa? You're adding a json file and some loadMapResources, but I don't see where you add the png data or get a picture out of it. Does putting it in PIXI.loader.add also put in the textures? How do you create the Sprite?

**Comment by paramahamsa** [comment]
Not sure about full example, it needs time =) But you can debug what you get in PIXI.loader.resources on load callback. The array should contain loaded data. It could be anything like json files or images.
If its image you can address it as PIXI.loader.resources[resourceName].texture
if json as PIXI.loader.resources[resourceName].data

If PIXI.loader.resources array is void means it cant download resource (wrong path/permissions, etc)

**Comment by patientplatypus** [comment]
I'm sorry I still don't understand - where are you importing the actual .png file in the example you posted above?

**Comment by patientplatypus** [comment]
Also -

> If its image you can address it as PIXI.loader.resources[resourceName].texture

First, according to the documentation, it is "textures" not "texture". Second,

See my post comment: 
`var littlemarioforwardwalk = PIXI.loader.resources[require("../../../../../public/mario_characters/littlemarioforwardwalk.json")].textures;`
This gives the error "cannot read textures of undefined."

If I remove the `require(` I get the same error. I've verified that the file exists at the correct path. So what you are saying is not the correct solution.

**Comment by paramahamsa** [comment]
ok, I hope this example will help you https://jsfiddle.net/y7bL22qr/1/

**Comment by patientplatypus** [comment]
paramahamsa - thank you for the example, but the issue seems to be that I cannot import relative paths in pixijs and React. Please see the last edit of my above comment.

**Comment by paramahamsa** [comment]
So its not a PIXI issue, looks like you need help with webpack or whatever tool you are using. The easiest way in this case to use react-create-app, you can put assets to public/assets folder (public will be in the root project folder) and access them as PIXI.loader.add('assetName', '/asssets/assetName.png')  without issues (at least with webpack in my case).

**Comment by patientplatypus** [comment]
No, it is an issue with Pixi - if Pixi cannot find files to import with React and webpack then it should say so in the documentation. If it can, it would be nice if there were an example so I didn't have to guess. I don't know if I am doing something wrong, Pixi will not work with webpack, or my webpack is misconfigured.

**Comment by englercj** [comment]
> if Pixi cannot find files to import with React and webpack then it should say so in the documentation

Can you elaborate on this? Pixi.js doesn't import anything (or have any way of 'finding files'), and neither does React.

When you `import` (or `require()`) a non-source file, like an image, and use webpack to build a bundle it you are techinically using [`webpack-file-loader`](https://github.com/webpack-contrib/file-loader). This loader finds the file, copies it to the output folder, and returns a relative URL to the copied file. In your source it just replaces the imported/required file path with the "correct" URL in the output folder. It is still up to you to ensure they get to the server in the same file/folder layout as your output folder, it is still up to you to load the file using some browser loading method (like XHR or Image).

For example, in your gist, this:

```js
import littlemarioforwardwalkpng from '../../../../../public/mario_characters/littlemarioforwardwalk.png';
```

Maybe be transformed by webpack-file-loader into something like this:

```js
var littlemarioforwardwalkpng = 'mario_characters/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.png';
```

If you are using hash names, which I often do so I can have my CDN just cache them forever, it make look similar to the above.

I only just now got to look at your answer, but I also saw this:

```js
PIXI.loader
        .add('./b.json')
        .load(spriteLoaded());
```

The error you are having here is that you are *calling* the `spriteLoaded` function and passing the result of it as the parameter to `.load()`. This is probably not what you want. You probably want to pass the function iteself: `.load(spriteLoaded)`. Looks like you've corrected this in your gist, by creating a new arrow function, which preserves the calling context, so you can call the spriteLoaded function with the correct `this` context.

In your original gist, it looks like you were trying to access the `PIXI.loader.resources` object with a URL that hadn't been loaded yet. The code you have here would probably work just fine, but you can't access a resource in that object until after it has loaded. Hence the need for the callback function to `.load(cb)`, because loading those remote files is an asynchronous operation. If you don't call `.add()` and `.load()` then `PIXI.loader.resources` is just an empty object, since nothing has yet been loaded.

Here are a few examples, documentation pages, articles, and source files you may find useful when working with webpack, PixiJS, and spritesheets:

### PixiJS

#### Examples

- https://pixijs.github.io/examples/#/basics/spritesheet.js
- https://pixijs.github.io/examples/#/demos/animatedsprite-demo.js

#### Documentation

- http://pixijs.download/release/docs/PIXI.loaders.Loader.html

### Webpack

#### Documentation

- https://github.com/webpack-contrib/file-loader#usage

#### Articles

- https://github.com/petehunt/webpack-howto#5-stylesheets-and-images
- https://medium.com/@bogdan_plieshka/loading-static-and-dynamic-images-with-webpack-8a933e82cb1e

Hope this helps!
