### ISSUE TITLE
[EVENT] sprite "pointermove" event emited from all document body area

### ISSUE THREAD

**Issue by MegaUITeam** [pixijs/pixi.js#4227]
PIXI 4.5.4
---

this emitted even when i moving mouse outside canvas

```javascript
sprite.on('pointermove', function(){
  console.log('pointermove')
})
```

Is this a bug?

black is canvas:

![image](https://user-images.githubusercontent.com/30184325/29261284-638997ee-80d7-11e7-9de6-93f611688189.png)

If not, then this behavior is not intuitive. Let's hang one global "pointermove" handler on the canvas element, and in it filter the sprites which have a "pointermove" handler, and to emit events directly on them

**Comment by themoonrat** [comment]
Could you provide an example please on somewhere like jsfiddle?

**Comment by MegaUITeam** [comment]
https://www.youtube.com/watch?v=N9h9UX1K8Ms

**Comment by MegaUITeam** [comment]
@themoonrat https://jsfiddle.net/o43ssr1t/2/

**Comment by themoonrat** [comment]
If you look at
https://jsfiddle.net/themoonrat/3v1ez4jt/3/
you can see that by adding
app.renderer.plugins.interaction.moveWhenInside = true;
you can replicate the behaviour you require

The documentation for this variable and why it is like it is can be found at http://pixijs.download/dev/docs/PIXI.interaction.InteractionManager.html#moveWhenInside

**Comment by MegaUITeam** [comment]
@themoonrat Excuse me, but is this behavior not a bug? It emit pointermove evet in sprite, even the cursor is not over the sprite. When can this be necessary?

**Comment by themoonrat** [comment]
As explained in the docs, it's by design, although in the docs it also says that default behavior could change in a future version.

Someone may come and correct me, but _I believe_ because some methods of dragging a sprite could fail if you tried to drag very quickly and moved your mouse quickly from over the sprite to not over the sprite. The cursor wouldn't be over the sprite anymore, so no moves given. By always emitting the event, you can always compare the starting point on mouse down to any more events points.

**Comment by MegaUITeam** [comment]
But the behavior of dragndrop always involves setting the handler to the parent container, because that's where the element will move, is not it?

**Comment by themoonrat** [comment]
For pixi v5, a re-think of how we do interaction is on the cards :) We understand that v4 interaction is not quite where we want it, but any major changes to how it works would break compatibility.

**Comment by MegaUITeam** [comment]
> break compatibility.
How I hate this thing, and at the same time I love. XD
