### ISSUE TITLE
Handle missing/undefined/null arguments in particleContainer.addChild()

### ISSUE THREAD

**Issue by griest024** [pixijs/pixi.js#4300]
I add a lot of children programmatically with the spread argument like `particleContainer.addChild(...arrayOfChildren)`. Sometimes this results in an array with `null`/`undefined` or sometimes an empty arguments list which causes this error:

```
TypeError: Cannot read property 'parent' of undefined
    at ParticleContainer.addChild
```

I think `addChild` should handle these arguments gracefully and simply discard those arguments that it can't process instead of throwing an error.

I can add some more isolated tests for other `DisplayObject`s and submit a PR if this is a feature that you want.

[Fiddle](https://jsfiddle.net/7wgutekc/1/)

**Comment by griest024** [comment]
This happens for `Container#addChild` as well

**Comment by ivanpopelyshev** [comment]
In flash, openfl, and other flash-like engines addChild crashes on null, however there are no spread operator. Do you know of any practice in game engines about spread operators?

**Comment by griest024** [comment]
Are you saying you are trying to provide behavior consistent with other similar game engines? I think its a mistake to not try to improve the usability of Pixi.js just to try and maintain consistent behavior.

EaselJS will not crash or produce unexpected behavior for `addChild()` (no args) though it will crash for `addChild(null)`. I'm mostly concerned about the no args use case although I think it would be good for Pixi.js to handle null or undefined children without crashing, I think a warning would be sufficient in this case.

**Comment by ivanpopelyshev** [comment]
Let it crash. I dont want to encourage people to produce code that relies on null filtering there. Also, if we start it, we'll have to support this in next versions too, then becomes a standart and we wont be able to remove this thing.

I dont know opinions of other maintainers.

**Comment by ivanpopelyshev** [comment]
Again, I dont know of any kind of JS ,libs or game engines that filter nulls from spread operator to produce the warning and not the crash.

**Comment by ivanpopelyshev** [comment]
Even more, I dont know of collections that filter input on add. If "null" is added it becomes "null" and not something else, and its not ignored, in JS, in Java, in C#.

**Comment by griest024** [comment]
so this is a wontfix?

**Comment by themoonrat** [comment]
Correct, it won't be fixed

You see, nicely handling garbage input in this case leads down a very deep rabbit hole of protecting against garbage input for all public APIs within pixi. What if I try to assign a texture property a number instead of a PIXI.Texture? What if I pass an array of booleans as a parameter for text colour? Etc. Etc. There are so so many things you could do to break the libs that goes beyond your use case, and so much extra defensive code would be required that I can't see anyone creating PR for soon! And some may make the point that all that defensive code everywhere may effect performance. I don't know the other guys opinions on this.

The solution that exists right now to help cover this.... use Typescript, and let it's compiler do that kind of type checking for you. In your case, you'd have to declare that your array may contain null/undefined entries, which is incompatible with the api

**Comment by griest024** [comment]
@themoonrat thanks for the nice explanation.
