### ISSUE TITLE
why pixi.js set field to null when object destroy?

### ISSUE THREAD

**Issue by luckyCatMiao** [pixijs/pixi.js#4302]
I have study pixi.js these day,and I noticed the destoy function was appear several in the source code.
Why it need set field to null?In my opinion when the host Object be garbage collected,all the field will be auto garbage collected,so manually set field to null looks like useless.
I ask a question in the stackoverflow but no one answer me,so i send a issue here to get help.
Because it was a famous framework,and I'm not a javascript expert.I think it may has some reason,can anyone tell me?

**Comment by ivanpopelyshev** [comment]
Honestly, I dont know too, but I can guess:

1. Its our code style
2. To make things crash if you access "destroyed" objects

Technically, you are right :)

**Comment by luckyCatMiao** [comment]
I get it,thanks for your detailed answer

**Comment by ivanpopelyshev** [comment]
I forked pixi two times: 

First one was for 2.5d effects:
https://github.com/gameofbombs/pixi.js , https://gameofbombs.github.io/pixi-bin/index.html?s=flip&f=cards.js&title=Cards

Second is for typescript and serious speedups for huge number of elements: https://github.com/gameofbombs/gobi , no demos yet.

I also totally remade pixi bunnymark on kotlin : https://github.com/pixijs/pixi-native 

So if you want to study pixi code more for a reason of porting or just copying to your own lib, just ask me more questions ;)

**Comment by luckyCatMiao** [comment]
Wow!that's so cool!I want study your code definitely!
Honestly,I have just started learning kotlin recently,so it's was really help to get a kotlin version of pixi!
And I also want to learn how to speedups for huge number of elements,I will watch your code carefully.
If i have some question,I will ask your :)
Finally,forgive my poor English :)

**Comment by ivanpopelyshev** [comment]
kotlin port was started a year ago, and now i have better variant on typescript, its using pixi-v5 alpha, supports webgl2 and more type-friendly than simple pixi. 

If I ever port it to kotlin it will be that version :) I need java/kotlin because i have huge java/scala/groovy codebase for "gameofbombs.com".

**Comment by englercj** [comment]
It is to ensure that the GC cleans up any owned objects by losing references to them. For example, if you called .destroy() on a sprite but didn't clear your reference to that sprite all resources would remain in memory. However in this model, which the sprite may stick around all the underlying objects should get cleaned up because destroy removed the references.
