### ISSUE TITLE
Canvas remains transformed after render

### ISSUE THREAD

**Issue by cawoodm** [pixijs/pixi.js#4313]
I'm using PIXI 4.5.5 and am drawing directly to the canvas as well as using PIXI's renderer.
I noticed that the canvas is being transformed by PIXI and not being restored.

Example:
1) I define a stage with a single PIXI circle at 100,100
2) I directly draw a rect on the canvas at 0,0
3) I call renderer.render(stage) and it draws a circle
4) I draw another rect at 0, 0 and it get's drawn at 100,100

So when I do ctx.save() before calling the renderer and ctx.restore() afterwards my final rect is correctly drawn at 0,0

I guess renderer is not properly saving and restoring the canvas.

**Comment by ivanpopelyshev** [comment]
Good catch! Make it your first PR into pixi :)

https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/canvas/CanvasRenderer.js#L202 

All renderer plugins just use setTransform, and CanvasRenderer doesnt have save/restore there, it even clears the transform before it calls `root.renderCanvas` . Add save/restore or something like that.

There are not many PR's dedicated to CanvasRenderer because most people use WebGL already, but I was canvas enthusiast years ago.

**Comment by cawoodm** [comment]
https://github.com/pixijs/pixi.js/pull/4322

**Comment by themoonrat** [comment]
Closing as fixed!
