### ISSUE TITLE
Additive blending hack using VoidFilter caused graphical glitch on certain hardware

### ISSUE THREAD

**Issue by Spigo-Kevin** [pixijs/pixi.js#4323]
## Hack
Firstly, let me explain the hack, I have a sprite that I want to draw additively, but I also need an alpha mask (sprite mask) applied to it. This doesn't work on it's own, the mask is applied, but it's not drawn additively, to get around this, I'm creating a VoidFilter instance, setting the blend mode on it to "ADD", then I apply that VoidFilter to the sprite with the mask.

## Issue
Now the problem is, on certain hardware, this causes a graphical glitch where the sprite texture is offset, sometimes stretched, the glitch looks like UV coordinates being offset.

Here's a video showing the glitch: [https://www.youtube.com/watch?v=H5KHHRGV8Us](https://www.youtube.com/watch?v=H5KHHRGV8Us)

In the video we first show the glitch, then we comment out the VoidFilter, which shows the sprite being drawn with the mask, but not additively, we then revert and comment out the mask, showing the sprite being drawn additively, but without the mask. The glitch only occurs when both the VoidFilter and the mask are applied.

Here's a link for the JSFiddle shown in the video: [https://jsfiddle.net/wug6pm8d/3/](https://jsfiddle.net/wug6pm8d/3/)

The issue has only been observed in Chrome.

## Computer hardware
**CPU:** Intel core 2 duo, E7500 2.93Ghz
**Graphics card:** Ati Radeon HD 4350
**RAM:** 3Gb
**OS:** Windows 7 64 bit
**Chrome version:** Version 61.0.3163.100 (Official Build) (32-bit)

**Comment by ivanpopelyshev** [comment]
oh wow, that's very interesting! Something wrong with our pow2-framebuffer-pool . I believe there's workaround: 
1) mask in that case is the same as SpriteMaskFilter with certian sprite in the input, dont forget to set "sprite.renderable = false";
2) now that we have two filters instead of mask, we can use filterArea on them both. 

```
spriteMaskFilter = new PIXI.filters.SpriteMaskFilter(spriteMask);
container.filters = [spriteMaskFilter, voidFilter]; 
voidFilter.filterArea = renderer.screen; 
```

instead of "renderer.screen" you can pass a rectangle that certainly contains all the mask. Its defined in global coordinates, but you can just make simple calculation based on element position or elements bounds. 

When you dont specify it, "container.getBounds()" are used and they are changing, thus somehow affecting the bug. That's why I want you to calculate bounds and pass them as filterArea manually.

**Comment by ivanpopelyshev** [comment]
I like special effects that are implemented through filters and blendmodes, like that one: https://pixijs.github.io/examples/#/layers/lighting.js

Re-doing pixi-lights and deferred rendering with normal maps through pixi-layers + normal map filter is in my TO-DO list :)

**Comment by Spigo-Kevin** [comment]
Hey @ivanpopelyshev 

Thank you, that workaround solved our problem for now. Sounds like you have some interesting stuff in the works too :)

**Comment by ivanpopelyshev** [comment]
Its secondary. That's my primary work for now, flash/as3 -> pixi/ts translator : https://www.youtube.com/watch?v=adixpp9CK_A

**Comment by ivanpopelyshev** [comment]
btw, we have special channel in pixi slack, dedicated to filters/shaders, there's @Dairnon who uses a number of filters to make better lighting in Rpgmaker : https://www.youtube.com/watch?v=SzqgMfZar4I , I can send you invite to email if you want to know more about it.

**Comment by themoonrat** [comment]
Closing as a workaround was provided for your scenario :)
