### ISSUE TITLE
[FEATURE] add support for texturepacker polygon algorithm.

### ISSUE THREAD

**Issue by akhimchak** [pixijs/pixi.js#4336]
Hello,
Please add support for polygon pack method, this is very important feature that will dramatically reduce atlases sizes which is very important in gamedev.

**Comment by englercj** [comment]
I think this is a duplicate of #2243

**Comment by akhimchak** [comment]
May I ask add that feature for v4?

**Comment by ivanpopelyshev** [comment]
@akhimchak Its in my TODO least for a year already, but there are so many things, and my strategy is just pick a random one. 

So far no one gave me the case that shows that polygon packing will help in their project. For example, https://github.com/pixijs/pixi-compressed-textures is much more important, it reduces videomemory usage 4 times.

**Comment by ivanpopelyshev** [comment]
Anyway, I think that i'll make it as a plugin in a month or two, but again, if I pick that by a chance.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
i am making a small plugin for my project.
[plugin link](https://forums.rpgmakerweb.com/index.php?threads/pixi-spritesheets-animations-core-texturepacker.83083/)

this is not a very important feature, but I think it would be great to be able to optimize these sprite Sheets to the maximum.
I wonder though if the rendering and the updates will be no heavier.
for calculate polygons rather than squares ?

**Comment by ivanpopelyshev** [comment]
This plugin supports polygon packing: https://github.com/gameofbombs/pixi-heaven

Use `PIXI.heaven.Sprite`
