### ISSUE TITLE
Renderer shows black background with transparency: true

### ISSUE THREAD

**Issue by jchayan** [pixijs/pixi.js#4351]
I've neem using pixi 4.2.2.

```javascript
this.renderer = PIXI.autoDetectRenderer(this.width, this.height, {
    antialias: true,
    transparent : true,
    preserveDrawingBuffer: true
});
```

Before (4.2.2):

![previous](https://user-images.githubusercontent.com/8838243/31252465-eb725514-a9e6-11e7-830f-791575829c6c.png)

After (4.5.6):

![after](https://user-images.githubusercontent.com/8838243/31252525-15ffdfb8-a9e7-11e7-8aff-9921d1e2d832.png)

Any clues on what's going on?

**Comment by ivanpopelyshev** [comment]
No, need a fiddle.

**Comment by mudcube** [comment]
Noticed this when the width value is undefined:

```
const renderer = new PIXI.WebGLRenderer(undefined, undefined, {
	antialias: true,
	preserveDrawingBuffer: true,
	transparent: true
})
renderer.resize(1000, 1000)
document.body.appendChild(renderer.view)
```

This occurs because `SystemRenderer` is not expecting options as `arg3` when `width` is not a number, which results in the options being ignored.  I'm not sure whether you want to throw in that instance, or mixin defaults—so will leave that to someone with more authority.

**Comment by bigtimebuddy** [comment]
Renderer supports two argument signatures: (width, height, options) or (options). In the latter width and height are in the options object, which is the recommended signature. I agree with @mudcube that this.width is probably undefined. Closing.
