### ISSUE TITLE
After add `AlphaFilter(1.0)`, the performance become better. Why?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#4454]
It's so strange.

I render many sprites (in app.stage) to screen directly .

When I add a filter `AlphaFilter(1.0)` to app.stage, the performance become better .
About 1.5x faster ....

**Comment by ivanpopelyshev** [comment]
Filters use extra framebuffer which differs from the one webgl creates for us. Difference can be AA (antialias) or some other params we dont know about. Also for plugins like pixi-picture, which use texture copy to simulate advanced blending modes, its necessary to use AlphaFilter, otherwise it'll fall back to readPixels which is synchronous and extremely slow operation.

**Comment by ivanpopelyshev** [comment]
Yeah, 4x memory on default webgl MSAA :)
