### ISSUE TITLE
Constant mouseout and how to fight it.

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi.js#4461]
https://jsfiddle.net/kc902djw/2/

If user clicks often on the rectangle, it emits mouseout events.

**Comment by ivanpopelyshev** [comment]
One of possible ways to try solve that: css `user-select: none`

**Comment by themoonrat** [comment]
From my investigations so far, this is a Chrome only bug.
The reason a 'mouseout' event is being sent through pixi is because a 'mouseout' event is being sent out via the browser, as if the mouse is no longer over the canvas (when it clearly is). I've tried a variety of 'preventDefault' for a number of interaction events, but nothing has stopped this weird losing of focus (the event itself even has 'movementX' and 'movementY' as 0 each

**Comment by bigtimebuddy** [comment]
Is this because of the `passive` option in Chrome? http://tonsky.me/blog/chrome-intervention/

**Comment by djmisterjon** [comment]
true it seems to be related to moving the mouse + click
but if not move (batch click) its not  emits mouseout.
i test it with **network automate 10**  script
http://www.networkautomation.com/automate/demo-videos/

**Comment by DerivcoHK** [comment]
Encountering the same issue, I have tried "user-select: none", yet no luck.
Anyone have a workaround or is working progress on this issue?
I have only found that "processPointerOverOut" have been triggered during the click/tap action

**Comment by themoonrat** [comment]
I could never find a workaround for this. It still seems to happen on the latest Chrome, but not other browsers. Closing as not sure there's anything we can do here :/
