### ISSUE TITLE
Invalid value of `0` passed to `checkMaxIfStatementsInShader`

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi.js#4531]
Hey! 👍 

I am doing some work with Angular and a Canvas just now which is actually not the best documented thing out there.  Anyway I was messing around with Pixi, and I extend PIXI.Application.   When I try to destroy the application, I always hit this error.

https://github.com/pixijs/pixi.js/blob/0faef4fa3bcd0af8dba3a589bf4ddb7716b4c62a/src/core/renderers/webgl/utils/checkMaxIfStatmentsInShader.js#L19

Does anyone know why this line would be triggered? 

Thanks 💃

**Comment by HgMs** [comment]
I met the same problem today and got this solved my way.

I tried to cache canvas rendered by PIXI.WebGLRenderer when it's removed from DOM tree so that I could reuse this canvas rather than instantiate a new one when I need to render again. And I met this problem when the reused canvas was rendered.
I solved this problem by caching WebGLRenderingContext of WebGLRenderer as well.

Key error stack of this problem is in `SpriteRenderer.js`: `this.MAX_TEXTURES = Math.min(gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS), settings.SPRITE_MAX_TEXTURES);`, the result of `gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS)` is 0.
So I guess it's problem with the `gl` here, so I just tried to cache it as well and don't look into it deeper.
