### ISSUE TITLE
V5 Cut down on redunent calls

### ISSUE THREAD

**Issue by johnnymast** [pixijs/pixi.js#4556]
For v5 i wonder why a container has a size? remove the calculation and save a load of kb's in size. I am recreating the engine from scratch to learn from it. My 2nd recommended call would be rename Container to plane to be ready for 3D. 

Also altho this engine is great and i love it, why would you calculate the bounds of a container if you don't really use it. Speaking of it it would be a nice thing if you keep it make sure we can debug a container by setting borders on it. This would show for example scaled spirtes withing a red bordered container. This would make it more easy to debug. 

Also i want to help with a a module that cocus creator has. It has a system that connects to the canvas element and lets you change the resolution and the renderer so you can debug it how ever you want.

![screen shot 2017-12-21 at 22 34 57](https://user-images.githubusercontent.com/121194/34275830-43aac6fe-e69f-11e7-9d9a-b274c7944a94.png)

In the above picture mind the above part of the screenshot. This is what i want for pixi 5

**Comment by johnnymast** [comment]
Then also i want a level editor :) but i don't know the standard standard ... i'm using tiled a lot .. can you tell me what the most used game editor standard is now days ? i See that Pixi uses a json standard for spritesheet animations but is it still the standard?

**Comment by ivanpopelyshev** [comment]
Because flash legacy. I agree that its not intuitive and people really shouldn't use  "width" and "height" aka getLocalBounds(). However getBounds() are used heavily in filter and some other places.

As for Tiled, everyone makes importer suited for their game.

The idea of PIXI is that we dont have any built-in persistance classes, Edit tools are not first-class citizens. We want to make it easier for people (like switch rotation to degrees), but when we choose code quality over editor support.

**Comment by artvinn** [comment]
hey @ivanpopelyshev 
You said 

> people really shouldn't use "width" and "height" aka getLocalBounds()

Could you please explain what you mean by that, and what would be the more proper way to do it in your opinion? Sorry if it's a little offtopic.

**Comment by ivanpopelyshev** [comment]
Because it changes internal transforms, temporarily. I made many changes to `_updateID` system but im still don't trust it much. 

Transform should be updated relative to the root, and if there's need to calculate local bounds, there must be temporary Transform object.

My PR related to that were too difficult, were rejected.

**Comment by ivanpopelyshev** [comment]
That's one of my tries: https://github.com/pixijs/pixi.js/pull/3711
