### ISSUE TITLE
ParticleContainer autoResize is being ignored

### ISSUE THREAD

**Issue by nscarcella** [pixijs/pixi.js#4649]
Hi guys, I'm relatively new to the library, but I have the feeling `ParticleContainer.autoResize` is misbehaving.

Basically, it looks like it's not auto-resizing at all. After setting `autoResize` to `true` children above the `maxSize` cap does not get rendered.

You can reproduce this on [the v4 examples](http://pixijs.io/examples/#/demos/batch.js) by replacing:

```js
var sprites = new PIXI.particles.ParticleContainer(10000, {
    scale: true,
    position: true,
    rotation: true,
    uvs: true,
    alpha: true
});
```

with:

```js
var sprites = new PIXI.particles.ParticleContainer(1, {
    scale: true,
    position: true,
    rotation: true,
    uvs: true,
    alpha: true
},undefined, true);
```

**Comment by ivanpopelyshev** [comment]
You are right. 

This is the place where it happens: https://github.com/pixijs/pixi.js/blob/dev/src/particles/webgl/ParticleRenderer.js#L176

This is non-priority issue, I added autoResize not so long ago.

**Comment by interwebjill** [comment]
I too would like to use the autoResize functionality.

**Comment by themoonrat** [comment]
@ivanpopelyshev I'm wondering if we'd close this down if it's sorted for v5?

**Comment by ivanpopelyshev** [comment]
I didnt look for this bug both in v4 and v5.

**Comment by Teoxoy** [comment]
This is still an issue and it's because of this https://github.com/pixijs/pixi.js/blob/ba03f57001cd8bae3ae3644911cd513c68184e7c/packages/particles/src/ParticleRenderer.js#L112 That line limits the nr of children the for loop loops over. I removed it locally and it seems that now `autoresize` works fine.
I also found this https://github.com/pixijs/pixi.js/issues/5314#issuecomment-450492188
@ivanpopelyshev said he forgot to remove it actually

There is also another problem in the `ParticleContainer` class: https://github.com/pixijs/pixi.js/blob/31dd1ac6179718917821810539e34950182dfd22/src/particles/ParticleContainer.js#L50 Here the `batchSize` is being limited by the `maxSize` which is wrong imo.

Tell me if you want me to put up a PR that fixes those 2 issues!

**Comment by bigtimebuddy** [comment]
PR welcome @Teoxoy

**Comment by Teoxoy** [comment]
Instead of removing it we could actually change it to `else if (totalChildren > maxSize && !container.autoResize)` and remove this check https://github.com/pixijs/pixi.js/blob/ba03f57001cd8bae3ae3644911cd513c68184e7c/packages/particles/src/ParticleRenderer.js#L158 so that it's not redundant
