### ISSUE TITLE
Multitouch screens interactiveManager problem

### ISSUE THREAD

**Issue by kopacabana** [pixijs/pixi.js#4785]
Hello,

I work with PIXI.js for an exhibiton. Your framework is great. Thanks for it.

I've got a problem with InteractiveManager when we use it on mulitouchscreen.

I create a class for interact with blocks (triangle, square, etc). 
On each block, I add events (pointerdown, pointermove, pointerup and pointerupoutside).
Everything works well but sometimes, event for pointerup and pointerupoutside are not fired. Only pointerdown ! 
I can not reproduce this bug, sometimes when I click on the shape, it happens sometimes when I try to move it.

Any idea ?
Thanks
Loïc

**Comment by ivanpopelyshev** [comment]
I think it should work. @themoonrat may know some tricks.

Anyway, please make a fiddle.

**Comment by ivanpopelyshev** [comment]
Also pixi is not framework, its a base for your own game engine or framework. We really love people who want to make their own tech. If you find something wrong with InteractionManager (https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L990), you can override it like here: https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#interaction

**Comment by themoonrat** [comment]
@kopacabana I sometimes have an event listener to the global up rather than just an object.
`renderer.plugins.interaction.on( 'pointerup', this._updatePointerLocation, this );`
Sometimes, the code to move the object means that when the release is processed the object is no longer under the  'up' point. By listening to the global up, and using `event.data.pointerId` to track which pointer has been actioned I think you might be able to achieve what you require?

**Comment by kopacabana** [comment]
Thanks.
I'll try your solution.

**Comment by themoonrat** [comment]
@kopacabana Closing since we haven't heard back from you so hoping you're sorted! Feel free to re-open if you're still having an issue with this
