### ISSUE TITLE
Video performance issue using webgl renderer (V4.7.1)

### ISSUE THREAD

**Issue by TimRoussilhe** [pixijs/pixi.js#4789]
Hello,

I'm trying to instantiate 3 videos at the same time. With the WebGL renderer, the FPS drops below 20fps. If I switch to the canvas renderer the performances are around 60FPS.

Any tips to improve the performances of the video with the WebGL renderer?

I also noticed that if two videos have the same size they will flicker when played ( once again WebGL only ).

**Comment by allanbreyes** [comment]
@TimRoussilhe can you share what Browser and OS you are using?

**Comment by TimRoussilhe** [comment]
Hey @allanbreyes 
OS: Mac ( Macbook Retina 2014, Sierra )
Browser: Chrome ( 65.0.3325.181)

Here is how I simply create the video Sprite, I also have a system to only play the visible one but FPS stay around 20 FPS either way

`createVideoSprite(videoSrc){

		let video = document.createElement('video');
		video.preload = 'auto';
		video.loop = true;
		video.autoplay = false;
		video.src = videoSrc;

		video.pause();

		// create a video texture from a path
		let texture = PIXI.Texture.fromVideo(video);
		// create a new Sprite using the video texture (yes it's that easy)
		let videoSprite = new PIXI.Sprite(texture);

		return videoSprite;
	}`

**Comment by bigtimebuddy** [comment]
There is one performance optimization that may help. The video texture is updated with Pixi’s Ticker. For video this can be a problem because most video doesn’t need to update 60fps since most video is probably 15-30.  Is you have three videos that would make the problem even worse. Try changing PIXI.ticker.shared.FPS or, even better, manually update the videos yourself with a new ticker (as not to interfere with other internal things that use the shared tickerlike interaction).

**Comment by themoonrat** [comment]
Putting as a v5 issue as a reminder to add in being able to control the update rate of videos to help situations like this

**Comment by jonhuang** [comment]
As a dirty hack for a quick demo, I was able to slow down my video updates with a quick monkeypatch and a library throttle.

`PIXI.VideoBaseTexture.prototype.update = _.throttle(PIXI.VideoBaseTexture.prototype.update, 33);`

**Comment by themoonrat** [comment]
Ability to limit update rate of videos is merged into v5
