### ISSUE TITLE
Flickering Sprites on Samsung Galaxy S7

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi.js#4790]
Hi,
I'm experiencing some strange flickering in my game on an S7.
I went through the PIXI demos to see if it occurred  on any of those and I found the Slots Demo exhibited the same behaviour.
I tried the legacy, antialias, preserveDrawingBuffer & transparent render options as per the Wiki - but with no luck. I also tried a gl.flush() after the render call.
I've been trying to isolate the cause by removing filters, blendmodes & masks but whatever i remove the flickering persists.
Anyone else having trouble with this device? I'm kind of out of ideas of what to try next.

**Comment by Patrick-Hammond** [comment]
If I remove the Blur filter from the Slots Demo by commenting out the line: `rc.filters = [reel.blur]`
then the flickering stops.
Hopefully that might be a clue!

**Comment by ronaldoklais** [comment]
Flickering problem in my android 4.2.1 phone, model BLU VIVO 4.8 HD.

I tried to open the examples from the pixijs website and they flicker too. Some times when scroll the page down until the scene disappear and back up again, they stop the flickering.

**Comment by themoonrat** [comment]
@Patrick-Hammond Any luck in investigating this? I'm wondering if browser updates will have meant Chrome has blacklisted certain commands for certain hardware to get WebGL working on them without issues

**Comment by Patrick-Hammond** [comment]
@themoonrat I'll take another look at it when I'm back at work Monday. I've since tested another PIXI based project on the S8 without problems, so it remains a bit of a mystery!

**Comment by themoonrat** [comment]
Indeed, we have no issues on that phone with the games at our company.

**Comment by Patrick-Hammond** [comment]
Just tested again and the flickering still persists on the S7 (not S8 as I mentioned previously) after a factory reset and then a Chrome update. We haven't seen this issue on any other Samsung device. Our solution was to sweep the problem under the rug and hope that noone trips over it anytime soon. If anyone can offer clues, perhaps regarding hardware or drivers on the S7, would be most appreciated!

**Comment by st3v0** [comment]
I can confirm this is an issue, we're having the same problem. Below are the phone specs I tested on;

Device: Samsung Galaxy S7
Model: SM-G930F
Android Version: 7.0
Kernel Version: 3.18.14-12365438
Build #: NRD90M.G930FXXU1DQJ8

**Comment by themoonrat** [comment]
So I have perhaps more information on this @bigtimebuddy / @GoodBoyDigital

I too, am now having issues _only_ on the Galaxy S7. One of the games has flickering, the other game just crashed the WebGL context. The former we solved by just not using a blur filter on the S7, but the later crash occurs when using a sprite mask.

I've attached an image of where the exception is found.

![image](https://user-images.githubusercontent.com/1528426/45106691-3a084580-b12f-11e8-9dd7-fdf631a2ce58.png)

The problem occurs when the `compileShader`  function fails, and returns null. It appears valid for compileShader to return null if something goes wrong, but nothing handles it. So then you're trying to pass through null to `attachShader`, and then Armageddon occurs.

**Comment by st3v0** [comment]
I've done some more investigation on this and I can confirm the issue is related to android 7 because it doesn't occur on android 6 or 8. Also it's not limited to the BlurFilter I've managed to reproduce this with other filters also, including using only the AlphaFilter.

**Comment by bigtimebuddy** [comment]
Does modifying the default precision settings change this at all? For instance:
```js
PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH;
PIXI.settings.PRECISION_VERTEX = PIXI.PRECISION.HIGH;
```

**Comment by st3v0** [comment]
@bigtimebuddy Unfortunately no it doesn't. I tried `LOW` and `MEDIUM` also with no effect.

**Comment by themoonrat** [comment]
@st3v0 - my crash happens on our s7 that's on Android 6, happened on our s7 edge on Android 7. We updated the s7 edge to Android 8... happens there as well! Not tested the flickering since the upgrade tho.

**Comment by st3v0** [comment]
@themoonrat unfortunately I haven't been able to reproduce the crash more then a couple of times. The only time it occurred for me was on the S7@7.0. I did test the flicker issue on S5@5.0, S6@6.0, S7@8.0 and S7Edge@7.0, none of them crashed however the flicker occurred on all Nougat devices.

**Comment by st3v0** [comment]
I realize this is closed however I'd just like to update everyone interested where I've gotten with this flicker issue, since I've become stuck, maybe my findings will help spark a thought.

I setup a [codepen](https://codepen.io/st3v0/pen/WdqrXX) to help replicate the problem. Firstly to easily highlight the problem I set `legacy: true, preserveDrawingBuffer: true, clearBeforeRender: false`. Also a BlurXFilter is being applied to each column. And the sprites are being tinted based on the column their in. Please look at the [codepen](https://codepen.io/st3v0/pen/WdqrXX) if you want to know more.

`Image 1` in the attached screenshot demonstrates what the pen looks like rendered on a desktop or android 8+ device. The other 2 images are showing the flicker being captured due to the above settings. These are screenshots taken from an S7@7.0.

![example](https://user-images.githubusercontent.com/2800093/53782820-bfdc4080-3f5a-11e9-90f3-e8dc1e175c98.jpg)

## Findings
The first interesting thing I found was that setting the quality of the blur filter to 1 resulted in the flicker not occurring. This suggested to me that it was a problem with the flip/flop in the filters apply method, since a quality of 1 results in 1 pass and skips the flip/flop altogether. 

I then thought it was a problem with the missing clear call in `filterManager.getRenderTarget` since the filter passes `true` for the clear arg however that arg isn't used in that method. So I added a clear check and cleared the render target before returning however this didn't solve the problem.

I then discovered that the renderTargets are cached and reused based on powers of 2. In my example each column was the same size which results in the same renderTarget being reused for all of them. Based on `image 2` above this lead me to believe that the render target isn't being cleaned properly before be reused. However executing clear on the target did nothing. 

To prove further that the render targets are not be cleaned properly I first adjusted the height of each column so there was 1 in column 1, 2 in column 2, 3 in 3, etc... This results in each column getting their own targets because the size of each column is unique for each the target for column 1 was 128x128, column 2 was 128x256, 3 was 128x512 and column 4 was 128x1024. 

This test resulted in no flicker occurring YAY!. I then changed column 3 to have 4 images instead of 3, which meant it would reuse the render targets from column 4 and BOOM! `image 3` shows the flicker again but only between the last 2 columns.

## Conclusion
Unfortunately this is where I'm stuck I can't figure out why calling `renderTarget.clear()` doesn't actually clean it up? Why when it reuses a render target does it draw what was last drawn on that target. Could it be a problem with the `gl.clear` or is it something in pixi, I don't know. Is there another way to clear the render targets?

**Comment by st3v0** [comment]
@bigtimebuddy @GoodBoyDigital I created a new [example](https://codepen.io/st3v0/pen/eXrOvv) using pixijs 5.0.0-rc2 and this issue still occurs.
