### ISSUE TITLE
TextMetrics.MeasureText () handles '\n' incorrectly (4.7.1)

### ISSUE THREAD

**Issue by robertswan** [pixijs/pixi.js#4791]
4.7.1 has introduced a new bug: strings using wordwrap that also include newline character are calculated incorrectly.

Looking through the code it appears the string is broken into words and measured per word (correct) but when checking for wordwrap it does not respond to a newline in the word (incorrect) by starting a new line measurement at 0 width. This leaves the the line and subsequent lines mis-measured and wrapping incorrectly. Rendering confirms this.

Repro on: 
* machine: macbook pro
* browser: chrome 65.0.3325.162
* I'd expect the bug on all platforms

Expected Result (4.7.0):
* http://pixijs.io/examples/?v=v4.7.0#/basics/text.js
* change ```Rich text with a lot of options and across multiple lines``` -> ```Rich text with a lot of options\nand across multiple lines```
* rerun
* see:
```
Rich text with a lot of
options
and across multiple lines
```

Actual Result (4.7.1):
* http://pixijs.io/examples/?v=v4.7.1#/basics/text.js
* change ```Rich text with a lot of options and across multiple lines``` -> ```Rich text with a lot of options\nand across multiple lines```
* rerun
* see:
```
Rich text with a lot of
options
and across
multiple lines
```

**Comment by bigtimebuddy** [comment]
Probably related to #4545 
@brenwell could you please take a look at this?

**Comment by brenwell** [comment]
Yes I see, I will take a look

**Comment by brenwell** [comment]
@bigtimebuddy 
Ok I am looking into the issue, and it has brought about a question. How to handle spaces, should they be preserved on new lines or not, I think previously it was removing the first space and keeping the rest on a new line unless its the first line.

### Multiple spaces

If the text is `this-is-my-text---I-love-it` (*dashes represent spaces*)

Should it be like this
```
|this-is-my-text-|
|--I-love-it     |
```
Or like this
```
|this-is-my-text  |
|I-love-it        |
```

### Single spaces

If the text is `this-is-my-text-I-love-it`  (*dashes represent spaces*)

Should it be like this

```
|this-is-my-text|
|-I-love-it     |
```
Or like this
```
|this-is-my-text|
|I-love-it      |
```

**Comment by bigtimebuddy** [comment]
These are good questions. In general if we are auto-wrapping I think it makes sense to trim. However, we should probably maintain spaces after explicit newline characters:

this-is-my-text--\n-I-love-it

this-is-my-text
-I-love-it

**Comment by bigtimebuddy** [comment]
What do others think? Thoughts, @themoonrat?

**Comment by themoonrat** [comment]
Sounds like a good strategy to me. Trim on word wrap, don't trim on newline characters.

**Comment by robertswan** [comment]
Following html everything is trimmed, and users can use non-breaking space if they want to add them.

FWIW I've just checked and pixi supports the unicode non-breaking spaces:
* \u00A0
* \u202F
* \u2007
* etc

**Comment by brenwell** [comment]
This task has alot of elements and I am trying to get them all locked down so I can have test for them
Does this look like the desired result then?

- [ ] keep spaces at beginning of text
- [ ] remove spaces from the end of all lines
- [ ] remove spaces from beginning of all wrapped lines
- [ ] keep spaces after a all newline char including overflow words
- [ ] apply letter spacing to all chars including spaces and considered in width calculation
- [ ] do not consider dropShadow  in width calculation
- [ ] overflow words start new line, then wrap as needed

> overflow words = words longer than wordWrapWidth

**Comment by brenwell** [comment]
I see another issue, should stroke be considered as a part of width?

```js
// |strokeWidth|charWidth|LetterSpacing|strokeWidth|

// if not space

const charWidth = (strokeWidth*2) + charWidth + LetterSpacing
```

**Comment by brenwell** [comment]
thats not correct its more like

```js
// |strokeWidth|lineWidth|strokeWidth|

const paddedWordWrapWidth = wordWrapWidth - (strokeWidth*2)
```

**Comment by bigtimebuddy** [comment]
I don't think we should consider stroke part of the character width. Stroke and shadow should be agnostic of layout. Padding should consider these things so they won't be clipped, but not char spacing.

**Comment by brenwell** [comment]
ok got it

**Comment by TheWyo** [comment]
I've recently run into a newline issue which I believe is related to the changes going on here.

Use of word wrap on text consisting of a single word which exceeds the wordWrapWidth causes TextMetrics.wordWrap to add a newline to the end of the word-wrapped string. I've not tested it, as it's easily reproducible with just the one word, but I assume similar behaviour will happen on any ending word which will exceed the wrap width.  
On Text objects with a 0 y-anchor this doesn't cause a visual difference (though would affect the results of measureText), but on an anchor of something like y0.5 you'll start getting unexpected visual offsets caused by the trailing newline character.

This seems to be caused by the addLine call here: 
https://github.com/pixijs/pixi.js/blob/7882eff0ad510a128d64e46c127647f35bfde043/src/core/text/TextMetrics.js#L249-L253

I've put a little workaround in my own local copy to fix it for my usage needs by checking if it's the last token like so:
```javascript
var isLastToken = i === tokens.length - 1;
lines += TextMetrics.addLine(token, !isLastToken);
```

 I haven't made a pull-request or anything for this it's more of a hacky/temp fix and there's been talk here already about how to handle trimming etc, but figured I'd let you know about this issue and where it's coming from.

**Comment by brenwell** [comment]
That solution seems like a fine to me.

**Comment by bigtimebuddy** [comment]
Wanna make a PR, someone? @brenwell?

**Comment by brenwell** [comment]
(iPhone typing sorry)

**Comment by TheWyo** [comment]
If you guys are happy with that suggestion then here you go. One PR for it.
