### ISSUE TITLE
Using only named imports for ES6 Modules

### ISSUE THREAD

**Issue by allanbreyes** [pixijs/pixi.js#4827]
This [article](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad) covers it better than I can. Would y'all accept a PR that refactored to named imports? I'm pretty sure this can can be achieved without breaking the API, e.g. modules can _still_ have default exports, but internally, they would only use named imports. Thoughts?

**Comment by bigtimebuddy** [comment]
I read the article and did a little more googling on the issue. Overall, it makes sense although the benefits in our case maybe a little overstated. None of our top level packages do default exports, so this mostly would be an internal change. Rollup flattens to all named exports so this feels more like a stylistic issue than a functional one.

That said, I’d be interested in seeing a PR for this, however, I’d like to get buy in from @englercj before you are off running with this. Chad, thoughts?

**Comment by bigtimebuddy** [comment]
Just to clarify, this would be for v5 only.

**Comment by bigtimebuddy** [comment]
One benefit is that export statements like this:

```js
export { default as Renderer } from './Renderer';
```
would become:
```js
export * from './Renderer'`;
```
👍

**Comment by allanbreyes** [comment]
I was hoping to reap some bundle size reduction benefits from dead code removal and tree-shaking when only using a subset of the features. I didn't notice any appreciable benefits from tree-shaking `import { Application } from 'pixi.js'` vs `import * as PIXI from 'pixi.js'` (on 4.x), despite the differences in the [dependency graphs](https://gist.github.com/allanbreyes/5254e03c4f8a1451c029a617786f6fc8) (generated via `madge`)

`Application.js`
![image](https://user-images.githubusercontent.com/7947900/38319501-c8ea99aa-37e6-11e8-954e-65c9f00ee1fa.png)

`index.js`
![image](https://user-images.githubusercontent.com/7947900/38319537-dec9d33a-37e6-11e8-8198-4c3ee16b1c02.png)

IIUC, having all internal imports/exports as named would mean that a developer could do a named import of whatever they needed, and it would result in (hopefully) significant bundle size savings when they tree-shake. Arguably, this could be a moot point for `next`/v5 due to Lerna.

**Comment by ivanpopelyshev** [comment]
You have to embed a bundle in your app: https://github.com/pixijs/pixi.js/blob/next/bundles/pixi.js/src/index.js . If you dont do that, plugins wont be registered. There's no way out of it. No amount of webpacks, rollups, lernas will save you from this thing.

**Comment by bigtimebuddy** [comment]
To @ivanpopelyshev's point, people _can_ import a package directly, but, yes, they need to install the renderer/loader plugins themselves. That'll take some work to explain to folks but that's the direction we want to head in.

**Comment by englercj** [comment]
I do like the stylistic benefit of being knowledgeable about exactly what you are importing. Generally I have no strong feelings, but named-only imports seems "better" on the surface.

The only two comments I have are:

1. We do need to interop with CommonJS and so we should ensure that continues to work, which generally implies default exports. Don't forget that some people `require()` source files directly, not just `index.js`. As long as named exports compile to something semantically meaningful in CJS, all is well.

2. I don't think the tree-shaking benefits they mention in that article really affect us, because we don't do the "default export an object containing other imports" pattern except in the main index.js file (which should include everything anyway).

My conclusion is that this sounds like a good practice to follow, but also has only nebulous or subjective benefits for pixi and may not be worth the trouble of enforcing. More important to simply enforce not falling into the anti-patterns that cause problems (which we currently don't use).

**Comment by bigtimebuddy** [comment]
Great thoughts Chad. So @allanbreyes, I think a good path forward might be to make a PR for maybe packages/core and see what the impact looks like and how much effort before we convert all import/exports. What do you think?

**Comment by allanbreyes** [comment]
:+1: sure thing, I'll take a look-see. Gotta get spun up on Lerna first (never used it in practice). Got a go-to-resource for it? (Side note: maybe something in `CONTRIBUTORS.md` should be said about it as well.)

**Comment by bigtimebuddy** [comment]
If you have any questions about v5, Lerna or the new build setup just message me on Slack. Happy to point you in the right direction.
