### ISSUE TITLE
PIXI.loader and loading progress.

### ISSUE THREAD

**Issue by anya1696** [pixijs/pixi.js#4862]
Hello,
I use PIXI.loader to load a lot of assets and there is need in displaying progress.  While loading big athlas the progress isn't updating at all. 
Is there a possibility to count progress by the loaded bytes not the number of files, or any other possibility to know loading progress of a big file?

**Comment by ivanpopelyshev** [comment]
I'm sure its possible.

Our loader is based on https://github.com/englercj/resource-loader/

@xerver knows how to do that.

**Comment by englercj** [comment]
AFAIK the only type of loading that the browser reports byte progress on is XHR requests. And it only does it with XHR if then server content headers are correct.

The Loader's progress is the progress of loading resources. It advances each time a resource completes loading. Individual resources can report their own individual progress (byte progress) as well, but like I mentioned only will do so under certain circumstances (XHR).

Currently the Loader doesn't combine the byte progress of a resource into the global progress of the Loader. Mostly because it requires a fair bit of work and no one has asked for it before. You can listen to the onProgress signal on the Resource object though if you wanted to use it in some clever way (`loader.resources[name].onProgress.add(() => {})`).

**Comment by ivanpopelyshev** [comment]
Summary: its not possible for images.

**Comment by englercj** [comment]
> Summary: its not possible for images.

Not true, like I said you can load it as a blob and have it get parsed. This should happen automatically as the [blob parser](https://github.com/englercj/resource-loader/blob/master/src/middlewares/parsing/blob.js) should turn it into an image, and then pixi's texture parsers will turn it into a texture.

The hard part is just going to be displaying the progress in a meaningful way. Lots of games have 2 progress bars, one for overall progress and one for the specific resource being loaded. That doesn't really make sense here though because the loader is a parallel loader. However, if you pick and choose a couple long-loading resources to show in a smaller bar under the first global one it will probably work well.

**Comment by anya1696** [comment]
I will try to load as blob and leave a comment later.

**Comment by themoonrat** [comment]
@anya1696 closing as I think you have the answer you need? :)
