### ISSUE TITLE
Video texture in loop blinks at the end

### ISSUE THREAD

**Issue by hellopath** [pixijs/pixi.js#4937]
Hi guys,

I have a video texture with the video element in loop. It loops correctly but at the end before start again, I have a empty frame and the video blink. It doesn't look smooth and it's even more visible when I have short videos. I experience that on both renderers, canvas and webgl, on chrome. 

You can reproduce the issue on `https://pixijs.io/examples/#/basics/video.js`, just add these 2 extra lines after the creation of the texture.
```
// create a video texture from a path
var texture = PIXI.Texture.fromVideo('required/assets/testVideo.mp4');
video = texture.baseTexture.source
video.setAttribute('loop', true)
```
- `pixi.js` version: 4.7.0
- Browser: Chrome 66.0.3359.181
- Device: Desktop

Thanks for you help

**Comment by photonstorm** [comment]
More often than not this is because of the way the video was encoded. You’d do well to pass it through an app like Handbrake which will optimise out the crap and leave you with a much smaller and better encoded video. Usually this is enough, but it can take quite a bit of trial and error with codecs and bitrates before you find something suitable for your specific video.

In short though, it’s not a problem Pixi can fix, it’s an asset / browser combo problem.

**Comment by hellopath** [comment]
Thanks for the answer @photonstorm, i'll try that!
