### ISSUE TITLE
4.8.0 BitmapText not rendering

### ISSUE THREAD

**Issue by digilocker** [pixijs/pixi.js#4957]
Hi, have recently tried updating our project from 4.7.3 to 4.8.0 - no noticeable issues only that the bitmaptext instances we are creating are not rendering at all.  No complaints within the console and they appear in the pixi-inspector, just not rendering.  The fonts were exported using shoebox, has anything changed that we should be aware of?

**Comment by FNevesFMQ** [comment]
I'm experiencing same problem here. After some tests I realized that the only way for this to work is in .fnt file, chars has to had attribute "page" defined, otherwise they don't appear.

This works:
`<char id="37" x="0" y="0" width="61" height="59" xoffset="0" yoffset="10" xadvance="63" page="0"/>`

This not:
`<char id="37" x="0" y="0" width="61" height="59" xoffset="0" yoffset="10" xadvance="63"/>`

And pages usually reffers to font image file, like:
`<pages>
<page id="0" file="FontImageFile.png"/>
</pages>`

**Comment by digilocker** [comment]
@FNevesFMQ that's brilliant thanks for sharing this, will take a look at the export options in shoebox and see if this can be automated, otherwise will try and edit manually for now :)

**Comment by andrewstart** [comment]
This was fixed yesterday in https://github.com/pixijs/pixi.js/pull/4951, so will be all set without having to change your exports when 4.8.1 comes out in the near future.

**Comment by bigtimebuddy** [comment]
Plan to make a release soon. But if you want to verify for us try this build: https://pixijs.download/dev/pixi.min.js

**Comment by FNevesFMQ** [comment]
Yes, with that dev version it's working again ;)
