### ISSUE TITLE
Video example v4 not working in Samsung Internet browser

### ISSUE THREAD

**Issue by vapesolius** [pixijs/pixi.js#4987]
https://pixijs.io/examples/#/basics/video.js
Video on this page is not playing in Samsung Internet browser and UC Browser
Only sound playing.
Also will be nice to have 2 video formats (mp4, webm) and dynamic switch between them.

### Expected Behavior
Video is playing
### Current Behavior
Only sound playing
### Possible Solution
BaseVideo texture size is 0,0 looks like problem here
### Steps to Reproduce
Open provided page in Samsung Internet browser
### Environment

- `pixi.js` version: 4.8.1
- Browser:Samsung Internet and US Browser
- Device:Samsung Galaxy S9

**Comment by ivanpopelyshev** [comment]
It all depends on video and codecs. Nothing can be done from pixi side about this problem.

**Comment by themoonrat** [comment]
Indeed. Video in pixi just takes a <video> tag and uses that as a source to draw to the screen. 
In terms of formats, I think that's for the developer to decide what is supported where, and therefore what extension to use where.
(although I'd guess that if you create your own video tag, with multiple sources, you'd be letting the browser use a compatible format, and you can use that as your texture source in PIXI)

**Comment by telime** [comment]
This problem is not a problem of the encoding method and it is not solved. 
Video texture does not work properly in Samsung Internet Browser in every environment.
(However, UC Browser seems to be a problem of "crossorigin")
Since "video sphire" of "a-frame" works, there seems to be some way.
https://aframe.io/examples/showcase/videosphere/
