### ISSUE TITLE
isWebGLSupported works incorrect

### ISSUE THREAD

**Issue by MinchukSergei** [pixijs/pixi.js#5012]
### Environment

- `pixi.js` version: 4.8.1
- Browser: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Device: Laptop Dell xps 15 L502x

**Comment by themoonrat** [comment]
Think of the function not just as a 'is WebGL supported by the browser' but 'is WebGL supported with features required by Pixi'.

There is a reason failIfMajorPerformanceCaveat is there... because without it, we'd be flooded with questions as to why the performance in canvas renderer is better then the WebGL renderer. And I believe stencil support is required for parts of pixi to work.

If you wanted to go against the recommendations then I'd say fork your own version of pixi, edit that function and see what happens! :)

**Comment by MinchukSergei** [comment]
Themoonrat, thank you very much, I got you.
