### ISSUE TITLE
Is there anyway to hooking when a DisplayObject was created?

### ISSUE THREAD

**Issue by tommyZZM** [pixijs/pixi.js#5035]
some thing like 

```javascript
PIXI.DisplayObject.on("created", displayObject => {
    // so programmer can do something to patching the displayObject
})
```

**Comment by jcyuan** [comment]
I think this is an user-level issue.
you can customize these events like:
class myclass extends PIXI.DisplayObject {
        constructor(){
                super();
                this.emit('created');
        }
}

**Comment by themoonrat** [comment]
Closing as I think the above solution is the best shout. Since the display objects are being created by you... it's your responsibility to track them. Whether that's via a customised  class, like jcyuan suggests, or via creating the objects via util functions, which you could then tap into; your choice :)
