### ISSUE TITLE
开发环境?

### ISSUE THREAD

**Issue by 958877748** [pixijs/pixi.js#5051]
开发环境是什么样的?  我不明白

**Comment by 958877748** [comment]
Can anyone tell me the details of the development environment?
有谁能告诉我开发环境的详细情况?

**Comment by 958877748** [comment]
IDE = WebStorm?

**Comment by fightingcat** [comment]
"issues" is a place to track bugs, not for asking for help. Pixi.js is basically a webgl renderer, not much a game engine, how to struct your project is up to you, there isn't a prefered IDE, it may require basic web front-end background knowledge, there are [awesome tutorials on the website](http://www.pixijs.com/tutorials) can help you getting started. Otherwise, try egret engine instead which have Chinese documents and official integration tools.

“issue”是追踪bug的地方，不是用来提问的。Pixi.js基本上是个webgl渲染器，不太算一个游戏引擎，如何搭建项目取决于你自己，并没有什么推荐的IDE之类的，可能还是需要你有基本的web前端背景知识，官网上有[很棒的例子](http://www.pixijs.com/tutorials)帮你起步。不然的话，试试egret引擎吧，有中文文档和官方的集成开发工具。

**Comment by 958877748** [comment]
I'm not asking how to use Pixi to develop something.
我不是在问怎么样使用pixi开发一些东西
But what is the development Pixi use?
而是开发 pixi 使用的是什么?
I'm sorry, I shouldn't be asking questions here.
抱歉不应该在这提问这些的
But I can't find some information.
但我实在是找不到一些相关资料

**Comment by jcyuan** [comment]
随便什么编辑器啊，vscode，sublime，选你自己熟的，环境当然是node.js + npm
工程插件babel + eslint + webpack

**Comment by 958877748** [comment]
We have found the details, thank you.
已找到详细资料,多谢各位

**Comment by soimy** [comment]
那就把这个issue关闭了把，毕竟这里不是Q&A

**Comment by fightingcat** [comment]
使用pixi.js和使用一个库进行前端开发非常类似，你可以按照前端的方式去搭建项目，你可以手动在HTML文件中引入pixi.js文件，也可以通过引入npm包，用webpack/rollup等bundler打包和注入代码到HTML。pixi.js没有提供一个脚手架工具，你也许可以以“pixi.js scaffold”为关键字搜索一下看有没有现成的工具。
