### ISSUE TITLE
Video pause on specific time

### ISSUE THREAD

**Issue by louisatome** [pixijs/pixi.js#5097]
I have a sprite with a video texture and I try to pause the video on a specific time and render the associated frame.
My code : 
```
// [...]
var videoSprite = new PIXI.Sprite(videoTexture);
button.on('pointertap', onClick);

function onClick() {
  videoTexture.baseTexture.source.currentTime = 5;
  videoTexture.baseTexture.source.pause();
  videoTexture.update()
}
```
The video sprite is paused but it doesn't update to the frame I set.

Fiddle : http://jsfiddle.net/v1qrtspw/4/

### Environment

- `pixi.js` version:  4.8.1
- Browser: Firefox 61

**Comment by themoonrat** [comment]
So, partly, this is because of how the html video works. When you seek video, it won't switch to that immediately; it needs to seek.

Goto http://jsfiddle.net/Flocke/NpgD5/ in Chrome, look at the source of the video, click the video tag and do 
```
$0.currentTime = 5;
$0.pause()
```
You'll see the video pauses where it is for a bit, and then updates to the earlier frame. So you're changing the currentTime, and wanting to update the texture immediately... but the way html video works, it's not going to change frame immediately.

And because you've paused the video, Pixi takes that as 'don't automatically update the texture anymore'; so when the html video does seek to somewhere else, the texture won't be updated. Thus you manually updating it is correct... but it's done too soon.

So....
Take a look at this fiddle: http://jsfiddle.net/8bmhfw5t/
You see I add
```
videoTexture.baseTexture.source.onseeked = function() {
    videoTexture.update()
};
``` 
So that when the video has completed a 'seek' operation (via changing it's current time) it will update the texture.

**Comment by louisatome** [comment]
@themoonrat Thank you for the clear explanation !
