### ISSUE TITLE
BitmapText maps incorrectly on UHD/retina displays

### ISSUE THREAD

**Issue by Metafaux** [pixijs/pixi.js#5171]
### Expected Behavior
Bitmap text readable on UHD / Retina displays

### Current Behavior
Bitmap text mapped incorrectly, displayed in jumbled fragments of letter forms
<img width="117" alt="bitmaptextuhd" src="https://user-images.githubusercontent.com/23660334/47111211-c1a1a380-d207-11e8-99f2-4df0b22c1979.PNG">
(text still maps correctly on standard HD/1080 PC screens, and renders correctly on all resolutions in Pixi 3)

### Steps to Reproduce
1. Create XML & PNG bitmap font in BMFont
2. Load *.fnt file into Pixijs 4.8.2 project
3. Create new BitmapText object using fnt "face" attribute as font name
4. AddChild to stage

- `pixi.js` version: 4.8.2
- Browser: Chrome 69, Edge 42, Firefox 62
- Device: Surface Pro 3, MacBook Pro

**Comment by ivanpopelyshev** [comment]
So, who wants to dig inside https://github.com/pixijs/pixi.js/blob/dev/src/extras/BitmapText.js#L550 and make it look at resource resolution?

**Comment by uorbe001** [comment]
Why was this flagged as won't fix? This looks like a pretty serious problem?

**Comment by bigtimebuddy** [comment]
We indiscriminately marked lots of things as wont fix recently with the release of v5. We need an example (fiddle) to see if this is still an issue in v5.

**Comment by Outfire** [comment]
@bigtimebuddy Still not works in v5. Don't know how to do example with bitmap text on fiddle, only local.
![image](https://user-images.githubusercontent.com/10809624/59357802-2334f600-8d34-11e9-8a1d-1efe97df6d98.png)
![image](https://user-images.githubusercontent.com/10809624/59357804-2334f600-8d34-11e9-9ed5-d037c5daffa7.png)

**Comment by n8isjack** [comment]
@bigtimebuddy @ivanpopelyshev or anyone, can this not be addressed? Pixi crashes hard if I uses text because new strings are being written, changed, and updated at a very high rate. It doesn't even flinch using bitmaptext. it is wonderful... but will not work with resoltion != 1;

Here it is with PIXI.settings.RESOLUTION = 2
The dots look great... but text is garbled. 
<img width="351" alt="BadBitmapText" src="https://user-images.githubusercontent.com/1445259/78256778-3a58f600-74b6-11ea-8d35-8b0b893c295a.png">

Here it is with PIXI.settings.RESOLUTION = 1
Text works, but graphics are garbled.
<img width="392" alt="GoodBitmapText" src="https://user-images.githubusercontent.com/1445259/78256780-3af18c80-74b6-11ea-86f0-44ae0dcd8b7e.png">

**Comment by bigtimebuddy** [comment]
If someone wants to fix added a bounty.
