### ISSUE TITLE
no reason to throw Error when 're'load from loader.add

### ISSUE THREAD

**Issue by loohoo** [pixijs/pixi.js#5249]
I have read [this ](http://www.html5gamedevs.com/topic/19105-is-there-a-reason-to-throw-error-when-reload-from-loaderadd/) and [this](https://github.com/pixijs/pixi.js/issues/2043);

I thinks it is no any reason to throw Error, just call complete if resource exist or been loaded. let's take a look at one situation：

I have two separate module, they did't know each other and they are depend on same resource, for example : 
Module A,

 // here I don't know the loading state of resB, so I just load it
PIXI.loader.add(['resA', 'resB', 'resC']).load(function(){ 
    // do some things ....
})

Module B,
 // here I don't know the loading state of resB, so I just load it
PIXI.loader.add(['resX', 'resB', 'resY']).load(function(){  
    // do another things ....
})

programmer who using pixi.js should not care about the resource's loading state(not or been loaded). 
should I ?
should I check resB if was beed loaded on every time when use it?
or
reset loader ?

sorry for my poor english.

**Comment by loohoo** [comment]
does these resource would be re download from internet? or once complete the load, does PIXI would re parse xxx.json (atlas resource or animation resource)?

```
const images = ['resX', 'resB', 'resY'].filter(src => !PIXI.utils.TextureCache[src]);
PIXI.loader.add(images).load(function(){
 // do stuff
});
```
if 'resX' 'resB', 'resY' had all beed loaded, the function would not be call.

**Comment by bigtimebuddy** [comment]
I believe resources will be downloaded again and re-parsed even if they exist in the Loaders resources. @englercj can confirm that.

**Comment by englercj** [comment]
Hey @loohoo thanks for your post.

> I thinks it is no any reason to throw Error, just call complete if resource exist or been loaded.

I think there is a reason, and it is because adding an additional resource once loading has started doesn't make any sense from the point of view of the loader's state. If you add `resB` twice do we expose it twice in the results? How does that affect progress? Do we recalculate the progress data for everything when you add something like that? What behavior exists when you add things to a completed loader? Does it reset all state automatically?

There is a ton of ambiguity as to what the behavior should be if you allow additional resources to be added after starting the load process. If that is not allowed, then it is very clear to the user what the behavior will be. If there was no error, you would assume it behaved in some way (there are many choices) and that may not have been the choice I made in the library.

Additionally, the loader was made with the philosophy that it would be used to load some set of resources then either thrown away (or `.reset()`). It is *not* meant to live forever and act as your asset cache. It is meant to load resources from the network, and give them to you in a parsed way. It is then up to you to store them somewhere and do what you want.

> programmer who using pixi.js should not care about the resource's loading state(not or been loaded).

I completely disagree. It is completely up to the programmer to know what the state of their loaded resources are. The loader is a loader, not an asset cache. If you want to dedupe loads, and pull assets out of memory when they are already loaded then you should be using an asset cache that falls back to using a loader when assets don't exist. Especially if you have multiple different places in your application loading data. Something needs to sit between them and manage the coordination of which resources need to be loaded. That thing is not the loader, it just loads stuff.

For your situation I'd have a class whose job it was to take a set of resources a module needs and create & start a new loader for the ones that are not cached (or are not already in-flight). Once all those loaded I would return control to the requesting module with the loaded versions of what it needed.

> does these resource would be re download from internet? or once complete the load, does PIXI would re parse xxx.json (atlas resource or animation resource)?

Again, this is a loader, not an asset cache. It cannot know what you have loaded in your application, especially after you call `.reset()`. If you tell it to load a resource, then it will load the resource.

That being said, the browser will likely have the resource cached and there won't be any actual network communication. The loader will still make the XHR (or Image) request, and the resource will be parsed as if it had just been downloaded; even if the browser doesn't actually make any HTTP requests and instead just serves us the data from memory. We have no way of knowing that is what happens.

**Comment by bigtimebuddy** [comment]
No problem, thanks for asking and for using PixiJS.
