### ISSUE TITLE
stage.removeChild removing all the sprites after the one that I want to move

### ISSUE THREAD

**Issue by Ziv-Barber** [pixijs/pixi.js#525]
stage.removeChild ( sprite )
// All sprites after 'sprite' will also be removed.

**Comment by karaliunas** [comment]
Hey, I know its an old case, but I think one can reproduce this bug here: https://codepen.io/gka/pen/rpQdqO
1. add a few circles
2. delete some (select and press Del key). Works fine.
3. try to delete more circles and I get an error, which says that parent is null ("Cannot read property 'children' of null")

Am i doing something wrong? Thank you in advance!

**Comment by ivanpopelyshev** [comment]
Just a reminder that you use 5.0.0-alpha which is under development. However, the parts that you are using weren't changed in it, so even if you use 4.7.0, the same problem will persist.

Your case is too difficult to understand in two minutes, please make it easier or create proper issue and wait for someone who's ready to spend 10 minutes on it.

**Comment by karaliunas** [comment]
Thanks @ivanpopelyshev , I've tried my best to make it shorter: #4623
