### ISSUE TITLE
Chrome takes 100% GPU, machine gets sluggish - one Sprite on the stage

### ISSUE THREAD

**Issue by wkamir** [pixijs/pixi.js#5260]
This issue does only occur on my workplace desktop (strong development machine).

At home everything works fine but at work, Chrome takes 100% GPU and nothing really works.
It gets faster when I make the window smaller though.

Here a jsFiddle - really simple, just setup a stage and add a sprite:
https://jsfiddle.net/xepL01yc/6/

This is how it looks in Task Manager:
![gpu100](https://user-images.githubusercontent.com/13885303/49370949-1a64c700-f6f6-11e8-8898-b4704c47463a.PNG)

**Comment by englercj** [comment]
`GPU 1` seems interesting. Can you share some specs? Do you have 2 GPUs? What are they? What resolution are you running? Etc.

**Comment by wkamir** [comment]
I will share what I can when I get into the office in ~9h.
What is the best way to get you all the info you need (which settings masks to screenshot?)

**Comment by wkamir** [comment]
Ok so yes - I have two display adapters here it seems:
![twoadapters](https://user-images.githubusercontent.com/13885303/49419992-a4aa3b00-f789-11e8-9484-306aeda23bad.PNG)

My resolution is 1920x1200 and I have three monitors attached.

This is my system information:
![sysinfo](https://user-images.githubusercontent.com/13885303/49420223-b8a26c80-f78a-11e8-8271-13423992d235.PNG)
![displayinfo](https://user-images.githubusercontent.com/13885303/49420227-bc35f380-f78a-11e8-97f3-e145021f3072.PNG)

**Comment by photonstorm** [comment]
Wow, you don't often see NVS cards in the wild! I remember servicing these in the past, mostly used by banks / accountants to drive multi-screen displays. Given the incredibly low spec of them, and the 315 is especially poor even in the NVS range, it isn't surprising it can't handle your jsfiddle at that resolution.

"NVS 315 is a professional Graphics Card certified for professional applications. 
Its drivers are not optimized for gaming purposes but rather for the use of professional applications. Its core, the Fermi GF119-825-A1, is used on the GeForce 510 and therefore its performance is comparable but only slightly better, due to not benefiting from the gaming optimizations the GeForce 510 does.

The Quadro NVS 315 is now an old, low-end graphics cards and will struggle to run most modern games." (or, it appears, WebGL at a decent fillrate)

:(

**Comment by wkamir** [comment]
Thanks for the input.

Problem is... everything works fine in Firefox and Edge :(

**Comment by photonstorm** [comment]
Perhaps Chrome blacklists the GPU and the others don't? Would be worth finding out. For example, I know it prevents all NVIDIA Fermi cards from using GPU rasterization on Windows (which the NVS cards are). Have you tried forcing Pixi to use the Canvas renderer rather than WebGL?

**Comment by djmisterjon** [comment]
try some argument in your chrome shortcut.
"chromium-args": "
--ignore-gpu-blacklist 
--enable-gpu-rasterization 
--enable-gpu-memory-buffer-video-frames 
--enable-native-gpu-memory-buffers ",

**Comment by wkamir** [comment]
Ok thanks everyone - it seems my gfx card is really just not very capable. I will switch to "forceCanvas" for now since the little game I'm working on is mostly mouse-over sprite switching and very minor animations anyway.
