### ISSUE TITLE
Pixi.Text doesn't render on right font-weight (like bold or 800) in IE

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi.js#5292]
This might be the same issue as https://github.com/pixijs/pixi.js/issues/2202 but in Pixi 4.x.x ?
It seems like text weight is rendering fine on all mayor browsers except IE (also Ms Edge is rendering fine).
Looking in IE text doesn't have weight and looks like it's always the 'normal' variant.

### Expected Behavior
Font rendering with the same weight in IE as in other browsers

### Current Behavior
Font not rendering with the same weight in IE as in other browsers

### Possible Solution
Don't have a clue

### Steps to Reproduce
1) Display a pixi text with fontweight set to 'bold' or '800'
2) Look in Chrome, Firefox (both okay), then in IE11... (not okay.. always seem to display the regular variant)

### Environment
Windows 10
pixi 4.8.3
Desktop

**Comment by themoonrat** [comment]
Hi @Friksel 

When I attempt to replicate this, I see the text correctly being bold in IE: https://www.pixiplayground.com/#/edit/KxzkHC1vW7lBtP1cTORkN

Is there any way you could create an example where it does go wrong? Thanks

**Comment by Friksel** [comment]
I'm sorry, at the moment I can't find the time to create a demo. I thought of changing your demo, but it looks like pixiplayground can only do javascript (?). Looking at your code I see you're using a system font. I was using an external font instead which was taken from Google Fonts:
`<link href="https://fonts.googleapis.com/css?family=Mountains+of+Christmas" rel="stylesheet"> `

It's a regular font. It is being made and shown bold in canvas/pixi in all browswers I tested in, except for IE. Looks like somehow the make-bold routine isn't executed when used with pixi/canvas in IE.

Hope this helps

**Comment by themoonrat** [comment]
Ah a custom font. This is an IE issue.

So, for Chrome and Firefox and other browsers, it'll bold the font if you just select 'Mountains+of+Christmas'. But for IE, you need to specifically state which font weights you require.

Here's a new playground: https://www.pixiplayground.com/#/edit/kw9k7WKb5vJoe86S9PV_5

In that playground, I've used `Mountains+of+Christmas:400,700` instead of just `Mountains+of+Christmas`, and this gets the correctly weighted font showing in IE. I've not used that in a different custom font (Arvo) and you see that it does not bold in IE, which is what you're seeing. 

So yeah, specify precisely the font weights you require, and bosh!

On https://fonts.google.com/specimen/Mountains+of+Christmas - when you click "Select this font" then click the black bar to get the url, go to customize and you can tick / untick bold. Go back to the first tab and you'll see the url you require has been updated to what I've used in that playground

**Comment by Friksel** [comment]
Thanks for your reaction @themoonrat . 
The project I'm using this font in is newly build in Pixi, but the original was build in EaselJS. In EaselJS the font was working perfectly in IE too with the exact same font and font-loader code. The only major difference between the EaselJS and Pixi projects are that EaselJs is working on 2D canvas, while Pixi uses WebGL here. 

So although I'm sure you're hitting the right spot here and I assume you're being right in that this is an IE issue, I don't really understand why EaselJs didn't have this problem. Is this IE issue perhaps only there in WebGL? Than it makes sense.

Anyway, thanks for your great feedback and help here and I'm gonna try your suggestions to see if it works in IE when loading in the bold-font itself instead of letting the browser make it bold.
