### ISSUE TITLE
beginTextureFill not a function

### ISSUE THREAD

**Issue by verybigelephants** [pixijs/pixi.js#5332]
i've been trying to draw texture on graphics element and use this function http://pixijs.download/dev/docs/PIXI.Graphics.html#beginTextureFill but it seems as if the library didn't even have it implemented 

```
	...
	let gfx_container = app.stage.scene = app.stage.addChild(new PIXI.Graphics());
	
	gfx_container.beginTextureFill(texture);
	gfx_container.drawRect((x * tile_size), (y * tile_size), tile_size, tile_size);
	gfx_container.endFill();
	...
```

`gfx_container.beginTextureFill is not a function`

**Comment by bigtimebuddy** [comment]
The version of PixiJS that you're using matters. We haven't released a version of v5 yet (currently the **dev** branch). That doc link you referenced is the latest **dev**. To see the latest v4 release (most stable) go here: http://pixijs.download/v4.8.4/docs/PIXI.Graphics.html

If you want to play around with beginTextureFill, you can use this build: http://pixijs.download/dev/pixi.min.js

Hope that helps clarify.

**Comment by verybigelephants** [comment]
thank you!

or perhaps you could recommend some other way of drawing a lot of simple graphic elements into one container?

i want to build a part of my scene tile-by-tile and there will be **a lot** of them. they are static drawn tiles that make up a picture, that will be updated once in a while. if i use classic sprites - there's a lot of them and it really heats the whole machine up

**Comment by bigtimebuddy** [comment]
From your description it's not clear to me what you're trying to achieve. In PixiJS there are multiple ways to draw the same thing, it depends largely of the details and what you're trying to achieve. 

Also, I'd recommend http://www.html5gamedevs.com/forum/15-pixijs/ if you're looking for advice or help on a particular approach.

I'm going to close this issue, because your initial question was answered. Feel free to open another issue if you're looking for something specific related to Graphics drawing.
