### ISSUE TITLE
Lines drawn with nativeLines are always 1px width

### ISSUE THREAD

**Issue by LeonLenclos** [pixijs/pixi.js#5352]
### Expected Behavior

Draw a nativeline with specific width.

### Current Behavior

The line width is always 1px.

### Steps to Reproduce

    let l = new PIXI.Graphics(true); // nativeLines option set to true 
    l.lineStyle(10, 0xFF0000); // lineWidth set to 10
    l.moveTo(0, 0);
    l.lineTo(100, 100);

This display a 1px width red line

### Environment

- **`pixi.js` version**:  4.5.5
- **Browser & Version**: Firefox 61
- **OS & Version**: Debian Gnome

**Comment by ivanpopelyshev** [comment]
That's expected behaviour, because native line directly calls corresponding webgl functions.

**Comment by LeonLenclos** [comment]
Ok... But the colorLine option works.
Is there a way to set a native line width ?

**Comment by ivanpopelyshev** [comment]
If you want your line size to be independent from transform scale, im sorry, pixi cant do that. You have to change width accordingly to the scale and re-fill all your graphics because Pixi can't just re-triangulate all things on fly.

Though, you can try: https://github.com/pixijs/pixi.js/tree/v4.x/src/core/graphics , all `buildXXX` functions are dedicated to transforming the stuff user wants to actual coordinates.

I know that it was possible in flash to make transform-independent strokes, but its messing with so many  functions that we have to recode all Graphics to support that. Even canvas2d API does not have that :(

**Comment by LeonLenclos** [comment]
Ok.
I was using native line because of some ugly artefacts on triangle strip (for a kind of painting app). But I did not understood limits of this feature. Too bad !
Thank you for your response, I close the issue.
