### ISSUE TITLE
Event interactive Right and Left click simultaneous

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#5384]
### Expected Behavior
when hold click left , the right click are emit.

### Current Behavior
when hold click left , the right click are not emit.

### Steps to Reproduce
1: Try hold click Left.
2: keep holding
3: and try also use Right click for cancel.
But if you try holding right and left click and release simultaneous it seem work ! ?

example
https://pixiplayground.com/#/edit/msMqGwsa9XKkWSGgTG760

this issue can also maybe related ?
https://github.com/pixijs/pixi.js/issues/4048

### Environment
- **`pixi.js` version**: 4.8.2
- **Browser & Version**: chromium: "70.0.3538.102"  nw: "0.34.3"
- **OS & Version**: _e.g. win10

**Comment by Dairnon** [comment]
https://github.com/pixijs/pixi.js/issues/4863#issuecomment-414044411

This is talked about here, just use mousedown and mouseup

Or if you need to use pointer, use pointermove as well to double check

**Comment by djmisterjon** [comment]
> [#4863 (comment)](https://github.com/pixijs/pixi.js/issues/4863#issuecomment-414044411)
> 
> This is talked about here, just use mousedown and mouseup
> 
> Or if you need to use pointer, use pointermove as well to double check

hum, i am not succeed to do what your suggest.
I replace the code in demo by `mousedown and mouseup` and i get the same behavior.
For now the only alternative i found it to add a new document listener between those interaction to check and control the double Right and Left click simultaneous.

```javascript

        document.addEventListener('mouseup',(event)=>{
            // disable fastmode si hold click left et click right
            if(event.button===2 && this.FASTMODES.renderable){
                this.disableFastModes(false);
            };
        });

    pDW_tile(e){
        const ee = e.currentTarget;
        const callBack = () => {
            ee.interactiveChildren = false; // disable thumbs interactions
            this.activeFastModes(ee);
        }
        this.startMouseHold(ee,callBack);
    };
    
    pUP_tile(e){
        if(this.FASTMODES.renderable){ this.disableFastModes(true) };
        if(this.mouseHold){return this.startMouseHold(false) };
        this.startMouseHold(false);
        const ee = e.currentTarget;
        this.remove_toMouse(ee); // detach from mouse
        // Right click => cancel delete current attach
        if(e.data.button===2){
            $stage.scene.removeChild(ee);
        };
        // Left click <= apply
        if(e.data.button===0){
            this.add_toMouse( this.add_toMap(ee) ); // attache to mouse
        };
    };

```

**Comment by themoonrat** [comment]
Hi @djmisterjon !

So I finally got to have a look at this. And once again, it's because the pointer event spec sucks, and doesn't send an extra 'down' if multiple buttons are pressed. I know you're looking at 'mousedown', but in Pixi, if the pointer event is available, we'll just re-use that rather than listening to pointerdown, mousedown AND touchstart.

A solution to that can be found: https://pixiplayground.com/#/edit/xtIWbq1wXXcMK5s02~JHG
Near the top, I've done
```
const interactionDOMElement = app.renderer.plugins.interaction.interactionDOMElement;
app.renderer.plugins.interaction.removeEvents();
app.renderer.plugins.interaction.supportsPointerEvents = false;
app.renderer.plugins.interaction.setTargetElement(interactionDOMElement);
```
So we force against using pointer events altogether, which means the mouse listener events will get sent on simultaneous presses.

I don't know what to do about this for v5. I think I'm leaning towards making using native pointer events optional. Then users can weigh the advantages / disadvantages themselves. 
- Advantages of using native pointer events: you get accurate extra data as defined in https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent
- Disadvantages of using native pointer events: you lose some control over simultaneous left & right clicks

**Comment by andrewstart** [comment]
I doubt it does, but is a pointermove event sent on a second button press
with and updated buttons property?

**Comment by themoonrat** [comment]
I've actually gone for a solution for v5 that checks the differences in `buttons` property from one event to the next: https://github.com/pixijs/pixi.js/pull/5605
