### ISSUE TITLE
If `Graphic.generateTexture` is moved to the renderer, how can a library use it?

### ISSUE THREAD

**Issue by carlsmith** [pixijs/pixi.js#5394]
I have a function that creates a rectangular graphic, converts it to a texture and uses that to create a sprite. The function currently works by calling `generateTexture` on the graphic, but that creates a deprecation warning. If the function uses `app.renderer.generateTexture`, it needs access to `app`, obviously, but that's a runtime object.

If I move the function to another module, it will not be able to reference `app` as a global. I appreciate I can pass `app` to it as an argument, but it *seems* like a library *should* be able to convert a graphic to a texture without a renderer??

Thanks for PIXI by the way. I'm new to WebGL, but am having tons of fun with PIXI, and everything is running super smooth.

**Comment by englercj** [comment]
In v3 we used a temporary canvas to draw the graphics and then used that as a texture, which is why you didn't need a renderer. Is that what you are referring to?

AFAIK in v4 and v5 you need a renderer, because we use it to draw the graphics to a texture.

**Comment by ivanpopelyshev** [comment]
Yes, that's a problem architecture because we dont have global renderer and there can be multiple renderers, we can't do `drawBitmap` like in flash. There's `graphics.generateCanvasTexture()` https://pixijs.download/dev/docs/PIXI.Graphics.html#generateCanvasTexture , but you have to understand that it will use CPU and upload that texture to GPU later.

**Comment by ivanpopelyshev** [comment]
Well, technically, the best solution is to make an element that will be liazily calculated before next tick by something if a special flag is set. For example, pixi-display plugin has `layer.useRenderTexture` and `layer.getRenderTexture()` operation that doesn't require renderer parameter, it just works due to 1. several fields inside my custom Layer class 2. lazy evaluation inside `renderWebGL()` method 

Suppose you add a plugin to Application itself that takes care of managing temporary textures based on your data inside your stage. Stage elements dont need to know about renderer, but when the time comes all renderer-specific stuff will be evaluated.

**Comment by carlsmith** [comment]
Thanks for getting back to me, and sorry for not being more responsive. I'm new to the library and need to take some time to properly understand your answers, but again, thank you.

**Comment by carlsmith** [comment]
I'm going to close this issue. It's quiet, and honestly, I don't understand your response well enough to respond intelligently at this stage.

Best.

**Comment by carlsmith** [comment]
I'm going to close this issue. It's quiet, and honestly, I don't understand your response well enough to respond intelligently at this stage.

Best.
