### ISSUE TITLE
Private variables and functions 5.0.0-rc

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi.js#5412]
Please make all private variables and functions protected. Typescript definition file does not contain private variables and functions. Sometimes it is necessary to work with these or to overwrite them.

**Comment by rkrasky** [comment]
Please make all private variables and functions protected. Typescript definition files does not contain private variables and functions. Sometimes it is necessary to work with these variables or to overwrite functions.

**Comment by ivanpopelyshev** [comment]
We have `protected` for that. Which private fields you want to access?

**Comment by bigtimebuddy** [comment]
We'd rather use a scalpel here, not a chainsaw. 

Like @ivanpopelyshev said, if you need things exposed, please identify them or make a pull request. 

We do not want to expose all the private variables and methods in our typings because that would be an insane amount of support required to maintain all that extra APIs, so we want to keep the API surface as small as possible. There maybe some legitimate reasons for extending or overriding stuff, but on the whole we don't want to encourage this.

One of the downsides of v4 is that 3rd party plugin creators were doing lots of prototype manipulation, mixins and/or overriding private things. It's important that we don't repeat this with v5, so we want to create supported paths for plugins.
