### ISSUE TITLE
how to craete sprite for node

### ISSUE THREAD

**Issue by yyman001** [pixijs/pixi.js#5454]
- **`pixi.js` version**: _e.g. 4.8.5_

i want to run pixi on NODE, i use `pixi-shim` for run success, but i want to create sprite for the images,
i test load network png is fail
```
const path = require('path')
let sprite_file = 'https://dev.resdiy.com/static/img/ui_hover.3862b29.png'

console.log('加载网络图片测试:', 'https://dev.resdiy.com/static/img/ui_hover.3862b29.png')

try {
  let loader = new PIXI.loaders.Loader();
  // add a resource to load
  loader.add('mySprite', sprite_file);
  loader.on('progress', function (target) {
    console.log('progress', target.progress)
  })

  loader.on('error', (error) =>{
    console.log('loader-error:', error)
  })

  loader.on('complete', (loader) => {
    console.warn('loader.resources:', loader.resources)
    loader.reset()
    loader.removeAllListeners()

  }, this)
  // start the loader and pass an anonymous function to be called back once the loading is complete
  loader.load()

} catch (error) {
  console.error(error)
}
```
how can i load images for `local` or `network` to create sprite in NODE,
i create `canvas` element in NODE is `{}`
    Thanks!

**Comment by bigtimebuddy** [comment]
Likely `Loader` will not work because it uses XMLHttpRequest to load resources. You should consider loading the resources through some other method or library (e.g., https://www.npmjs.com/package/image-data-uri).

Either way, you should file an issue with https://github.com/Prozi/pixi-shim since PixiJS does not support rendering in node.js-only environments.
