### ISSUE TITLE
Can you support WeChat?

### ISSUE THREAD

**Issue by redw** [pixijs/pixi.js#5459]
WeChat is one of the most popular h5 game platforms in China, but pixi.js v5 does not support WeChat games, new Function cannot be successfully executed.

**Comment by MyselfeCodeandIdea** [comment]
Yes, we use the version before pixi. js v5, WeChat small game platform can still be compatible with Pixi after adaptation.

**Comment by MyselfeCodeandIdea** [comment]
Maybe you don't know micro letter little game, but developers in China it seems this is an important platform, Facebook, the same look and abroad integrated chat, information, payment (and function is the same as the PayPal, and QR code), applications and games, yes it is amazing, so can pixijs compatible with micro letter little game developers are particularly important for China, because pixijs really quickly.

**Comment by ivanpopelyshev** [comment]
Thank you for the report!

So, basically, we have to make a fallback to `generateUniformsSync` so it returns a static function. It will slow things down but it'll work.

**Comment by redw** [comment]
> Thank you for the report!
> 
> So, basically, we have to make a fallback to `generateUniformsSync` so it returns a static function. It will slow things down but it'll work.

Can you help me? If it is a WeChat version, we will use the function mode.
If it is another version, it is new Function(...).
I tried to modify it, but it is a bit problematic.

**Comment by ivanpopelyshev** [comment]
Test this build: https://pixijs.download/dev-new-function-fallback/pixi.js
