### ISSUE TITLE
RenderTexture not rendering when sprite with children has parent

### ISSUE THREAD

**Issue by replaysMike** [pixijs/pixi.js#5489]
I've run into a problem with Rendering to texture that I can't find a solution for.

I'm rendering a sprite to a texture, and converting that to an image to display on a different canvas.

```
const parent = this.app.stage.getChildByName('parentContainer');
const sprite = new PIXI.Sprite(texture1);
sprite.addChild(...);
sprite.addChild(...);
parent.addChild(sprite);
const renderTexture = PIXI.RenderTexture.create(sprite.width, sprite.height);
app.renderer.render(sprite, renderTexture);
```

in the above case, nothing renders. If I tell it to skipUpdateTransform=true then I see "something" but all the children are rendered at position 0,0.
`app.renderer.render(sprite, renderTexture, false, null, true);`

The weirdest part is, if I _don't add the sprite to it's parent_ it renders. It's hard for me to isolate what's going on here.

### Environment

pixi.js 4.8.1
Browser: Chrome
OS: Windows 10

**Comment by Dairnon** [comment]
If your spirte children are in an area larger then sprite width and height, then you need to make sure the renderTexture renders that size of area. 

Try setting the renderTexture area larger and see if your sprite children render.

**Comment by replaysMike** [comment]
The children are within the dimensions of the parent sprite. I tried setting the renderTexture to the stage dimensions, but it didn't make any difference.

**Comment by replaysMike** [comment]
I just noticed another oddity - when the sprite being copied has an anchor of 0.5 (centered) the texture only copies the bottom right corner. I haven't figured out how to get around that yet either.

**Comment by bigtimebuddy** [comment]
In general, adding children to Sprite is technically possible but a bit of an anti pattern in Pixi. It’s difficult to control ordering and there no real benefit performance wise over using a vanilla Container. Unless you are using something advanced with Sprite, would strongly recommend you don’t add children too it because you’ll run into issues like this when trying to cacheAsBiitmap, RenderTexture, filters etc.

**Comment by ivanpopelyshev** [comment]
Adding childs to Sprite is fine.

I consider passing elements with existijng parent to `generateTexture`, and `render` as an anti-pattern because there are many bugs with temporary changing the parent. Also `width` `height` on element with childs is bad unless you understand what is going on under the rug, it changes transforms too , and there might be bugs with caching transforms.

The best way is to use `getBounds` and manual reassignment of parent, that way you are in control of those operations and buggy parts of pixi internals cant affect it.

**Comment by replaysMike** [comment]
yea I'm trying to accomplish something advanced here. I'm attempting to copy a particular pixi display object (a sprite with children) and paste it onto a separate canvas. That canvas is transparently overlaid on top of pixi's canvas so that I can place particle effects behind it.  I'm using the Proton particle system and its pixi renderer doesn't support alpha blending so I'm having to resort to this to get a good look.

Yup I also tried cacheAsBitmap and didn't have a lot of luck with that either. Not quite sure how to achieve this, I may have to drop the entire feature which would be unfortunate.

**Comment by replaysMike** [comment]
I should note I kinda had partial success when I rendered the texture out, and cached that texture before the object was added to the stage. It was still a little wonky though, I may have to try building and rendering it entirely offscreen and then using that to render the texture. There's some downloading of avatar images outside of the preloader that makes some of this hard to structure.

**Comment by ivanpopelyshev** [comment]
```
PIXI.RenderTexture.create(sprite.width, sprite.height, false, null, true)
```
those are not renderTexture poarams, that's `render` method params.

**Comment by replaysMike** [comment]
> ```
> PIXI.RenderTexture.create(sprite.width, sprite.height, false, null, true)
> ```
> those are not renderTexture params, that's `render` method params.

My bad, I corrected the original it was a copy/paste error.
