### ISSUE TITLE
PIXI.Graphics.beginTextureFill() Draws BaseTexture, not Texture?

### ISSUE THREAD

**Issue by M00nR4bb1t** [pixijs/pixi.js#5503]
### Expected Behavior
I don't know if I'm just stupid, but I expected that PIXI.Graphics.beginTextureFill(texture) would begin a fill with the given texture.
### Current Behavior
PIXI.Graphics.beginTextureFill(texture) begins a fill with the given texture's `baseTexture`.
### Possible Solution
I have no idea.
### Steps to Reproduce
Load BaseTexture. Create Texture (part of BaseTexture). PIXI.Graphics.beginTextureFill(texture).
### Environment

- **`pixi.js` version**: 5.0.0-rc.2
- **Browser & Version**: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
- **OS & Version**: macOS Mojave
- **Running Example**: https://jsfiddle.net/gazenx30/8/

**Comment by ivanpopelyshev** [comment]
The problem is that we'll need tiling shader for that and its extremely slow (see TilingSprite) and not batchable.

So, BaseTexture with wrapMode = REPEAT is the only way to use it in fills. Remember `context.createPattern` thingy? Same here, it has to be special object.

Of course for compatibility we might make that shader with a warning to console.

**Comment by ivanpopelyshev** [comment]
Also there will be MANY problems with tiling in Graphics, same as in TilingSprite. Of course we can use them for graphics too, but I remember #3048 and how many fixes I made afterwards and I'm afraid of doing the same thing again. 

Also that way tiling fills will break the batching and I dont know whether to switch shader for certain graphics elements or only for this fill. There are just too many variants on how to do that.

If you can answer on them, I'll do it fast :)

**Comment by M00nR4bb1t** [comment]
If so, what is the most efficient way to draw multiple `Texture`s with the same `BaseTexture` (for now)? I am trying to make a tilemap, and I can imagine using individual `Sprite`s would be very slow with hundreds or thousands of tiles. I guess I might have to switch to PIXI v4 and use pixi-tilemap.

**Comment by M00nR4bb1t** [comment]
Is having each tile as separate sprites but rendering them to `RenderTexture` only when needed plausible in terms of performance? Reading [this thread](http://www.html5gamedevs.com/topic/20271-redraw-only-when-needed/), the main advantage of pixi-tilemap seems to be a significant reduction in draw calls. Can a similar effect (albeit not as efficient) be achieved with `Sprite`s and a `RenderTexture`?

**Comment by M00nR4bb1t** [comment]
[Here](https://jsfiddle.net/nezdq8tu/) is a quick demonstration of what I'm talking about. Would something like this be plausible with larger map sizes?

**Comment by ivanpopelyshev** [comment]
Oh, that's different. if you want a tilemap i know how to do it with graphics and textures, it just needs some adjustment.

**Comment by ivanpopelyshev** [comment]
Actually, now that i think about it... we can make auto-detect for those textures, which period to show :) Even if we cant wrap-repeat them, we can detect the offset!

**Comment by M00nR4bb1t** [comment]
> I'll make a demo based on yours today or tomorrow

That'd be great, thanks :)

**Comment by ivanpopelyshev** [comment]
OK, im working on pixi-tilemap v5 but it will take day or two.

**Comment by mrspeaker** [comment]
> Graphics and beginTextureFill, its just you need to generate matrices for every tile type and give it to beginTextureFill

I'm interested in doing a simple TileMap implementation in my game and noticed it was slow just using a bunch of Sprites. I tried to implement the suggestion above - but I could not figure it out. It seems that beginTextureFill will "flood fill" the texture as big as the drawRect area. If I make that area 32x32 (size of one tile in the tilesheet) then if I draw a grid, it will be as if I just drew the image (because the offset is fixed). Do I need to calculate and subtract the current background offset, then add the offset of the image to the matrix for every tile? 

Also I noticed that in Graphics.js that beginTextureFill does `matrix.clone(); matrix.invert();` every call. That seems like it would be very slow if I call beginTextureFill once per tile - or have I got the idea wrong? Thanks!
