### ISSUE TITLE
pv5 beginHole & endHole not (always) working

### ISSUE THREAD

**Issue by JohnKarel** [pixijs/pixi.js#5585]
1. Drawing 2 rects and then adding a hole, doesn't work
2. Drawing 1 rect and then adding a hole that doesn't fit in the borders of the rect, doesn't work

### Expected Behavior
1. Drawing 2 rects and then adding a hole should make a hole in the pixi graphics
2. Drawing 1 rect and then adding a hole that doesn't fit in the borders of the rect should make a hole in the pixi graphics

### Current Behavior
1. It doesn't make a hole
2. It doesn't make a hole

- **`pixi.js` version**: _e.g. 5.0rc3
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: https://pixiplayground.com/#/edit/eavRukjDT14LsuNRCrq4b

**Comment by ivanpopelyshev** [comment]
We use https://github.com/mapbox/earcut to handle triangulation and holes.

### Preambula

I'm working on porting SWF format to pixi and I had to make many adjustments to v5 graphics in my private repo, of course it was very difficult to count all hole cases that Flash handles.

I know many cases that dont work in `PIXI.Graphics` but can be handled by Flash or canvas2d context (skia and other browser backends).

For example, I know that if you make 2 drawRects hole will be applied only to second one, but you can use moveTo/lineTo instead and cut the hole from first rect.

### Your case

However, stuff that you want doesn't work even in canvas2d context:

https://pixiplayground.com/#/edit/b~N7WpFXIfCrFJL4GiBIL

№1 is just wrong and i dont know which rule should produce the result you want

№2 two parts appear because of `even-odd` rule, However `nonzero` shows the same.

### Summary

Welcome to 2d vector graphics. Many things work the way authors made them, its just how it is. Not everything is a bug.

However there are many bugs, make sure to report strange things if you see them! You never know when you dig out real treasure.

**Comment by jdelrue** [comment]
Ivan, is there any way to erase pixels in a particular shape from a texture in pixi? It's something we miss in pixi from the moment we started using it. Our hope was that holes in v5 would fix it but apparently not.

**Comment by ivanpopelyshev** [comment]
There's `ERASE` blendMode aka `DST_OUT`, http://pixijs.download/fix/color-utils-docs/docs/PIXI.html#.BLEND_MODES

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/state/utils/mapWebGLBlendModesToPixi.js#L47

You can easily backport it to v4, there's link to old thread in wiki: https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#no-custom-webgl-blend-modes

**Comment by jdelrue** [comment]
Thanks works!
