### ISSUE TITLE
Invalid metrics for some tall chars when zooming in the browser. For example "Å"

### ISSUE THREAD

**Issue by iv-menshenin** [pixijs/pixi.js#5594]
The fact is that Danish fonts are drawn with a slight deviation in the metrics.  
Due to deviations at some scale values, circles above large letters become truncated. 

Code example:  
```js
  var stage = new PIXI.Container(),
      renderer = PIXI.autoDetectRenderer(640, 480);
  document.body.appendChild(renderer.view);
  var t = new PIXI.Text("Letter \"|ÅÉM\" is cut of", {
    fontFamily: "Roboto",
    fontSize: "20px"
  });
  stage.addChild(t);
  renderer.render(stage);
```

This is the solution of the problem: 
```js
PIXI.TextMetrics.BASELINE_SYMBOL = "|Åq";
```
And then:
![image](https://user-images.githubusercontent.com/38577106/56383515-a6e5d100-6222-11e9-926a-a6836c6841df.png)

- **`pixi.js` version**: 4.8.2
- **Browser & Version**: Chrome 73.0.3683.86
- **OS & Version**:  Ubuntu 18.04

**Comment by themoonrat** [comment]
Unsure of how making this change would effect v4, but there's potential for making this the default for v5?
You've found the right setting for your usage on v4 tho, that's why it's exposed like that :)

**Comment by iv-menshenin** [comment]
How it will affect v4, we will soon find out. But I think it would be right to do this in v5 as the default setting.

**Comment by themoonrat** [comment]
So actually after having a look, I don't think it'd negatively effect any visuals, but I'm not quite sure your approach is quite correct.
 
You see, the `measureFont` function tries to work out the width and height of a fonts by using `METRICS_STRING` and `BASELINE_SYMBOL`, drawing them to a canvas, and reading pixels

```
const metricsString = TextMetrics.METRICS_STRING + TextMetrics.BASELINE_SYMBOL;
const width = Math.ceil(context.measureText(metricsString).width);
let baseline = Math.ceil(context.measureText(TextMetrics.BASELINE_SYMBOL).width);
const height = 2 * baseline;

baseline = baseline * TextMetrics.BASELINE_MULTIPLIER | 0;

canvas.width = width;
canvas.height = height;
```

The canvas api has something to measure width, but not height. So to get an idea of height, we take the 'M' character, since that's often wide, and multiply that by 2 and say "yeah, that's probably tall enough". We then draw that character (with others) to a canvas, scan the pixels and see how tall it actually is.

So there are 2 things your change effects.
1. Because there are lots of characters, its adding up the width of all of those, and making a canvas taller to start with. Plus side, taller characters can fit in, downsite, scanning lots of empty pixels now.
2. The Å character could be actually taller than anything in METRICS_STRING or BASELINE_SYMBOL, so when it's scanning pixel data, it might stop earlier.

I'll use your example to work out what the optimum solution is this weekend :)

**Comment by bigtimebuddy** [comment]
Merged in v5

**Comment by iv-menshenin** [comment]
After that changes on our codebase, we have a side-effect: we have offset of baseline for regular font versus bold font. did you check it?

**Comment by iv-menshenin** [comment]
there is another way to fix it:
in `pixi.js/packages/text/src/TextMetrics.js`

**al line 544:**
```js
canvas.height = height + 1;
```
instead of
```js
canvas.height = height;
```
and then, **at 584 line:**
```js
properties.ascent = baseline - i + 1;
```
instead of
```js
properties.ascent = baseline - i;
```
it just adds 1px to the top of the canvas. this method has no side-effects
have a look please
@bigtimebuddy @themoonrat
