### ISSUE TITLE
Container bounce while Pixi's extracting data

### ISSUE THREAD

**Issue by martinboksa** [pixijs/pixi.js#5627]
### Expected Behavior
While PIXI's extracting container from canvas so then everything working nice and great without bouncing.

### Current Behavior
While PIXI extracting container from canvas so then PIXI moves container to the left top corner for a while.

My Code:
`const imageResult = app.renderer.extract.canvas(
     contentContainer
    )`

Video:
https://vimeo.com/333293612

At video I am trying to create small image of Stark sprite.

### Possible Solution
- Maybe create hidden copy of canvas and extract data there ?
- Or any idea how to fix it ?

### Environment

- **`pixi.js` version**:  4.8.7 
- **Browser & Version**: Safari
- **OS & Version**: iPhone (iOs)

**Comment by ivanpopelyshev** [comment]
Pixi renders container in his bounds. You have to call 'getBounds' and move container according to it. 

You can look into how 'renderer.generateTexture' works to get that code. 

there are many problems with extract and generateTexture, and ive tried to fix them all before but my solution was too heavy, PR was rejected.

Please use workarounds i've mentioned. Also please be wary of premultipliedAlpha , you have to postDivide it if you need transparent object . Postdivide can be found in closed PRs, cant post a link because im on mobile. Also watch out for current parent of container, it might cause problems.

I'll make attempt on fixing everything in extract this summer, maybe ill name it 'Bitmap'.

**Comment by martinboksa** [comment]
Thanks. So i was trying find out how code works. But I need to get deeper knowledge, maybe your PR would help me or explanation of idea 'use getBounds() and move container'
Please, could you send it here ? It should help next guys as well.
