### ISSUE TITLE
Issue with BlendMode Additive

### ISSUE THREAD

**Issue by SergiyTopalov** [pixijs/pixi.js#5673]
I`ve got an issue on my project with BlendMode Additive. Here is an example: https://jsfiddle.net/oq2jcyga/46/
From my perspective, it breaks somehow and I have no idea why it happens.

**Comment by ivanpopelyshev** [comment]
it looks like we have two issues:
 
1. something wrong with graphics bounds, because generated texture shouldn't have (0,0) in it, it should be exactly size of circles, circle should have bounds with same left-top corner

2. ADD alpha-channel problem. something is wrong there. Source code has the correct coefficients: https://github.com/pixijs/pixi.js/blob/v4.x/src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js#L18 , but maybe generateTexture() did something wrong?

**Comment by ivanpopelyshev** [comment]
When I run it in v5 it looks different. Interesting.

**Comment by ivanpopelyshev** [comment]
ok, about ADD , i think its actually legit , our coefficients are based on flash, and I'll test it again, but for now I just say that:

If background if transparent, even transparent parts of of sprite will affect the output.

If you want different ADD, add it manually, here's the workaround: https://github.com/pixijs/pixi.js/issues/5446#issuecomment-464366174 its not plain JS but i think you can convert it ;)

**Comment by ivanpopelyshev** [comment]
OK, I understood why circles have the same center. You've used Sprite, it has no texture by default but still it affects its bounds. That's why generateTexture() produces big texture.

Here we are: https://www.pixiplayground.com/#/edit/9aIDacLYssdzq2lqGrlAB
