### ISSUE TITLE
QUESTION: Alternatives for anti aliasing effect using WebGL and shapes

### ISSUE THREAD

**Issue by stagr** [pixijs/pixi.js#5714]
We are struggeling getting good visual results with PIXI.Graphics using the WebGL renderer and we are writing for some guidance/tips/ideas on how we can improve the visual result. 

Our use case requires

- visually appealing edges of shapes and lines
- beeing able to render the shapes and lines on screen 
- beeing able to extract the resulting stage of shapes and lines to an image (with visual quality maintained)
- animating the scale, position and rotation of individual shapes and lines

Using CanvasRenderer the graphics are antialiased by default with good enough visual result. With the WebGL Renderer, however, the resulting graphics have jagged edges in some cases. 

After reading up on the issue I believe I understand that there are quite some aspects to consider regarding anti-alias and WebGL rendering in PIXI:

- anti-aliasing can be enabled on render level at a cost (the antialias option passed to the Renderer constructor)
- the PIXI WebGL implementation of Graphics uses the stencil buffer which does not support anti-aliasing
- applying filters to a Graphics object cancels the render level anti-alias since secondary frame buffers do not support anti-aliasing
- extracting a display object or the whole stage using PIXI.extract does not apply the render level anti-alias
- there are several alternative "work-arounds" for getting "smoother" edges without the renderer level anti-alias
    - FXAA filter on renderer level or on individual display objects
    - Blur filter on individual display objects
    - Rendering Graphics objects using canvas renderer and using it as a texture
    - Rendering Graphics objects at a higher resolution and downscaling it using linear scaling
    - Rendering the whole stage at a higher resolution and downscaling it using linear scaling

I made an example in PIXI Playground (https://www.pixiplayground.com/#/edit/WMr27ZIwI3RWRotaap00L) where I have experimented with different ways of drawing the graphics, different ways of extracting a frame from the rendered view and also tested different settings for forceCanvas, antialias and forceFXAA. Hopefully these examples can serve as help for others and also serve as basis for further discussion.

Based on the experiments and the fact that we also require anti-alias on graphics that are animated (scale and rotation) we have come to the conclusion that we will pay the performance price of using render level antialias, not allow the application of filters on Graphics objects and use HTMLCanvasElement.toBlob() to extract a particular frame from the animation.

All that said, we would appreciate some input from someone with more experience in WebGL and PIXI to give us a hint on if any of the statements above are incorrect, if we are on the right track with our conclusions or if we have missed or misjudged some alternative altogether.

We are also very curious on if there are any plans of adapting the implementation of PIXI.Graphics to WebGL2 where I understand it could be made to support antialias on Graphics display object level and on render level together with filters. Or if there are any other plans of improving the visual results of using PIXI Graphics with the WebGL renderer?

### Environment

- **`pixi.js` version**: 4.8.7 and 5.0.3
- **Browser & Version**: Chrome 74.0.3729.157
- **OS & Version**: Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/WMr27ZIwI3RWRotaap00L

**Comment by ivanpopelyshev** [comment]
Need MSAAx4 ,.its available in weblgl2 but pixiv5 does not support multisample framebuffers yet. That way we'll have the same quality as Flash.

For downscaled graphics to look the best need a least x3 (means x9 area) , but then it requires advanced downscaling because just linear filtering works only with scale less than 2.

Bear in mind that canvas2d antialias is worse than msaa x4 because its alplied PER PATH, it has transparent exges between two touching paths! Even svg in browser is bad, look at google doodle for US veterans day. Somehow nvidia pascal videos show different result on svg, something about directx enabling msaa automatically. Its fun that we need Pascal to get quality that already existed in Flash for many years.

My personal choice is using 2d for non animated shapes to generate mips and changing sprite texture to certain mip level based on scale log2. If my algo detects that shape is basic enough, it uses plain pixi graphics. There are also special cases for holes gradients and masks. Cant explain it in a few words, im on vacation, but my take on vector graphics with full support of SWF files will be published in autumn.

**Comment by ivanpopelyshev** [comment]
I can make a guess that you are making something serious. In this case its good if you contact me in t.me/hackerham and we can see whether i can give you some of my experimental code that wasnt published yet.

**Comment by stagr** [comment]
Thanks for your response @ivanpopelyshev, it is very apreciated.

I interpret it as that as long as PIXI does not support MSAAx4 it is **hard** to get better results (visual and performance) than our suggested solution.

Looking forward to seeing MSAAx4 in PIXI in the future and also to your work on vector graphics. The "full support of SWF files" (including animation?) is a work without MSAAx4 or is it something that requires MSAAx4? Please let me know how I can find that work when it is finished!

**Comment by ivanpopelyshev** [comment]
hmm, rust
https://nical.github.io/posts/a-look-at-pathfinder.html

**Comment by stagr** [comment]
Closing the issue...
