### ISSUE TITLE
Tiling doesn't work with lineTextureStyle if texture size is not power-of-two

### ISSUE THREAD

**Issue by redbeardmickey** [pixijs/pixi.js#5742]
### Expected Behavior
My assumption is that lineTextureStyle should tile texture but couldn't find in the docs about what's expected behavior.

### Current Behavior
Tiling doesn't work unless texture has power-of-two dimensions.
Demo: https://www.pixiplayground.com/#/edit/5k4oHv8mNofjoE8rxYUpN

### Environment

- **`pixi.js` version**: v5.0.3

**Comment by mofnire** [comment]
Might be caused by the limited support of non-power-of-two (NPOT) texture support in WebGL 1.0. Namely, setting a repeat mode to anything other than gl.CLAMP_TO_EDGE leads to an error in WebGL 1.0. I guess that's why PixiJS automatically set the repeat mode of NPOT textures to gl.CLAMP_TO_EDGE.

https://www.khronos.org/webgl/wiki/WebGL_and_OpenGL_Differences#Non-Power_of_Two_Texture_Support

https://github.com/pixijs/pixi.js/blob/6ba610d5d7ceec1dba8963f858486c027053c269/packages/core/src/textures/TextureSystem.js#L368-L372

However, WebGL 2.0 fully supports NPOT textures (Please refer to [the section 4.1.3](https://www.khronos.org/registry/webgl/specs/latest/2.0/#4.1.3)). So, if your browser supports WebGL 2.0, PixiJS can relax this restrictions on NPOT textures.

**Comment by mofnire** [comment]
No, I am completely wrong.
The reason why NPOT texture is not tiled seems like the default MIPMAP mode is PIXI.MIPMAP_MODES.POW2.

https://www.pixiplayground.com/#/edit/8YR5ko0Q_G2kta6pmodx~

**Comment by redbeardmickey** [comment]
@mofnire Ahhh I see. Thanks for explaining!
