### ISSUE TITLE
WebGL 2 Filter GLSL #version support

### ISSUE THREAD

**Issue by lekzd** [pixijs/pixi.js#5752]
### Expected Behavior
I start implementing fragment shader using newest 3.3 GLSL standard supported by WebGL2
I write directive `#version 300 es` as a first line of my shader to switch behavior
I can use built-in GLSL functions  `textureSize`, `texelFetch`, e t.c.

### Current Behavior
I can't start fragment shader from `#version 300 es` directive, because of Pixi already made first line of shader for me here https://github.com/pixijs/pixi.js/blob/a39a4a2c845a5cbdfda81613b0e4306740d4f06a/packages/core/src/shader/Program.js#L68

So, I found non-documented solution to copy standard vertex shader with adding of `#version` directive https://github.com/pixijs/pixi.js/blob/a39a4a2c845a5cbdfda81613b0e4306740d4f06a/packages/core/src/shader/Program.js#L53 

### Possible Solution
On my opinion it will be better to check first line of fragment shader to check version directive existence.

### Steps to Reproduce
```
const fragmentShader = `
#version 300 es

in vec2 vTextureCoord;
uniform sampler2D uSampler;
out vec4 color;

void main(void) {
    color = texture(uSampler, vTextureCoord);
}
`;

const filter = new PIXI.Filter(null, fragmentShader, {});
```

### Environment

- **`pixi.js` version**: 5.0.2
- **Browser & Version**: _e.g. Chrome 74
- **OS & Version**: does not matters

**Comment by ivanpopelyshev** [comment]
#5331

https://www.pixiplayground.com/#/edit/u~ylQ25fgguC~Eoqy91Qt

I added that `if` as a temporary solution.

Improving preprocessor from `just a pair of ifs` to something actually configurable is on our roadmap.

I cannot guarantee that it will be done tomorrow, or in a week or two. Its really hard to negotiate that stuff. For now use the workaround you found.

**Comment by lekzd** [comment]
@ivanpopelyshev thanks for a such fast answer, what about help from my side? It could be interesting to investigate issues based on this behavior.

**Comment by ivanpopelyshev** [comment]
Which issues? Just use version 300 on both vertex and fragment and it'll be fine.

The problem is architecture. We have to inject some pixi constants, and I'm not sure how to make preprocessor. Something like shaderlib in threejs. Even simple approach that adds name and precision failed , and I had to add `if`. If I asked more in that PR, it could be turned down.

 Now there is an idea in about automatic generation of multi-texture shaders. If we implement it on current base, the problem will become even worse! That's why we need better preprocessor.

**Comment by lekzd** [comment]
Issues based on broken backward compatibility with injectable constants in GLSL code in case of using #version. Patching of shaders header is usual way for popular WebGL frameworks. I just can help with it, if you have another plans ok.

Couple of years ago I already solve problem with auto-binding of data from object to shader uniforms using `glsl-tokenizer` from npm. On my opinion it could be better try to read what user wrote instead of generated shader code for uniforms list to make potentially corrupted code.

**Comment by ivanpopelyshev** [comment]
oh right, you mean GLSL module? Yeah, its broken. We need @GoodBoyDigital to solve that.

**Comment by Spade-and-Archer** [comment]
When you scour the web for how to use version 300 es shader code in Pixi, when you search every crevice and every corner, when you tug at that thread in the hopes of the salvation of functionality like `textureSize` or `texelFetch` functions and better naming conventions, this stale issue is what you find.

If you are reading this, you know at least some of the pain, for you are probably at least an hour or two into your own quest, and I am here to tell you that there is hope. Because I did it, and I made a stack overflow post explaining how I did it: https://stackoverflow.com/questions/73243599/how-to-get-glsl-300-es-shaders-running-in-pixi-js/

In case that link dies at some point, here is some code you can use:

Javascript:
```
let shaderCode = eventShaderCode;
var simpleShader = new PIXI.Filter(eventVertexShaderCode, shaderCode, this.shaderUniforms);
if (!simpleShader.program.fragmentSrc.includes("#version 300 es")) {
    simpleShader.program.vertexSrc = "#version 300 es \n" + simpleShader.program.vertexSrc;
    simpleShader.program.fragmentSrc =
        "#version 300 es \n" + simpleShader.program.fragmentSrc;
}
```
vertex shader:
```
in vec2 aVertexPosition;

uniform mat3 projectionMatrix;

out vec2 vTextureCoord;

uniform vec4 inputSize;
uniform vec4 outputFrame;

vec4 filterVertexPosition( void )
{
    vec2 position = aVertexPosition * max(outputFrame.zw, vec2(0.)) + outputFrame.xy;

    return vec4((projectionMatrix * vec3(position, 1.0)).xy, 0.0, 1.0);
}

vec2 filterTextureCoord( void )
{
    return aVertexPosition * (outputFrame.zw * inputSize.zw);
}

void main(void)
{
    gl_Position = filterVertexPosition();
    vTextureCoord = filterTextureCoord();
}
```
fragment shader:
```
precision highp float;
uniform sampler2D uSampler;
in vec2 vTextureCoord;
out vec4 color;

void main(){
    color =  texture(uSampler, vTextureCoord);
}
```

I know this isn't strictly speaking what this thread is for, but it took me so long to figure this out, and I ended up finding this thread like 100 times and it gets you *close* to a solution, but just doesn't quite get you there (the pixi playground thing doesn't work at all, maybe it worked in some previous version? IDK).
