### ISSUE TITLE
renderer.plugins.extract will add shadow?

### ISSUE THREAD

**Issue by MisakiHCL** [pixijs/pixi.js#5758]
Hi, i try extract a image/png, it will add shadow like example, how can i extract what i see in stage

Example: https://www.pixiplayground.com/#/edit/XmhidIALUkC8ZI5VwCQaF

version: PixiJS 5.0.3
browser: Chrome 74.0.3729.169

**Comment by ivanpopelyshev** [comment]
You need postdivide function from here: 

https://github.com/pixijs/pixi.js/pull/4632
https://github.com/pixijs/pixi.js/pull/4632/files#diff-e38c1de4b0f48ed1293bccc38b07e6c1R123

Unfortunately, that PR wasnt merged because it was too big and I tried to fix too many errors at once.

So, the only way is ask extract for `pixels` and then apply that function. 

Hope that function source and extract source will help you: https://github.com/pixijs/pixi.js/blob/dev/packages/extract/src/Extract.js

**Comment by MisakiHCL** [comment]
Thank you very much, postdivide function works
