### ISSUE TITLE
Extension directive should occur before any non-preprocessor tokens

### ISSUE THREAD

**Issue by markobilanovic** [pixijs/pixi.js#5764]
**--Bug Description--**
With update of Chrome to v75.0.3770.80 PIXI.Shader makes problem when first line of shader source doesn't start with 'precision'. It injects precision definition to the first line of imported shader which can produce errors.

**--Error--**
*extension directive should occur before any non-preprocessor tokens*

Shader starts with:
*#ifdef GL_OES_standard_derivatives*
    *#extension GL_OES_standard_derivatives : enable*
*#endif*

and in [pixi.js/src/core/Shader.js - Line 17](https://github.com/inteliphy/pixi.js/blob/f41370e05684c49bd730f93f1e3d83039ab85ce1/src/core/Shader.js#L17) precision definition is injected into shader which later breaks with error already mentioned:
**ERROR: 0:3: '
' : extension directive should occur before any non-preprocessor tokens** (it requires that extensions should be defined before precision that is injected)

**--Possible Solution--**
Skipping extensions (and maybe other things) for checking if 'precision' is on the start OR leaving up to user when defining shader to care about precision.

**--Environment--**
- pixi.js: 4.8.8
- Browser & Version: Chrome 75.0.3770.80 
- OS: Windows 10

**Comment by ivanpopelyshev** [comment]
That's a big problem with PixiJS preprocessor (that is called `setPrecision`) that we want to solve in next releases.

Related: #5752

Currently there is workaround: use `#version 100` in beginning of the **vertex** shader

https://www.pixiplayground.com/#/edit/HwbFRpeOP2QuY~g0UMWNp

I injected this `if` exactly because we are still in the process of negotiating, what should we put in preprocessor and how to manage it. https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/shader/utils/setPrecision.js#L14
