### ISSUE TITLE
graphicsData.shape.points for a Polygon is incorrect with rotation

### ISSUE THREAD

**Issue by MRVDH** [pixijs/pixi.js#5798]
I expect the points list to be updated to the actual new points when rotation is added, rather than displaying the original coordinates.

https://www.pixiplayground.com/#/edit/47~W4JKeToE8KP34Z6YeP

- **`pixi.js` version**: _4.8.7_
- **`pixi-viewport.js` version**: 4.0.0-beta.0
- **Browser & Version**: _Brave 0.65.120 (Chromium: 75.0.3770.90)_
- **OS & Version**: _Windows 10_

**Comment by ivanpopelyshev** [comment]
Its static data in local coords, its not supposed to be transformed.

Try that instead: 

```js
graphics.calculateVertices();
console.log(graphics.vertexData)
```

**Comment by MRVDH** [comment]
Hi @ivanpopelyshev 
.calculateVertices(); is not a function on the Graphics object and vertexData is not a property anywhere in the object.

**Comment by MRVDH** [comment]
@ivanpopelyshev I need the coords on every update for collision detection.

**Comment by ivanpopelyshev** [comment]
Well, if you cant update to v5, you have to take some code from those functions: 

https://github.com/pixijs/pixi.js/blob/v4.x/src/core/graphics/Graphics.js#L1049
https://github.com/pixijs/pixi.js/blob/v4.x/src/core/graphics/Graphics.js#L1094

Hope it helps :)

**Comment by ivanpopelyshev** [comment]
If you want to pass it to a physics engine - it usually the other way: create physics object and then duplicate it in graphics.

If you want just to test collision with point, a `containsPoint` function is enough.

**Comment by MRVDH** [comment]
I'm testing the collision between two polygons. I already have the function for that (by passing the vector array of each polygon).
If it is not possible at all to get live vector data from a polygon in v.4 then I wonder how everyone else did collision detection.

**Comment by ivanpopelyshev** [comment]
> I'm testing the collision between two polygons.

PixiJS is not a physics lib, we provide only a few functions to detect collision with a point, because everyone wants to use their own physics. We cant force our math on people.

As an example, this project contains integration with p2 physics: https://github.com/eXponenta/pixi5-playables-boilerplate/ .

> If it is not possible at all to get live vector data from a polygon in v.4

Its possible but in local coords. Its easy to convert it to global just by multiplying them by that matrix, like `updateLocalBounds` does it. v5 also has an option to add graphics in batch, that's why `calculateVertices` exists, it also multiplies everything by world transform matrix.

**Comment by MRVDH** [comment]
I updated to v5 and now use vertexData
