### ISSUE TITLE
tint + renderTexture breaks in canvas

### ISSUE THREAD

**Issue by photonstorm** [pixijs/pixi.js#582]
Just making a note of this bug here, will try and submit a fix for it next week.

But with the canvas renderer if you've got a Sprite that uses a RenderTexture and you update the RenderTexture, then the Sprite happily displays the changes. But if you tint the Sprite all changes to the RenderTexture stop being updated in any tinted Sprite using it as a texture.

Only happens in canvas, WebGL is fine. Most likely something to do with:

`if(this.cachedTint !== this.tint)`

Not checking for texture updates. Will investigate later.

**Comment by englercj** [comment]
This is still an issue in v3, @GoodBoyDigital thoughts on how to fix it? Even if we remove the `cachedTint` check, the CanvasTinter still caches tinted textures based on color. So it still wouldn't update.

**Comment by bQvle** [comment]
I'm having issues here aswell, I'm creating a level-editor, and when i want to save a level-preview i render the stage onto a renderTexture, but if i change textures on sprites, they wont update when I re-render the stage. (tint isn't working at all).

The Preview is its own Canvas, and I'm forced to use a regular Canvas, because i cant have two WebGL canvas on one page.

Do you have any eta. on this?

**Comment by GoodBoyDigital** [comment]
Due to the fact 99% of browsers are using WebGL we will not be looking to address this edgecase issue instead focusing our efforts onto the WebGL future! We will certainly accept any PRs to address this if anyone wishes to contribute. Thanks! 👍
