### ISSUE TITLE
ERASE and DST_OUT blend modes not working

### ISSUE THREAD

**Issue by patatopotato** [pixijs/pixi.js#5839]
The goal I'm trying to achieve is to cut out any number of figures from an image in a container so that anything behind the container shows through.

I'm not sure why the figures' silhouettes [in my test](https://jsfiddle.net/MasterPtato/e578gkuy/1/) are black when using ERASE or DST_OUT and not red since they should erase the pixels from the background image and let the red from the renderer background show through.

Does the blend mode apply to everything in the render including the renderer itself? If so, how would I limit the blend mode to only a certain image or container?

PS. I've tried using `PIXI.display.Layer()` and its `getRenderTexture()` functionality, but it does not work when the child display object I tried to make cut out of the layer had a mask (masks in general are very iffy I've come to find). I was hoping to use blend modes since they are very simple and easy to use for me coming from canvas2d.

**Comment by ivanpopelyshev** [comment]
How it works in your case:

1. RED back color applied
2. Background is applied
3. clears sprites

The problem is there's no way to put the stuffing back to living turkey, background is lost the moment picture is shown.

Now, lets add that line:

```js
container.filters = [new PIXI.filters.AlphaFilter()];
```

How it works:
1. RED back color applied to main framebuffer
2. because of a filter, temp framebuffer is bound
3. in temp framebuffer background is drawn
4. in temp framebuffer, two hole sprites are erased
5. because of a filter, temp framebuffer is drawn on main framebuffer

That's how its supposed to work.

**Comment by ivanpopelyshev** [comment]
Also I'd like to thank you, as you are one of first users of that blendMode in v5! We had is at official hack before : https://github.com/pixijs/pixi.js/wiki/v4-Gotchas#blend-modes

I'll rewrite that page for v5 soon, and thanks to you I'll include a demo!

**Comment by patatopotato** [comment]
Thanks for the reply and clarification, I didn't know that was how the rendering was handled since in canvas2d everything was simply drawn on top of everything else.

> I'll rewrite that page for v5 soon, and thanks to you I'll include a demo!

Glad I could help!
