### ISSUE TITLE
Possible versioning bug when installing via NPM

### ISSUE THREAD

**Issue by creyD** [pixijs/pixi.js#5851]
### Expected Behavior
In my package.json I have the following 2 lines:
`"@pixi/core": "5.0.0-rc.3",
    "pixi.js": "5.0.0-rc.3",`
This should in my opinion install the version 5.0.0-rc.3 as we need this version specifically.
### Current Behavior
When I run `npm i` however it installs 5.0.4.
### Possible Solution
I don't really know how to fix it quite honestly. I opened a question on Stack Overflow (https://stackoverflow.com/questions/56805264/npm-installs-different-version-from-package-json) but no solution seems to work for me.
### Steps to Reproduce
- npm install electron and pixi
- look at the package-lock.json
### Environment

- **`pixi.js` version**: That's kind of the problem
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: Windows 10

**Comment by creyD** [comment]
Stack Overflow solved how to work around this by manually defining the dependencies to the specific version, which still doesn't explain why this happens.

**Comment by bigtimebuddy** [comment]
This seems more like an npm issue than something specific to Pixi. We only manage the latest release tag on npm so if you do “npm install pixi.js” that should pull latest which is 5.0.4. Everything else, including pinning old versions, using package lock or yarn lock, is up to users to manage for their projects.

**Comment by creyD** [comment]
@bigtimebuddy Thanks for clarifying! I will close this issue then.

**Comment by englercj** [comment]
Probably because we use `^` in our dependencies. So if you install with `"@pixi/core": "5.0.0-rc.3"` specified it will read the package.json of `@pixi/core` which says it needs `"^5.0.0-rc.3", which `v5.0.4` is semver compatible with. So as far as npm knows it is doing the right thing: installing the latest compatible version.

**Comment by Leftium** [comment]
I think it would be better to not use `^` in the main pixi.js package when specifying @pixi sub-module dependencies. If the user is specifying a specific version in the NPM command, there is probably a reason they need that version and not the latest compatible version:

- `npm install pixi.js@5.0.0-rc.3` would work as expected (instead of actually installing the latest compatible version like v5.0.4)
- `npm install pixi.js@^5.0.0-rc.3` could be used to get the current behavior.


Since the current package.json specifies @pixi sub-modules with `^`, the only way to install a specific version of pixi.js is to force all the 30+ sub-module versions in the client project's package.json. There is no simple way to do it from the command line.

And as the [StackOverflow question](https://stackoverflow.com/questions/56805264/npm-installs-different-version-from-package-json) indicates, it is confusing if you do `npm install pixi.js@5.0.0-rc.3`, but another version is installed (effectively).

**Comment by creyD** [comment]
@englercj Any updates on this? Was @Leftium s advice implemented?

**Comment by bigtimebuddy** [comment]
This has been fixed in the latest releases. All dependencies are locked to exact versions and all sub packages have matching versions to reduce confusion.

**Comment by creyD** [comment]
That is very good to hear! Thanks for the quick reply!
