### ISSUE TITLE
WordPress install

### ISSUE THREAD

**Issue by tomjimlondon** [pixijs/pixi.js#5904]
Could you please provide further instruction to install pixi on WordPress?

**Comment by GoodBoyDigital** [comment]
not quite sure what you are asking for here? is there a specific problem you are trying to solve?

**Comment by tomjimlondon** [comment]
I just don't know how to install it. In what folder? I tried the main one in the server and other locations and it does not work. I also tried adding the external link on the header and neither.
Have you ever try to make a Wordpress installation?

**Comment by themoonrat** [comment]
Hi @tomjimlondon - I don't think this is a place we can help on this I'm afraid. There are many examples of how to use PixiJS normally; I think this is more of a 'ask wordpress experts on how to take pixi examples and put that in a wordpress website'!

**Comment by tomjimlondon** [comment]
Yes, I tried.

They reply that because it is a custom script they do not offer support.

So, I will assume that pixijs does not work in wordpress, as far as I never heard or seen a wordpress site working with it.

In the other hand is a pity that you not offer support for it, regarding that half of the planet or even more use wordpress.

But thanks for replying.


________________________________

**Comment by GoodBoyDigital** [comment]
@tomjimlondon, pixijs.com is powered by wordpress 👍 
@themoonrat is correct, The problems you encounter will not be pixi issues, but wordpress integration issues.

**Comment by djmisterjon** [comment]
from what i remember in wordpress you can add custom scripts
![image](https://user-images.githubusercontent.com/24865815/62035772-7963d880-b1be-11e9-8efd-879720f47eb4.png)
just load pixijs here

**Comment by tomjimlondon** [comment]
I tried all that. Actually I have been using three without problems. But pixijs do not work.

________________________________

**Comment by themoonrat** [comment]
If you could provide an example of it going wrong, that'd help a huge amount

**Comment by jjhesk** [comment]
i worked on wordpress before. this is a frontend related problem from its script loading. pixi could not be loaded from its library or it might have crashed from other loaded symbols. check your browser console first and start from there.

**Comment by bigtimebuddy** [comment]
I need to close this issue mostly because it’s off topic. WordPress installation is something better served by stack overflow or searching for general info on working with third party JS libraries in WP. If there’s a specific Pixi related bug, please provide more information and we can reopen. Thank you for everyone who responded with suggestions.

**Comment by leventmuslim** [comment]
If they have a solution or opinion they would share it already 
It looks like, this PixiJS doesn't have a use in a Worpdress installation and/or its developer wants to keep this knowledge to himself

Either way; walk away from such people and their apps unless you are a developer too. 
Otherwise, experience talking here, you'll be left alone in the field by such developers. They are poisonous for rookies and should be avoid in every scenario
