### ISSUE TITLE
Filter/Shader - local coordinates

### ISSUE THREAD

**Issue by dev-zetta** [pixijs/pixi.js#5906]
Hello there,

I just started with shaders in pixi, and I started by twiddling with this shadow sample: https://pixijs.io/examples/#/filters-advanced/pixie-shadow-filter.js

Now I see that all coordinates are in global space.... not the local sprite/object space.

Why is that? What I've seen, most of shader samples that I've found online, use local space. I mean at http://glslsandbox.com/ and https://www.shadertoy.com/, for example.

I've seen that it was already requested to switch to local space, few years ago:
https://github.com/pixijs/pixi.js/issues/1092

Is there any way how to easily switch to local space? Or do I have to customize the filter class?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters
https://github.com/pixijs/pixi.js/wiki/v4-Creating-Filters

There are 15 possible coordinate systems and I saw usage for almost all of them. I didnt finish v5 doc yet but there is a way to switch between systems. You are welcome to try simplify it all but I'm very that its possible. 

The problem is that those sandboxes use only fullscreen shaders, and we deal with "part of screen" most of the time because of nature of 2d stage and its optimizations.

**Comment by dev-zetta** [comment]
Thank you Ivan :) I managed to convert the shaders to "correct" coordinate system.
