### ISSUE TITLE
Pixels on bottom edge of RenderTexture are inconsistent when using BlurFilterPass in Pixi5

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi.js#5969]
### Expected Behavior
Pixels in generated texture should be consistent with source object

### Current Behavior
Pixels at bottom edge of generated texture are not consistent

### Steps to Reproduce
- Apply a BlurFilterPass to a sprite
- Render it to a RenderTexture
	
Pixi5 example (not working) - https://www.pixiplayground.com/#/edit/4kgn~bpbYpQMU17cVu5Xl
Pixi4 example (working) - https://www.pixiplayground.com/#/edit/fH6RLPM_wFUd_~piDZF7s

Both of these samples have near-identical code (with only pixi4 -> pixi5 differences).

Sorry for the vague issue title, but I'm not actually sure what's happening.  When comparing the pixi4 and pixi5 samples above, the pixi4 sample works correctly, while the pixi5 sample has a red blur at the bottom of the texture.  It could be a sampling issue since it only occurs at the edge of the texture, but that's just a guess.

Note: The actual blur is different between Pixi4's BlurYFilter and Pixi5's BlurFilterPass, but that's not part of the issue.

**Comment by ivanpopelyshev** [comment]
I worked with v5 blur a lot. Yes, there can be differences on edge.

This exact difference happens because v5 applies padding BEFORE fit to source, and v4 applies it AFTER.

v4: https://github.com/pixijs/pixi.js/blob/v4.x/src/core/renderers/webgl/managers/FilterManager.js#L147
v5: 
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/filters/FilterSystem.js#L217

You can switch off autoFit (`filter.autoFit = false`) , it will work but it will compute whole area of the container. If you want to emulate v4 behaviour to the point, try this thing:

```js
// required
filter.autoFit = false;
container.filters = [filter];

//optional
container.filterArea = container.getBounds();
//now somehow we need source frame size... like, your renderTexture frame?
container.filterArea.fit(rt.frame);
//or screen frame?
container.filterArea.fit(renderer.screen);
//pad it like before
container.filterArea.pad(filter.padding);
```

**Comment by ivanpopelyshev** [comment]
Here it is: https://www.pixiplayground.com/#/edit/pggBKzea5fchB0eECV0Vj

**Comment by jmlee2k** [comment]
Thanks for the quick response!  I think we'll be able to use this to fix the problem we're having.

**Comment by bigtimebuddy** [comment]
Seems addressed, closing.

**Comment by ivanpopelyshev** [comment]
Yeah , we can add compatibility mode later, i added a mention to wiki.
