### ISSUE TITLE
Crash Chrome when using BlinkMacSystemFont with PIXI.Text

### ISSUE THREAD

**Issue by mp3** [pixijs/pixi.js#6001]
### Expected Behavior

BlinkMacSystemFont should be rendered with PIXI.Text.

### Current Behavior

Crash a browser tab. Only occurs in Chrome, not in Safari or Firefox.
![image](https://user-images.githubusercontent.com/18319970/62685816-56c39200-b9fe-11e9-8679-74998fb4ad32.png)

When I use Pixi.js v5.0.4, this error has never happened on Chrome.

#### Example code

```
const app = new PIXI.Application({ backgroundColor: 0x1099bb });
document.body.appendChild(app.view);

const style = new PIXI.TextStyle({
    fontFamily: 'BlinkMacSystemFont',
});

const text = new PIXI.Text('text', style);

app.stage.addChild(text);
```

### Environment

- **`pixi.js` version**: 5.1.1
- **Browser & Version**: Chrome 75.0.3770.142
- **OS & Version**: macOS 10.14.5

**Comment by themoonrat** [comment]
This is odd.

I had a Mac sitting on Chrome 68, and that worked absolutely fine with 5.1.0+ of PixiJS.
And Chrome 75+ with 5.0.4 of PixiJS works fine.
But for some bizarre reason, Chrome 75 along with PixiJS 5.1.0+ crashes. Bizarre. 

Chrome has had issues with this font before: https://github.com/cytoscape/cytoscape.js/issues/2249 - but I don't see why we'd have this issue. I changed something on text to have better drop shadows.... but this text doesn't have that, so that theory is ruled out.

**Comment by ivanpopelyshev** [comment]
@themoonrat something with OffscreenCanvas ?
