### ISSUE TITLE
Garbage on screen after computer has been asleep for many hours

### ISSUE THREAD

**Issue by patrick99e99** [pixijs/pixi.js#6025]
I am using a game engine which uses PIXI as its canvas rendered, and I am finding after loading the game in the browser, if I put the computer to sleep for several hours, when I wake the computer up, the screen is littered with "garbage".

For example, before closing my laptop:
<img width="384" alt="Screen Shot 2019-08-19 at 7 14 15 PM" src="https://user-images.githubusercontent.com/28946/63312205-9cf9da80-c2b5-11e9-8f8a-7779d92d767e.png">

and then after closing it and reopening hours later:
<img width="366" alt="Screen Shot 2019-08-19 at 7 00 05 PM" src="https://user-images.githubusercontent.com/28946/63312003-e5fd5f00-c2b4-11e9-98e2-7b4e3ac45f9f.png">

I was just wondering if this is a known issue?  Also, is there any sort of pixi method I can call on browser window focus or something to force it to clear its cache/refresh itself?

- **`pixi.js` version 4.5.4
- **Browser & Version Chrome 76.0.3809.100 
- **OS & Version**: Mac OS X 10.14.3

**Comment by ivanpopelyshev** [comment]
Looks like huge scroll artifacts. If you pass big numbers to graphics lineTo and other functions or to TilingSprite transform, it can degrade, because those numbers are passed in shaders where precision is small. If speed of scrolling is too big, even double-precision numbers can degrade.

Do you know what are "far lands" in minecraft?
