### ISSUE TITLE
Slient errors when using the new Sprite.from in v5

### ISSUE THREAD

**Issue by danrostron** [pixijs/pixi.js#6032]
Previously (in Pixi v4) when you tried to create a Sprite using Sprite.fromFrame('textureId'), and textureId didn't exist in the texture cache, it would throw an error. 

In the new Pixi (5.1.1), using the Sprite.from('textureId') method, it now doesn't throw any error and just displays an empty Sprite. This is a problem for me when re-skinning a game, and need to remove unused textures etc. Is there a way to turn on a warning / error in this case?

**Comment by ivanpopelyshev** [comment]
'from' is universal function, it tries url if thing wasnt found in textureCache. I suggest to copy it and replicate v4 behaviour.  I honestly dont know why it is like that :)

**Comment by danrostron** [comment]
Previously did:

` throw new Error('The frameId "' + frameId + '" does not exist in the texture cache');`

**Comment by ivanpopelyshev** [comment]
You can trace who made those changes, maybe @bigtimebuddy knows whats the deal with new behaviour.

It will take time to switch back or make new API, so its better if you use obvious workaround for now

**Comment by danrostron** [comment]
Yeah it just means that whenever I create a new sprite, I'd need to check the TextureCache first, which is a annoying :(

**Comment by bigtimebuddy** [comment]
Yeah, I definitely think we need something here like `fromCache` or pass an option flag  like:

`Texture.from(“imgName”, { cached: true })`

If it doesn’t exist in the cache it will throw an error. I prefer using “cache” instead of “frame” because it’s a little more aligned with texture cache.

Thoughts on this API?

**Comment by badeebee** [comment]
I'm sorry if I sound completely ignorant but thats exactly what it is but wouldn't doing something like imprinting information in a PNG the more enduring and less likely Timmy thrown out or a hidden recycle bin to catch this discarded cache? please don't mock me I'm just learning I don't even know why I'm commenting on this I'm actually just trying to meet some people I'm trying to understand Android I haven't studied since 93 so cut me a little bit of slack if that's okay and yes I will from now on sit back and just listen I just had a deja Vu with that question that's all and again apologies for sounding or being rather so green and out of my league I do want to be part of the conversation even if it's that part that's been corrected because at least I'll be learning thanks and I'm assuming that you're not going to completely with me apart or be terribly cruel I just took add on to that to ensure that you don't make me cry and do you have learning disability in the middle handicap I'm trying to pick up the pieces okay if I'm wrong just you can explain that I'm wrong and I will be quiet and take it back seat and just listen thank you you guys have a great day I hope you figure it out

**Comment by themoonrat** [comment]
@bigtimebuddy I think that would be useful, yes. I'd also wonder if it would accompany a global setting to change the default behaviour?

Some apps, like mine, only ever want to grab assets that have been preloaded. It'd be annoying to put this setting in every time I did .from

**Comment by argelricpher** [comment]
I still believe cheater never wins...big mistake for a new beginner...but
full of lessons

**Comment by brightest-dazes** [comment]
With no guidance or counsel comes ignorance. What is needed are team players never has there been or will be an (I) in team.

**Comment by eXponenta** [comment]
I think its API must be dropped instead of fixed.
Because 'from' used with any texture source, but cacheID isn't texture source.
If needs to use textures from cache - can be use TextureCache[key], or may be regress and add Texture#fromCache(id: string | number).

**Comment by bigtimebuddy** [comment]
I added a PR to address this. Feedback or other approaches welcome.
