### ISSUE TITLE
Cropped curved text ( padding included )

### ISSUE THREAD

**Issue by martinboksa** [pixijs/pixi.js#6033]
Hello, 
I was trying to create curved/bold/italic texts but some of them are cropped ( padding is already included ). Please any idea how to fix it?

### Expected Behavior
The whole text visible

### Current Behavior
![screen](https://user-images.githubusercontent.com/4490694/63513541-d8c7b680-c4e6-11e9-8dfc-66b3a417e19f.png)

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/AkpqkMJtxVGFmkPw5hL9Z

### Environment

- **`pixi.js` version**: 4.8.8
- **Browser & Version**: Chrome 76.0.3809
- **OS & Version**: Mac OS
- **Running Example**: https://www.pixiplayground.com/#/edit/AkpqkMJtxVGFmkPw5hL9Z

**Comment by eXponenta** [comment]
It's works propertely.
You try use texture from Text on rope, but there is difference between sprite ( Text is Sprite-like) and Mesh.

Paddings generate  trimed texture, but trim works only as vertex shift on Sprites. 
Instead of text use canvas and draw text directly, or extend PIXI.Rope and override `_refresh` method and fix `uvs` generation. 
http://pixijs.download/v4.8.8/docs/mesh_Rope.js.html#line120
