### ISSUE TITLE
pixi.renderer.extract.pixels bug

### ISSUE THREAD

**Issue by developer-av** [pixijs/pixi.js#6054]
### Expected Behavior
```
    console.log(pixi.renderer.extract.pixels(graphics));
    setTimeout(() => {
        console.log(pixi.renderer.extract.pixels(graphics));
    }, 5000);
```
`Uint8Array(4) [255, 0, 0, 255]`
`Uint8Array(4) [255, 0, 0, 255]`
### Current Behavior
`Uint8Array(4) [255, 0, 0, 255]`
`Uint8Array(4) [0, 0, 0, 0]`

### Steps to Reproduce
```
    let graphics = new PIXI.Graphics();
    graphics.beginFill(0xFF0000);
    graphics.drawRect(0, 0, 1, 1);
    graphics.endFill();
    graphics.x = 959;
    graphics.y = 238;
    layer.addChild(graphics);
    
    console.log(pixi.renderer.extract.pixels(graphics));
    setTimeout(() => {
        console.log(pixi.renderer.extract.pixels(graphics));
    }, 5000);
```
without a set position everything works fine
Thanks for the work

### Environment

- **`pixi.js` version**:  5.1.2
- **Browser & Version**: Chrome 76.0
- **OS & Version**: _e.g. win 10

**Comment by ivanpopelyshev** [comment]
Hello! The bounds that `generateTexture` takes is a big problem - we have those kind of bugs often,

I've tried to make PR that fixes it all and covers with tests 2 years ago but it was rejected, Because it was too big and affected pixi architecture the bad way. I'm gonna make another attempt this year, I think :)

For now my default advice on that kind of issues - use `getBounds` manually, pass them to `generateTexture`, pass the texture to `pixels`, destroy the texture. Of course I'll try to fix that one , but there's no guarantee that you wont stumble across another one later :(
