### ISSUE TITLE
Canvas-Renderer calls renderCanvas which is not a function

### ISSUE THREAD

**Issue by lwallent** [pixijs/pixi.js#6069]
I am having some issues displaying nice readable text using WebGL renderer in Pixi. So I wanted to see how the text rendered if I used the legacy Canvas-Renderer.

I did the following:
1) installed "@pixi/canvas-renderer" version 5.1.2

1) imported the canvas-renderer. 

1) used forceCanvas in Application.

When launching the application is correctly using CanvasRender, but it seems that it calls the *old* rendering methods? Shouldn't it call *render* instead of *renderCanvas*?

Error examples:

```
errors.ts?a631:16 ERROR Error: Uncaught (in promise): TypeError: displayObject.renderCanvas is not a function
TypeError: displayObject.renderCanvas is not a function
    at CanvasRenderer.render (CanvasRenderer.js?7522:237)
    at CanvasRenderer.generateTexture (AbstractRenderer.js?0ef5:264)
   ....

```
and

```
errors.ts?a631:16 ERROR TypeError: displayObject.renderCanvas is not a function
    at CanvasRenderer.render (CanvasRenderer.js?7522:237)
    at Application.render (Application.js?6633:97)
```
    

### Environment

- **`pixi.js` version**: 5.1.2

**Comment by SukantPal** [comment]
Hi Iwallent,

PixiJS defers drawing algorithms to the display-objects, i.e. the objects are responsible for using the renderer instance and using it to draw themselves. The `render` methods are implementing assuming that the renderer instance will be a `Renderer` (with a WebGL `context`). If a display object also has a `renderCanvas` method, that means it supports drawing itself using a `CanvasRenderer` (with a 2D context).

By default, PixiJS display-objects do not support canvas renderer. However, on installing `@pixi/canvas`, it merges mixins into the `Graphics`, `Sprite`, `Particles`, & `Text` display-objects. Other than that, any custom/3rd-party display-objects will have to support canvas rendering.

I'm not sure why your problem is occurring (I'm not working on PixiJS nowadays); however, I don't think `BitmapText` is supported for canvas rendering, only regular `Text` is.

**Comment by ivanpopelyshev** [comment]
BitmapText is rendered through sprites, so it should work. 

> installed "@pixi/canvas-renderer" version 5.1.2

That's how pixi.js-legacy works: https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js-legacy/src/index.js

Renderer doesn't work without display overrides, such as https://github.com/pixijs/pixi.js/tree/dev/packages/canvas/canvas-display/src

To use single pixi modules you have to create a bundle file, either manually either use https://pixijs.io/customize/ .

**Comment by klerick** [comment]
I have a similar problem.
I have application and it works correctly if I use 
`import {Application} from 'pixi.js-legacy;`

But if I replace pixi.js on
`import {Application} from 'pixi.js-legacy;`
The application does not work. 
The method render does not call in child container.

Can you explain how correct use canvas render with default application?

**Comment by bigtimebuddy** [comment]
@lwallent could you provide an example repo of this issue please? That would help diagnose what’s going on here.

**Comment by ivanpopelyshev** [comment]
pixijs-legacy just works. You can add "forceCanvas: true" to pixi examples that can work with canvas2d: https://pixijs.io/examples/#/demos-basic/container.js

Also latest pixijs tests work just fine. 

That means the problem with your packer or something that our test dont cover, and, unfortunately, my telepathy doesn't work on your issue - please provide the minimal reproducable demo, not as one string but all the files in zip. You can also try to set it up in codesandbox.com with parcel, its easy :)
