### ISSUE TITLE
Bug with combining Babylon.js and Pixi.js with PBRMaterial

### ISSUE THREAD

**Issue by itubiaoge** [pixijs/pixi.js#6078]
I’m trying to mix pixijs and babylonjs. According to the Babylonjs official [example](https://doc.babylonjs.com/resources/babylonjs_and_pixijs), I added PBRMaterial to the scene and found that the rendering was wrong. The error example is shown below:
1. The backgroundimage changed color automatically.
2. PBRMaterial cannot take effect.
3. Background image disappear when I move ground and sphere leaving off screen.
[https://jsfiddle.net/vr6wd9sm/](https://jsfiddle.net/vr6wd9sm/)

I have already gone to the babylonjs forum for help and solved the first two problems with Sebavan.  [https://jsfiddle.net/fjyqmtv3/](https://jsfiddle.net/fjyqmtv3/)
The third question makes us confused. Sebavan  said "Something looks wrong with the VAO in pixijs Could you check with them ? I wonder why the reset does not look like resetting everything."   [https://forum.babylonjs.com/t/how-to-combine-babylon-js-and-pixi-js-with-pbrmaterial/5394/7](https://forum.babylonjs.com/t/how-to-combine-babylon-js-and-pixi-js-with-pbrmaterial/5394/7)

Who can help us?

**Comment by ivanpopelyshev** [comment]
Time to combine Babylon in Pixi, right?

OK, lets try that one: 

```js
pixiRenderer.reset();
pixiRenderer.render(stage);
pixiRenderer.reset(); // <-- i've added it
```

I think that pixi binds vao, and because babylon isn't statles, nor does it have `reset` operation, it just assumes that everything that is bound is his to manage, and modifies that vao :)

First reset() notifies pixi that someone worked with context and there's no guarantee on stuff that is already bound in context, second reset() that it needs to unbind everything before some strange guy used it :)

**Comment by ivanpopelyshev** [comment]
OK, answered there: https://forum.babylonjs.com/t/how-to-combine-babylon-js-and-pixi-js-with-pbrmaterial/5394/11?u=hackerham

**Comment by itubiaoge** [comment]
@ivanpopelyshev Thank you for your prompt reply
