### ISSUE TITLE
How to use pixi touch event without div

### ISSUE THREAD

**Issue by wss534857356** [pixijs/pixi.js#6096]
**It is not bug**, I just want to get some help.
I try to use pixi without dom, but pixi  relies on div to implement click or touch events.What should I do to better handle this problem? How should I remove the dependency of the click event on the div?

**Comment by ivanpopelyshev** [comment]
Hi! search for pixi-shim plugin. You might need adjustments for latest version of pixi.

**Comment by bigtimebuddy** [comment]
Unfortunately this is not a workflow PixiJS supports. There are some people that are attempting to polyfill, like Ivan suggested. I’m closing this issue because it’s not something we can help with officially, but people are welcome to leave other ideas. Also, the author might consider html5gamedevs.com or stackoverflow.

**Comment by wss534857356** [comment]
@bigtimebuddy @ivanpopelyshev  thanks for you help!
What are the optional polyfills? Can pixi-shim help me solve this problem?

**Comment by wss534857356** [comment]
I fixed this question,just I ** missed the buttonMode **
