### ISSUE TITLE
Bad WebGL detection when Chrome disable "Use hardware acceleration when available"

### ISSUE THREAD

**Issue by cqvol** [pixijs/pixi.js#6109]
### Expected Behavior
Support WebGL.

### Current Behavior
The browser support WebGL but not work when disable hardware acceleration.
from 5.0.0-rc3 ~ Now

### Possible Solution
N/A

### Steps to Reproduce

1. `chrome://settings/system` set "`Use hardware acceleration when available`" to `disable`
2. Open [Example](https://www.pixiplayground.com/#/edit/iYVa93CevZ3vAfQpvhNw1)
3. throw exception and the `PIXI.utils.isWebGLSupported` will return `false`
> WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.

### Environment

- **`pixi.js` version**: 5.0.0-rc3 - ~
- **Browser & Version**: _e.g. Chrome65 - ~
- **OS & Version**: _e.g. Windows 10
- **Running Example**: https://www.pixiplayground.com/#/edit/iYVa93CevZ3vAfQpvhNw1

**Comment by themoonrat** [comment]
Set
`PIXI.settings.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT = false;`
before creating your renderer. 

Since hardware acceleration is disabled, you're going to get terrible WebGL performance, and Chrome can report that to us. By default, if the browser itself says performance is going to be terrible, then we'll fail the WebGL check.

But you can set that flag to false to ignore the browsers recommendation and use WebGL anyway

**Comment by themoonrat** [comment]
PS. You'll need 5.1.0 or above of PIXI for this settings to exist
