### ISSUE TITLE
Scaling outline rectangles

### ISSUE THREAD

**Issue by ptsans** [pixijs/pixi.js#6121]
Hi, I think I have a well-known problem, but still, how to solve it?

I have a big random map of outline sprites. As the map zooms out in random places the stroke becomes thicker or absent. In addition, when the camera slows down, this effect appears.

### Expected Behavior

- proportional stroke width when zooming and moving the camera

### Current Behavior
![screen1](https://user-images.githubusercontent.com/18110232/65570808-b45b7000-dfa5-11e9-9161-9d6e7b3799c8.png)

![screenshot-192 168 1 216-2019 09 25-12_42_40](https://user-images.githubusercontent.com/18110232/65570829-c2a98c00-dfa5-11e9-9ac4-833e00117e03.png)

### Possible Solution

Use PIXI.Graphics() instead of sprites and redraw the rectangles each time with a new position and size. But this will greatly reduce performance.

### Steps to Reproduce

https://codepen.io/Pakos/pen/YzKgWQK?editors=0010

### Environment

- **`pixi.js` version**: _5.1.5_
- **`pixi-viewport` version**: _4.2.3_
- **Browser & Version**: _Chrome 76_
- **OS & Version**: _Linux Mint 19.2_
- **Running Example**: _https://codepen.io/Pakos/pen/YzKgWQK?editors=0010_

**Comment by ivanpopelyshev** [comment]
Strokes are made with geometry, need to change lineWidth and recalculate that after zoom. You can change inner lineStyle:

https://www.pixiplayground.com/#/edit/GYy0QCPK1I62IyCxr2WH1

however if you have 1000 rects there, they all will have different lineStyle objects, its up to you how to deal with that. Maybe manually change it to your own instance of lineStyle after 

Another approach - use `native` lines, there was a switch in `lineStyle`. It'll always be 1 pixel width, supported by webgl. 

Of course there's a question "why such a simple thing still not done" - because its difficult, we need special shaders for that, that stops batching, it has different balance of performance, and just no one made a plugin. I saw multiple times that people hacked graphics to work like that but each time authors didnt bother to make it into a plugin.

**Comment by distinctdan** [comment]
You should be able to solve your issue by using graphics objects and putting them all in a container, and then moving/scaling the container when your "camera" moves, instead of redrawing all the graphics. I've done this camera technique for the level editor of the game I'm building in PIXI, and it's been able to handle thousands of lines no problem. To move the camera, I move the global container the opposite direction of the camera movement. So if the "camera" is moving right, I move the container left. To do zoom also, you'll have to do a little math to calculate the scaled movement, but it's not too bad.
