### ISSUE TITLE
[Docs] Arrays must be converted to textures before passing them to shaders

### ISSUE THREAD

**Issue by carlsmith** [pixijs/pixi.js#6130]
It is not obvious or clear when passing a typed array into a shader (to be accessed as a sampler2D uniform) that it needs converting to a `Texture` first. This has caught me out twice now, and I only know from help I was given in the past (#5484).

Updating the docs would maybe prevent confusion in future. Thanks.

**Comment by eXponenta** [comment]
What article of docs you can not understand?

**Comment by ivanpopelyshev** [comment]
In general, in javascript its often a problem - people putting stuff in functions and it somehow doesnt work. Example : `container.addChild(new PIXI.Rectangle(x,y,w,h))`.

The only way for JS is to define it in documentation or to make typings. However, in cases like Uniforms its very difficult to make proper typization, in that case we have to use actual english language.

Since its more creative thing than just "guys you have a bug", please clarify which english phrase and where exactly we have to put. In this particular ticket you are dealing with two russians , and @eXponenta english level is below the floor :)

I'm actually afraid that the issue is much more difficult - we dont have even partial articles regarding uniforms of shaders and filters.

Relevant places where extra warning can be put: 

https://github.com/pixijs/pixi.js/wiki/v5-Creating-filters
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/shader/Shader.js#L14
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/filters/Filter.js#L8

Relevant place that already uses `Texture.from`: https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js .

**Comment by eXponenta** [comment]
@ivanpopelyshev, hey! My english is higher than floor level, about baseboard level.

**Comment by carlsmith** [comment]
> What article of docs you can not understand?

Hey, @eXponenta. I *understand* the docs, but the [doc for `PIXI.Filter`][1] lacks information about the `uniforms` argument to the `PIXI.Filter` constructor. It only says this:

> `uniforms [object] [optional]` Custom uniforms to use to augment the built-in ones.

The [doc for the `PIXI.Shader` base class][2] only reiterates the same information. 

The example code (for `PIXI.Filter`) makes it clear that the `uniforms` object is a flat hash of initializers, so it's obvious how to define an int or float, but it's not obvious that typed arrays (say a`Uint8Array` of RGBA bytes) will fail silently unless you convert it to a `PIXI.Texture` first.

Conversion to a `PIXI.Texture` is specific to the PIXI API, so should be covered by the API docs.

[1]: https://pixijs.download/dev/docs/PIXI.Filter.html
[2]: https://pixijs.download/dev/docs/PIXI.Shader.html

**Comment by carlsmith** [comment]
@ivanpopelyshev - Sorry, I didn't see your response until after I replied to @eXponenta.

> Since its more creative thing than just "guys you have a bug", please clarify which english phrase and where exactly we have to put. 

No problem. I think maybe just a note in [the `PIXI.Filter` doc][1], at the end of the **Usage** section. Something like...

> Please note that you cannot directly use an `ArrayBuffer` as a uniform. It must be converted to a texture first (see `PIXI.Texture.fromBuffer`).

[1]: https://pixijs.download/dev/docs/PIXI.Filter.html

**Comment by carlsmith** [comment]
I don't want to make any real commitments at this stage, but I might be able to help with the docs. I'm not very busy, I've been using PIXI for a while, I've worked as a tech writer for years, and the docs are already good, so even just lightly editing everything to fix the minor grammatical issues could add quite a lot of polish.

I didn't know you guys were Russian. That's cool. I'm English (but use US grammar for docs). I'll have a look at what tech the docs are using this evening, and see what I could help with.

**Comment by carlsmith** [comment]
How are the docs generated? I looked for the repo, but the only one I found was archived back in 2017.

**Comment by bigtimebuddy** [comment]
@carlsmith we would LOVE your help. There are definitely places in the docs the need improvement.

The latest docs for the dev branch are always updated here: https://pixijs.download/dev/docs/index.html

The documentation is auto generated from the source code using the JSDoc tool. It can be run locally by running `npm run docs`. PRs are always welcome for things like you suggested.

Let me know if any of that doesn’t make sense or if you need some more context on navigating the project.

**Comment by carlsmith** [comment]
Thanks @bigtimebuddy - much appreciated. I'll dive into it tomorrow (it's late here now), and let you know if I need any pointers. I'm really looking to forward to getting involved. Thanks again.
