### ISSUE TITLE
Question about efficiently rendering text

### ISSUE THREAD

**Issue by smparsons** [pixijs/pixi.js#6136]
Hi All,

My overall goal is to compare the performance of both PIXI and three.js in regards to rendering complex 2D charts. My question was specifically about rendering text in PIXI.

In my 2D chart, I need to draw a lot of text. The font size of the text needs to increase as the user zooms in on the chart, and decrease when the user zooms out. I would like the text to remain crisp and easy to read as the size increases and decreases. 

I attempted to implement this using BitmapText, however I quickly realized that it doesn't scale well when changing the font size. I noticed that the text would become too blurry when decreasing the font size. Even if I loaded two bitmap fonts, a small-sized font and large-sized font, the text would still appear too blurry at small sizes (my definition of small is around 6px - the smallest possible text size on the chart).

I did a little research and came across the following article: http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/

This article describes a technique to efficiently render text in WebGL that involves making the GPU render glyphs using bezier curve data. I viewed the demo and it was very impressive. The text size scales very well, and the performance is great. I'm trying to see if it would be possible to implement the techniques described in the above article within PIXI. If you take a look at his demo source code, it is written in raw WebGL. I wasn't sure if it would be possible to achieve this same effect in PIXI, or if PIXI is too high-level and I will need to use raw WebGL to achieve this? Is this solution too much of an overkill?

**Comment by ivanpopelyshev** [comment]
I'm working on better texts for pixi-v5, including porting stuff from v4 like pixi-sdf and pixi-rich-text. I'm aware of that thing. 

The problem is not overkill, its just that all those solutions are connected and we need one person to know EVERYTHING, then to code all that so people can choose between different techniques.

You certainly can port raw WebGL to pixi internal webgl api, its one of pixi use-cases - do your expert algorithm and use our expertise in everything else.

That particular technique also depends on AA, as far as i understand, and my current focus is plugin for better AA.

In general, it all depends on whether you are ready to do dirty stuff yourself or you want to wait when one of us does that :)

**Comment by smparsons** [comment]
Thanks for the response Ivan. I had a feeling that implementing this technique would be pretty difficult. I'm closing this question.
