### ISSUE TITLE
How does geometry batching/instancing work in pixi, as well as shader batching? I've found conflicting information.

### ISSUE THREAD

**Issue by Ekuju** [pixijs/pixi.js#6224]
I've found various questions about this but haven't figured out exactly what I'm looking for.

In my scene I have multiple meshes in different containers that will all have the same geometry instance, the same shader instance, and different uniforms. What I want to do is have 1 draw call for all my meshes since they all use the same geometry, and I don't want to swap shaders 
 on the gpu between all my meshes since they're all using the same shader.

In the pixi examples theres demos showing multiple meshes using the same geometry, and multiple meshes using the same shaders, but none of these demos explain exactly why you would do this. I assume it's to accomplish the perf improvements I listed above, but I've found closed issues here indicating that object instancing with custom shaders isn't really a thing unless you write your own batch renderer. This doesn't make much sense to me considering that would make the demos pointless (only saving very marginal memory, no perf gains), so I think this information must be outdated, but I want to confirm.

Does creating meshes using the same geometry instance automatically enable gpu instancing? Likewise does creating meshes using the same shader/filter instance batch the draw calls thus preventing the shaders from swapping out randomly on the gpu between draw calls?

**Comment by ivanpopelyshev** [comment]
Hello!

> What I want to do is have 1 draw call for all my meshes since they all use the same geometry, and I don't want to swap shaders
on the gpu between all my meshes since they're all using the same shader.

That's the basics:
```js
let prog = new PIXI.Program(...);
let shader = new PIXI.Shader(prog, uniforms);
```

Also if you use `PIXI.Shader.from(...)` with same vertexSrc,fragSrc for multiple shaders - it will actually use the same program.

PixiJS doesnt switch shaders if meshes use the same. As for other things, look at https://github.com/pixijs/pixi.js/blob/dev/packages/mesh/src/Mesh.js#L260

If you want to batch inside the same drawcall, which makes sense for hundreds meshes, you have to use custom batch renderer, like here: https://www.pixiplayground.com/#/edit/~tlXTadqt1qCEvHf~cMQE 

There's no gpu instancing in pixi in default shaders. Its possible, yes, you have to look in GeometrySystem and how geometry is actually bound.

Unfortunately , we cant provide full documentation yet because we are still changing this stuff and there has to be done big amoung of work to cover everything , i think ~100 examples. You have to look in sources.

As for filters, its completely different mechanism, I dont want to explain it all, i just say that usually there's always a shader and framebuffer switch, because, duh, its a filter. If its multipass filter, yeah, its possible to not switch shader multiple times.

> but I've found closed issues here indicating that object instancing with custom shaders isn't really a thing unless you write your own batch renderer
Yes, that was in v4. Now its much easier, but you still have to look in pixi internals just to be sure that it does what you want.

**Comment by ivanpopelyshev** [comment]
Also I advice you to use SpectorJS when you debug, to see that pixi is really optimizing those calls.
