### ISSUE TITLE
Loading plugins with modules & @pixi

### ISSUE THREAD

**Issue by PandawanFr** [pixijs/pixi.js#6227]
Hi, I'm not sure if this has already been discussed, I tried looking for it but could not find issues that specifically talked about this.

Since the pixi.js packages have been separated into various `@pixi/` packages, I was wondering what the best practices were for loading them. I saw the [module customizer](http://pixijs.io/customize/) which is very good. But it seems that you still need to import all of these packages at once when you want to use Pixi and other modules.

For example, I cannot do `import { CompositeRectTileLayer } from 'pixi-tilemap'`. Instead, I have to do this:
```js
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;
import 'pixi-tilemap';
// With that, I can then use the tilemaps like so PIXI.tilemap.CompositeRectTileLayer
```

This kind of breaks any attempt at modularity that can be provided with `@pixi/packages` or with basic imports like `import { Application } from 'pixi.js'`. So what are the best practices for this? And are there any plans on allow something like this:
```js
import { Application } from '@pixi/app';
import { CompositeRectTileLayer } from 'pixi-tilemap';
```

PS: If this is more of an issue with pixi-tilemap, I can report it on their repository instead. But IIUC, Pixi still uses side-effects internally.

**Comment by eXponenta** [comment]
Some plugins use legacy API for capability with pixi v4, and some plugins patch core classes (pixi-spine, pixi-projection, pixi-layer, pixi-pictures, pixi....) and can't be imported as es6 module.
Pixi-tilemap was write for pixi v3 and works perfectly still.

U can fork any plugins and rewrite it for clean es6 always:)

**Comment by ivanpopelyshev** [comment]
The thing is, i'm the maintainer of pixi-pictures pixi-layers and others. I don't know how to make them modular AND support old vanilla approach. I better ask people who use webpack to suffer rather than break compatibility. If you know how to make that - please show me on any of those extra modules :)

**Comment by PandawanFr** [comment]
Hmm, so off the top of my head I can think of this for exporting both as a module and to window. 
```js
export class ExampleClass {
  /* ... */
}

if (window.PIXI !== undefined) {
    window.PIXI.example.ExampleClass = ExampleClass;
}
```

But I'm unsure how the ExampleClass itself could access the Pixi library without having to use a bundler. (Since I'm guessing simply adding an `import { Application } from '@pixi/app';` wouldn't work for older setups that rely on window.PIXI instead of a bundler).

**Comment by ivanpopelyshev** [comment]
> But I'm unsure how the ExampleClass itself could access the Pixi library without having to use a bundler.

Yep, and its also in typescript. And I need typings. Now you get it :) That's why I'm waiting for our community webpack knowlkedge keepers to figure it out. I have many plugins and i cant just update one, i need a surefire way.

Probably, it'll be easier to make when main PixiJS repo will be fully on typescript with submodule typings.
