### ISSUE TITLE
pixi.js-legacy not work

### ISSUE THREAD

**Issue by 429365799** [pixijs/pixi.js#6256]
### Expected Behavior
My website run on virtual machine that without gpu, so I use pixi.js-legacy to use canvas not webgl.

### Current Behavior
Just new Application.
![image](https://user-images.githubusercontent.com/7577355/69944965-835a6700-1523-11ea-8468-900f7359c76b.png)

then:
![image](https://user-images.githubusercontent.com/7577355/69944911-5dcd5d80-1523-11ea-8265-c821097eb070.png)

### Environment

- **`pixi.js` version**: "pixi.js-legacy": "^5.2.0",
- **Browser & Version**: 66.0.3359.139
- **OS & Version**: window 7
- **Running Example**: _url_

and more infomations: 

chrome://gpu: 
![image](https://user-images.githubusercontent.com/7577355/69945279-33c86b00-1524-11ea-9fd3-e7da10061d4a.png)

chrome://flags:
![image](https://user-images.githubusercontent.com/7577355/69945327-493d9500-1524-11ea-8dbc-8b6f22443c36.png)

**Comment by ivanpopelyshev** [comment]
I bet its webpack issue again, did you update your pixi fomr 5.1? If so, remove node_modules, package.lock and `npm i` it all again.

**Comment by 429365799** [comment]
@ivanpopelyshev Thanks, but still not working. Here is my depandencies 
```json
"dependencies": {
    "pixi.js-legacy": "^5.2.0",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-scripts": "3.2.0",
    "uuid":"^3.3.3"
}
```
I use create-react-app then add pixi.js-legacy package and new PIXI.Application, thats all.

**Comment by 429365799** [comment]
OK, I use plain html 5, now it work.

![image](https://user-images.githubusercontent.com/7577355/70049581-f210f080-1607-11ea-9f14-0988d7446e2b.png)

so, the problem is webpack? how to use pixi.js-legacy in react app?

**Comment by ivanpopelyshev** [comment]
1. most hardcore pixi games are made without bundlers.
2. there is big number of react users who want to use pixi.

Right now we are at balance, but we dont have surefire solution that satisfies both. Also, I'm not expert on react/webpack and bundlers, I hate those new JS modules, so usually I answer "well, you use webpack, its your problem", but due to point 2 its not possible anymore.

My new default answer is "well, i tried, now wait for someone else from PixiJS team to answer or solve it yourself, in which case i'll share solution with other users" :)

**Comment by ivanpopelyshev** [comment]
I can help debug it in weekend but only if you provide whole app, because my knowledge ends at `npm i`  and `npm run start`.

**Comment by ivanpopelyshev** [comment]
Here, parcel works: https://codesandbox.io/s/white-glade-bycg3
Maybe its webpack problem.

**Comment by 429365799** [comment]
OK, This is my problem, I just delete package.lock.json but not delete yarn.lock. Sorry to take your time.
