### ISSUE TITLE
can I add numbers inside imagines on pixi sprite?

### ISSUE THREAD

**Issue by novaknole** [pixijs/pixi.js#6278]
This should be simple I guess.

I create sprite from texture. and show it on the screen. Now, what I want is for those creation of the sprites, I have for loop. and I want each of the sprite to have the index inside the image, such as (1,2,3,4,5,6). 

I don't want to have billions of images already containing these indexes.

Any clue?

Thanks.

**Comment by ivanpopelyshev** [comment]
I can give advices to certain word but not the whole phrase because I dont understand what you want :)

> I create sprite from texture. and show it on the screen.
One sprite per texture or multiple sprites per textures?

> to have the index inside the image
1. Add a Text child to Sprite.
2. Alternative: Hook texture uploading that way it goes to canvas first and renders a digit, then uploads canvas
3. `sprite.myAwesomeId = 3;` then use it in any place in your code

> (1,2,3,4,5,6).
1. Make a global variable that stores last issues ID.
2. If you need index per texture, store that counter inside texture and not globally.

> I don't want to have billions of images already containing these indexes.
Number of sprites is like 100000 maximum. Usually people have a few hundreds in their apps.
