### ISSUE TITLE
Feature Support: Renderbuffer multisampling support in WebGL2 machines

### ISSUE THREAD

**Issue by SukantPal** [pixijs/pixi.js#6288]
I think we should start supporting multisampling in our base render-textures. This would be great for the filter system: by using multisampling instead of rendering at higher resolutions, we could improve perfs.

**Comment by ivanpopelyshev** [comment]
Its architectural nightmare. Support of MSAA isn't enough for real projects, no one uses it even in threejs projects.

I have a draft plugin here, but i didnt port examples from my work to it: https://github.com/gameofbombs/pixi-blit/

It has two fallbacks for webgl1, but my current implementation is slow at work. I'm trying to make it work on real project, but we need shapes cache to make it super-fast on all browsers.

When its 100% super-ready I'll put it to pixi.

**Comment by SukantPal** [comment]
@ivanpopelyshev What do you mean by "shapes cache"?

**Comment by SukantPal** [comment]
@ivanpopelyshev I think you got the architectural side wrong in `pixi-blit`. A renderbuffer is not supposed wrap around a texture. Note that they are supported in WebGL 1, but only that multi-sampling isn’t available. I am working on creating a slightly tweaked addition of your work in pixi.js by creating a `RenderbufferSystem`. 

Then a frame buffer could have a renderbuffer attached, rather than only color textures. This system would be more robust - we could separate the “blit” part of the process from render-textures and framebuffers.

**Comment by ivanpopelyshev** [comment]
Just one ability to use MSAA is not enough because it seriously affects memory. and performance from MSAA is still not enough, well, its better than just x3 scale but bad anyway.

You have to detect all shapes that need AA in this frame, render them once in AA-ed buffer and then do one blit operation. If one buffer is not enough - do it multiple times with multiple blits, but result is collection of atlases.

I didnt put my current atlases in this because of one thing: even that is not enough. I'm working on better solution.

Your blitting API is good enough but i have an issue with it: people cant use it on apple devices and they'll never be. Without fallbacks its all just a chunk of academical code.  I don't know what to do with this one, because  yes, it can be merged, but what if it would be just dead piece of code like in threejs?

Lets ask @GoodBoyDigital.

**Comment by eXponenta** [comment]
This is will be dead code for Apple platform.
Multisampling doesn't must be inside core yet, i think.
It increase package size without profits.

And PIXI force webGL 1 on any mobile devices now.

**Comment by SukantPal** [comment]
I was thinking of using this to replace higher-resolution filters with MSAA if WebGL 2 is being used.

**Comment by SukantPal** [comment]
@ivanpopelyshev The PR isn’t finished, there will be a fallback; don’t worry about that.

**Comment by SukantPal** [comment]
@eXponenta Not all users run only on Apple devices, and a lot of stuff will run both on mobile & laptop. Using MSAA has perf “profits” if the user uses higher resolution filters.
