### ISSUE TITLE
pixi with websocket

### ISSUE THREAD

**Issue by brianwong3** [pixijs/pixi.js#6301]
Hey,

I am trying to use pixi with a websocket, but seem to be hitting a spike in GPU over a short period of time. 

First version
```onmessage: function (evt) {
if (evt.data instanceof ArrayBuffer) {
    let blob = new Blob([evt.data], { type: "image/jpeg" });
            let imageUrl = URL.createObjectURL(blob);
            camera.image.src = imageUrl;
            var texture = new PIXI.Texture(new PIXI.BaseTexture(camera.image));
            var bunny = new PIXI.Sprite(texture);
            camera.stage.addChild(bunny);
            camera.renderer.render(camera.stage);
        } else {
            alert(evt.data);
   }
}
```
Played around and maybe thought its due to me continuously creating a new texture, and sprites, and continuously calling addChild..

Changed it to create a single instance of a Sprite, call addChild once, and set the Sprite's texture with
```
var texture = new PIXI.Texture( new PIXI.BaseTexture(camera.image) );
camera.sprite.texture = texture
```

but all i get is a white screen. 

Any ideas ?

### Environment

- **`pixi.js` version**: _e.g. 5.20
- **Browser & Version**: _e.g. Chrome 79.0.3945.88
- **OS & Version**: _e.g. Windows 10
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
```
camera.image.src = imageUrl;
var texture = new PIXI.Texture(new PIXI.BaseTexture(camera.image));
```
that is asynchronous operation. You cant just expect `renderer.render` work after that, you have to wait when the png/jpg texture is parsed by browser, then pixi can render it correctly. Look at `onload` event of baseTexture or assign that callback to image itself.

**Comment by ivanpopelyshev** [comment]
Oh, the problem is in spike, right? Its PNG decoding + texture upload. use `createImageBitmap` to make it async operation, and pixi kinda has that already, you can enable it if you pass certain field in `ImageResource` constructor, just pass that ImageResource instead of Image to BaseTexture constructor.

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/ImageResource.js#L72

And here is `createImageBitmap` call, you can debug whether it goes there, by placing a breakpoint:
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/ImageResource.js#L188

There are only one or maybe two projects that use that async loading , so beware - you have to dig inside and create a new case for us, its up to you to check if that thing actually can be used :)

**Comment by bigtimebuddy** [comment]
I think the issue is that you’re continually creating a new Sprite/Texture/BaseTexture every time. Depending on how often that’s called with WebSocket, it can create issues for your browser with memory. The most ideal solution is to not recreate your objects every time. You could achieved this by redrawing to a canvas owned by a BaseTexture then updating the BaseTexture. If the dimensions keep changing, you’ll need to save a reference to that Sprite and call destroy (also destroy the BaseTexture by passing `true` to destroy).

**Comment by brianwong3** [comment]
just wanted to update..

i ended up with a "loaded" event on the BaseTexture and it solved my problem...
