### ISSUE TITLE
InteractionManager belongs on Application

### ISSUE THREAD

**Issue by laino** [pixijs/pixi.js#6307]
### Expected Behavior

No ``InteractionManager`` should be created on a ``Renderer`` and the user should be responsible for calling ``InteractionManager.update``.

``Application`` should take care of creating an ``InteractionManager`` and adding it to its own ``Ticker``. 
The same goes for ``AccessibilityManager`` by the way. Neither should be tied in with rendering - they have nothing to do with rendering a scene.

This would then allow us to get rid of ``AbstractRenderer._lastObjectRenderered``, which is an ugly to hack make this current weirdness work in the first place.

Finally this would give users more control over when 'hover' states are updated with ``InteractionManager.update``. For instance one could do so before each render - making the application appear more responsive (at the cost of an extra ``updateTransform()``).

### Current Behavior

An ``InteractionManager`` is created for each ``Renderer`` instance, even though all
it really cares about is the ``stage`` container of the application, resolution, and some element to listen for events on.

On top of that it does ``Ticker.system.add(this.update, ...)`` when it should just use the application ticker.

In my case I don't use ``Application`` at all and instead use ``Renderer`` directly with a custom logic to trigger rendering only when needed, but I get that pesky automatically created ``InteractionManager`` instance as well which adds to the global system trigger and suddenly
my browser is doing this at 60 frames per second:

<img src="https://i.imgur.com/u8xKBOB.png"></img>

Even though no work is being done! I'm not even rendering!

On a desktop that just causes mild CPU usage. On mobile say "goodbye battery life".

### Environment

- **`pixi.js` version**: 5.2.0

**Comment by eXponenta** [comment]
You always can build custom pixi bundle and disable any plugins include interation. 

https://github.com/pixijs/pixi.js/blob/dev/bundles/pixi.js/src/index.js#L34

**Comment by laino** [comment]
I still need the interaction manager and it is written as a Renderer plugin for now. I just want more control over  it.

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital and I discussed this very idea issue before v5 came out and recognized the architecture is not great here but could be easily changed later.

Most of this is vestigial—when interaction and accessibility were added we didn’t have Application or the concept of systems on Renderer. Architecturally, decoupling interaction from Renderer and making extract/prepare Renderer systems seems better. 

I’d love to remove Renderer plugins all together. @GoodBoyDigital also felt strongly about removing AbstractRenderer layer and find a mixin, non-inheritance approach for the CanvasRenderer.

Not everyone is pro-Application. There are some users who don’t require or want that convenience. Maybe because they are making a static Renderer or something highly customized with their own game loop. The question of why is interaction on Renderer is more that it seems core, most things made with Pixi will use interaction, not not all may use Application. I’m not personally swayed by this argument, but I’m aware some users have expressed. IMO, If someone is doing something customize, they can create their own interaction manager.

**Comment by laino** [comment]
@bigtimebuddy 

I was thinking more along the lines of making ``InteractionManager`` a standalone class
that takes an HTML element and a root element in its constructor, then making ``Application`` create an instance of that automatically just for convenience. I didn't mean to make the whole thing an ``Application`` plugin.

**Comment by ivanpopelyshev** [comment]
I made PR for more than a year ago, and @GoodBoyDigital rejected it. From my point of view - yes, it should be separate, it should be created like a Ticker. But its not that problem. 

Maybe PR that makes it optional if special flag is passed to renderer will succeed :)
