### ISSUE TITLE
Mouse Wheel event handling

### ISSUE THREAD

**Issue by erenard** [pixijs/pixi.js#634]
I'm making a game with a big zoomable map, and i want to zoom in/out with the pinch gesture or the mouse wheel.

As desktop environment are mostly driven by mouse and keyboard, and mobile environment is mostly tactile. Having the mouse wheel would give an equivalent to the pinch gesture.

**Comment by andrevenancio** [comment]
I just came across this "necessity" to target zoomable sprites. @englercj makes a valid point, specially because wheel events can fire several times in a split of a second which will slow down the renderer.

However, for future reference, is there a Rectangle class or something we can hook up and build something custom using the same methods you guys already use for detecting which sprite is being "clicked" ?

**Comment by Qix-** [comment]
Sorry to gravedig, I also have a use-case for scroll wheeling. In my case I can work around it, but I could see myself wanting it for more specific cases in the future.

This is pretty much the one mouse interaction that's been left out...
