### ISSUE TITLE
How to use PIXI.Point on node.js? Getting: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by stevemarksd** [pixijs/pixi.js#6446]
I have some isomorphic code (runs both on client and server side) and would like to keep using pixi.js library instead of some pixi-shim or similar. I don't need any server side rendering, I just need to use PIXI.Point. 

I'm getting:

ReferenceError: window is not defined

    at Module../node_modules/@pixi/polyfill/lib/polyfill.es.js

### Environment

- **`pixi.js` version**: current npm
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment]
PixiJS is not made with server in mind. You need something like https://github.com/Prozi/pixi-shim for it to work.

Why can't we accept PR's like https://github.com/pixijs/pixi.js/pull/4367 ? Because they limit contributions with new code restrictions. We are not ready for those particular limitations in our codebase.

**Comment by stevemarksd** [comment]
ok thanks
