### ISSUE TITLE
Graphics' unexpected comportement while tinting with 2d context.

### ISSUE THREAD

**Issue by LituOffi** [pixijs/pixi.js#6478]
### Expected Behavior
Only one graphics will be tinted (same as webgl context)
### Current Behavior
Every graphics are tinted
### Possible Solution
??
### Steps to Reproduce
tint some graphics from the same geometry
### Environment

- **`pixi.js` version**: 5.2.1 legacy and dev version
- **Browser & Version**:  chrome 80.0.3987.132
- **OS & Version**:  Windows 10.0.18362.720
- **Running Example**: [here](https://www.pixiplayground.com/#/edit/02gZJCxCpwYf9IqafPZs_)

**Comment by ivanpopelyshev** [comment]
Confirmed. https://www.pixiplayground.com/#/edit/02gZJCxCpwYf9IqafPZs_

**Comment by bigtimebuddy** [comment]
I don't see anything in that playground @ivanpopelyshev

**Comment by LituOffi** [comment]
use my running example @bigtimebuddy

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy somehow `_` isnt treated as a part of url

**Comment by LituOffi** [comment]
up :)

**Comment by bigtimebuddy** [comment]
Yes, looks like there's an issue with tint canvas:
https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js#L329

Tint shouldn't use `geometry.dirty` since tinting is a Graphics-level property. @ivanpopelyshev this looks like an easy fix, right?

**Comment by ivanpopelyshev** [comment]
It requires a bit of refactoring to store transformed tints in Graphics and not GraphicsGeometry. I can do it next week, there is just too much going on right now.

**Comment by SukantPal** [comment]
@bigtimebuddy @ivanpopelyshev  You have to use `geometry.dirty` because `updateGraphicsTint` essentially multiplies the tint with each fill/stroke color.

`_fillTint` and `_lineTint` is essentially a "cache" that `Graphics` is putting into `GraphicsData`. If multiple graphics share that cache, then both of their tints will be updated. To prevent that:

* make `Graphics` store `_fillTint` and `_lineTint` in an object that is tagged by an unique id. Something like `glTexture`. So access like `graphicsData[I].cache[this.id]._fillTint`

* calculate the fill-tint and line-tint whenever you are rendering. It doesn't look like an expensive operation.

Pick your poison :)

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev what do you think?

**Comment by ivanpopelyshev** [comment]
I think someone has to fix it :)

**Comment by ivanpopelyshev** [comment]
Option 3: don't store it in graphicsData at all. Store it in graphics, like we store batches for spriterenderer

**Comment by SukantPal** [comment]
@ivanpopelyshev If we store each transformed fill and stroke color in graphics, we need another array of data. That doesn't seem too good. I'll go with other option 2.

**Comment by bigtimebuddy** [comment]
Fixed! Thanks @SukantPal
