### ISSUE TITLE
How to handle large numbers of images in pixi 5

### ISSUE THREAD

**Issue by EloB** [pixijs/pixi.js#6495]
I found solution in this old issue from 2015:
https://github.com/pixijs/pixi.js/issues/1653#issuecomment-92098256

But I don't think it's up to date with Pixi 5. I couldn't find these functions in the latest version.

I'm having a image gallery with huge amount of images and my problem is that crashes after awhile navigating them because of memory issues. So how do I handle large amount of images now?

**Comment by ivanpopelyshev** [comment]
`baseTexture.dispose()` still exists.

> But I don't think it's up to date with Pixi 5. I couldn't find these functions in the latest version.

That's because no one cared to make new article on image disposing. And making huge app, I think that's because no one actually made those apps! You have a chance to become hero, learn it all and share with community!

You have to learn how PixiJS stores images. Learn about new texture Resources, experiment with them. How `TextureSystem` works. Look in `textureGC` thingy , sometimes it disposes old images. Pixi TextureCache is kind of stupid, if you dont track how it works - it can "hang up" some images and Javascript GC wont collect them.

Use devtools heapdump to see which elements ate all your memory. Cant use it if its over gigabyte - yes, use it before it gets over.

Do you know that html `HTMLImage` element can have both png and RGBA representations in and it drops RGBA when its not used for long time?

To make things more efficient in rendering you might use runtime atlases - like the one i had back in v4: https://github.com/gameofbombs/pixi-super-atlas . However, I've spent last 6 months to make good image cache, and that work is heavy! You can do it later if basic solution works fine.

If you somehow find miraculous html5 renderer that gives you ability to cache images efficiently and control memory - please share, I really need all the ideas for my super-vector-image-cache.

=====

If you want something more than general knowledge I give - please make a demo and specify exact problem. Yes, it could be that I already knew solution for your case, but this issue isn't lucky for us :(

**Comment by bigtimebuddy** [comment]
@Elob good response here from Ivan. Closing this. Let us know if your question isn’t answered and we can reopen. If you need more help please provide a specific example or link to your project. Thanks!
