### ISSUE TITLE
Shader screenshot

### ISSUE THREAD

**Issue by stla** [pixijs/pixi.js#6498]
Hello,

 I render an image with a fragment shader:

```
    var app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, antialiasing: false });
    app.resizeTo = window;

    let fragmentShader = document.getElementById('fragmentShader').textContent;
    let filter = new PIXI.Filter(null, fragmentShader);
    filter.uniforms.iResolution = {x: app.screen.width, y: app.screen.height};
    filter.uniforms.xmin = xmin;
    filter.uniforms.xmax = xmax;
    filter.uniforms.ymin = ymin;
    filter.uniforms.ymax = ymax;
    filter.uniforms.phase = 0;

    let container = new PIXI.Container();
    container.filterArea = app.screen;
    container.filters = [filter];
    app.stage.addChild(container);    
    document.getElementById('container').appendChild(app.view);
```

I tried [this technique](https://pixijs.io/examples/?v=v5.1.6#/demos-advanced/screenshot.js) (the `takeScreenshot` function) to take a screenshot. But I only get a black 1x1 image. Should I use something else to take a screenshot?

**Comment by ivanpopelyshev** [comment]
`extract.canvas(app.stage)` caculates bounds of stage and takes that part of screen. It doesnt see `filterArea`. You have to create renderTexture of appropriate size, use `renderer.render(app.stage, renderTexture);` and then `extract.canvas(renderTexture);` - that will ensure that size of output is correct

Why do you need a Filter in first place when you dont use container contents (uSampler uniforms) ?  Use mesh shader, its easier: https://pixijs.io/examples/#/mesh-and-shaders/triangle-textured.js

There are two ways of evading those kind of problems:

1. Help PixiJS team produces articles and examples for all user cases like this one, maybe make one example yourself and ask to publish it in wiki

2. Using pixijs cloned repo instead of just docs. Open it in separate IDE window and search for classes you use when you work with pixijs. If you read `Extract` class sources and tried to debug it a bit - you would see the problem. Extract itself isnt magic it is just a wrapper around other  pixi operations and WebGL `readPixels`.

**Comment by ivanpopelyshev** [comment]
OK. done: https://github.com/pixijs/pixi.js/wiki/v5-Hacks#extract

**Comment by stla** [comment]
Thanks a lot, I succeeded !!

I use `Filter` because I copied some code from somewhere, I didn't know another way to render a shader.

However, the image I get on the screenshot is symmetrical to the image displayed in the canvas.

This is the original image, displayed in the canvas:

![Capture du 2020-03-26 13-42-21](https://user-images.githubusercontent.com/4466543/77648327-4568cf00-6f68-11ea-8cc8-10ac120775b7.png)

And this is the screenshot:

![mandelbulb000 (14)](https://user-images.githubusercontent.com/4466543/77648512-8c56c480-6f68-11ea-81e7-dedc49deb94c.png)

**Comment by ivanpopelyshev** [comment]
FlipY stuff. It happens. Cant guarantee that we'll fix it, previous attempt to fix all problems in extract was 3 years ago and took a lot of my nerves. I believe you can fix it yourself, just go into extract code and switch some functions in prototypes

```js
PIXI.Extract.prototype.funtionXXX = function() { ... }
```

or reverse it manually after. Which function do you use, `canvas()` ?

**Comment by stla** [comment]
Thanks. Yes, I use `canvas`.

**Comment by MM19871987** [comment]
go away from nintendo and icloud account no more emails from github

**Comment by ivanpopelyshev** [comment]
Probably it detects `flipY` wrongly: https://github.com/pixijs/pixi.js/blob/3ffe52d29aedd79a5a281b4a6032e7c95f5ea98c/packages/extract/src/Extract.ts#L162

**Comment by bigtimebuddy** [comment]
Seems answered. Closing. @stla let me know if it’s not and we can reopen.
