### ISSUE TITLE
Interactivity is blocked by mask

### ISSUE THREAD

**Issue by TytiX** [pixijs/pixi.js#6509]
Hi,

There is something that i have tried and do not seem to work.

If i apply a mask on a container and this mask as child :
- it's a instance of container
- it's a Graphics instance with child
The interactivity on the masked container is blocked... but the render seems ok.

[Graphics container --> interactivity not working](https://jsfiddle.net/7cwh48ms/8/)

[Graphics --> interactivity working](https://jsfiddle.net/7cwh48ms/9/)

[Container mask --> interactivity not working](https://jsfiddle.net/7cwh48ms/10/)

**Comment by ivanpopelyshev** [comment]
oh right. 

Because container doesnt have `containsPoint` method and that's what we use when testing mask: https://github.com/pixijs/pixi.js/blob/3ef0c85bc30fbbfbcdbccf3f86ef3441440ad199/packages/interaction/src/TreeSearch.js#L87

I honestly don't know how to fix that fast, but workaround should be obvious ;) Add recursive containsPoint in your masked containers.

**Comment by ivanpopelyshev** [comment]
Also, whatever you do - make sure to check that place when you update pixi to newer version. 

That's a "hot" place of interaction, it can be easily changed by our contributors, especially when you already said there's a missing feature!

**Comment by JetLua** [comment]
Try my Interaction plugin：https://jsfiddle.net/qs7mknoj/

**Comment by TytiX** [comment]
This is my solution for now:
`export class MaskContainer extends Container {
  containsPoint(point: Point): boolean {
    for (const child of this.children) {
      if (typeof (child as any).containsPoint === "function") {
        if ((child as any).containsPoint(point)) return true;
      }
    }
    return false;
  }
}`

**Comment by ivanpopelyshev** [comment]
Added it here: https://github.com/pixijs/pixi.js/wiki/v5-Hacks#masked-elements-dont-work

**Comment by EskelCz** [comment]
I ran into this issue, can you please reopen it?

**Comment by shsiena** [comment]
I just ran into a similar issue when using masks with `inverse: true` on v8:

```ts
container.setMask({
    mask,
    inverse: true
});
```

When `container` has children with interactivity, the mask culls pointer events as if it was not inverted, rather than inverting the hit testing to match the visual inversion.

I was able to fix this by using `.arc()` instead of inverting a circle mask because I only needed a simple hole, but I feel like this is probably not intended behavior and would be a huge pain for anyone trying to work with a more complex mask and interactive children.
