### ISSUE TITLE
A bug by using ismobilejs because of the wrong api uesed

### ISSUE THREAD

**Issue by HypnosNova** [pixijs/pixi.js#6511]
### Expected Behavior
no mistakes when compiling
### Current Behavior
![image](https://user-images.githubusercontent.com/7953802/78137334-b40dc700-7457-11ea-9a53-a1d587564a52.png)

### Possible Solution
![image](https://user-images.githubusercontent.com/7953802/78137413-dbfd2a80-7457-11ea-8025-4dd50dc8d387.png)

### Steps to Reproduce
STEP 1: npm i pixi.js and then using 
import * as PIXI from './pixi.js'; 
And just write a hello world demo.
STEP 2: compiler the project and failed

### Environment

- **`pixi.js` version**: _e.g. newest
- **Browser & Version**: _e.g. any bloswers
- **OS & Version**: _e.g. any os
- **Running Example**:

**Comment by bigtimebuddy** [comment]
Please provide a repo the reproduces the issue. Your step are insufficient and the tools you’re using to compile probably matter.

**Comment by HypnosNova** [comment]
Using PIXI with react.
When compiling the whole project and run it on browser, we could see following error:
![image](https://user-images.githubusercontent.com/7953802/78205892-ef4bdc80-74cf-11ea-9d1b-4d8313335523.png)
I add a console to see what ismobilecall is.
And in browser console, we could see ismobilecall is an object that contains several APIs,
![image](https://user-images.githubusercontent.com/7953802/78205995-3639d200-74d0-11ea-86a3-2b7f84370d74.png)
That means after the project compiled, ismobilejs export default an Object instead of a function.

But strangely,  I create a new project and use rollup to compile, nothing went wrong, only in react project it went wrong.
So is it a bug in react tools? Or do you know any solutions to solve it

**Comment by notorigine** [comment]
I believe it is an issue with v1 of ismobilejs - see [issue #115](https://github.com/kaimallea/isMobile/issues/115). 

Using a complete different stack than React (Gulp, ES6), it is also causing an error when running my build process, because ismobilejs isn't transpiled when imported as a dependancy by @pixi/settings (see screenshots).

![Capture d’écran 2020-04-09 à 00 59 45](https://user-images.githubusercontent.com/4939395/78841629-29e8d400-79fe-11ea-863b-cb6f43e58fed.jpg)
<img width="650" alt="Capture d’écran 2020-04-09 à 00 59 23" src="https://user-images.githubusercontent.com/4939395/78841638-2d7c5b00-79fe-11ea-8092-acc0bfa0aaf6.png">

Any thoughts on how to solve this?

**Comment by bigtimebuddy** [comment]
Fixed, will try to get out a release ASAP.
