### ISSUE TITLE
Texture.from succeeds in generating a valid texture from an invalid relative URL

### ISSUE THREAD

**Issue by aaclayton** [pixijs/pixi.js#6514]
### Expected Behavior
Attempting to load a texture using a URL path which is invalid would raise an error. This seems to happen as expected with a fully qualified URL, but not with a relative path.

```js
const invalidFullURL = "https://domain/this/url/does/not/exist.png"
const invalidRelativeURL = "this/url/does/not/exist.png";
texFull = PIXI.Texture.from(invalidFullURL); // expected error and invalid texture -> works
texRelative = PIXI.Texture.from(invalidRelativeURL); // expected error and invalid texture -> surprise!
```

### Current Behavior
Loading a texture with an invalid URL produces a "valid" empty 1px by 1px texture.

```js
const invalidRelativeURL = "this/url/does/not/exist.png";
const tex = PIXI.Texture.from(invalidRelativeURL);
tex.valid; // true
tex.baseTexture.valid // also true
tex.baseTexture.width // 1
tex.baseTexture.height // 1
```

Of note, using `PIXI.Texture.fromLoader(invalidURL);` also succeeds despite showing a GET error, however in that case the resulting `tex.valid` is `false`.

### Possible Solution
Throw an error if the requested texture doesn't exist instead of mysteriously succeeding.

### Steps to Reproduce
See above code

### Environment
- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- **OS & Version**: Windows 10

**Comment by eXponenta** [comment]
Not use `from` for this cases,
When u use `from`, and texture should be always available, because `from` is asynchronous and updates when loaded, otherwise it has width/height is 1 and `valid`
We can't throw error, or return null synchronous.

**Comment by bigtimebuddy** [comment]
There's definitely room to improve error handling of invalid paths.

Here's an example that reproduces the issue:
https://pixiplayground.com/#/edit/ZuhIYMiHyaXovRtvD47Ph

I think there are two distinct areas that need to be addressed:
* We probably shouldn't be creating Textures from things that didn't load with Loader
* We don't have a great way to surface async errors resulting from inline-loading `Texture.from` 

The second one is a little tricky, but we could at least surface a console warning. Throwing errors is not a great option, because there would be no opportunity to catch/handle those. `Texture.from` like @eXponenta mentioned is designed to be largely synchronous.

I would strongly suggest using `PIXI.settings.STRICT_TEXTURE_CACHE` to forbid inline loading of resources with `Texture.from`). This at least allows you to catch errors from the loader using `loader.onError.add((err, loader, resource) => console.log(err))`

**Comment by aaclayton** [comment]
Thanks for the replies, definitely part of the issue is my own misunderstanding of what is the proper usage mode. Perhaps an additional component of the problem is that the API docs state that using the `.from()` method with an image URL is endorsed - and other areas of the docs also recommend using `Texture.from()`

> Helper function that creates a new Texture based on the source you provide. The source can be - frame id, image url, video url, canvas element, video element, base texture

Perhaps it would be good to factor out a couple different loaders since there's already `fromBuffer`, maybe `fromSource()` which could be synchronous and `async fromURL()` which could be explicitly used when you know you're loading from a URL. Return a Promise and reject it if the requested URL is not valid?

**Comment by bigtimebuddy** [comment]
I like `fromURL` as a distinct API that returns a Promise. :+1:

**Comment by eXponenta** [comment]
Texture resources `load` return promise.
We can redirect promise from resources to texture.
Something like this:
```
Texture.prototype.load = function () {
     return this.baseTexture.resource.load();
}

// prevent autoload 
const t = Texture.from({lazy: true})

await t.load()
```

**Comment by aaclayton** [comment]
Very cool, thank you @bigtimebuddy!
