### ISSUE TITLE
Q: Is it possible to set the transparency of an element through shader?

### ISSUE THREAD

**Issue by JetLua** [pixijs/pixi.js#6542]
fragment: 
```shader
varying vec2 vTextureCoord;
uniform sampler2D uSampler;

void main() {
  vec4 fg = texture2D(uSampler, vTextureCoord);
  fg.a = .0; // Why are elements still displayed
  gl_FragColor = fg;
}
```

https://jsfiddle.net/JetLu/4c5hwL89/

![1586582321912](https://user-images.githubusercontent.com/6738986/79036071-05a41780-7bf7-11ea-9d6a-afef79a434ac.jpg)

**Comment by ivanpopelyshev** [comment]
Yes it is! 

PixiJS uses premultiplied alpha. Here's where we discussed it week ago: https://www.html5gamedevs.com/topic/44978-shader-performances/

if you have `fg.rgb` and `fg.a = 1.0` to make it 0.5 you have to multiply whole fg

`fg *= 0.5;`

http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/

that's why some of my shaders have pm -> npm convertions: https://github.com/pixijs/pixi-picture/blob/master/src/OverlayShader.ts#L18

**Comment by JetLua** [comment]
@ivanpopelyshev Thanks
