### ISSUE TITLE
Should there be a mechanism to capture and handle unhandled errors in Ticker?

### ISSUE THREAD

**Issue by hubol** [pixijs/pixi.js#6547]
When an unhandled error occurs in a Ticker listener, there is no way to handle it. This causes the next animation frame to not be requested. Is this desired behavior?

You can see a smallish repro here: https://repl.it/@hubol/pixijs-unhandled-ticker-error

**Comment by ivanpopelyshev** [comment]
Yes, its correct behaviour, we just let it crash.

PixiJS does not have its own ways to handle because our users are more smart in that area and can make solutions suited for their projects. Its not a rocket science. Whole app & ticker stuff is a mashup, you should add your own things there: https://github.com/pixijs/pixi.js/wiki/v5-Custom-Application-GameLoop . 

I suggest to override one of ticker functions related to running RAF :)

If we add anything there, people will ask countless questions like "why dont you use this awesome class for nested errors" or "where do you save past errors" or "how connect google analytics to track my user problems". 

This will also be an indicator that PixiJS became a framework and we are avoiding that at all costs.

**Comment by hubol** [comment]
Cool, thanks!
