### ISSUE TITLE
Offset blend mode

### ISSUE THREAD

**Issue by TheOriginalArkless** [pixijs/pixi.js#6570]
To be honest, it is more that I need help, rather than there being an issue.
I've tried looking into blend modes but I did not find enough to create one myself.

What I am doing:
I am using the displacement filter to move everything in the entire view.
By default, everything is moved by 0x80 (r and g part of the color) towards the top left.
To move to the left, I just need to add to the r part of the color.
To move to the right, I just need to subtract from the r part of the color.
To move up, I just need to add to the g part of the color.
To move down, I just need to subtract from the g part of the color.
This works fine and looks really good!

The problem:
I want this movement to be dynamic (e.g. moving objects that may as well overlap).
To achieve this, I am rendering a displacement texture on every update.
However, I cannot find a blendMode (or other method) to add/subtract the difference between the texture color parts and 0x80.

Example:
1. The color 0x85 would move the scene 5 pixels to the left.
Two overlapping shapes with the color 0x85 should move the scene 10 pixels to the left.
2. The color 0x7B would move the scene 5 pixels to the right.
Two overlapping shapes with the color 0x7B should move the scene 10 pixels to the right.
3. Two overlapping shapes, one with the color 0x85 (example 1) and the other with the color 0x7B (example 2), should not move the scene (they should cancel each other out).

My personal favorite solution would be a blend mode that results in the following color - for all color parts: new color part = clamp(0, (source color part + (target color part - 0x80)), 0xFF)

If you give me more information about blend modes, I'm more than willing to create this myself.
If you know another solution I'd really like to learn more about it as well.

I've uploaded an example: http://f5701d018d0e19fa9fc64eeb1f20b5d2.epizy.com/

**Comment by ivanpopelyshev** [comment]
Intereseting. Yeah, need a blendMode for those sprites that can subtract a constant value. The problem is that we dont use [blendColor](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendColor) , so you have to make that call manually `renderer.gl.blendColor(...)` . 

However, you need to do it only once, because we dont use it ;) You can add one more blendMode that has correct webgl coefficients for subtracting constant color, it should be easy enough, let me know if you have problems with that.

Btw, I usually use my plugin pixi-layers and its `useRenderTexture` feature to add extra . Basically its doing the same as you do, but if you have many layers and effects like that - its better to use a plugin and keep your code clean.

**Comment by TheOriginalArkless** [comment]
Thanks for your answer.

Today I read a lot about webgl blending. I got the feeling that it's impossible to combine 3 things at once:
src color + dst color - const color

If you do know a way, please give me another hint.

I do have a workaround. However, it is comparably slow.
I can archieve the desired effect by splitting the one 2d offset sprite into 2. One blends additive and one subtracts.

**Comment by ivanpopelyshev** [comment]
You can make custom shader that subtracts color in it, easy to do with batch renderer, discussion is here: https://www.html5gamedevs.com/topic/44978-shader-performances/ . 

The problem is where exactly clamp wil be applied: after fragment shader or after blending operation? i dont know :)  I think there shouldnt be problem with negative values in fragment shader result.

In case it doesnt work - you can use float renderTexture instead of rgba (doesnt work on some devices). In that case you have to change `renderTexture.baseTexture.type = PIXI.TYPES.FLOAT` before you bind it first time.

**Comment by TheOriginalArkless** [comment]
Updated exmple with the slow double sprite version: http://f5701d018d0e19fa9fc64eeb1f20b5d2.epizy.com/

I've now read up a bit on shaders as well.
As far as I can tell, they are only applied on the whole scene/container, right?
If so, blending multiple shapes adds the basecolor multiple times.

I can also see a workaround for that:
I am not yet using the blue part of the textures. Putting 1 as blue color value I can later remove (blue * basecolor) from both red and green.

Do you foresee any problems I might run into with that method?


> Btw, 0x808080 is not the centrarl color, because its actually 128/255, not 0.5 , If you want to fix that , you have to change displacementFilter shader anyway - 128/255 instead of 0.5

That does not bother me at all. The displacement is applied globally and recentered by moving the scene by (displacementStrength * neutralDisplacementColor / 255). This means the scene is still centered correctly. 
neutralDisplacementColor not being exactly 255 / 2 just means that you can move objects 1/127 further to the left than to the right. That is a really rare occurrence and should be unperceivable in nearly all situations.

**Comment by ivanpopelyshev** [comment]
> As far as I can tell, they are only applied on the whole scene/container, right?

You can make custom batch shader that'll be used instead for all sprites you tag with `pluginName="myPlugin"` . In that shader you can specify`gl_FragColor = color - color.a * 0.5` . Here's how to invert colors with it: https://www.pixiplayground.com/#/edit/CMKvgOt-bvlCG4QHdswIP
