### ISSUE TITLE
Drawing a hole in a graphics object from a callback does not work

### ISSUE THREAD

**Issue by oteph** [pixijs/pixi.js#6576]
So i want to add holes to a `Graphics ` object as the consequence of a callback. Adding hole in a normal context works as expected. If i try to add the hole inside a (event) callback, the hole is not drawn.

Pixi version is 5.2.1

Example code:
https://www.pixiplayground.com/#/edit/9Aey72NS_KrO_-94pb_zj

**Comment by eXponenta** [comment]
It shouldn't works by design:)
Holes supports only for `drawPolygon` operator.
https://pixijs.download/dev/docs/PIXI.Graphics.html#beginHole

**Comment by oteph** [comment]
@eXponenta good to know, but using `drawPoylgon` does not fix the issue:

https://www.pixiplayground.com/#/edit/o4Vqd8t47cwSczGOyLcBh

**Comment by ivanpopelyshev** [comment]
You cant append a hole if shape was already rendered. In pixi internal logic render finalizes the shape. 

Even `graphics.geometry.invalidate()` cant help you.

However it should be easy enough to make a hack one you look inside graphics sources. We cannt do that for you right now because we are busy with our other vector stuff, all we can is to post your solution in pixijs wiki if you get it done, and maybe actually support the feature in future.

Another idea is to separate that graphics to background and holes , and draw holes with blendMode=ERASE, you can trigger cacheAsBitmap on it or manually draw to renderTexture each time it changes, or just put it inside AlphaFilter. I recommend to start experimenting with rnderTexture, blending and that kind of stuff, we have demos 

If you want holes in random places - yes, you need layered approach because triangulation does not support intersecting holes. If you want them in specific places - you can make holes and cover them with other graphics, then remove othe graphics elements.

SUMMARY:
1. wait for us to add this feature (loooong time)
2. debug graphics, make your own hack, i think its a few lines of code away
3. layered approach: renderTexture, blendModes, AlphaFilter. You can find issues like that here and in forums
4. premeade holes.

**Comment by bigtimebuddy** [comment]
You cannot append holes to Graphics after the fact. 

Basically, you have to redraw your shape using `clear`. Something like this:
https://www.pixiplayground.com/#/edit/bCeaLU29zFWl-LV06glQp

**Comment by oteph** [comment]
So the hacky solution for me was to spilt the the overlay into small tiles (normally my game is not tiled). While tiling i check if the tile is is visible or not, if not I don't draw the overlay tile . I redraw all tiles on any change to the overlay. 
To check if a tile is to be drawn or not i added a  'Set \<number>' that encodes a ID for each tile, so the performance should be reasonable.

This also fixed any potential issues with overlapping holes and keeps the state that has to move between client small.

If i have time i might still look into fixing the underlying issue.

**Comment by ivanpopelyshev** [comment]
yes, it usually something like that. 

No, in your case graphics holes are bad thing, draw holes with ERASE sprite/graphics-rect on separate renderTexture that covers your map.

You just assumed that holes are cheap and easy to draw - no its not, touching holes will affect tringulation. Graphics Holes are not for layering.

Look at renderTexture demos, and our drawing stuff. There are many threads both here in issues and in hrtml5gamedevs pixijs subforum about clearing/erasing stuff.
