### ISSUE TITLE
Latest Pixi not compatible with Angular 9

### ISSUE THREAD

**Issue by oshri** [pixijs/pixi.js#6578]
### Expected Behavior
Should Run Angular 9 with Pixi.

### Current Behavior
I manage to run but after 2s my GPU processor go up 100%
<img width="995" alt="Screen Shot 2020-04-22 at 10 52 30" src="https://user-images.githubusercontent.com/4602814/79956796-49194400-8489-11ea-8576-1184ad1ffd3d.png">
### Steps to Reproduce
Clone demo repo and run, npm run start

### Environment
<img width="1520" alt="Screen Shot 2020-04-22 at 10 52 20" src="https://user-images.githubusercontent.com/4602814/79956742-37d03780-8489-11ea-984f-6a770535cb39.png">

- **`pixi.js` version**: 5.2.1
- **Browser & Version**:  81.0.4044.113
- **OS & Version**: macOs Catalina 10.15
- **Running Example**: https://github.com/oshri/pixijs-5-angular-9

**Comment by bigtimebuddy** [comment]
Supporting Angular unfortunately is not a promise of this project. There are many third party integrations that we don’t have the expertise to debug, this is one. Will leave this open but we need help identifying if this is actually a pixi problem or not.

**Comment by jjwallace** [comment]
"Zone.js changes the prototypes of all async calls in the browser api (setTimeout, etc.) so that a) context can be shared across call stacks and b) that hooks can be emitted at the end of micro, macro, and event tasks.
Cool. And Angular?
Angular creates a new zone called NgZone which is a child of the root zone. This way when those end-of-task hooks are emitted, angular can run change detection on the off chance that a call has resulted in something, somewhere, changing. Which is great when you don’t have a ton of components. Not so much when you have lots."

-Source
https://medium.com/@hazterisk/how-3-lines-of-code-reduced-cpu-and-memory-consumption-by-13-b451de874701
