### ISSUE TITLE
BaseTexture#loaded event is not fired if source is loaded from memory cache

### ISSUE THREAD

**Issue by redbeardmickey** [pixijs/pixi.js#6583]
According to the doc `PIXI.BaseTexture#loaded` is fired

> when a not-immediately-available source finishes loading.

However, if the image at `imgUrl` is loaded from browser memory cache, `cb` is not invoked.

`PIXI.BaseTexture.from(imgUrl).on("loaded", cb)`

Is it still considered not-immediately-available in this case? Thanks much.

Environment:
OS: MacOS 10.15.4
Chrome: 81.0.4044.122
PixiJS: 5.2.2

**Comment by ivanpopelyshev** [comment]
This thing is default logic for handling assigned textures: 

https://github.com/pixijs/pixi.js/blob/c513e9287112ff8ed3f0326f700b731c204550b9/packages/sprite/src/Sprite.ts#L688-L694

Its done that way because most of the time you dont have to register the callback, and its easier to debug.

Your way looks more like Promise or something from reactive programming - yes, its fine, but no guarantee that whatever implementation of promise you use can just call `cb` right from this place.

**Comment by redbeardmickey** [comment]
Thanks @ivanpopelyshev for the pointer. I got tired last night and should have dug just a little bit deeper :).

In this case, I can check for `BaseTexture.valid` and resolve promise, or invoke callback immediately if `true`.
