### ISSUE TITLE
[Question] Standardizing anchor property for all Display Objects

### ISSUE THREAD

**Issue by st3v0** [pixijs/pixi.js#6593]
I'm not sure if this has been covered in the past, I was just looking over the API and how our team consumes it. I was wondering if any thought has been given to standardizing the `anchor` property across all display objects. Moving it from `Sprite` to `DisplayObject`.

It seems to be a pretty handy API that could be used for all display objects.

**Comment by ivanpopelyshev** [comment]
That requires fixed width/height for all objects or calculated layout.

width/height are not first-class citizens in pixi, they are calculated

for sprite and maybe a few other objects width and height match texture size multiplied by scale

**Comment by ivanpopelyshev** [comment]
Extra clarification: there are many things I want to use in pixi trees but if we put them there it will become bloated. I want better handling of transforms, color transforms, queue for changes in stage, added_to_stage , removed_from_stage events and many other things, that's why I'm pushing for changes that lead to possibility of making custom tree nodes.

**Comment by bigtimebuddy** [comment]
Thanks for the suggestion. We’ve gotten requests like this before and unfortunately we’ve had to say “no” for the reasons Ivan articulated. I’m going to close this.
