### ISSUE TITLE
Sprite/Container set width/height

### ISSUE THREAD

**Issue by cjsjy123** [pixijs/pixi.js#6609]
I found that setting the width / height property of sprite or container will change the scale, but should n’t the developer control the scale as an open property? This may happen if I change it before and the scale is not what I expected . I know that scale will participate in the calculation of the updatetransform of the transform, but is it better to set the width / height changed scale to use another point object. Developers can also accurately control the scale, and the calculation of the transform can also be calculated correctly

**Comment by SukantPal** [comment]
@cjsjy123 A container, by itself, has no intrinsic width/height. If you set the width/height, the only way for PixiJS to conform is to change the scale proportionally.

**Comment by cjsjy123** [comment]
First: `const tsdbunny = new PIXI.Sprite(texture);
tsdbunny.tint =0xff00ff;
tsdbunny.x =-100;
tsdbunny.y =-60;
setTimeout(()=>
{
    tsdbunny.width=10
    tsdbunny.scale.set(5,5)
},1000)

container.addChild(tsdbunny)`

`const tsdbunny = new PIXI.Sprite(texture);
tsdbunny.tint =0xff00ff;
tsdbunny.x =-100;
tsdbunny.y =-60;
setTimeout(()=>
{
    tsdbunny.scale.set(5,5)
    tsdbunny.width=10
},1000)

container.addChild(tsdbunny)`


But this will lead to a completely different result if the order of setting width and scale is exchanged, and this anomaly is not easy to find, but if the two attributes are independent of each other, this problem will not happen @SukantPal

**Comment by SukantPal** [comment]
@cjsjy123 You're correct. I think this is by design. The results are different because the result is dictated **by the last change to width or scale**.

1. In your first snippet, the final result is that the **scale of the sprite is 5x of the texture width/height**.

2. In your second snippet, the final result is such that the **scale of the sprite results in the final width of the sprite to be 10px, i.e. scale is set to 10/texture-width**.

Setting `width` or `scale` is essentially the an operation on the same thing. Think of it like this, **setting the width of the sprite does _not_ change the intrinsic width of the sprite**. It only appears to be width you've set because it is **scaled** proportionally by PixiJS.

---

The documentation [Container#width](https://pixijs.download/release/docs/PIXI.Container.html#width) does explicitly say that it sets the scale accordingly.

---

I think the confusion arises because you're thinking that setting the "width" on the sprite changes its intrinsic width. It only changes the width it appears on the screen (and that is achieved by changing the scale).

**Comment by cjsjy123** [comment]
But once I do not deal with it in settimeout, the result is consistent, because the change of their rendering results will eventually be triggered by ontextureupdate. This performance difference is very dangerous and difficult for developers to control, and the maintenance cost of developers increases Off @SukantPal

**Comment by bigtimebuddy** [comment]
@cjsjy123 Sorry if this doesn't meet your expectations, but this is part of the design of Pixi and has been for a long time. We are unlikely to change how this works.

In summary, width/height and scale allow users to adjust the size of their Sprite in real pixels (width/height) or percentage of original size (scale). Choose whichever unit best supports your use-case.

**Comment by cjsjy123** [comment]
Ok, but there is a problem that may need to be paid attention to, that is, the difference between when texture initialization is completed and when it is not initialized,
When the initialization is completed, set the width / height or scale, the scale will be calculated based on the last set value, but when the texture is not initialized, the width / height or scale set when the sprite is constructed, only the width / height will take effect, because ontextureupdate will set the scale based on _width / _height, resulting in different performance results. I do n’t see any explanation in this document. If width / height or scale is used at the same time, and the texture status is unknown (or when the sprite is loaded for the first time and the sprite for the same texture is loaded for the second time, With the same settings and different results, it is easy to have unexpected results. Does the official need to make supplementary explanations in the document?@bigtimebuddy

**Comment by bigtimebuddy** [comment]
Sure, that behavior can be clarified in the docs. It’s also good practice to preload images whenever possible avoiding this issue entirely.
