### ISSUE TITLE
Browser uses CPU instead of GPU for filters

### ISSUE THREAD

**Issue by manix** [pixijs/pixi.js#6672]
First thanks for the great work on this awesome project.

In my project I'm generating a bunch of circles and at some point it starts lagging a bit. I measured performance and it takes ~100ms to draw the stage which I know is probably not useful information at all since it may vary due to a thousand factors. 

I could have just reduced the number of particles and called it a day but I dug deeper. If I can help you to improve the library that would be great. 

So I tested it in Firefox and Chromium both of which have enabled HW acceleration and both seem to perform relatively equally bad. I monitored my processor and not surprisingly 1 core jumps to 100% until the stage is clear of particles, while GPU is chilling at ~15%.

I made a standalone snippet of the code in question which I'll add a gist to.

### Expected Behavior
Should see GPU usage spike not CPU or at least both.

### Current Behavior
Only CPU skyrockets

### Possible Solution
F me if I know

### Steps to Reproduce

Copy the code from the gist below into an HTML file and open it. Click the green area if you're brave enough and observe. Interestingly enough, if you comment out the color matrix and blur filters you can click as much as you want and the browser will not slow down, at least not noticeably.

https://gist.github.com/manix/cef245ce877b72f186f65c519a4d6670

### Environment

- **`pixi.js` version**: 5.something, latest as of writing
- **Browser & Version**: latest Firefox and Chromium
- **OS & Version**: Ubuntu 18.04
- **Running Example**: ^

**Comment by ivanpopelyshev** [comment]
colorMatrixFilter on each dot => many `bindFramebuffer` operations, getBounds() calculations and other things, both CPU and GPU intensive. 

Filter is very expensive, it also breaks batching. You can use SpectorJS browser extension to capture one frame and see what's going on with webgl commands.

You can use `tint` instead of brightness. If its not enough, you can use dark tint from pixi-heaven plugin. If even that is not enough, you can make your own batching shader using batch renderer https://www.pixiplayground.com/#/edit/CMKvgOt-bvlCG4QHdswIP or new plugin https://github.com/pixijs/pixi-batch-renderer/
