### ISSUE TITLE
Cannot read property 'baseTexture' of null

### ISSUE THREAD

**Issue by limpbizkit107** [pixijs/pixi.js#6726]
Hi,
Updating from 5.2.1 to 5.3.0 causes follwing error:

Uncaught TypeError: Cannot read property 'baseTexture' of null
    at new Spritesheet (spritesheet.es.js:58)
    at onImageLoad (spritesheet.es.js:313)
    at MiniSignal.dispatch (mini-signals.js:93)
    at resource-loader.esm.js:2256
    at next (resource-loader.esm.js:47)
    at Loader.push../node_modules/@pixi/spritesheet/lib/spritesheet.es.js.SpritesheetLoader.use (spritesheet.es.js:298)
    at resource-loader.esm.js:2254
    at resource-loader.esm.js:55

Interesting part of this issue is that the Texture from constructor is loaded and for some reason **this_texture** is **null**

Here are some screenshots: 
![error_pixi](https://user-images.githubusercontent.com/1725650/85856384-9c2cb180-b7c0-11ea-801a-15b219028e8e.PNG)

![error_pixi_1](https://user-images.githubusercontent.com/1725650/85856624-034a6600-b7c1-11ea-9bd0-8025b3626fb5.PNG)

Any suggestions?
I saw that you have made some changes to the Spritesheet class recently  is it possible that this may be some regression?

**OS**: Windows 10
**Browser**: Chrome Version 83.0.4103.116 (Official Build) (32-bit)

**Comment by bigtimebuddy** [comment]
One thing worth checking is to make sure you don't have any 5.2.1 packages lingering in your project (everything should be 5.3.0). This can happen if `@pixi/spritesheet` is importing a different `@pixi/core` package than the loader which would cause `texture instanceof Texture` to be false because `Texture` is referring to a different class.

Try cleaning your pixi packages and see if that helps.

**Comment by limpbizkit107** [comment]
Thank you @bigtimebuddy!

You ware right, clening my pixi packages helped.
