### ISSUE TITLE
Pixi to video 

### ISSUE THREAD

**Issue by iamappmaker** [pixijs/pixi.js#6731]
I had created the video animation maker using pixijs, outcome is awesome and i can play output smoothly.
Now the biggest problem i am facing is converting to webm. 
I have tried recordRTC and ccapture.
in recordRTC - frames dropping, freezes and if i use video in canvas, output get flickering
in ccapture - 10s recording gives 2s fast forwarded video. input and output video length varies with huge difference.

I have spent many days for this project. Please suggest me some idea to get video output (in any format).

**Comment by laino** [comment]
You get stuttering because you are trying to record the canvas "live". 
This is a bad idea and will fail horribly on underpowered hardware.
No video maker does this.

Look if you can use one of those libraries on a lower level.

What you want to do is create those videos on a frame by frame basis. 
Basically render a single frame with pixi, push that frame into the encoder,
advance your animations (update your scene), render the next frame with pixi,
then push that into the encoder and so on and so on.

**Comment by iamappmaker** [comment]
Thank you very much. I will try this now

**Comment by ivanpopelyshev** [comment]
@iamappmaker Long time no see! yeah, either its mediastream and it skips rames, either its webm-wasm or https://github.com/ffmpegwasm/ffmpeg.wasm

Pick your poison. Either way is a problem :)

**Comment by iamappmaker** [comment]
@ivanpopelyshev  I am using GSAP plugin for timeline. I used progress (only option available) to capture each frame in png and then i made video from those image. Converting each frame to png took more time so i need to try webp. Little busy in updating existing projects so i was very slow in completing this project.

**Comment by iamappmaker** [comment]
@ivanpopelyshev @laino  I manged to download sequence of images and converted to MP4 using ffmpeg. While downloading images (600 images for 10s video) browser crashes. 
Please suggest the correct way to do it.

**Comment by laino** [comment]
You don't want to export those images as some image format. You're spending time encoding that image as webp/png and decoding it again.

Your pipeline right now is basically: Raw Image -> WEBP -> Raw Image -> Video
What you want is: Raw Image -> Video

Grab the raw pixel data from the canvas. That should be much faster.

``webm-wasm`` says it has out-of-the-box support for the [``ImageData``](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) you get from canvas with [``canvas.getImageData()``](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData)

**Comment by iamappmaker** [comment]
@laino Thank you. 
Yes i tried this but i got error.

var canvas = document.getElementById('canvas');
var ctx = canvas.getContext('2d');   // Error : return null
ctx.getImageData(0, 0, 960, 960); // error because ctx=null

Also tried 
canvas.toDataURL("image/png"); // gives blank png image

Sorry to ask silly doubts

**Comment by laino** [comment]
Have a look at the first answer here, I think that ought to be the easiest way to go about it (unless you just use pixi's canvas renderer instead of webgl): https://stackoverflow.com/questions/40273927/read-pixel-information-from-a-webgl-3d-canvas-return-all-0-0-0-255

**Comment by iamappmaker** [comment]
I have tried this
var app = new PIXI.Application({ 
    width: width,      
    height: height ,      
backgroundColor:0xff0000,
preserveDrawingBuffer:true 
  });
playground.appendChild(app.view); 
var renderer = new PIXI.autoDetectRenderer(width, height, {antialias: true, transparent: false, preserveDrawingBuffer:true, backgroundColor	:0xff00f0});
renderer.autoResize = true;




 var offscreenCanvas = document.createElement("canvas");
  offscreenCanvas.width = width;
  offscreenCanvas.height = height;

  while(master.progress()<1.0){
    master.progress(current++ / frames);
    var renderTexture = PIXI.RenderTexture.create({width, height});
    renderer.render(app.stage, renderTexture);  
    var webglCanvas=renderer.view; // also tried document.getElementsByTagName("canvas")[0]
   var ctx =offscreenCanvas.getContext('2d');
    
   ctx.drawImage(webglCanvas,0,0);
    var imageData = ctx.getImageData(0,0, width,height);

    worker.postMessage(imageData.data.buffer, [imageData.data.buffer]);
    console.log(imageData.data);  // Uint8ClampedArray [] length 0
   
  }
This gives empty  Uint8ClampedArray [] with length 0

**Comment by laino** [comment]
What is that render texture good for? You want to render to the canvas, not a render texture.

This works for me: https://www.pixiplayground.com/#/edit/R2Wv96v4fGwcA-pvYmsRW

**Comment by lostrepo** [comment]
It's overall not a Pixi issue. I've decided to add few dimes while I'm lurking around Pixi and other rendering libs for some time, can't decide if convenience worth some perf penalties of this library (procrastination is heavy around starting gamedev stuff as a hobby).

First, you can always draw canvas with `webgl` context into another canvas with `2d` context (you can't switch between them for single canvas AFAIK Canvas API).
```javascript
// Pixi Canvas (probably with webgl context)
var canvas1 = document.getElementById('canvas');
// Our Canvas with 2d context (fastest element creation, for some reason I like it more than createElement, maybe because it's short and without perf penalty unlike most Array methods)
var canvas2 = canvas1.cloneNode(false);
var width = canvas1.width;
var height = canvas1.height;
canvas2.width = width;
canvas2.height = height;
var ctx2 = canvas2.getContext('2d', {
  // hint to browser to detach from main event loop
  // so browser can make some optimizations if it understands this hint
  desynchronized: true
});

// In render iterations
// draw webgl into 2d
ctx2.drawImage(canvas1, 0, 0, width, height);
// heaviest operation (it makes all custom image processing hard for 2d context in browser)
var imageData = ctx2.getImageData(0, 0, width, height);
```

Second, 
1. You detaching ImageData memory Buffer:
>     worker.postMessage(imageData.data.buffer, [imageData.data.buffer]);
2. After that you log Uint8ClampedArray view into empty buffer:
>     console.log(imageData.data);  // Uint8ClampedArray [] length 0
3. And Buffer exists now only in worker context where you can:
```javascript
self.onmessage = function (e){
  var data = e.data;
  if (data && data.byteLength > 0){
    var imageData = new Uint8Array(data);
    console.log(imageData);
    
    // encoding code
    
    self.postMessage({
      ok: true,
      msg: 'Successfully encoded',
      // can be returned for every frame or dumped in the end as a response to special command
      data: encodedData
    });
  } else {
    console.log('Wasted');
    self.postMessage({
      ok: false,
      msg: 'Got data: '+ typeof data +'; with byteLength: '+ data.byteLength,
      data: null
    });
  }
}
```
4. But bombarding worker with data in while loop will blow up memory and for mobile devices main<-->worker channel throughput
5. Better to use few functions for frame rendering iterations:
A. Launch worker
B. Receive OK status from worker.
C. If received encoded frame data - Save It (depends on encoder)
D. If all frames encoded Exit
C. Encode frame
D. Send buffer to worker
E. Receive not OK status from worker. Deal with it. Otherwise GOTO B.

I've done some MP4 building (H264 encoding + muxing with MP3 audio) in browser using manual Canvas 2d/webgl drawing+layer composition to eliminate overhead.
In the end browser was able to render frames (1080p to 2k) for 16 encoder workers - CPU threads (~99% load on each thread) and bottlenecked on actual encoding (For 1080p time depended on number of frames and was a bit faster than realtime video playback).
For `webm` encoding should be less CPU intensive if I'm not mistaken.

In NodeJS using node-canvas (2d only) and native module with encoder library exposing direct views into memory for writing ImageData Buffer and reading encoded result gave 3-4 times faster per CPU thread performance but server CPUs aren't cheap)

**Comment by sinapis** [comment]
@lostrepo we're trying to do the exact same thing, so far, we have very bad performance. Would really appreciate if you can share more info about your solution. Did you use pixi on nodejs? Which encoder library did you use? Anything at all would be very helpful

**Comment by sinapis** [comment]
getting ImageData is horribly slow. Sucks up my CPU.

**Comment by lostrepo** [comment]
@sinapis No, I didn't use `Pixi` on Node (I think it's possible but requires a lot of fake apis).
Encoder: `openh264` compiled as Node module (some task specific utils written in C/C++ to avoid multiple JS<->C/C++ border crossing).
2d renderer: `node-canvas` (partial webgl renderer for Node also exists but I didn't try it).

Main idea: shared memory region for encoder and 2d renderer (ideally both compiled into one Node module).
From JS (you can split task to utilize all cores that you have but your rendering must be frame based to avoid issues with synchronizing):
1. Configure renderer and encoder;
2. For each frame: Call rendering functions => encoder => save h264 stream data;
3. Free renderer and encoder memory;
4. Wrap h264 bitstream into MP4 container.
