### ISSUE TITLE
drawCircle radius parameter crashes Chrome tab with out of memory exception when value is Infinity (canvas renderer handles gracefully)

### ISSUE THREAD

**Issue by vleipnik** [pixijs/pixi.js#6748]
### Expected Behavior
When passing `drawCircle(x, y, r)`, the value of r should not crash the browser tab in any circumstance. An exception should be raised instead. Using the CanvasRenderer, the tab does not crash - this is only with WebGL.

### Current Behavior
The Chrome tab delivers an "Aw, Snap" error, when debugged reveals to be an OutOfMemory exception. The tab is not however out of memory, with plenty of heap space left over. 

### Possible Solution
Check for Infinity value and handle gracefully as a validation error.

### Steps to Reproduce
See https://www.pixiplayground.com/#/edit/UPx8TOsfb1d5IqL8mUKFc -- just replace the 200/1 to be 200/0, or Infinity and the tab will crash.

### Environment

- **`pixi.js` version**: PixiJS 5.3.0

- **Browser & Version**: Version 83.0.4103.116 (Official Build) (64-bit)
- **OS & Version**:  macOS Catalina 10.15.5 (19F101)
- **Running Example**: https://www.pixiplayground.com/#/edit/UPx8TOsfb1d5IqL8mUKFc

**Comment by vleipnik-consensys** [comment]
![Screen Shot 2020-07-06 at 9 14 03 PM](https://user-images.githubusercontent.com/33700506/86682041-2dc0ce00-bfce-11ea-913b-898b5826cb47.png)

**Comment by vleipnik-consensys** [comment]
![Screen Shot 2020-07-06 at 9 21 28 PM](https://user-images.githubusercontent.com/33700506/86682546-af186080-bfce-11ea-9c5b-b5430d2d2477.png)

**Comment by bigtimebuddy** [comment]
Thanks for the detailed report and example.

PixiJS does not validate user inputs, generally speaking. We rely on users to sanitize their own inputs and try to indicate in documentation valid ranges. In the future, we are planning to add inline asserts for debug builds, but we haven't hooked that up yet. The best fix for this is documentation note. But honestly, a radius of `Infinity` seems somewhat obvious an invalid size.

**Comment by vleipnik-consensys** [comment]
The main reason I reported this is because of the behavior of the crash, and the fact there was an obscure condition resulting in a divide by zero error sent our team on a wild goose chase for quite a while, due to the complexity of our app. Having the browser crash this badly, without any useful error messages was painful to debug.

It's an easy check to add and avoid a lot of heartache downstream for some your users. It was also interesting that there was varying behavior between the different renderers, which was unexpected. I was hoping to save some time for others by reporting this.

**Comment by bigtimebuddy** [comment]
Understood, thank you for reporting the error. Hopefully this will be helpful for others.

The problem is that there are _many_ places in Graphics, not just `drawCircle`, that would likely have this same result. For instance `drawEllipse` produces the same problem. Using `Infinity` to generate geometry is going to be a world of pain.

I'm going to leave this open, because hopefully it'll motivate me to actually support adding asserts to our builds without bloating the production build. If anyone wants to take a stab at adding **rollup-plugin-unassert** to our build process for dev browser builds, PRs welcome.

**Comment by vleipnik-consensys** [comment]
Thank you for the prompt replies - I understand the situation you describe, and appreciate the long-term consideration for asserts. Cheers, and thank you for your work on a great library.
