### ISSUE TITLE
Render 16 bit RGBA Texture

### ISSUE THREAD

**Issue by Mason-Chou** [pixijs/pixi.js#6758]
I'm trying to configure the gl renderer to render unsigned 16 bit RGBA images. I've read the documentation and it seems that all I have to do is extend the `PIXI.resources.Resource` class and pass it the correct configuration (internalFormat, format, type, etc...).

I'm running into an issue and I have no clue how to debug this. A warning message of this shows up whenever load my page.

`WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 0 is of type UINT, but the shader samples as FLOAT.`

The sample code is a bit too complicated to post here, but here's the gist of what I'm doing

```typescript
// this variables are part of the webgl2 enums.
// needed for the resource to know that i'm passing in UInt16 RGBA data.
const UNSIGNED_INT_TYPE = 5125;
const RGBA_INTEGER = 36249;

// Assume this array is filled with UINT16 values in RGBA format.
// width and height are made up for this purposes, assume it'll always match the data array length.
const data = new Uint16Array();
const width = 800;
const height = 800;

// Buffer16RGBAResource is the a custom resource that I've made.
// This class will set the internalFormat to be GL_RGBA16I
const resource = new Buffer16RGBAResource(data, {
    width,
    height,
});

const baseTexture = new BaseTexture(resource, { 
    format: RGBA_INTEGER,
    type: UNSIGNED_INT_TYPE,
    scaleMode: PIXI.SCALE_MODES.NEAREST,
});

// Use this texture to pass to the stage / sprite.
const texture = new Texture(baseTexture);
```

There might be a reason why Pixi.js doesn't support Uint16 or Uint32 data. Maybe someone with more experience with Pixi.js can help me understand why.

Thanks.

**Comment by ivanpopelyshev** [comment]
First time i try to use those webgl constants. 

How its usually done: we take existing webgl example, and put same constants and typed arrays to PixiJS :)

16-bit RGBA... hm, do you mean 16 bit per pixel or you want 5-6-5 stuff?

Imagine that you do it, what value should return `texture2D()` inside shader? Is it normalized vector4 (0-1), or actual vector4 of ints (0-65535) ?

**Comment by ivanpopelyshev** [comment]
i'm afraid we need full example. Please make it as simple as possible. zip-file, jsfiddle, or codesandbox is fine

**Comment by Mason-Chou** [comment]
My assumption is that texture2D should return a normalized vec4 (0 -1). I'm pretty new to WebGL, so I'm learning as I go. My buffer is in 16 bit per pixel. The original image is 16-bit grayscale, but I made it into a RGBA format for simplicity sake.

**Comment by Mason-Chou** [comment]
Here's a quick example I forked from this [comment](https://github.com/pixijs/pixi.js/issues/6436#issuecomment-591695313)

https://jsfiddle.net/w9zsmcbx/

If you open the console, you'll notice the warning message I'm getting.

**Comment by ivanpopelyshev** [comment]
This is my result, but it doesnt work: https://jsfiddle.net/Hackerham/ydoxj2r7/13/

Because https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/shader/utils/generateUniformsSync.ts#L56 doesnt have `usampler2D` (need same value as `usampler`)

You can rebuild pixi with that extra string and test it, I cant test this in a few hours.

**Comment by ivanpopelyshev** [comment]
Fixed !

https://jsfiddle.net/Hackerham/ydoxj2r7/17/

copy link to pixijs build from this fiddle.

1. I changed sampler type to `usampler2D`
2. `/65535.0` inside shader
3. alphaMode should be NPM (0) , so premultiplyAlpha wont be triggered. 

3b. Alternatively: `false` in corresponding place in upload. This is not recommended because `premultiplyTint` function somewhere on js side depends on alphaMode.
