### ISSUE TITLE
Properties from PIXI.TextStyle aren't all used in PIXI.bitmapText / PIXI.bitmapFont

### ISSUE THREAD

**Issue by Bouh** [pixijs/pixi.js#6789]
### Expected Behavior

The value of align from PIXI.TextStyle should be used in PIXI.bitmapFont and visible with  PIXI.bitmapText 

### Current Behavior

The value of align isn't visible and need to be setup in the bitmapText instead style of the font.
[See in sandbox
](https://www.pixiplayground.com/#/edit/hODHZEmb_ZMO-zYjwHyFo)

### Possible Solution
Also the style align is in PIXI.TextStyle and in the PIXI.bitmapText, why split the style.
I need setup my value on which? Style from textStyle or bitmapText ?

align, fontSize, letterSpacing have this issue.
Also there is a tint value on bitmapText and a fill color in textStyle, i use fill but tint is just useless ?

Also breakWords dosen't work with bitmapText.
[And font is broken when fontVariant is used.](https://www.pixiplayground.com/#/edit/SWMHiEwM1vyVuMp2bEr0_)

### Steps to Reproduce
[Playground with styles](https://www.pixiplayground.com/#/edit/hODHZEmb_ZMO-zYjwHyFo)
[Playground with fontVariant](https://www.pixiplayground.com/#/edit/SWMHiEwM1vyVuMp2bEr0_)

### Environment
v5.3.2

**Comment by bigtimebuddy** [comment]
PR is welcome to clarify the documentation for this.

**Comment by bigtimebuddy** [comment]
There are several other issues here: 

* the fontVariant thing looks like a bug
* `breakWords` is a feature request for BitmapText and not currently supported
* tint (on BitmapText) vs fill (on TextStyle): `tint` is dynamic and can easily be changed at runtime where fill is "baked-in" to the font and cannot be changed without re-generating the font.

**Comment by bigtimebuddy** [comment]
@SukantPal would you mind taking a quick peak at this:
https://jsfiddle.net/bigtimebuddy/9ptj1a04/

Unsure if this is a glyph measurement problem or a rendering problem. The font atlas looks okay.

**Comment by Bouh** [comment]
I would add some characters dissapear when the fontSize is big, i think it's the same issue than the fontVariant on width of the characters.
https://jsfiddle.net/Bouh/jwdhgecz/

**Comment by bigtimebuddy** [comment]
I actually think that's a bug having to do with fitting the glyphs on the atlas:
https://jsfiddle.net/bigtimebuddy/q1jdLoz3/ 
Looks like "m" doesn't fit. @SukantPal another one for you.

One easy workaround @Bouh is to increase the texture size:
https://jsfiddle.net/bigtimebuddy/42aw9gxh/

**Comment by SukantPal** [comment]
> @SukantPal would you mind taking a quick peak at this:
> https://jsfiddle.net/bigtimebuddy/9ptj1a04/
> 
> Unsure if this is a glyph measurement (data) problem or a rendering problem (BitmapText). The font atlas looks okay.

This is a glyph measurement problem. In fact, `BitmapFont.from` actually multiplies the width by 2 to ensure italic characters don't collide in the atlas.

https://github.com/pixijs/pixi.js/blob/651c54fccac7ec7a8e706ddce93fd58dffe00cb0/packages/text-bitmap/src/BitmapFont.ts#L402

The problem here is that italic characters have "overlap". If a character is 2px wide without italics, and it takes 4px with italics, the width is still measured as 2px. Why? That's because the "x-shift" is still 2px; the characters essentially overlap. BitmapText doesn't account for this difference.

<img width="119" alt="Screen Shot 2020-08-02 at 1 30 40 PM" src="https://user-images.githubusercontent.com/22450567/89128575-9b282780-d4c4-11ea-8404-12ef33e3dc1a.png">

The widths of the characters as measured by `TextMetrics` are same with or without italics:


<img width="187" alt="Screen Shot 2020-08-02 at 1 33 07 PM" src="https://user-images.githubusercontent.com/22450567/89128591-b5fa9c00-d4c4-11ea-966e-a3a987be5ab4.png">

**Comment by SukantPal** [comment]
> I actually think that's a bug having to do with fitting the glyphs on the atlas:
> https://jsfiddle.net/bigtimebuddy/q1jdLoz3/
> Looks like "m" doesn't fit. @SukantPal another one for you.
> 
> One easy workaround @Bouh is to increase the texture size:
> https://jsfiddle.net/bigtimebuddy/42aw9gxh/
> 
> ```js
> PIXI.BitmapFont.from("fontName", style, { textureWidth: 1024 }); // default is 512
> ```

https://github.com/pixijs/pixi.js/pull/6793
