### ISSUE TITLE
Many PIXI.AnimatedSprites causes too lag

### ISSUE THREAD

**Issue by KennethGomez** [pixijs/pixi.js#6814]
I have a project on which I have like **5k animated sprites** _(being 100 containers of 50 animatedSprites)_ being animated simultaneously but that drops to 40FPS, I tried using `cacheAsBitmap` on every sprite container but that stops the animation and bumps to 60FPS.

Any idea?

**Comment by ivanpopelyshev** [comment]
How many textures do you use?

Is this CPU or GPU problem? Did you look at webgl commands (spectorJS, yay!) or to CPU profile (regular chrome devtools)?

**Comment by KennethGomez** [comment]
It's GPU problem, can you explain me how actually can I find the bottleneck? I am kinda new on game development and it's kinda difficult.

I am using like 500 textures.

**Comment by ivanpopelyshev** [comment]
https://twitter.com/goshki/status/1294553707204554752

record 12-15 seconds of game gameplay in devtools profiler, take 10 middle, look at which functions are taking most of time. Make a screenshot of this thing, or save it, share with on random file hosting.

I cant get in details because im helping several people at the same time, sorry.

**Comment by KennethGomez** [comment]
Don't worry, any help is welcome, here do you have a single frame profiler [screenshot](https://prnt.sc/u01mtw).
