### ISSUE TITLE
Ticker.lastTime has wrong initial value

### ISSUE THREAD

**Issue by Prior99** [pixijs/pixi.js#6838]
The initial value of the ticker's `lastTime` is wrong.

```typescript
const app = new PIXI.Application({});

console.log("initial", app.ticker.lastTime); // ~500

const cb = () => {
    console.log("update", app.ticker.lastTime); // ~300
    app.ticker.remove(cb);
}

app.ticker.add(cb);
```

### Expected Behavior

The initial value is less than the value in the update loop (or -1 as per documentation).

### Current Behavior

The initial value is a random value higher than value in the update loop, hence the timer "decreases".

### Possible Solution

I have no clue.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/6O-lXs-O7SdM2CwFXU8H7

### Environment

- **`pixi.js` version**: 5.3.0
- **Browser & Version**: Chrome 85.0.4183.49, Electron
- **OS & Version**: Arch Linux
- **Running Example**: https://www.pixiplayground.com/#/edit/6O-lXs-O7SdM2CwFXU8H7

**Comment by SukantPal** [comment]
I don't see such a large delta, but this maybe due to the fact that `requestAnimationFrame` does not receive the same time as `performance.now()`. If you run the following code in a console, you'll see that the timestamps on each line don't match:

```js
const raf = ((t) => {
    console.log(t, performance.now())
    requestAnimationFrame(raf);
});

requestAnimationFrame(raf);
```

The ticker updates the timestamp based on requestAnimationFrame on each tick (https://github.com/pixijs/pixi.js/blob/064135e795dbfe7b53248ff457d71cb8536077ac/packages/ticker/src/Ticker.ts#L182), except when the first rAF callback is requested (https://github.com/pixijs/pixi.js/blob/064135e795dbfe7b53248ff457d71cb8536077ac/packages/ticker/src/Ticker.ts#L211)

@bigtimebuddy or @ivanpopelyshev might want to confirm this.

**Comment by SukantPal** [comment]
@Prior99 The documentation does say the initial `lastTime` is -1. You don't see that b/c the application ticker starts immediately when created, unless you pass `{ autoStart: false }`.
