### ISSUE TITLE
Programmatic click does not reach the pixi object

### ISSUE THREAD

**Issue by robert-gogolan** [pixijs/pixi.js#6931]
I can not click pixi objects programatically, does anyone else had this problem?

### Expected Behavior
Dispatching MouseEvent should trigger pixi object's click listener

### Current Behavior
Click event does not reach pixi object

### Steps to Reproduce
Open the fiddle and run it, a console log should appear after 3 seconds

### Environment
- **`pixi.js` version**: 5.3.3
- **Browser & Version**: Google Chrome Version 86.0.4240.75
- **OS & Version**: _e.g. Windows 10
- **Running Example**: https://jsfiddle.net/robert23mg/b9evm0uL/4/

**Comment by themoonrat** [comment]
So, I did this very thing recently in our libs.
I used pointer events then, so convering your example to do that, I get: https://jsfiddle.net/dv8Lbr20/1/ - which works perfectly.

I think the issue with yours is that, because your browser supports pointer events, PixiJS actually ignores mouse events, and just uses the pointer ones.

**Comment by bigtimebuddy** [comment]
@robert-gogolan did that answer your question?

**Comment by robert-gogolan** [comment]
Sorry, I wanted to reply and got caught with other stuff and then i totally lost track of this.
Yes, thank you very much @themoonrat for your time and help.
I think we can close the issue.

**Comment by Amansaxena001** [comment]
@robert-gogolan if i want to perform an agnostic click event on console using browser console that is also not registering on pixi level
