### ISSUE TITLE
[Question] How to determine id deeply nested child was added?

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixi.js#6958]
Hey guys, I am working on a layout engine for pixi that stops main application ticker and manually re-renders upon layout change. I wanted to ask if there are mechanisms in pixi that can help determine if deeply nested element was added to a container in order to signal to all parents of that element that they need to re-adjust their layout parameters. 2 sollutions I cam e up with were to ree-inable pixi's ticker and check for changes there or keep a json tree of all parent/child relations and then diff it with something like `JSON.stringify`, however both of these solutions would hit the performance.

Does pixi have some sort of event system or anything of that like to signal that child was added to a container, no matter how deep the parent/child tree is?

**Comment by andrewstart** [comment]
When a child is added, it emits an `"added"` event and its parent emits a `"childAdded"` event; Events in PixiJS don't bubble, however,  because that would hit your performance as well. 

Your best bet would probably be using only display objects from your layout engine (that subclass the PixiJS ones) that all interact with a single global event handler automatically when added/removed from the stage.
