### ISSUE TITLE
The CPU memory usage of 100,000 circles is too high.

### ISSUE THREAD

**Issue by Tangkkk** [pixijs/pixi.js#6989]
When drawing 100,000 or a million circles. How Do I Reduce the CPU Memory Usage?

**Comment by bigtimebuddy** [comment]
If you're asking this type of question, please provide a concrete examples of what you're trying to do. At the margins of performance, details matter a lot. This question is not worth answering without those details.

Also, there are a few past issues that resemble this question. Please do a little digging first through old issues. I'm sure you'll find some useful information.

**Comment by Tangkkk** [comment]
> 如果您问这种类型的问题，请提供您要尝试做的具体示例。在性能方面，细节至关重要。没有这些细节，这个问题就不值得回答。
> 
> 另外，过去有一些与此问题类似的问题。请先对旧问题进行一些深入研究。我相信您会找到一些有用的信息。

I create a geometry object, use geometry.drawShape(shap, fillStyle, lineStyle, matrix) to add circles or line segments, and graphics = new PIXI.Graphics(geometry). Then, convert it to a sprite image and add it to the PIXI object. The CPU usage reaches 1 GB.

**Comment by ivanpopelyshev** [comment]
It should work. Please provide a demo.

**Comment by eXponenta** [comment]
Doesn't should.
Because this will allocate a a lot of VRAM If enabled cacheAsBitmap on all of 100k circles separately.

Then, any case, case of 100k circles is not solved naive because 1 circle can allocate buffer at 100+vertices (100 * (2 + 2 + 4 + 1) * 4 = 3600 bytes).
100k circles already allocated a 360mb in vram.
Welcome!

**Comment by SukantPal** [comment]
Please close this thread if you're done @Tangkkk. 🙏
