### ISSUE TITLE
FAIL_IF_MAJOR_PERFORMANCE_CAVEAT on Linux FF83

### ISSUE THREAD

**Issue by SnowyCoder** [pixijs/pixi.js#7054]
Hello, I would like to suggest setting the default value of [FAIL_IF_MAJOR_PERFORMANCE_CAVEAT](https://pixijs.download/dev/docs/PIXI.settings.html#.FAIL_IF_MAJOR_PERFORMANCE_CAVEAT) to false. I know it has been already discussed in older issues but a recent problem has risen: As discussed [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1679671#c14) in FF82 and below the flag was being ignored on Linux and now a lot of users will see their app crash (unless they have enabled the unstable Servo rendering or they have disabled the flag globally in about:config).

Citing a mozilla developer on [a bugzilla discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1679671#c14): `The answer for frustrated website authors is straightforward: Don't ask for failIfMajorPerformanceCaveat: true unless you do want context creation to fail for many many users.`. This is not a major issue since most Linux users will be experienced enough to sort this out for themselves, but still it's not ideal.
(I removed the issue template as this is not a regular bug)

**Comment by themoonrat** [comment]
So, this is an interesting one. 
On one hand, we put it to false by default, WebGL works for more users, but then more will complain about bad performance.

Hmmmm.

You could almost make a case for... if you are _just_ using a WebGL renderer, you'd prefer it to be 'false' so as many users can enjoy the content, no matter what the cost. But if you're using pixi-legacy, like I do, then you'd prefer it to be 'true' because there's already a good fallback with a bit more guaranteed performance in the canvas renderer.

Which doesn't help much decide one way or the other!

**Comment by SnowyCoder** [comment]
In most of the Linux machines in which it fails it does not mean that the performance is that low, in mine for example it is lower than running the same app in chromium but it still achieves 60FPS with a lot of custom shaders and multiple passes. Reading from the [specs](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2) and from the mozilla discussions I found online it seems like the rendering still happens on the GPU but at each frame the buffer is read back to the CPU because it's needed for the compositor.

Running some benchmarks with [the aquarium](https://webglsamples.org/aquarium/aquarium.html) on my machine (GTX 1660, as an example) firefox can achieve 20FPS with 5'000 fishes and chromium still holds a stable 60FPS with 10'000 fishes, the GPU usage goes to 40% with both of them tough so it does not seem to be completely rendered on the CPU.

I'm not a developer on the project but I would suggest a more complex strategy than just a boolean. If you can use a three-value setting with 'auto' as the default you can do some more complex strategy to make the app work in most systems out of the box.

As an easier fix I would suggest to just print a warning message on the console to let the developer know that the performance might be bad and continue running the app anyways. No developer has reported a bug back when `failIfMajorPerformanceCaveat` did not fail so I don't think that they will do it now.

**Comment by SparK-Cruz** [comment]
Same issue here but I don't see how performance is degraded:
![image](https://user-images.githubusercontent.com/1179000/101554930-5c384000-3996-11eb-8524-a80e67ee75b2.png)

**Comment by themoonrat** [comment]
I think I'm convinced to swap the flag over, on Linux at least. We make best efforts to get WebGL working, performance issues then become the developer to debug.

What would be good is if we could find evidence in Windows or Android or iOS of what happens, performance wise, if we set this to false. Because on Linux it's more a detection for a certain compositor feature, rather than actual performance. Is it the same elsewhere?

**Comment by SnowyCoder** [comment]
Thank you,
Closed by: #7068
