### ISSUE TITLE
Event priority for example pointertap event before mousedown

### ISSUE THREAD

**Issue by hvbnet** [pixijs/pixi.js#7103]
Hi

I need to handle mouse click and mousedown/mousemove/mouseup to move Sprite from A to B (user can do it by drag and drop or click Sprite to select it and then click on location B to move)

but problem is that click event fire after mousedown and mouseup.

How to handle this issue?

**Comment by andrewstart** [comment]
1. On mousedown -> save mouse down position, start listening for mouse up & mouse move
2. On mousemove -> if mouse has moved from the starting position more than a specified threshold, activate dragging state, and mouseup will end the drag.
3. On mouseup -> if mouse has _not_ moved more than the threshold yet and thus isn't dragging, activate sticky-click. Otherwise, complete your drag.
