### ISSUE TITLE
Setting PIXI.settings.RESOLUTION breaks iOS Webview

### ISSUE THREAD

**Issue by IljaDaderko** [pixijs/pixi.js#7115]
### Expected Behavior
I have been using pixi successfully via [Capacitor](https://capacitorjs.com) (Runs web apps in a webview, kinda like cordova did). I recently added ability to cache some complex elements via `cacheAsBitmap`, this worked but cached content was blurry. I was able to fix it by setting `PIXI.settings.RESOLUTION = window.devicePixelRatio`. This worked while I was testing in browser on my mac, but was broken when I tested my app in iOS simulator and actual iOS Device (iPhone XS).
Note: No issues arise when setting `Application` resolution and `PIXI.settings.FILTER_RESOLUTION`. All of this works good.

### Current Behavior
1. This is how scene looks on iOS simulator and actual device without **`PIXI.settings.RESOLUTION`**

<img width="341" alt="Screenshot 2020-12-31 at 12 02 17" src="https://user-images.githubusercontent.com/3154053/103405556-369af280-4b60-11eb-852e-7bed8c069159.png">

2. This is how scene looks on iOS simulator with `PIXI.settings.RESOLUTION`. Notice how only text works, text is a `BitmapFont` / `BitmapText`

<img width="351" alt="Screenshot 2020-12-31 at 12 04 16" src="https://user-images.githubusercontent.com/3154053/103405619-5fbb8300-4b60-11eb-92f9-75152ff0877a.png">

3. On actual iOS device with `PIXI.settings.RESOLUTION` set, application crashes with following error
```
2020-12-31 11:52:23.769068+0200 App[9255:2862777] [ProcessSuspension] 0x1078c5000 - ProcessAssertion: Failed to acquire RBS Background assertion 'ConnectionTerminationWatchdog' for process because PID is invalid
2020-12-31 11:52:23.771697+0200 App[9255:2862777] [Process] 0x103037618 - [pageProxyID=6, webPageID=7, PID=9256] WebPageProxy::processDidTerminate: (pid 9256), reason 3
2020-12-31 11:52:23.793303+0200 App[9255:2862777] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
2020-12-31 11:52:23.793385+0200 App[9255:2862777] [ProcessSuspension] 0x1078c5040 - ProcessAssertion: Failed to acquire RBS Background assertion 'WebProcess Background Assertion' for process with PID 9256, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
2020-12-31 11:52:23.802323+0200 App[9255:2862777] [Loading] 0x103037618 - [pageProxyID=6, webPageID=7, PID=9256] WebPageProxy::dispatchProcessDidTerminate: reason = 3
2020-12-31 11:52:23.816338+0200 App[9255:2862777] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
2020-12-31 11:52:23.816590+0200 App[9255:2862777] [ProcessSuspension] 0x1078c5100 - ProcessAssertion: Failed to acquire RBS Background assertion 'WebProcess Background Assertion' for process with PID 9256, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
```

### Possible Solution
Not sure. I am also not entirely sure if this is issue related to pixi or `WKWebView` itself, but I decided to start here. 

### Steps to Reproduce
You'll probably need to test this in XCode and set `PIXI.settings.RESOLUTION = window.devicePixelRatio`.
I also use render textures as showcased below, doing so helps me to ensure assets are always ready in the game without any delays / extra work. Might be possible cause of the problem as well?

```ts
      // Create a loader, name is a string, image is an image source
      loader.add(name, image);
      loader.load((_, resources) => {
        // Get texture
        const texture = resources[name]?.texture;
        
        if (texture) {
          // Create sprite from texture
          const sprite = new Sprite(texture);
          const { width, height } = sprite;
          // Create render texture
          const renderTexture = RenderTexture.create({
            width,
            height
          });
          // Render the render texture
          renderer.render(sprite, renderTexture);
          // Create Spritesheet using renderTexture
          const sheet = new Spritesheet(renderTexture, json);
          // sheet is then stored and used as a texture source for all sprites in a game
        }
      });
```

### Environment
- **`pixi.js` version**: 5.3.7
- **Browser & Version**: iOS WKWebView
- **OS & Version**: iOS 14.3
- **Running Example**: -

**Comment by IljaDaderko** [comment]
iOS device crashing, leads me to think that there might be possible memory usage issue, however I monitored it without `PIXI.settings.RESOLUTION` and app was running within 45-50mb range (this is with application resolution set to `devicePixelRatio` so in case with iPhoneX it was 3), so unless that setting causes massive spike in memory usage, this might not be the case.

**Comment by themoonrat** [comment]
So, a bit of a wild stab in the dark, but it _might_ be that your generated resolutions are becoming too big.
I personally advise against using devicePixelRatio ... because, say you have your renderer size at 1280x720. Now you use devicePixelRatio on top of that, and suddenly you're rendering and generating textures at 4k. Which 
1: is massively overkill for phones with just small screens (until recently, iphone was only 720p!) and
2: If you're generating render textures, they may go over the texture size limits that WebGL supports on that device  (look at max texture size on https://webglreport.com/)

**Comment by IljaDaderko** [comment]
@themoonrat Could very well be, perhaps I might be approaching this wrong, I will outline how everything is set up at the moment, may you correct my approach if you see anything odd please?

1. I have a `4096x4096` png with images for all my graphics. Each individual image within this png is big, so it looks crisp when scaled down i.e each image satisfies `@3X`
2. I Then create a sprite-sheet from this via [TexturePackeer](https://www.codeandweb.com/texturepacker)
3. I then load this image as demonstrated above, using `renderTexture`
4. Initially this made my app look blurry, so I changed my `PIXI.Application.resolution` to use `devicePixelRatio`. This worked great, ran smoothly, memory usage was low, phone was not heating up, the only issue I had was when using `cacheAsBitmap`, that content looked blurry.
5. When I changed `PIXI.settings.RESOLUTION`, on my mac everything looked sharp again, but iOS devices started crashing.
6. I then removed `PIXI.Application.resolution`, but issue still persisted as I kept `PIXI.settings.RESOLUTION`

I assume I am doing something wrong starting with step `4`. Is there any other way to ensure that containers that are `cacheAsBitmap` remain sharp, without altering resolution?

**Comment by bigtimebuddy** [comment]
How big are the containers that you're cacheAsBitmap on? This could allocate a lot of memory if you're using it a lot at such high resolution and dimensions. Try calling getBounds to see dimensions and calculate memory needed. Also, do you need cacheAsBitmap in your circumstance? It's not always a huge performance win that it seems to be.

**Comment by IljaDaderko** [comment]
@bigtimebuddy Not big at all, my use case is following - I have a game world map that is scrollable vertically and horizontally. On this map I have "map pins" place, each pin consists of 4 sprites + bitmap text (4 sprites are needed to relay different map location states to the user visually).

Once I place few of these pins on the map, There is noticeable scrolling lag. If I cache each pin as bitmap, it goes away, so the only issue that remains is that they are blurry, hence my usage of `PIXI.settings.RESOLUTION`.

That said, even if I don't `cacheAsBitmap` anything in my app, but still keep that resolution setting, it still crashes.

I'm trying to understand why, what would the difference be between setting `Application.resolution` and `PIXI.seettings.RESOLUTION`? Application one works perfectly, even on @3x display, as I mentioned before, memory usage is low, power usage is low, everything besides `cacheAsBitmap` looks fine.

**Comment by IljaDaderko** [comment]
As a side question, if each individual image in my sprite-sheet png is sized at @3x, so for example game header image is 900x150, but on device itself it only occupies 300x50 space. Does setting resolution scale that original graphic to be 2700x450 by any chance, when texture is created?

**Comment by bigtimebuddy** [comment]
I think we’ve gotten to the point where we need a running isolated example. Can you create something that crashes with the fewest elements? It’s hard to debug from your description alone.

**Comment by IljaDaderko** [comment]
@bigtimebuddy Alright, I created very very minimal reproduction here https://github.com/IljaDaderko/pixi.js-7115
I didn't go as far as creating ios project and adding webpack (if you need those do let me know, I will try to get them set up by tomorrow or so, as there are quiet a few things involved).

I also added exact replica of my sprite-sheet, I just made all textures pink, for content copyright purposes.

`index.js` file contains code that is breaking on ios, it works if `PIXI.settings.RESOLUTION = devicePixelRatio` line is commented out.

Here are results I got from that minimum replica code:

1. Without `PIXI.settings.RESOLUTION = devicePixelRatio` app renders correctly in simulator and actual device
<img width="370" alt="Screenshot 2021-01-01 at 14 35 15" src="https://user-images.githubusercontent.com/3154053/103438804-ca8fbb80-4c3f-11eb-91c9-5fe83dbf91ce.png">

2. With `PIXI.settings.RESOLUTION = devicePixelRatio` in simulator, nothing is rendered
<img width="371" alt="Screenshot 2021-01-01 at 14 36 08" src="https://user-images.githubusercontent.com/3154053/103438807-d7acaa80-4c3f-11eb-903f-45c84e14604f.png">

3. With `PIXI.settings.RESOLUTION = devicePixelRatio` on actual device, an error is thrown same as in original issue

**Comment by bigtimebuddy** [comment]
Awesome, thanks.

**Comment by IljaDaderko** [comment]
While the investigation is ongoing, I wanted to ask if it is possible to apply this type of resolution to a single container as opposed to globally perhaps?

`Application.resolution` satisfies all my needs in terms of making app appear sharp on retina devices and I only have few containers that use `cacheAsBitmap` that need `PIXI.settings.RESOLUTION` to appear sharp. As far as I can tell there is no method on `Container` itself to set individual resolution, but perhaps there is a trick to do so?

**Comment by themoonrat** [comment]
It's definitely due to going above the max support texture size.
For example, forcing devicePixelRatio to 1, for both PIXI.settings.RESOLUTION and resolution means that when I do
`sprite.texture.baseTexture` the realWidth and realHeight are 2040x3950 - which matches the original spritesheet correctly
But set to 2, and now the real dimensions are 7900x4080. 
Set to 3, and you can see how we're way beyond the 8096x8096 limit within iOS for max texture size (desktop devices often support up to 16384x16384, which is why the Mac works fine).

In your example, there is an optional parameter for 'resolution' when manually creating a render texture.

```
const renderTexture = PIXI.RenderTexture.create({
    width,
    height
});
```

Could become

```
const renderTexture = PIXI.RenderTexture.create({
    width,
    height,
    resolution: 1
});
```

But this doesn't help you with cacheAsBitmap. And it'll decrease the quality.

You _could_ try
```
PIXI.settings.RESOLUTION = 1;
sprite.cacheAsBitmap = true;
PIXI.settings.RESOLUTION = devicePixelRatio
```

It's not graceful, but it might work? But again, that's likely to decrease quality. Maybe you could set the resolution to higher than 1, but less than devicePixelRatio, as a compromise.

We have no other way to control in-built 'cacheAsBitmap' resolution. It'll always use that top level one.

@bigtimebuddy We already knew there was confusion between the resolution property when creating a renderer, and the top level one. Dunno how we 'combine' them. Either deprecate the one passed through as constructor? Or if there is one passed through constructor, it always overwrites the top level one, to ensure they always match? I can't think of a reason why these 2 settings are different. Might be worth putting on priority list for v6 to at least point in a certain direction for the future?

I've had a play, and the only way to guarantee that cacheAsBitmap looks the same quality as the renderer... is how things currently are. So there's no optimisation we could put into cacheAsBitmap to, for example, always have the resolution at 1. The render texture resolution _must_ match the render resolution, or else you'll lose quality.

**Comment by themoonrat** [comment]
So after all that @IljaDaderko  - how about this as a suggestion. I still don't believe you need a full on x3 resolution on such devices. x2 will be plenty, imo. So rather than just using devicePixelRatio outright, which could take you into 4k resolutions and such, which is massively overkill, try something like
`const devicePixelRatio = window.devicePixelRatio > 1 ? 2 : 1; `
So your app is either x1 resolution or x2 resolution, and that's it.

**Comment by IljaDaderko** [comment]
@themoonrat Ok, so with this further explanation I w as able to achieve desired result by combining these:

1. Set `PIXI.settings.RESOLUTION = devicePixelRatio`
2. Set optional `resolution` argument of `RenderTexture` to 1
3. Remove `resolution` option from my `Application` completely

This results in a sharp looking app as well as all of my `cacheAsBitmap` textures looking sharp as well. I assume you need your sprite sheet exported at  `@3x` for this approach to work as well.

As far as I can tell memory / power / cpu usage is also good 👍 

So this solves it for my personal use-case, I assume issue can be closed, or do you guys want to keep it open, as there was a mention of some clarifications / deprecation of related functionality in v6?

And just one final question, when I create `cacheAsBitmap` container, it does not re-create / copy that massive sprite-sheet graphic, it only creates image of what's inside of the container correct?

**Comment by themoonrat** [comment]
`And just one final question, when I create cacheAsBitmap container, it does not re-create / copy that massive sprite-sheet graphic, it only creates image of what's inside of the container correct`
Think of cacheAsBitmap as 'an automatic way to create, and use a render texture, based on the container and it's contents, rather than render them all individually'. Plus sides; only have to render 1 texture now, rather than all the children, so can be quicker. Downside, it has to create this render texture, which has a 1 off little time to create, and will increase amount of memory the gpu is using. 
The problem you were having, was that the size of the renderTexture cacheAsBitmap was creating was _bigger_ than the original sprite-sheet, because it was creating a render texture of the image dimensions * resolution, to keep the sharp look.

`So this solves it for my personal use-case, I assume issue can be closed, or do you guys want to keep it open, as there was a mention of some clarifications / deprecation of related functionality in v6?`
We've already got this covered elsewhere, thank you, we just haven't quite known what strategy to take to resolve :)
