### ISSUE TITLE
Masks slow down the frame rate

### ISSUE THREAD

**Issue by rodighiero** [pixijs/pixi.js#7244]
Hi all,

I am working on a pretty small data visualization in which nodes are presented as images. I use masks to round these images and the result looks good, but the computation becomes really heavy.

You can see the problem by zooming here, https://rodighiero.github.io/NISO2021/

or look a the code, which is very simple here, from line 45, https://github.com/rodighiero/NISO2021/blob/master/src/draw/nodes.js

Thanks for helping,
Dario

P.S. All libraries are updated, I work on OS X and experienced the problem with all the major browsers.

**Comment by SukantPal** [comment]
These images aren't vectors so there isn't any use of masking them. You should either:

* use `Graphics.drawCircle` with a texture fill-style (see `beginFill`)
* or `cacheAsBitmap` on the masked sprites (less ideal)

If there are too many circles (> 20 at once) or are too low-poly (you don't want any edges visible at high zoom), I suggest you try @pixi-essentials/conic. It provides batching by default so performance will be same/better if the images are placed serially in the scene graph (i.e. add each image circle as children together). The magic here is that the package uses a parametric shader to draw the circle as a quadratic curve; each circle takes four vertices instead of 50-100 by Graphics.

```ts
import { Conic, ConicDisplay } from '@pixi-essentials/conic';

const conic = new ConicDisplay(Conic.createCircle(48));

conic._texture = <imageTexture>;

viewport.addChild(conic);
```

The docs are here - https://api.pixijs.io/@pixi-essentials/conic/ConicDisplay.html (albeit not perfect)

**Comment by bigtimebuddy** [comment]
I think there are lots of things this user could do before resorting to a plugin solution. Drawing a Graphics circle for each node is very expensive no doubt. There's no reuse so you're having to render all that geometry all the time.

Two things to try: use shared GraphicsGeometry (constructor parameter for Graphics). This will keep you from having to drawn many many circles over and over. The idea is you create one circle and then pass the geometry around by creating new Graphics(geometry). 

Alternatively, convert this circle to a RenderTexture and share the Texture by creating a Spite mask instead.

In both these instance, you're reusing either texture or geometry.

**Comment by rodighiero** [comment]
Thank you both for your help, which gives me the opportunity to explore further PIXI.js.

I started by exploring the creation of a Graphics.drawCircle with a texture fill-style. It works pretty well, and it improved a lot the rendering speed. Code is always available at https://github.com/rodighiero/NISO2021/blob/master/src/draw/nodes.js

However, I have an unpleasant issue with texture origin. It is at the center splitting the image into four pieces, and I can't change its origin. Here, the screenshot https://github.com/rodighiero/NISO2021/blob/master/docs/Screen%20Shot%202021-02-15%20at%201.00.00%20AM.png

I tried this `texture.orig = new Rectangle(width / 2, height / 2, width, height)`
and this `texture.rotate = 12`
with no success

Any idea how to move the origin? Thanks a lot.

**Comment by SukantPal** [comment]
@rodighiero Instead of drawing the circle with center (0, 0) (which is why the top-left corner of the image is at the center of the circle), you should set the center to match that of the image; you can set the pivot of it so that the `position` still indicates the center:

```ts
g.drawCircle(width / 2, width / 2, width / 2);
g.pivot.set(width / 2, width / 2);
```

Another solution is to use a texture matrix in the fill-style; this is a little more complicated:

```ts
g.beginFill({ texture, matrix: new Matrix().translate(width / 2, width / 2) })
  .drawCircle(0, 0, width / 2);// same as your current solution
```

---
Re @bigtimebuddy

* Sharing the graphics geometry won't account for the different textures. Perhaps you'd tweak the geometry and change the texture for the circle shapes, but that becomes a hack. Also, using a lot of circles means less batching b/c the geometry is large and Graphics will skip it (max. batchable size is 200 vertices by default; and circle has 30 * radius segments right now)
* A sprite mask is still too expensive (a filter after all) and won't be crisp when zooming in (would it?)

**Comment by rodighiero** [comment]
@SukantPal It works perfectly now, thanks a lot!

**Comment by SukantPal** [comment]
Feel free to ask another question in our discussions page!

**Comment by rodighiero** [comment]
Hi @SukantPal,

Actually, I have a question. I don't understand why the texture-based circles do no allow mouseover, while the graphic-only ones work promptly.

Code is very simple:

```
// Set circle

        const side = 20
        const thickness = 5

        if (node.image) {

            loader.load(function (loader, resources) {
                const texture = resources['index_' + node.index].texture
                const width = texture.width
                const height = texture.height
                const options = { texture: texture }
                node.circle = new Graphics()
                node.circle.beginTextureFill(options)
                node.circle.lineStyle(thickness, '0xFFFFFF', 1)
                node.circle.drawCircle(width / 2, width / 2, width / 2)
                node.circle.endFill()
                node.circle.pivot.set(width / 2, width / 2);
                node.circle.width = side
                node.circle.height = side
                node.circle.position = new Point(node.x, node.y)
                node.circle.interactive = true
                node.circle.hitArea = new Circle(0, 0, s.distance)
                node.circle.mouseover = mouseData => mouseover(node)
                node.circle.mouseout = mouseData => mouseout(node)
                stage.addChild(node.circle)
            })

        } else {
            node.circle = new Graphics()
            node.circle.lineStyle(.5, '0xFFFFFF', 1)
            node.circle.beginFill(color, 1)
            node.circle.drawCircle(0, 0, side / 2)
            node.circle.endFill()
            node.circle.position = new Point(node.x, node.y)
            node.circle.interactive = true
            node.circle.hitArea = new Circle(0, 0, s.distance)
            node.circle.mouseover = mouseData => mouseover(node)
            node.circle.mouseout = mouseData => mouseout(node)
            stage.addChild(node.circle)
        }
```
