### ISSUE TITLE
pointerId is always 0

### ISSUE THREAD

**Issue by Seb-135** [pixijs/pixi.js#7407]
### Expected Behavior
The pointerId is supposed to be a unique identifier for the current pointing device. I wanted to use this to distinguish between multiple simultaneous touches on the same sprite.

### Current Behavior
If the Pixi app was created on a mobile device, the InteractionEvent pointerId is unhelpfully set to 0. 
For Chrome on PC with the device toolbar toggled/Chrome on mobile, the pointerId in a window EventListener will always increment from 1. This doesn't happen in the corresponding Pixi event.

After further testing, it turns out that if there are simultaneous touches, the first touch is given 0, the next is 2, and the last one is the actual pointerId that is reported by the window pointer event. 
This means I can tell apart touches, however, I'm using both event listeners for different things, and they don't agree on the pointerId.

### Steps to Reproduce
In the below fiddle, the sprite for the event listener is the white square in the top left of the canvas. Clicking it will log the pointerIds from the two events to the console.
For a regular mouse, the pointerId seems to always be 1.
If you run the fiddle on mobile, or simulate a mobile environment with Shift+Ctrl+M from Chrome DevTools, and click the sprite, then the window pointerId will increment, while the pixi pointerId will be set to 0.

Note: the bug does not occur if you load the page normally on PC, enable the device toolbar, and run the fiddle. If you do that, then the pixi pointerId will be correct.
It does occur if you enable the device toolbar, and then refresh the page before running the fiddle.

### Environment

- **`pixi.js` version**: 6.0.2
- **Browser & Version**: Chrome 89
- **OS & Version**: Windows 10, Android 9.0
- **Running Example**: https://jsfiddle.net/d86oza31/

**Comment by andrewstart** [comment]
Because users wanted access to the original touch events (for multitouch reasons, I believe), if a browser supports PointerEvents and TouchEvents, we use the touch event instead of the pointer event, and that means we use `changedTouches[i].identifier` as the pointer id. As you've found, in at least some implementations (and conditions) the touch identifier count is reset every time a "finger" is removed from the screen, while a true pointerId uses different values.

You can force the touch events to be ignored by changing the interaction manager's settings, see https://jsfiddle.net/rdy28tq5/
