### ISSUE TITLE
getChildByName is set as optional in v6

### ISSUE THREAD

**Issue by MrEmanuel** [pixijs/pixi.js#7444]
Updating to pixi v6 we've run in to a minor issue. The method `getChildByName` on `Container` is set as optional. 
Is this method (and other attributes added via GlobalMixins) actually undefined at any point, or is the typing wrong? 
We're using the method frequently in our code base and it's tedious to add falsy checks everywhere. If it's actually not guaranteed to be defined, then we will of course do the checks, but I suspect that it's actually always defined. 

Also, I don't understand why the method is moved to a mixin and not defined on the class directly as it was in v5. 

In summary, this boils down to two questions:
1. Is the `getChildByName` not always guaranteed to be defined and the typing is correct, or not? 
2. What's the reasoning behind the `GlobalMixins` and why was `getChildByName` moved there in v6?

Thanks in advance! 

```ts
// https://github.com/pixijs/pixi.js/blob/dev/packages/mixin-get-child-by-name/global.d.ts
declare namespace GlobalMixins
{
    interface DisplayObject
    {
        name?: string;
    }

    interface Container
    {
        getChildByName?(name: string, isRecursive?: boolean): import('@pixi/display').DisplayObject;
    }
}
```

**Comment by SukantPal** [comment]
The method was always defined as a mixin. This is a typings issue I think.

**Comment by ivanpopelyshev** [comment]
this mixin is moved to separate package, so you can build pixi without it through `pixi-customize`. That's why its optional.

**Comment by SukantPal** [comment]
Yeah, but since the typings is declared in the mixin package, it shouldn’t be optional.

**Comment by MrEmanuel** [comment]
Thanks for the fast response @SukantPal. 
I think there are more of the same problems with other methods added via mixins. 
For instance `getGlobalPosition`. There might be more attributes that we're not using and thus haven't noticed.

**Comment by ivanpopelyshev** [comment]
> I think there are more of the same problems with other methods added via mixins.

We found only one method to make typings for mixins in new ES6 modules. I didnt see any other projects that use it, everyone just ignore the problem.

It took us a year to find it and implement.

The downside - all those methods and variables are optional, because we inject in global interfaces that other pixi classes implement. 

There are two ways to fix that:
1. find us another method to do mixins.
2. make your own fork of pixi, put all mixins in same package.

It might be easy to do with only a few mixins but try to do something like https://github.com/pixijs/pixi-spine/blob/next/packages/loader-3.8/global.d.ts , there are many fields that are injected by biggest pixi plugin, `pixi-spine`. I have 5 more plugins that inject new fields and methods, i didnt move them to v6 yet.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev Each mixin package has own _local_ global.d.ts file. These typing should definitely _not_ be optional. I believe this probably an artifact of the development of the GlobalMixins and moving stuff around. If you're installing `@pixi/mixin-get-child-by-name` this is expected behavior.

This should look more like the Application plugins, for instance:
https://github.com/pixijs/pixi.js/blob/8c42699aae78199a4cfd1feeef6dc862afd724fe/packages/ticker/global.d.ts#L1-L15

I believe @MrEmanuel is correct here. There are likely other places this occurs too.

**Comment by ivanpopelyshev** [comment]
Hm, its interesting. Why doesn't it complain that class `Application` does not implement  the interface? Is that why we used this trick?

```ts
export interface Application extends GlobalMixins.Application {}

export class Application {
}
```
