### ISSUE TITLE
Rendering a sprite created from texture doesnt appear on stage

### ISSUE THREAD

**Issue by zlobjul** [pixijs/pixi.js#7481]
### Expected Behavior

The Sprite should appear on the stage

### Current Behavior

Current behavior can be confirmed by this example : 

https://www.pixiplayground.com/#/edit/zI1a807CKp1QueSLypGGO

```
// Create our application instance
var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

let line = new PIXI.Graphics()
line.lineStyle(2,0x008aff)
    .moveTo(100, 0)
    .lineTo(0,0)
line.position.set(200,100)
let texture = app.renderer.generateTexture(line)
let sprite = new PIXI.Sprite(texture)
sprite.anchor.set(0.5)
app.stage.addChild(sprite)
```

When we add the "sprite" child , it will not appear on the stage. 

### Possible Solution

N/A

### Steps to Reproduce

Please see the playground example mentioned below. 

### Environment

- **`pixi.js-legacy` version**: 6.0.2
- **Browser & Version**:  90.0.4430.93
- **OS & Version**: Windows 10 
- **Running Example**: https://www.pixiplayground.com/#/edit/zI1a807CKp1QueSLypGGO

**Comment by bigtimebuddy** [comment]
This is working as intended. The issue here is this line: `line.position.set(200,100)` and your element being detached (not added to any tree).

The API `generateTexture` uses `getLocalBounds` for determining the region to render. If you are using a detached element like in your cases, you have a few options:

### Remove setting the position

```js
// line.position.set(200,100)
let texture = app.renderer.generateTexture(line)
```

### Add the line, then remove it
```js
app.stage.addChild(line);
let texture = app.renderer.generateTexture(line);
app.stage.removeChild(line);
```

### Manually provide the region
```js
app.stage.addChild(line);
let texture = app.renderer.generateTexture(line, undefined, undefined, line.getBounds());
```
