### ISSUE TITLE
Issue with application and backgroundAlpha set to 0

### ISSUE THREAD

**Issue by Pandan** [pixijs/pixi.js#7482]
Hi,

I am having issues when trying to run pixi application with a transparent background.
If the backgroundColor is anything else then 0x000000 it will not be totally transparent. 

Check example. 
https://www.pixiplayground.com/#/edit/PR0v6Sjv-xQMrtqPI0Eza

EDIT:
Seems like this is only affecting Firefox.
Even tough I could have sworn I seen in Chrome also 

Thanks,
Jonas

**Comment by SukantPal** [comment]
Hi Pandan, I think the background color might have to be premultiplied alpha like PixiJS uses everywhere. As such, it's impossible for a alpha = 0 to have a color not equal to #000 (because after multiplying anything by 0, it becomes zero).

Hopefully, this should not have a visual effect since any color looks the same when fully transparent.

**Comment by Pandan** [comment]
Thanks!
useContextAlpha: 'notMultiplied' did the jobb.

@SukantPal To clarify, even if backgroundAlpha: 0 makes the background fully transparent.
I am using the backgroundColor to give a visual effect when masking with a RenderTexture.
But probably there is a cleaner way to handle this. 
https://www.pixiplayground.com/#/edit/CZIlabXCwrS9bhI2mBKcl
