### ISSUE TITLE
Add lineCap and other context properties

### ISSUE THREAD

**Issue by kanecko** [pixijs/pixi.js#891]
Today, I found a need of making the line end rounded. 
However it doesn't seem possible to set a lineCap within the Graphics class?

**Comment by Lange** [comment]
Apologies for the very late bump, but I too am in need of the ability to set `lineCap` on my graphics. Did this ever make it in?

**Comment by ouzhou** [comment]
any solutions?

**Comment by Fabiantjoeaon** [comment]
Any updates on this, or any simple workarounds to implementing line caps? Right now I just render a circle or an arc at the end of every straight line, but this doesn't seem like the best implementation to me..

**Comment by jessegavin** [comment]
Not sure what the protocol is on feature requests, but I am chiming in to say this would be a very nice feature to have.

**Comment by 1j01** [comment]
If anyone needs to implement a workaround, I have some code for drawing lines, polylines, and polygons with rounded ends and corners, with WebGL: [1j01/jspaint - image-manipulation.js](https://github.com/1j01/jspaint/blob/886d14f09eef7edb56d0fc2053444ad59c3c741c/src/image-manipulation.js)
One could possibly integrate this into a PIXI scene somehow... (with a custom object? ..or a [plugin](https://github.com/pixijs/pixi-plugin-example)? idk, i haven't used PIXI, i just looked into using it for this purpose, which is why i'm subscribed to this issue)

**Comment by carlsmith** [comment]
@Fabiantjoeaon - I only needed to connect lines together smoothly to form 'roads' along the edges in a hexagonal grid, so putting a circle at each end works pretty well for me. Thanks.
