### ISSUE TITLE
Limitation of the tinting system

### ISSUE THREAD

**Issue by bchevalier** [pixijs/pixi.js#939]
Hello!
Being in the need of a 2D rendering engine (in order to render Flash animations that I convert to javascript) I happened upon Pixi which seems to be a great library in terms of performance and features. However I noticed something missing with respect to Flash (which I saw is on the roadmap), that is the colorisation:

1 - In Flash there are 2 possible tints, an additive tint and a multiplicative tint. However Pixi seems to support only the multiplicative one.

2 - Also it is not possible to interpolate between 2 tints in Pixi, for instance if I have tint0 = 0xFF0000 at time t0 and tint1 = 0x0000FF at time t1 then at time (t0 + t1) / 2 I would want to obtain 0x7F007F (green component remains 0) but instead I could obtain values having a non-null green component such as 0x7FFFFF. If I want to avoid this issue I would need to store the different components of the tint separately and recombine them at every frame.

3 - The tinting does not seem to propagate onto the children of a sprite (only had a quick look so I could be wrong).

First, are these 3 issues relevant?
Second, if someone was to fix it, would the following method be satisfactory?
Create a Tint class with 4 components rgba. (to solve 2)
Add 2 tint attributes to the DisplayObject constructor tintAdd and tintMul. (to solve 1)
Implement tint propagation in DisplayObject.updateTransform. (to solve 3)

In the WebGLRenderer I propose to separate the tint components from the vertex positions and texture coordinates:
1 buffer with vertex positions + texture coordinates as gl.FLOAT (4 components per vertex)
1 buffer with tints components as gl.BYTE (8 components per vertex)

Removing the interleaving would not impact performance as the GPU is not the bottleneck. The total number of bytes passed to the GPU remains unchanged (16 Bytes per vertex). But some performance would be lost on CPU side when populating the tint buffer.

**Comment by Megabyteceer** [comment]
Additive tint is much flexible against multiplicative. Its will be great to add it, at least switcher between multiplicative/additive via pixi settings globally

**Comment by Dairnon** [comment]
https://github.com/gameofbombs/pixi-heaven actually supports add/multi tintingf or pixi v4. 

It uses a modified sprite renderer. It's possible we can move some of this code over to sprites. 

The issue is that supporting both at the same time would cause all sprites be rendered slightly slower as you are increasing the complexity of the sprites we are rendering. 

I'm not sure if that's a trade off the rest of the pixi team is willing to make for an extra layer of tinting. 

A global switcher isn't a bad idea as it shouldn't effect performance, but it does require adding in code for the batchGenerationShader to swap out the correct tint type. 

@GoodBoyDigital What do you think we should do?
